Repository Graylog2/graylog2-server, pull requests merged in 2018-09, with the labels that each got.

#5053 Remove unused content pack auditlog events
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
Labels: content-packs, ready-for-review

#5020 Update to elasticsearch 6.x compatibility
  ELASTICSEARCH_UPGRADES.md
  graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/RequestResponseLogger.java
  graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java
  pom.xml
Labels: ready-for-review

#5059 Make optional collector fields nullable
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java
  graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js
  graylog2-web-interface/src/stores/sidecars/CollectorsStore.js
  graylog2-web-interface/src/stores/sidecars/SidecarsStore.js
Labels: ready-for-review, sidecar

#5063 Remove audit log from resolve action of catalog recource
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/CatalogResource.java
Labels: ready-for-review

#5033 Add GrokPatternInput to GrokExtractorConfiguration
  graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.css
  graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.jsx
Labels: feature, ready-for-review, web

#5070 Remove Content Pack Auto Loader
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
  graylog2-server/src/main/java/org/graylog2/bundles/ContentPackLoaderConfig.java
  graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java
Labels: ready-for-review

#5052 Improvements in collector status
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/filter/StatusAdministrationFilter.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/mapper/SidecarStatusMapper.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/periodical/PurgeExpiredSidecarsThread.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Sidecar.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/AdministrationResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/SidecarService.java
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationFilters.jsx
  graylog2-web-interface/src/components/sidecars/administration/FiltersSummary.jsx
  graylog2-web-interface/src/components/sidecars/common/CommonSidecarStyles.css
  graylog2-web-interface/src/components/sidecars/common/StatusIndicator.jsx
  graylog2-web-interface/src/components/sidecars/common/StatusMapper.js
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
  graylog2-web-interface/src/logic/sidecar/SidecarStatusEnum.js
  graylog2-web-interface/src/stores/sidecars/SidecarsAdministrationStore.js
  graylog2-web-interface/src/stores/sidecars/SidecarsStore.js
Labels: ready-for-review, sidecar

#5074 Adapt action after #5059
  graylog2-web-interface/src/components/sidecars/common/CommonSidecarStyles.css
  graylog2-web-interface/src/components/sidecars/common/OperatingSystemIcon.jsx
  graylog2-web-interface/src/components/sidecars/styles/SidecarStyles.css
  graylog2-web-interface/src/pages/SidecarEditCollectorPage.jsx
  graylog2-web-interface/src/pages/SidecarNewCollectorPage.jsx
  graylog2-web-interface/src/pages/SidecarNewConfigurationPage.jsx
  graylog2-web-interface/src/pages/SidecarStatusPage.jsx
Labels: ready-for-review, sidecar

#5083 Fix loading of collector on edit collector page
  graylog2-web-interface/src/pages/SidecarEditCollectorPage.jsx
Labels: ready-for-review, sidecar

#5066 Rename Collector*Entity and *Facade to SidecarColloector
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorConfigurationEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorEntity.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java
Labels: ready-for-review

#5092 Mark inactive sidecars in administration page
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx
  graylog2-web-interface/src/components/sidecars/common/CommonSidecarStyles.css
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.css
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
Labels: ready-for-review, sidecar

#5067 Fix editing of content packs
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx
  graylog2-web-interface/src/pages/EditContentPackPage.jsx
Labels: ready-for-review

#5112 Run template validation before saving collector configuration
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/template/RenderTemplateException.java
  graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js
Labels: ready-for-review, sidecar

#5058 Implement content pack uninstallation
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/RootEntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/UnsupportedEntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/jackson/ReferenceConverter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackUninstallation.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityV1.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/jackson/ReferenceConverterTest.java
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx
Labels: content-packs, ready-for-review

#5030 Not serializing `type` field twice for `TimeRange` instances.
  graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/TimeRange.java
Labels: ready-for-review

#5121 Using loadable-components to split out pages and brace.
  graylog2-server/src/main/java/org/graylog2/web/PluginAssets.java
  graylog2-web-interface/.babelrc
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/injection/CombinedProvider.js
  graylog2-web-interface/src/injection/builtins.js
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/pages/ServerUnavailablePage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppFacade.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/loadAsync.jsx
  graylog2-web-interface/test/setup-jest.jsx
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/webpack/UniqueChunkIdPlugin.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5029 Make "license:check" and "license:format" work from the project root
  graylog-plugin-parent/pom.xml
  pom.xml
Labels: ready-for-review

#5122 Updating to React 16.
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap
  graylog2-web-interface/src/components/users/UserPreferencesButton.test.jsx
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/test/setup-jest.jsx
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5123 Make "license:check" and "license:format" work from the project root
  graylog-plugin-parent/pom.xml
  pom.xml
Labels: ready-for-review

#5104 Adapt default winlogbeat paths
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/sidecar_collectors.json
Labels: ready-for-review, sidecar

#5127 Randomize chunk id only once.
  graylog2-web-interface/webpack/UniqueChunkIdPlugin.js
Labels: infrastructure, ready-for-review, web

#5102 Enable collector template preview on new configurations
  graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/SourceViewModal.jsx
Labels: ready-for-review, sidecar

#5128 Add missing tests for UniqueChunkIdPlugin.
  graylog2-web-interface/webpack/UniqueChunkIdPlugin.js
  graylog2-web-interface/webpack/UniqueChunkIdPlugin.test.js
  graylog2-web-interface/webpack/__snapshots__/UniqueChunkIdPlugin.test.js.snap
Labels: ready-for-review, web

#5118 Remove "AutoValue_" prefix from API error JSON
  graylog2-server/src/main/java/org/graylog2/plugin/rest/ApiError.java
  graylog2-server/src/main/java/org/graylog2/plugin/rest/DetailedError.java
  graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationApiError.java
Labels: ready-for-review

#5133 Add more lifecycle indicators to `PageHeader`
  graylog2-web-interface/src/components/common/PageHeader.jsx
  graylog2-web-interface/src/components/common/PageHeader.md
Labels: ready-for-review

#5134 Manually add store injection to UI documentation
  graylog2-web-interface/styleguide.config.js
Labels: ready-for-review

#5135 Remove legacy config options from config example
  misc/graylog.conf
Labels: ready-for-review

#5129 Upgrading to Babel 7.
  graylog2-web-interface/.babelrc
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/.babelrc
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/src/components/outputs/OutputList.jsx
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, web

#5146 Revert "Upgrading to Babel 7. (#5129)"
  graylog2-web-interface/.babelrc
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/.babelrc
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/src/components/outputs/OutputList.jsx
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5139 Add quotes to default winlogbeat collector parameter
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/sidecar_collectors.json
Labels: bug, ready-for-review, sidecar

#5126 Updating dependencies to webpack 4.19.1.
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, web

#5151 Upgrading to babel 7 - Take II
  graylog2-web-interface/.babelrc
  graylog2-web-interface/babel.config.js
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/.babelrc
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/src/components/outputs/OutputList.jsx
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5131 Isolate notification badge updates.
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/NotificationBadge.jsx
  graylog2-web-interface/src/components/navigation/NotificationBadge.test.jsx
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Labels: ready-for-review

#5117 Add DNS Lookup adaptor to graylog2-server repository
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/ADnsAnswer.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsAnswer.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClient.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClientNotRunningException.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsLookupType.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/PtrDnsAnswer.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/TxtDnsAnswer.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/dnslookup/DnsClientTest.java
  graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterDocumentation.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterFieldSet.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterSummary.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/index.js
Labels: ready-for-review

#5160 Enforce newlines at the end of rendered configurations
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java
  graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/ConfigurationServiceTest.java
Labels: ready-for-review

#5154 Implement Error Boundary for Navigation Bar children.
  graylog2-web-interface/src/components/support/ContactUs.jsx
  graylog2-web-interface/src/components/support/SupportSources.jsx
  graylog2-web-interface/src/pages/ErrorPage.css
  graylog2-web-interface/src/pages/ErrorPage.jsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/routing/AppErrorBoundary.jsx
  graylog2-web-interface/src/routing/AppErrorBoundary.test.jsx
  graylog2-web-interface/src/routing/__snapshots__/AppErrorBoundary.test.jsx.snap
  graylog2-web-interface/webpack.config.js
Labels: ready-for-review
