Repository Graylog2/graylog2-server, pull requests merged in 2018-11, with the labels that each got.

#5150 Add default grok pattern migration
  graylog2-server/src/main/assembly/graylog.xml
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns.java
  graylog2-server/src/main/resources/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns_Default_Grok_Patterns.json
  misc/contentpacks/grok-patterns.json
Labels: content-packs

#5256 Update vendor-module-ids after latest upgrades
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#5255 Fix collector name validator when called on itself
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java
  graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
  graylog2-web-interface/src/stores/sidecars/CollectorsStore.js
Labels: ready-for-review

#5260 Upgrade moment and moment-timezone
  graylog2-web-interface/npm-shrinkwrap.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#5253 Log exception when handling generic exception in field types poller.
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
Labels: ready-for-review

#5212 Make search query in alert conditions configurable in the UI
  graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/AlertConditionTestResponse.java
  graylog2-server/src/test/java/org/graylog2/alerts/AbstractAlertConditionTest.java
  graylog2-server/src/test/java/org/graylog2/alerts/types/FieldContentValueAlertConditionTest.java
Labels: alerting, ready-for-review

#5279 Update netty-tcnative to 2.0.19
  pom.xml
Labels: blocker, bug, ready-for-review

#5277 Make search query in alert conditions configurable in the UI (#5212)
  graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/AlertConditionTestResponse.java
  graylog2-server/src/test/java/org/graylog2/alerts/AbstractAlertConditionTest.java
  graylog2-server/src/test/java/org/graylog2/alerts/types/FieldContentValueAlertConditionTest.java
Labels: ready-for-review

#5226 Fix index stats collection
  graylog2-server/src/main/java/org/graylog2/indexer/indices/stats/IndexStatistics.java
Labels: ready-for-review

#5224 Fix description and default value for Key and Value column (#4973)
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/DSVHTTPDataAdapter.java
  graylog2-web-interface/src/components/lookup-tables/adapters/DSVHTTPAdapterFieldSet.jsx
Labels: ready-for-review

#5278 Remove Sidecar collector configuration path
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorEntity.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/sidecar_collectors.json
  graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
Labels: improvement, ready-for-review, sidecar

#5286 Update gelfclient version to latest 1.4.4 (uses Netty 4.1.31)
  pom.xml
Labels: ready-for-review

#5218 Add throttling to the AWS Flow Logs/Logs inputs
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/ThrottleableTransport.java
Labels: ready-for-review

#5290 Fix gl2_source_collector field for default collector
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
Labels: ready-for-review, sidecar

#5292 Allow showing/hiding BootstrapModalForm declaratively.
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.test.jsx
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
Labels: ready-for-review

#5064 Add Jest actions for use with ES Task API
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/RequestResponseLogger.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/tasks/CancelTask.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/tasks/GetTasks.java
  graylog2-server/src/test/java/org/graylog2/ElasticsearchBase.java
  graylog2-server/src/test/java/org/graylog2/ElasticsearchConfiguration.java
  graylog2-server/src/test/java/org/graylog2/ElasticsearchRule.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/jest/tasks/GetTasksTestIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/results/ScrollResultIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
Labels: ready-for-review

#5295 Fix alignment of content pack selection
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
Labels: content-packs, ready-for-review

#5301 Allow passing container prop to `ClipboardButton`.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/ClipboardButton.jsx
  graylog2-web-interface/src/components/common/ClipboardButton.test.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5304 Fix slow CSV export by using a bigger default batch size
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
Labels: ready-for-review

#5306 Fix index stats collection (#5226)
  graylog2-server/src/main/java/org/graylog2/indexer/indices/stats/IndexStatistics.java
Labels: ready-for-review

#5300 Treat reindexed indices as managed indices in Graylog
  graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
  graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
Labels: elasticsearch, ready-for-review

#5269 support for decimal IPv4 representation in to_ip
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ips/IpAddressConversion.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/int2ipv4.txt
Labels: feature, ready-for-review

#5308 Limit user details to self and admins in API (#5079)
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Labels: ready-for-review

#5310 Stream alerting overview page
  graylog2-server/src/main/java/org/graylog2/rest/resources/alerts/AlertResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertResource.java
  graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionForm.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionSummary.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionsComponent.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionsList.jsx
  graylog2-web-interface/src/components/alertconditions/CreateAlertConditionInput.jsx
  graylog2-web-interface/src/components/alertconditions/EditAlertConditionForm.jsx
  graylog2-web-interface/src/components/alertconditions/StreamAlertConditions.jsx
  graylog2-web-interface/src/components/alertconditions/index.jsx
  graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx
  graylog2-web-interface/src/components/alertnotifications/AlertNotificationsComponent.jsx
  graylog2-web-interface/src/components/alertnotifications/AlertNotificationsList.jsx
  graylog2-web-interface/src/components/alertnotifications/CreateAlertNotificationInput.jsx
  graylog2-web-interface/src/components/alertnotifications/StreamAlertNotifications.jsx
  graylog2-web-interface/src/components/alertnotifications/index.jsx
  graylog2-web-interface/src/components/alerts/Alert.jsx
  graylog2-web-interface/src/components/alerts/AlertsComponent.jsx
  graylog2-web-interface/src/components/alerts/StreamAlerts.jsx
  graylog2-web-interface/src/components/alerts/StreamAlertsOverviewContainer.jsx
  graylog2-web-interface/src/components/alerts/index.jsx
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
  graylog2-web-interface/src/components/streams/StreamList.jsx
  graylog2-web-interface/src/pages/EditAlertConditionPage.jsx
  graylog2-web-interface/src/pages/NewAlertConditionPage.jsx
  graylog2-web-interface/src/pages/NewAlertNotificationPage.jsx
  graylog2-web-interface/src/pages/ShowAlertPage.jsx
  graylog2-web-interface/src/pages/StreamAlertsOverviewPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/alertconditions/AlertConditionsStore.js
  graylog2-web-interface/src/stores/alerts/AlertsStore.js
Labels: ready-for-review

#5311 Stream alerting overview (#5310)
  graylog2-server/src/main/java/org/graylog2/rest/resources/alerts/AlertResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertResource.java
  graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionForm.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionSummary.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionsComponent.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionsList.jsx
  graylog2-web-interface/src/components/alertconditions/CreateAlertConditionInput.jsx
  graylog2-web-interface/src/components/alertconditions/EditAlertConditionForm.jsx
  graylog2-web-interface/src/components/alertconditions/StreamAlertConditions.jsx
  graylog2-web-interface/src/components/alertconditions/index.jsx
  graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx
  graylog2-web-interface/src/components/alertnotifications/AlertNotificationsComponent.jsx
  graylog2-web-interface/src/components/alertnotifications/AlertNotificationsList.jsx
  graylog2-web-interface/src/components/alertnotifications/CreateAlertNotificationInput.jsx
  graylog2-web-interface/src/components/alertnotifications/StreamAlertNotifications.jsx
  graylog2-web-interface/src/components/alertnotifications/index.jsx
  graylog2-web-interface/src/components/alerts/Alert.jsx
  graylog2-web-interface/src/components/alerts/AlertsComponent.jsx
  graylog2-web-interface/src/components/alerts/AlertsHeaderToolbar.jsx
  graylog2-web-interface/src/components/alerts/StreamAlerts.jsx
  graylog2-web-interface/src/components/alerts/StreamAlertsOverviewContainer.jsx
  graylog2-web-interface/src/components/alerts/index.jsx
  graylog2-web-interface/src/components/common/ExternalLinkButton.jsx
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
  graylog2-web-interface/src/components/streams/StreamList.jsx
  graylog2-web-interface/src/pages/AlertConditionsPage.jsx
  graylog2-web-interface/src/pages/AlertNotificationsPage.jsx
  graylog2-web-interface/src/pages/AlertsPage.jsx
  graylog2-web-interface/src/pages/EditAlertConditionPage.jsx
  graylog2-web-interface/src/pages/NewAlertConditionPage.jsx
  graylog2-web-interface/src/pages/NewAlertNotificationPage.jsx
  graylog2-web-interface/src/pages/ShowAlertPage.jsx
  graylog2-web-interface/src/pages/StreamAlertsOverviewPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/alertconditions/AlertConditionsStore.js
  graylog2-web-interface/src/stores/alerts/AlertsStore.js
Labels: ready-for-review

#5314 Fix Backslash Escaping for Phrase Searches (#4477)
  graylog2-web-interface/src/stores/search/SearchStore.test.jsx
  graylog2-web-interface/src/stores/search/SearchStore.ts
Labels: ready-for-review

#5315 Add API endpoint to get and update index templates in Elasticsearch
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexTemplatesResource.java
Labels: ready-for-review

#5316 Add test button to alert conditions
  graylog2-web-interface/src/actions/alertconditions/AlertConditionsActions.jsx
  graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.css
  graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.jsx
  graylog2-web-interface/src/components/alertconditions/index.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/alertconditions/AlertConditionsStore.js
Labels: alerting, ready-for-review

#5321 Add throttling to the AWS Flow Logs/Logs inputs (#5218)
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/ThrottleableTransport.java
Labels: ready-for-review

#5322 Add test button to alert conditions (#5316)
  graylog2-web-interface/src/actions/alertconditions/AlertConditionsActions.jsx
  graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx
  graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.css
  graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.jsx
  graylog2-web-interface/src/components/alertconditions/index.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/alertconditions/AlertConditionsStore.js
Labels: ready-for-review

#5326 Add permissions to all admins to see user details
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Labels: ready-for-review

#5287 Fix flaky ConnectionCounterTest by waiting for serverChannel to be set
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/util/ConnectionCounterTest.java
Labels: ready-for-review

#5330 Add permissions to all admins to see user details (#5326)
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Labels: ready-for-review

#5340 Include re-indexed indices in index retention
  graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
  graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
Labels: ready-for-review

#5341 Update to jest-2.4.15+jackson to fix an issue with field terms
  pom.xml
Labels: ready-for-review
