Repository Graylog2/graylog2-server, pull requests merged in 2018-03, with the labels that each got.

#4632 Fix potential NPE in NodeImpl
  graylog2-server/src/main/java/org/graylog2/cluster/NodeImpl.java
Labels: ready-for-review

#4626 Add colour picker components
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/ColorPicker.jsx
  graylog2-web-interface/src/components/common/ColorPicker.md
  graylog2-web-interface/src/components/common/ColorPickerPopover.css
  graylog2-web-interface/src/components/common/ColorPickerPopover.jsx
  graylog2-web-interface/src/components/common/ColorPickerPopover.md
  graylog2-web-interface/src/components/common/SelectPopover.css
  graylog2-web-interface/src/components/common/SelectPopover.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#4633 Let user of DataTable control if table is responsive
  graylog2-web-interface/src/components/common/DataTable.jsx
Labels: ready-for-review

#4629 Remove all access tokens of a user when the user is deleted
  graylog2-server/src/main/java/org/graylog2/security/AccessTokenImpl.java
  graylog2-server/src/main/java/org/graylog2/security/AccessTokenService.java
  graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: feature, ready-for-review

#4639 Add stream title to notification
  graylog2-server/src/main/java/org/graylog2/streams/StreamFaultManager.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
Labels: improvement, ready-for-review

#4584 Adjust resolution of dashboard layout for wide screens
  graylog2-server/src/main/java/org/graylog2/bundles/Dashboard.java
  graylog2-server/src/main/java/org/graylog2/dashboards/Dashboard.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardImpl.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/WidgetPosition.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolutionTest.java
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
  graylog2-web-interface/src/components/widgets/types/index.js
  graylog2-web-interface/src/pages/ShowDashboardPage.jsx
Labels: bug, ready-for-review

#4640 Fix vulnerability of moment.js
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, security

#4644 Create assembly in package phase automatically
  graylog2-server/pom.xml
Labels: ready-for-review

#4645 Create assembly in package phase automatically (#4644)
  graylog2-server/pom.xml
Labels: ready-for-review

#4642 Fix the way TypeScript loads type definitions.
  graylog2-web-interface/src/stores/widgets/WidgetsStore.ts
  graylog2-web-interface/tsconfig.json
Labels: ready-for-review

#4636 Remove Cobertura Maven plugin
  graylog-project-parent/pom.xml
  pom.xml
Labels: ready-for-review

#4581 Collect and expose index field type information
  graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeDTO.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeLookup.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeMapper.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypes.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypesModule.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePoller.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesDTO.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MongoFieldTypeLookup.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/jobs/SetIndexReadOnlyAndCalculateRangeJob.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/FieldTypeMapperTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesServiceTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MongoFieldTypeLookupTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
  graylog2-server/src/test/resources/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.json
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx
  graylog2-web-interface/src/components/indices/IndexSetDetails.jsx
  misc/graylog.conf
Labels: ready-for-review

#4650 Disable unreliable tests.
  graylog2-server/src/test/java/org/graylog2/configuration/HttpConfigurationTest.java
Labels: ready-for-review

#4648 Update codename for 3.0.0
  graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
Labels: ready-for-review

#4652 Updating Jest and Enzyme.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/users/TokenList.test.jsx
  graylog2-web-interface/src/components/users/UserPreferencesButton.test.jsx
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
  graylog2-web-interface/test/setup-jest.jsx
  graylog2-web-interface/yarn.lock
Labels: infrastructure, ready-for-review, web

#4661 Support drag handles in ReactGridContainer.
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Labels: ready-for-review, web

#4660 Prevent ForkedBooter process from stealing window focus on Mac OS
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
Labels: ready-for-review

#4659 Adding keys to plugin routes.
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: ready-for-review, web

#4668 Add PaginatedDbService class
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
  graylog2-server/src/main/java/org/graylog2/lookup/db/DBCacheService.java
  graylog2-server/src/main/java/org/graylog2/lookup/db/DBDataAdapterService.java
  graylog2-server/src/main/java/org/graylog2/lookup/db/DBLookupTableService.java
  graylog2-server/src/main/java/org/graylog2/rest/models/PaginatedResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java
  graylog2-server/src/test/java/org/graylog2/database/PaginatedDbServiceTest.java
Labels: ready-for-review

#4670 Fix JSON serialization of PaginatedResponse
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/rest/models/PaginatedResponse.java
  graylog2-server/src/test/java/org/graylog2/rest/models/PaginatedResponseTest.java
  pom.xml
Labels: ready-for-review

#4508 Fixed CSS rules for main-nav dropdown
  graylog2-web-interface/public/stylesheets/graylog2.less
Labels: ready-for-review

#4674 Add HOC generator connecting ES6 class components to stores.
  graylog2-web-interface/src/stores/connect.jsx
  graylog2-web-interface/src/stores/connect.test.jsx
Labels: infrastructure, ready-for-review, web

#4675 Add activePage prop to PaginatedList.jsx
  graylog2-web-interface/src/components/common/PaginatedList.jsx
Labels: ready-for-review
