Repository Graylog2/graylog2-server, pull requests merged in 2018-02, with the labels that each got.

#4572 Remove unused SearchResponseCsvWriter class
  graylog2-server/src/main/java/org/graylog2/rest/SearchResponseCsvWriter.java
Labels: ready-for-review

#4550 Make API Tokens configurable in web interface
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/Permissions.java
  graylog2-server/src/test/java/org/graylog2/shared/security/PermissionsTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
  graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx
  graylog2-web-interface/src/components/common/TableList.jsx
  graylog2-web-interface/src/components/users/PermissionSelector.test.jsx
  graylog2-web-interface/src/components/users/TokenList.css
  graylog2-web-interface/src/components/users/TokenList.jsx
  graylog2-web-interface/src/components/users/TokenList.test.jsx
  graylog2-web-interface/src/components/users/UserList.css
  graylog2-web-interface/src/components/users/UserList.jsx
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/pages/EditTokensPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/users/UsersStore.ts
  graylog2-web-interface/test/helpers/mocking/react-dom_mock.js
Labels: feature, ready-for-review

#4579 TableList improvements
  graylog2-web-interface/package.json
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/components/common/ControlledTableList.jsx
  graylog2-web-interface/src/components/common/ControlledTableList.md
  graylog2-web-interface/src/components/common/ControlledTableListHeader.css
  graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx
  graylog2-web-interface/src/components/common/ControlledTableListItem.jsx
  graylog2-web-interface/src/components/common/TableList.css
  graylog2-web-interface/src/components/common/TableList.jsx
  graylog2-web-interface/src/components/common/TableList.md
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/users/PermissionSelector.jsx
  graylog2-web-interface/src/components/users/TokenList.jsx
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#4542 Add JSON factory method for `LookupResult`
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCacheKey.java
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
  graylog2-server/src/test/java/org/graylog2/plugin/lookup/LookupResultTest.java
Labels: bug, ready-for-review

#4537 Ignore `LookupCacheKey#isPrefixOnly()` when (de-) serializing with Jackson
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCacheKey.java
  graylog2-server/src/test/java/org/graylog2/plugin/lookup/LookupCacheKeyTest.java
Labels: bug, ready-for-review

#4587 Add JSON factory method for `LookupResult`
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCacheKey.java
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
  graylog2-server/src/test/java/org/graylog2/plugin/lookup/LookupResultTest.java
Labels: ready-for-review

#4586 Ignore `LookupCacheKey#isPrefixOnly()` when (de-) serializing with Jackson
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCacheKey.java
  graylog2-server/src/test/java/org/graylog2/plugin/lookup/LookupCacheKeyTest.java
Labels: bug, ready-for-review

#4521 Display Timestamp in User Timezone
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
  graylog2-web-interface/src/components/search/MessageDetail.jsx
  graylog2-web-interface/src/components/search/MessageField.jsx
  graylog2-web-interface/src/components/search/MessageFieldDescription.jsx
  graylog2-web-interface/src/components/search/MessageFields.jsx
  graylog2-web-interface/src/components/search/MessageShow.jsx
  graylog2-web-interface/src/components/search/MessageTableEntry.css
  graylog2-web-interface/src/components/search/MessageTableEntry.jsx
  graylog2-web-interface/src/components/search/MessageTableEntry.test.jsx
  graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap
  graylog2-web-interface/src/logic/datetimes/DateTime.js
Labels: ready-for-review

#4582 Reduce development startup time by improving globbing.
  graylog2-web-interface/webpack.combined.config.js
Labels: infrastructure, ready-for-review, web

#4526 Prevent ldap server password leak
  graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/requests/LdapSettingsRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/responses/LdapSettingsResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ldap/LdapSettings.java
  graylog2-web-interface/src/components/ldap/LdapComponent.css
  graylog2-web-interface/src/components/ldap/LdapComponent.jsx
Labels: bug, ready-for-review

#4597 Merge Enterprise Integration plugin into Graylog core
  graylog2-web-interface/src/components/enterprise/PluginList.css
  graylog2-web-interface/src/components/enterprise/PluginList.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/pages/EnterprisePage.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: ready-for-review

#4575 Merge Map Widget plugin into Graylog core
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/plugins/map/MapWidgetModule.java
  graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java
  graylog2-server/src/main/java/org/graylog/plugins/map/config/GeoIpResolverConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/processor/GeoIpProcessor.java
  graylog2-server/src/main/java/org/graylog/plugins/map/rest/MapDataResource.java
  graylog2-server/src/main/java/org/graylog/plugins/map/search/MapDataSearch.java
  graylog2-server/src/main/java/org/graylog/plugins/map/search/MapDataSearchRequest.java
  graylog2-server/src/main/java/org/graylog/plugins/map/search/MapDataSearchResult.java
  graylog2-server/src/main/java/org/graylog/plugins/map/widget/strategy/MapWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/map/widget/strategy/MapWidgetStrategyConfiguration.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/test/java/org/graylog/plugins/map/ConditionalRunner.java
  graylog2-server/src/test/java/org/graylog/plugins/map/ResourceExistsCondition.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/field-analyzers/index.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/index.js
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterDocumentation.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
  graylog2-web-interface/src/components/maps/adapter/index.js
  graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.jsx
  graylog2-web-interface/src/components/maps/configurations/index.js
  graylog2-web-interface/src/components/maps/field-analyzers/FieldAnalyzerMapComponent.jsx
  graylog2-web-interface/src/components/maps/widgets/MapVisualization.css
  graylog2-web-interface/src/components/maps/widgets/MapVisualization.jsx
  graylog2-web-interface/src/components/maps/widgets/index.js
  graylog2-web-interface/src/components/widgets/types/index.js
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
  graylog2-web-interface/src/stores/maps/MapsStore.js
  pom.xml
Labels: ready-for-review

#4589 Merge Beats plugin into Graylog core
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsCodec.java
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsFrameDecoder.java
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInput.java
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInputPluginModule.java
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsTransport.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/MessageInputBindings.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsCodecTest.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsFrameDecoderTest.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsInputDescriptorTest.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportConfigTest.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportTest.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/ConsolePrinter.java
  graylog2-server/src/test/resources/org/graylog/plugins/beats/filebeat.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-cloud-alibaba.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-cloud-digital-ocean.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-cloud-ec2.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-cloud-gce.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-cloud-tencent.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-docker.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-fields.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic-with-kubernetes.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/generic.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-docker-container.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-docker-cpu.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-docker-diskio.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-docker-info.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-docker-memory.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-docker-network.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-mongodb-status.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-mysql-status.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-core.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-cpu.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-filesystem.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-fsstat.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-load.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-memory.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-network.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/metricbeat-system-process.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/packetbeat-dns.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/topbeat-filesystem.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/topbeat-process.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/topbeat-system.json
  graylog2-server/src/test/resources/org/graylog/plugins/beats/winlogbeat.json
  misc/vagrant_winlogbeat/Vagrantfile
  misc/vagrant_winlogbeat/download.sh
Labels: ready-for-review

#4602 Sync yarn.lock after plugin merges
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#4530 Only update dashboard positions when necessary
  graylog2-web-interface/src/components/common/ReactGridContainer.css
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Labels: bug, in progress

#4608 Add plugin merge notes to UPGRADING.rst
  UPGRADING.rst
Labels: ready-for-review

#4609 Update to netty-4.1.22
  pom.xml
Labels: ready-for-review

#4610 remove docker
  docker/README.md
  docker/config/do.conf
  docker/config/elasticsearch/elasticsearch.yml
  docker/config/elasticsearch/logging.yml
  docker/config/mongodb/mongod.conf
  docker/do
  docker/docker-compose.yml
Labels: ready-for-review

#4607 Move pipeline-processor and map-widget REST resources out of /plugins prefix
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog/plugins/map/MapWidgetModule.java
  graylog2-server/src/main/java/org/graylog/plugins/map/rest/MapDataResource.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/PipelineProcessorModule.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/RestControllerPackage.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/maps/MapsStore.js
  graylog2-web-interface/src/stores/pipelines/PipelineConnectionsStore.js
  graylog2-web-interface/src/stores/pipelines/PipelinesStore.js
  graylog2-web-interface/src/stores/rules/RulesStore.js
  graylog2-web-interface/src/stores/simulator/SimulatorStore.js
Labels: ready-for-review

#4605 Remove warnings from browser console
  graylog2-web-interface/src/components/alertconditions/AlertConditionSummary.jsx
  graylog2-web-interface/src/components/alerts/Alert.jsx
  graylog2-web-interface/src/components/dashboard/Dashboard.jsx
  graylog2-web-interface/src/components/dashboard/DashboardList.jsx
  graylog2-web-interface/src/components/extractors/converters_configuration/LookupTableConverterConfiguration.jsx
  graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.jsx
  graylog2-web-interface/src/components/extractors/extractors_configuration/LookupTableExtractorConfiguration.jsx
  graylog2-web-interface/src/components/indices/IndexSetsComponent.jsx
  graylog2-web-interface/src/components/lookup-tables/CacheTableEntry.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterTableEntry.jsx
  graylog2-web-interface/src/components/lookup-tables/LUTTableEntry.jsx
  graylog2-web-interface/src/components/lookup-tables/LookupTable.jsx
  graylog2-web-interface/src/components/nodes/JournalDetails.jsx
  graylog2-web-interface/src/components/pipelines/PipelineConnectionsForm.jsx
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
  graylog2-web-interface/src/components/pipelines/Stage.jsx
  graylog2-web-interface/src/components/pipelines/StageForm.jsx
  graylog2-web-interface/src/components/rules/RuleForm.jsx
  graylog2-web-interface/src/components/rules/RuleList.jsx
  graylog2-web-interface/src/components/search/MessageDetail.jsx
  graylog2-web-interface/src/components/search/MessageFieldExtractorActions.jsx
  graylog2-web-interface/src/components/search/MessageTableEntry.jsx
  graylog2-web-interface/src/components/search/SearchResult.jsx
  graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap
  graylog2-web-interface/src/components/simulator/ProcessorSimulator.jsx
  graylog2-web-interface/src/components/sources/SourceOverview.jsx
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/users/RoleList.jsx
  graylog2-web-interface/src/pages/LoginPage.jsx
  graylog2-web-interface/src/pages/NodeInputsPage.jsx
  graylog2-web-interface/src/pages/SearchPage.jsx
  graylog2-web-interface/src/pages/ShowDashboardPage.jsx
  graylog2-web-interface/src/pages/StreamOutputsPage.jsx
Labels: ready-for-review, web

#4538 Simplify `ByteBufferUtils#readBytes()`, document side-effects, add tests
  graylog2-server/src/main/java/org/graylog2/shared/utilities/ByteBufferUtils.java
  graylog2-server/src/test/java/org/graylog2/shared/utilities/ByteBufferUtilsTest.java
Labels: ready-for-review
