Repository Graylog2/graylog2-server, pull requests merged in 2018-05, with the labels that each got.

#4756 Update to webpack 4
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/webpack.vendor.js
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: infrastructure, web

#4764 Fix links in README
  README.markdown
Labels: bug, documentation, ready-for-review

#4771 Initializing map holding element refs in `GeoIpResolverConfig`.
  graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.jsx
Labels: bug, ready-for-review

#4768 Rule Helper Filter
  graylog2-web-interface/src/components/common/FilterInput.jsx
  graylog2-web-interface/src/components/common/FilterInput.md
  graylog2-web-interface/src/components/common/FilterInput.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/FilterInput.test.jsx.snap
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/rules/RuleHelper.jsx
Labels: feature, ready-for-review

#4793 Do not reset SelectPopover filter on hide
  graylog2-web-interface/src/components/common/SelectPopover.jsx
Labels: ready-for-review

#4789 Support case-insensitive auth-scheme token in proxy authentication
  graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
Labels: bug, ready-for-review

#4790 Support case-insensitive auth-scheme token in proxy authentication
  graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
Labels: bug, ready-for-review

#4795 Stripping out flow types from JS files.
  graylog2-web-interface/.babelrc
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/yarn.lock
Labels: infrastructure, ready-for-review

#4792 Disabling unreliable AbstractTcpTransportTest test case.
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
Labels: ready-for-review

#4796 Improving stores/connect helper function.
  graylog2-web-interface/src/stores/connect.jsx
  graylog2-web-interface/src/stores/connect.test.jsx
Labels: ready-for-review, web

#4717 Add `join()` function to join an array of strings
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Join.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Split.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/split.txt
Labels: feature, ready-for-review

#4718 Add `replace()` function to replace occurrences of a string
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Replace.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/strings.txt
Labels: feature, ready-for-review

#4805 Upgrade to Jest 2.4.13+jackson
  pom.xml
Labels: blocker, bug, ready-for-review

#4806 Upgrade to Jest 2.4.13+jackson
  pom.xml
Labels: blocker, bug, ready-for-review

#4803 Add filter for inputs
  graylog2-web-interface/src/components/bootstrap/Input.jsx
  graylog2-web-interface/src/components/common/ExternalLinkButton.jsx
  graylog2-web-interface/src/components/common/FilterInput.jsx
  graylog2-web-interface/src/components/common/FilterInput.md
  graylog2-web-interface/src/components/common/FilterInput.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/FilterInput.test.jsx.snap
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/inputs/InputsList.jsx
  graylog2-web-interface/src/components/rules/RuleHelper.jsx
Labels: feature, ready-for-review, web

#4808 Do not update positions after click in widget actions
  graylog2-web-interface/src/components/common/ReactGridContainer.css
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Labels: ready-for-review
