Repository Graylog2/graylog2-server, pull requests merged in 2018-10, with the labels that each got.

#5161 Improving MockComponent by rendering custom component.
  graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap
  graylog2-web-interface/test/helpers/mocking/MockComponent.jsx
Labels: ready-for-review

#5168 Catch Netty exceptions and avoid logging stacktraces
  graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/ExceptionLoggingChannelHandler.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/NettyTransport.java
Labels: bug, inputs

#5166 Fix configurations load in includes helper
  graylog2-web-interface/src/components/sidecars/configuration-forms/IncludesHelper.jsx
Labels: ready-for-review, sidecar

#5165 Handle 404s in sidecar
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
  graylog2-web-interface/src/components/sidecars/configuration-forms/SourceViewModal.jsx
  graylog2-web-interface/src/pages/SidecarEditCollectorPage.jsx
  graylog2-web-interface/src/pages/SidecarEditConfigurationPage.jsx
  graylog2-web-interface/src/pages/SidecarStatusPage.jsx
  graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js
  graylog2-web-interface/src/stores/sidecars/CollectorsStore.js
  graylog2-web-interface/src/stores/sidecars/SidecarsStore.js
Labels: ready-for-review, sidecar

#5153 Fixes for content packs
  graylog2-web-interface/src/components/common/ExpandableListItem.jsx
  graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/ContentPackInstall.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
Labels: content-packs, ready-for-review

#5130 Fix content pack serialisation
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPack.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/Constraint.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/Entity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/parameters/Parameter.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/ContentPackTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/model/expected_content_pack.json
Labels: ready-for-review

#5178 Bumping node version to current LTS, yarn to most recent stable.
  pom.xml
Labels: infrastructure, ready-for-review

#5177 Return helpful error message when CSRF protection fails.
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
Labels: bug, ready-for-review

#5181 UI improvements for configuring and starting collectors
  graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorProcessControl.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationActions.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationFilters.jsx
  graylog2-web-interface/src/components/sidecars/common/StatusIndicator.css
  graylog2-web-interface/src/components/sidecars/common/StatusIndicator.jsx
Labels: ready-for-review, sidecar

#5185 Add CSRF backward compatibility for older Sidecars
  graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
Labels: improvement, ready-for-review, sidecar

#5169 Enrich client cert warning message with info about input
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
Labels: improvement, inputs, ready-for-review

#5093 removed drools plugin
  UPGRADING.rst
Labels: ready-for-review

#5076 Fix Show Page of Content Packs
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.test.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
Labels: ready-for-review

#5182 Return helpful error message when CSRF protection fails. (#5177)
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
Labels: ready-for-review

#5194 Add changes to yarn.lock which happend with yarn upgrade
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5196 Fix failing content pack tests
  graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.json
Labels: ready-for-review

#5163 Fixing editing outputs from web and REST API.
  graylog2-server/src/main/java/org/graylog2/streams/OutputServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/streams/OutputServiceImplTest.java
  graylog2-server/src/test/resources/org/graylog2/streams/single-output.json
Labels: bug, ready-for-review

#5108 Add file system type and name to FsStats
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/FsStats.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/SigarFsProbe.java
Labels: ready-for-review

#5197 Add Beats default templates
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
  graylog2-web-interface/src/components/sidecars/configuration-forms/FilebeatHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.jsx
Labels: ready-for-review, sidecar

#5193 Support navigation dropdowns contributed by plugins.
  graylog2-web-interface/src/components/common/IfPermitted.jsx
  graylog2-web-interface/src/components/common/IfPermitted.test.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/NavigationLink.jsx
  graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
  graylog2-web-interface/src/util/PermissionsMixin.jsx
Labels: ready-for-review

#5198 Rename "Beats Legacy" input to "Beats (deprecated)"
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsCodec.java
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInput.java
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInputPluginModule.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsInputDescriptorTest.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/DeprecatedConsolePrinter.java
Labels: improvement, inputs, ready-for-review

#5213 Prevent overwriting children's props in `IfPermitted`.
  graylog2-web-interface/src/components/common/IfPermitted.jsx
  graylog2-web-interface/src/components/common/IfPermitted.test.jsx
Labels: bug, ready-for-review

#5179 Adapting plugin archetype to recent changes.
  graylog-plugin-archetype/src/main/resources/archetype-resources/package.json
  graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml
  graylog-plugin-parent/pom.xml
Labels: ready-for-review

#5222 Improve Content Pack Constraints Overview
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
Labels: content-packs, ready-for-review

#5247 Upgrade moment and moment-timezone
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5250 Update netty to 4.1.31
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/util/ConnectionCounterTest.java
  pom.xml
Labels: ready-for-review

#5228 Prevent content packs to be deleted if installations exists
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java
  graylog2-web-interface/src/pages/ContentPacksPage.jsx
  graylog2-web-interface/src/pages/ShowContentPackPage.jsx
Labels: content-packs, ready-for-review
