Repository Graylog2/graylog2-server, pull requests merged in 2018-06, with the labels that each got.

#4817 Add button after to input component again
  graylog2-web-interface/src/components/bootstrap/Input.jsx
  graylog2-web-interface/src/components/bootstrap/Input.test.jsx
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
Labels: bug, ready-for-review

#4830 Load pipeline actions and stores through a provider
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
  graylog2-web-interface/src/components/pipelines/Stage.jsx
  graylog2-web-interface/src/components/pipelines/StageForm.jsx
  graylog2-web-interface/src/components/rules/RuleHelper.jsx
  graylog2-web-interface/src/components/rules/RuleList.jsx
  graylog2-web-interface/src/components/simulator/ProcessorSimulator.jsx
  graylog2-web-interface/src/injection/CombinedProvider.js
  graylog2-web-interface/src/pages/PipelineDetailsPage.jsx
  graylog2-web-interface/src/pages/RuleDetailsPage.jsx
  graylog2-web-interface/src/pages/RulesPage.jsx
  graylog2-web-interface/src/stores/codecs/CodecTypesStore.js
  graylog2-web-interface/src/stores/pipelines/PipelineConnectionsStore.js
  graylog2-web-interface/src/stores/pipelines/PipelinesStore.js
  graylog2-web-interface/src/stores/rules/RulesStore.js
  graylog2-web-interface/src/stores/simulator/SimulatorStore.js
Labels: ready-for-review

#4716 Add URL encode/decode functions `urlencode()` and `urldecode()`
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/urls/UrlDecode.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/urls/UrlEncode.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/urls.txt
Labels: feature, ready-for-review

#4849 Unbreak input throttling by publishing throttle state again
  graylog2-server/src/main/java/org/graylog2/periodical/ThrottleStateUpdaterThread.java
  graylog2-server/src/main/java/org/graylog2/shared/events/DeadEventLoggingListener.java
Labels: ready-for-review

#4850 Unbreak input throttling by publishing throttle state again
  graylog2-server/src/main/java/org/graylog2/periodical/ThrottleStateUpdaterThread.java
  graylog2-server/src/main/java/org/graylog2/shared/events/DeadEventLoggingListener.java
Labels: ready-for-review

#4851 Add content packs support for collectors and collector configurations
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/CollectorConfigurationFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/CollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/CollectorConfigurationEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/CollectorEntity.java
Labels: ready-for-review

#4853 Add option to render Wizard in horizontal
  graylog2-web-interface/src/components/common/Wizard.css
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/common/Wizard.md
  graylog2-web-interface/src/components/common/Wizard.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
Labels: ready-for-review

#4826 Preventing index size/time input to hide rotation strategy dropdown.
  graylog2-web-interface/src/components/common/Select.css
  graylog2-web-interface/src/components/common/Select.jsx
Labels: bug, ready-for-review

#4867 Check for permission before terminating input.
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
Labels: bug, ready-for-review, security

#4868 Requires user to be authenticated to retrieve plugin list.
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/SystemPluginResource.java
Labels: bug, ready-for-review, security

#4873 Add missing permission checks
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/LookupTableTesterResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Labels: ready-for-review, security

#4875 Requires user to be authenticated to retrieve plugin list
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/SystemPluginResource.java
Labels: ready-for-review

#4878 Add missing permission checks
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/LookupTableTesterResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Labels: bug, ready-for-review

#4880 Preventing index size/time input to hide rotation strategy dropdown
  graylog2-web-interface/src/components/common/Select.css
  graylog2-web-interface/src/components/common/Select.jsx
Labels: ready-for-review

#4879 Allocating unused port for Jersey Test Container.
  graylog2-server/src/test/java/org/graylog2/rest/GenericErrorCsvWriterTest.java
Labels: bug, ready-for-review

#4877 Move RequiresAuthentication annotation to the top of sidecar endpoints
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ActionResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/AdministrationResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
Labels: ready-for-review

#4809 New grok pattern input component
  graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx
  graylog2-web-interface/src/components/grok-patterns/EditPatternModal.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.css
  graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.test.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatterns.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
Labels: feature, ready-for-review, web
