Repository Graylog2/graylog2-server, pull requests merged in 2018-07, with the labels that each got.

#4798 Add stream ID to stream rule metrics name
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/streams/StreamMetrics.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
  graylog2-server/src/test/java/org/graylog2/streams/StreamMetricsTest.java
Labels: improvement, ready-for-review

#4881 Move back to upstream java-grok library
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/GrokResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/GrokTesterResource.java
  graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java
  pom.xml
Labels: ready-for-review

#4884 Improve log messages for alert conditions and configuration requests
  graylog2-server/src/main/java/org/graylog2/alerts/AlertConditionFactory.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/ConfigurationRequest.java
Labels: improvement, ready-for-review

#4886 Change collector status data from a map to a set of objects
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/filter/StatusAdministrationFilter.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/CollectorStatus.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/CollectorStatusList.java
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
Labels: ready-for-review, sidecar

#4893 Map widget improvements
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/maps/widgets/MapVisualization.jsx
  graylog2-web-interface/src/components/maps/widgets/index.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#4846 Make "keyword" field type enumerable instead of full-text searchable
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeMapper.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/FieldTypeMapperTest.java
Labels: ready-for-review

#4902 Escape Typeahead templates content
  graylog2-web-interface/src/components/common/TypeAheadInput.jsx
  graylog2-web-interface/src/components/search/QueryInput.ts
Labels: ready-for-review

#4888 Avoid creating duplicate Grok patterns
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V2018070614390000_EnforceUniqueGrokPatterns.java
  graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V2018070614390000_EnforceUniqueGrokPatternsTest.java
Labels: bug, ready-for-review

#4901 Ensure mandatory parameters in search resources are valid
  graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/AbsoluteRange.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/DecoratorResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/SavedSearchesResource.java
  graylog2-server/src/test/java/org/graylog2/plugin/indexer/searches/timeranges/AbsoluteRangeTest.java
Labels: bug, ready-for-review

#4894 Add missing spacing in ExpandableListItem
  graylog2-web-interface/src/components/common/ExpandableListItem.css
Labels: ready-for-review

#4906 Fix potential NullPointerException in csv and maxmind data adapters
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/plugin/utilities/FileInfo.java
  graylog2-server/src/test/java/org/graylog2/plugin/utilities/FileInfoTest.java
Labels: ready-for-review

#4912 Fix potential NullPointerException in csv and maxmind data adapters
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/plugin/utilities/FileInfo.java
  graylog2-server/src/test/java/org/graylog2/plugin/utilities/FileInfoTest.java
Labels: ready-for-review

#4917 Fixing `Date.now` for WidgetFooter tests.
  graylog2-web-interface/src/components/widgets/WidgetFooter.test.jsx
Labels: bug, ready-for-review

#4840 Ensure that only SMTPS or SMTP with STARTTLS can be used at the same time
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/configuration/EmailConfiguration.java
  graylog2-server/src/test/java/org/graylog2/configuration/EmailConfigurationTest.java
  misc/graylog.conf
Labels: ready-for-review

#4911 Encode URI query string params in DataAdapters query
  graylog2-web-interface/src/stores/lookup-tables/LookupTableDataAdaptersStore.js
  graylog2-web-interface/src/stores/lookup-tables/LookupTablesStore.js
Labels: ready-for-review

#4929 Remove debug console.log
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
Labels: ready-for-review

#4924 Set `displayName` for mocked components.
  graylog2-web-interface/test/helpers/mocking/MockComponent.jsx
Labels: ready-for-review

#4949 Fix overlapping rows with long descriptions
  graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.css
  graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameterList.css
  graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
Labels: ready-for-review

#4934 List Content Pack Installations
  graylog2-web-interface/src/actions/content-packs/ContentPacksActions.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstallView.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstallations.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstallations.test.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/pages/ShowContentPackPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/content-packs/ContentPacksStore.jsx
Labels: ready-for-review
