Repository Graylog2/graylog2-server, pull requests merged in 2018-12, with the labels that each got.

#5307 Fix react CSS warning
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
Labels: ready-for-review

#5328 Guarding against `undefined` in `isPermitted`/`isAnyPermitted`.
  graylog2-web-interface/src/components/common/IfPermitted.test.jsx
  graylog2-web-interface/src/util/PermissionsMixin.js
  graylog2-web-interface/src/util/PermissionsMixin.test.js
Labels: bug, ready-for-review

#5309 Create value classes for Content Packs
  graylog2-web-interface/src/components/content-packs/ContentPackDetails.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEdit.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstall.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameterList.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameters.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackPreview.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackVersions.test.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/logic/content-packs/ContentPack.js
  graylog2-web-interface/src/logic/content-packs/ContentPack.test.js
  graylog2-web-interface/src/logic/content-packs/ContentPackRevisions.jsx
  graylog2-web-interface/src/pages/CreateContentPackPage.jsx
  graylog2-web-interface/src/pages/EditContentPackPage.jsx
  graylog2-web-interface/src/pages/ShowContentPackPage.jsx
  graylog2-web-interface/src/stores/content-packs/ContentPacksStore.jsx
Labels: content-packs, ready-for-review

#5351 Fix search query error with invalid time keyword query
  graylog2-web-interface/src/components/search/MalformedSearchQuery.jsx
Labels: bug, ready-for-review

#5296 Redirect to content pack overview if no content pack can be found
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
  graylog2-web-interface/src/pages/ShowContentPackPage.jsx
Labels: content-packs, ready-for-review

#5227 Add dependency resolution to InputFacade
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/LookupTableExtractor.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/inputs.json
Labels: content-packs, ready-for-review

#5320 Use nicer local css style class names for development
  graylog2-web-interface/webpack.config.js
Labels: infrastructure, ready-for-review

#5388 Add CSRF backward compatibility for older Sidecars
  graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
Labels: ready-for-review

#5299 Calculate necessary uninstall for content pack and display it for confirmation
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackUninstallDetails.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackUninstallation.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.json
  graylog2-web-interface/src/actions/content-packs/ContentPacksActions.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstallEntityList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstallEntityList.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstallView.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap
  graylog2-web-interface/src/pages/ShowContentPackPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/content-packs/ContentPacksStore.jsx
Labels: content-packs, ready-for-review

#5372 Create random ids for Entities in Content Packs
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelId.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityV1.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupCacheFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupTableFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineRuleFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
Labels: content-packs, ready-for-review, triaged

#5383 Port ES 6 support from 2.5 branch
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/RequestResponseLogger.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexTemplatesResource.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java
  pom.xml
Labels: ready-for-review

#5357 Keep Content Pack entities when creating a new version
  graylog2-web-interface/src/components/common/ExpandableListItem.css
  graylog2-web-interface/src/components/common/ExpandableListItem.jsx
  graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameters.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.css
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/logic/content-packs/ContentPack.js
  graylog2-web-interface/src/logic/content-packs/Entity.jsx
  graylog2-web-interface/src/logic/content-packs/EntityIndex.js
  graylog2-web-interface/src/pages/CreateContentPackPage.jsx
  graylog2-web-interface/src/pages/EditContentPackPage.jsx
  graylog2-web-interface/src/stores/content-packs/CatalogStore.jsx
Labels: bug, content-packs, ready-for-review, triaged

#5303 Add Sidecar collector configuration variables
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/SidecarModule.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/audit/SidecarAuditEventTypes.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Configuration.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/ConfigurationVariable.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationVariableResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationVariableService.java
  graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/ConfigurationServiceTest.java
  graylog2-web-interface/src/actions/sidecars/ConfigurationVariableActions.js
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationHelper.css
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationVariablesHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/EditConfigurationVariableModal.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/IncludesHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.jsx
  graylog2-web-interface/src/components/sidecars/configurations/CollectorList.css
  graylog2-web-interface/src/components/sidecars/configurations/ConfigurationList.css
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/pages/SidecarEditConfigurationPage.jsx
  graylog2-web-interface/src/pages/SidecarNewConfigurationPage.jsx
  graylog2-web-interface/src/stores/sidecars/ConfigurationVariableStore.js
Labels: feature, ready-for-review, sidecar

#5396 Updating module ids of vendor bundle.
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#5403 Fix config paths handling for ValueReference objects
  graylog2-web-interface/src/components/content-packs/ContentPackApplyParameter.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEntityConfig.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntityConfig.test.jsx.snap
  graylog2-web-interface/src/pages/EditContentPackPage.jsx
  graylog2-web-interface/src/util/ObjectUtils.js
  graylog2-web-interface/src/util/ObjectUtils.test.jsx
  graylog2-web-interface/src/util/ValueReferenceData.js
  graylog2-web-interface/src/util/ValueReferenceData.test.js
Labels: ready-for-review

#5407 Include alert conditions and alarm callbacks in content packs
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntityDescriptor.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/StreamAlarmCallbackEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/StreamAlertConditionEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/StreamEntity.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
Labels: ready-for-review

#5317 Add "requestOnMaster()" method to ProxiedResource
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java
  graylog2-server/src/test/java/org/graylog2/shared/rest/resources/ProxiedResourceTest.java
Labels: ready-for-review

#5389 Remove nonexistent "consistency" parameter from index/bulk requests
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
Labels: elasticsearch, ready-for-review

#5216 Add Bouncy Castle dependency
  graylog2-server/pom.xml
  pom.xml
Labels: improvement, ready-for-review, security

#5415 Avoid failing JSON deser. if ext. type is present, but prop is not.
  graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/SerializeSubtypedOptionalPropertiesTest.java
Labels: ready-for-review

#5400 Content Pack Dependency Resolution for Grok Extractors in Inputs
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/inputs.json
Labels: content-packs, ready-for-review

#5414 Rename requires to constraints and move it from top level to entity
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/RootEntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/UnsupportedEntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPack.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackV1.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/LegacyContentPack.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/GraylogVersionConstraint.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntitiesWithConstraints.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityV1.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contenpacks/responses/CatalogResolveResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/CatalogResource.java
  graylog2-server/src/main/resources/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns_Default_Grok_Patterns.json
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupCacheFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupTableFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineRuleFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/ContentPackTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/EntityTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/CatalogResourceTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/model/contentpack_reference.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/model/entities/entity_reference.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/model/expected_content_pack.json
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackPreview.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/logic/content-packs/Constraint.js
  graylog2-web-interface/src/logic/content-packs/Constraint.test.js
  graylog2-web-interface/src/logic/content-packs/ContentPack.js
  graylog2-web-interface/src/logic/content-packs/Entity.jsx
  graylog2-web-interface/src/pages/CreateContentPackPage.jsx
  graylog2-web-interface/src/pages/EditContentPackPage.jsx
Labels: bug, content-packs

#5410 Upgrade to Bootstrap 3.4.0
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review

#5428 Update to netty 4.1.32 and netty-tcnative-boringssl 2.0.20
  pom.xml
Labels: ready-for-review

#5431 Rename value and type in Value Reference
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/jackson/AsValueReferenceTypeDeserializer.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ValueReference.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ValueTyped.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/parameters/Parameter.java
  graylog2-server/src/main/resources/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns_Default_Grok_Patterns.json
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/jackson/ReferenceConverterTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/jackson/ValueReferenceTypeIdResolverTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/ContentPackTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ValueReferenceTest.java
  graylog2-server/src/test/java/org/graylog2/rest/models/system/contenpacks/responses/ContentPackInstallationRequestTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/model/contentpack_reference.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/model/expected_content_pack.json
  graylog2-web-interface/src/components/content-packs/ContentPackApplyParameter.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEntityConfig.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstall.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstall.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameters.test.jsx
  graylog2-web-interface/src/logic/content-packs/Entity.jsx
  graylog2-web-interface/src/util/ValueRefHelper.js
  graylog2-web-interface/src/util/ValueReferenceData.js
  graylog2-web-interface/src/util/ValueReferenceData.test.js
Labels: content-packs, ready-for-review

#5434 Fix dependency resolving for content packs
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/EntityDescriptorIds.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/RootEntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/UnsupportedEntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityV1.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityWithConstraints.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupCacheFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupTableFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineRuleFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/CatalogResourceTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/sidecar_configurations.json
  graylog2-web-interface/src/util/ValueRefHelper.js
  graylog2-web-interface/src/util/ValueRefHelper.test.js
Labels: ready-for-review

#5376 Sidecar migration helper
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/SidecarModule.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/periodical/PurgeExpiredConfigurationUploads.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/CollectorUpload.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/responses/CollectorUploadListResponse.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ImportService.java
  graylog2-web-interface/src/actions/sidecars/CollectorConfigurationsActions.js
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ImportsViewModal.jsx
  graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js
Labels: ready-for-review, sidecar
