Repository Graylog2/graylog2-server, pull requests merged in 2018-04, with the labels that each got.

#4697 SelectPopover improvements
  graylog2-web-interface/src/components/common/SelectPopover.jsx
Labels: ready-for-review

#4691 Add new Wizard Component to common
  graylog2-web-interface/src/components/common/Wizard.css
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/common/Wizard.md
  graylog2-web-interface/src/components/common/Wizard.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/common/index.jsx
Labels: feature, ready-for-review

#4685 Avoid DOM structure changes when there are no pages to show
  graylog2-web-interface/src/components/common/PaginatedList.jsx
Labels: ready-for-review, web

#4684 Some SearchForm.jsx improvements and fixes
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/common/SearchForm.md
Labels: ready-for-review, web

#4713 Move expanded list from enterprise to server
  graylog2-web-interface/src/components/common/ExpandableList.css
  graylog2-web-interface/src/components/common/ExpandableList.jsx
  graylog2-web-interface/src/components/common/ExpandableList.md
  graylog2-web-interface/src/components/common/ExpandableList.test.jsx
  graylog2-web-interface/src/components/common/ExpandableListItem.css
  graylog2-web-interface/src/components/common/ExpandableListItem.jsx
  graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap
  graylog2-web-interface/src/components/common/index.jsx
Labels: feature, ready-for-review

#4703 Disabling unreliable AbstractTcpTransportTest test case.
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
Labels: ready-for-review

#4715 Change select behaviour in SelectPopover
  graylog2-web-interface/src/components/common/SelectPopover.jsx
Labels: ready-for-review

#4723 Allow passing measureBeforeMount to ReactGridContainer.
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Labels: ready-for-review, web

#4726 Properly escape text in toastr
  graylog2-web-interface/src/util/UserNotification.js
Labels: ready-for-review

#4731 Clean-up DashboardList
  graylog2-web-interface/src/components/dashboard/DashboardList.jsx
  graylog2-web-interface/src/components/dashboard/DashboardListPage.jsx
Labels: ready-for-review

#4719 Add `regex_replace()` function to replace parts of strings backed by regular expressions
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/RegexReplace.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/regexReplace.txt
Labels: feature, ready-for-review

#4735 Fixing typo in proptypes.
  graylog2-web-interface/src/pages/EditTokensPage.jsx
Labels: ready-for-review

#4733 Add support for int values in SearchQuery
  graylog2-server/src/main/java/org/graylog2/search/SearchQueryField.java
  graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java
  graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java
Labels: ready-for-review

#4720 More detailed error message for missing Grok patterns
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
  graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/GrokTesterResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/responses/GrokTesterResponse.java
  graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
  graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/tools/GrokTesterResourceTest.java
  graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.jsx
  pom.xml
Labels: bug, ready-for-review

#4737 Cleanup node_modules in plugins like we do in the main web interface
  graylog-plugin-parent/pom.xml
Labels: ready-for-review

#4730 Set dashboard title and description with React
  graylog2-web-interface/src/components/dashboard/Dashboard.jsx
  graylog2-web-interface/src/components/dashboard/EditDashboardModal.jsx
  graylog2-web-interface/src/pages/ShowDashboardPage.jsx
Labels: ready-for-review

#4738 Disable automatic retries and replace Jest retries
  graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/GraylogJestRetryHandler.java
  pom.xml
Labels: ready-for-review

#4698 Remove Drools-based blacklist
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/bindings/MessageFilterBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/filters/FilterService.java
  graylog2-server/src/main/java/org/graylog2/filters/FilterServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/filters/RulesFilter.java
  graylog2-server/src/main/java/org/graylog2/filters/blacklist/BlacklistFieldEqualityCondition.java
  graylog2-server/src/main/java/org/graylog2/filters/blacklist/BlacklistIpMatcherCondition.java
  graylog2-server/src/main/java/org/graylog2/filters/blacklist/BlacklistPatternCondition.java
  graylog2-server/src/main/java/org/graylog2/filters/blacklist/FilterDescription.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/filters/BlacklistSourceResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
  graylog2-server/src/main/resources/blacklist.drl
  graylog2-server/src/main/resources/log4j2.xml
  graylog2-server/src/test/java/org/graylog2/filters/FilterServiceImplTest.java
  graylog2-server/src/test/java/org/graylog2/filters/blacklist/BlacklistFieldEqualityConditionTest.java
  graylog2-server/src/test/java/org/graylog2/filters/blacklist/BlacklistIpMatcherConditionTest.java
  graylog2-server/src/test/java/org/graylog2/filters/blacklist/BlacklistPatternConditionTest.java
  misc/graylog.drl
Labels: ready-for-review

#4734 Add prop to render help trigger in SearchForm component
  graylog2-web-interface/src/components/common/SearchForm.css
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/common/SearchForm.md
Labels: ready-for-review

#4739 Set dashboard title and description with React
  graylog2-web-interface/src/components/dashboard/Dashboard.jsx
  graylog2-web-interface/src/components/dashboard/EditDashboardModal.jsx
  graylog2-web-interface/src/pages/ShowDashboardPage.jsx
Labels: ready-for-review

#4743 Maintaining saved search id across search execution.
  graylog2-web-interface/src/components/search/SearchBar.jsx
Labels: bug, ready-for-review

#4744 Maintaining saved search id across search execution
  graylog2-web-interface/src/components/search/SearchBar.jsx
Labels: ready-for-review

#4752 Make sure to reload the default stream if it has been changed
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultStreamProvider.java
  graylog2-server/src/main/java/org/graylog2/streams/DefaultStreamChangeHandler.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
Labels: ready-for-review

#4754 Make sure to reload the default stream if it has been changed 2.4 backport
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultStreamProvider.java
  graylog2-server/src/main/java/org/graylog2/streams/DefaultStreamChangeHandler.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
Labels: ready-for-review

#4750 Implement HTTP proxy server authentication in OkHttpClientProvider
  graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
  misc/graylog.conf
Labels: ready-for-review

#4758 Implement HTTP proxy server authentication in OkHttpClientProvider
  graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
  misc/graylog.conf
Labels: ready-for-review

#4749 Replacing babel es2015 preset with env preset.
  graylog2-web-interface/.babelrc
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/.babelrc
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/graylog-web-plugin/yarn.lock
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, web

#4740 Upgrade to java-grok 0.1.9-graylog to allow commas in date patterns
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
  pom.xml
Labels: bug, ready-for-review

#4279 Retain timezone if date pattern contains TZ
  graylog2-server/src/main/java/org/graylog2/inputs/converters/DateConverter.java
  graylog2-server/src/test/java/org/graylog2/inputs/converters/DateConverterTest.java
Labels: bug, ready-for-review
