Repository Graylog2/graylog2-server, pull requests merged in 2019-02, with the labels that each got.

#5641 Remove unused template variables
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java
  graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.jsx
Labels: ready-for-review, sidecar

#5642 Remove unused template variables 3.0 backport
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java
  graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.jsx
Labels: ready-for-review

#5666 Fix checkboxes on lookup tables
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx
  graylog2-web-interface/src/components/lookup-tables/caches/GuavaCacheFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Labels: blocker, ready-for-review

#5668 Fix checkboxes on lookup tables (#5666)
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx
  graylog2-web-interface/src/components/lookup-tables/caches/GuavaCacheFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Labels: ready-for-review

#5669 Fix slow loading UI after server startup
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityBinding.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityContextFilter.java
Labels: performance, ready-for-review

#5671 Fix test depending on Graylog minor version.
  graylog2-web-interface/src/routing/AppErrorBoundary.test.jsx
  graylog2-web-interface/src/routing/__snapshots__/AppErrorBoundary.test.jsx.snap
Labels: ready-for-review

#5703 Prevent double prefixing paths for navigation items in system menu.
  graylog2-web-interface/src/components/navigation/NavigationLink.jsx
  graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx
Labels: ready-for-review

#5734 Mask password fields of inputs returned by the REST API. (#5432)
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
  graylog2-server/src/main/java/org/graylog2/shared/inputs/InputDescription.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/inputs/InputsResourceMaskingPasswordsTest.java
Labels: ready-for-review

#5733 Mask password fields of inputs returned by the REST API. (#5432)
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
  graylog2-server/src/main/java/org/graylog2/shared/inputs/InputDescription.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/inputs/InputsResourceMaskingPasswordsTest.java
Labels: ready-for-review
