Repository Graylog2/graylog2-server, pull requests merged in 2019-03, with the labels that each got.

#5738 Add GracefulShutdownService
  graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericInitializerBindings.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdownHook.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdownService.java
  graylog2-server/src/test/java/org/graylog2/system/shutdown/GracefulShutdownServiceTest.java
Labels: ready-for-review

#5739 Add GracefulShutdownService
  graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericInitializerBindings.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdownHook.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdownService.java
  graylog2-server/src/test/java/org/graylog2/system/shutdown/GracefulShutdownServiceTest.java
Labels: ready-for-review

#5741 Upgrading to React 16.8.3.
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5748 Update to hi-res logo & favicon as well as optimize all image files
  graylog2-web-interface/public/images/auth/loginbg.jpg
  graylog2-web-interface/public/images/favicon.png
  graylog2-web-interface/public/images/not-found-bg.jpg
  graylog2-web-interface/public/images/topbg.png
  graylog2-web-interface/public/images/toplogo.png
  graylog2-web-interface/public/images/toplogo.svg
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/components/navigation/NavigationBrand.jsx
  graylog2-web-interface/templates/index.html.template
Labels: improvement

#5751 Fix AdjustDashboardPosition Migration
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardImpl.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolutionTest.java
Labels: backport, bug, dashboards, ready-for-review

#5763 Fix AdjustDashboardPosition Migration
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardImpl.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolutionTest.java
Labels: backport, bug, dashboards, ready-for-review

#5730 Add support of wildcards in query parser
  graylog2-web-interface/src/logic/search/queryParser.test.js
  graylog2-web-interface/src/logic/search/queryParser.ts
Labels: ready-for-review

#5725 Fix HTTP 100 handling in http inputs
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
Labels: backport, bug, inputs, ready-for-review

#5728 Fix http input keep-alive handling
  graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/HttpHandler.java
Labels: backport, bug, inputs, ready-for-review

#5768 Fix HTTP 100 handling in http inputs (#5725)
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
Labels: backport, ready-for-review

#5769 Fix http input keep-alive handling (#5728)
  graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/HttpHandler.java
Labels: backport, ready-for-review

#5670 Server changes for Forwarder
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java
  graylog2-server/src/main/java/org/graylog2/initializers/OutputSetupService.java
  graylog2-server/src/main/java/org/graylog2/outputs/MessageOutputFactory.java
  graylog2-server/src/main/java/org/graylog2/plugin/GlobalMetricNames.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
  graylog2-server/src/main/java/org/graylog2/plugin/outputs/MessageOutput.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/outputs/MessageOutputFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
Labels: ready-for-review

#5771 Fix missing guice bindings for MessageOutput.Factory2
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
Labels: ready-for-review

#5765 Prevent double prefixing paths for navigation items in system menu.
  graylog2-web-interface/src/components/navigation/NavigationLink.jsx
  graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx
Labels: ready-for-review

#5766 Add support of wildcards in query parser (3.0)
  graylog2-web-interface/src/logic/search/queryParser.test.js
  graylog2-web-interface/src/logic/search/queryParser.ts
Labels: ready-for-review

#5756 Remove commented code
  graylog2-web-interface/src/components/navigation/NavigationBrand.jsx
Labels: ready-for-review

#5749 Flatten grok pattern result when applied with OR
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java
  graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/GrokTesterResource.java
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
Labels: backport, bug, ready-for-review

#5790 Flatten grok pattern result when applied with OR
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java
  graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/GrokTesterResource.java
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
Labels: backport, bug, ready-for-review

#5791 Allowing to retrieve current state from `InputsStore`.
  graylog2-web-interface/src/stores/inputs/InputsStore.js
Labels: ready-for-review

#5729 Fix Cisco ASA netflow handling
  graylog2-server/src/main/java/org/graylog/plugins/netflow/flows/NetFlowFormatter.java
  graylog2-server/src/main/java/org/graylog/plugins/netflow/v9/NetFlowV9FieldDef.java
  graylog2-server/src/main/resources/netflow9.yml
  graylog2-server/src/test/java/org/graylog/plugins/netflow/codecs/NetflowV9CodecAggregatorTest.java
  graylog2-server/src/test/resources/netflow-data/cisco-asa-netflowv9.pcap
Labels: bug, inputs, ready-for-review

#5792 Fix Cisco ASA netflow handling (#5729)
  graylog2-server/src/main/java/org/graylog/plugins/netflow/flows/NetFlowFormatter.java
  graylog2-server/src/main/java/org/graylog/plugins/netflow/v9/NetFlowV9FieldDef.java
  graylog2-server/src/main/resources/netflow9.yml
  graylog2-server/src/test/java/org/graylog/plugins/netflow/codecs/NetflowV9CodecAggregatorTest.java
  graylog2-server/src/test/resources/netflow-data/cisco-asa-netflowv9.pcap
Labels: backport, ready-for-review

#5678 Do not show an "(optional)" for boolean configuration fields
  graylog2-web-interface/src/components/configurationforms/FieldHelpers.jsx
Labels: improvement, ready-for-review, ux

#5764 Add comment about MongoDB username/password escaping
  misc/graylog.conf
Labels: ready-for-review

#5800 Switch back to a repackaged and fixed version of java-grok
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/java/org/graylog2/grok/GrokPatternServiceTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok.txt
  pom.xml
Labels: backport, ready-for-review

#5807 Switch back to a repackaged and fixed version of java-grok (#5800)
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/java/org/graylog2/grok/GrokPatternServiceTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok.txt
  pom.xml
Labels: ready-for-review

#5795 Add comment about MongoDB username/password escaping (#5764)
  misc/graylog.conf
Labels: ready-for-review

#5817 Forwarder server changes (backport)
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java
  graylog2-server/src/main/java/org/graylog2/initializers/OutputSetupService.java
  graylog2-server/src/main/java/org/graylog2/outputs/MessageOutputFactory.java
  graylog2-server/src/main/java/org/graylog2/plugin/GlobalMetricNames.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
  graylog2-server/src/main/java/org/graylog2/plugin/outputs/MessageOutput.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/outputs/MessageOutputFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
Labels: ready-for-review

#5818 Fix problem with captureFlattened
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
  pom.xml
Labels: backport, bug, ready-for-review

#5820 Fix problem with captureFlattened (#5818)
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
  pom.xml
Labels: ready-for-review

#5662 Fix transport_email_use_ssl to actual default
  misc/graylog.conf
Labels: ready-for-review
