Repository Graylog2/graylog2-server, pull requests merged in 2019-05, with the labels that each got.

#5894 Checking health of production build assets during compilation.
  graylog2-server/pom.xml
  graylog2-web-interface/checkProductionBuild.js
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5629 Give usefull message on default grok patterns fail
  graylog2-server/src/main/java/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns.java
Labels: bug, content-packs, ready-for-review

#5937 Changing default build directory for production web asset health check.
  graylog2-web-interface/checkProductionBuild.js
  graylog2-web-interface/package.json
Labels: ready-for-review

#5938 Give useful message on default grok patterns fail
  graylog2-server/src/main/java/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns.java
Labels: bug, content-packs

#5923 Update to netty 4.1.36 and netty-tcnative-boringssl 2.0.25
  pom.xml
Labels: ready-for-review

#5861 Add `name` prop to Input component
  graylog2-web-interface/.gitignore
  graylog2-web-interface/src/components/bootstrap/Input.jsx
  graylog2-web-interface/src/components/bootstrap/Input.test.jsx
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/pages/LoginPage.jsx
Labels: ready-for-review, ux

#5665 Fix auto-completion in several drop-down fields
  graylog2-web-interface/src/components/extractors/converters_configuration/LookupTableConverterConfiguration.jsx
  graylog2-web-interface/src/components/extractors/extractors_configuration/LookupTableExtractorConfiguration.jsx
  graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.jsx
  graylog2-web-interface/src/components/lookup-tables/CacheCreate.jsx
  graylog2-web-interface/src/components/lookup-tables/CachePicker.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterCreate.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterPicker.jsx
  graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.jsx
Labels: ready-for-review

#5954 Do not initialize `inputs` variable to prevent merging duplicate key in.
  graylog2-web-interface/src/pages/ExtractorsPage.jsx
Labels: ready-for-review

#5956 Fix auto-completion in several drop-down fields
  graylog2-web-interface/src/components/extractors/converters_configuration/LookupTableConverterConfiguration.jsx
  graylog2-web-interface/src/components/extractors/extractors_configuration/LookupTableExtractorConfiguration.jsx
  graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.jsx
  graylog2-web-interface/src/components/lookup-tables/CacheCreate.jsx
  graylog2-web-interface/src/components/lookup-tables/CachePicker.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterCreate.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterPicker.jsx
  graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.jsx
Labels: backport, ready-for-review

#5953 Fix link to global output list on stream output page.
  graylog2-web-interface/src/pages/StreamOutputsPage.jsx
Labels: ready-for-review

#5967 Upgrade jquery to 3.4.1
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, security

#5968 Remove unused import
  graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/ShardRouting.java
Labels: ready-for-review

#5974 Allow specifying view for `PaginatedService`.
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Labels: ready-for-review
