Repository Graylog2/graylog2-server, pull requests merged in 2019-12, with the labels that each got.

#6885 Fix error on adding field to Event Definition
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
Labels: ready-for-review

#6893 Adding Area Chart Visualization type.
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.fixtures.js
  graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.jsx
Labels: ready-for-review, search

#6865 Guard against empty metrics array
  graylog2-web-interface/src/components/metrics/MetricContainer.jsx
  graylog2-web-interface/src/logic/metrics/MetricsExtractor.js
  graylog2-web-interface/src/stores/metrics/MetricsStore.js
Labels: ready-for-review

#6878 Update disabled Dropdown style
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/NavDropdown.md
  graylog2-web-interface/src/components/graylog/styles/menuItem.js
  graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
Labels: ready-for-review, ux

#6891 Updating vendor module ids
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#6902 Adding interpolation options for line/area visualizations.
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AreaVisualizationConfigDTO.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/Interpolation.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/LineVisualizationConfigDTO.java
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AreaVisualizationConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/LineVisualizationConfiguration.jsx
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/AreaVisualizationConfig.js
  graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/BarVisualizationConfig.js
  graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/Interpolation.js
  graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/LineVisualizationConfig.js
Labels: search

#6894 Implement error boundary for widgets.
  graylog2-web-interface/src/views/components/widgets/ErrorWidget.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.test.jsx
Labels: ready-for-review, search

#6906 Improve styled-components performance with useMemo
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackUploadControls.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/components/graylog/Badge.jsx
  graylog2-web-interface/src/components/graylog/Button.jsx
  graylog2-web-interface/src/components/graylog/FormControl.jsx
  graylog2-web-interface/src/components/graylog/Jumbotron.jsx
  graylog2-web-interface/src/components/graylog/Label.jsx
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
  graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
  graylog2-web-interface/src/components/widgets/__snapshots__/WidgetFooter.test.jsx.snap
  graylog2-web-interface/src/pages/ErrorJumbotron.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
Labels: ready-for-review

#6921 Update Alert Wizard styles
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.css
Labels: ready-for-review, ux

#6916 Adjust ErrorWidget layout gabs and add basic component test
  graylog2-web-interface/src/views/components/widgets/ErrorWidget.jsx
  graylog2-web-interface/src/views/components/widgets/ErrorWidget.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageWidgets.css
Labels: ready-for-review, search

#6845 Centralize logic to get current view from store, when executing the search
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: ready-for-review, search

#6908 Fix tests by using JSONAssert equals
  graylog2-server/pom.xml
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ValueReferenceTest.java
Labels: processing, ready-for-review

#6929 Add missing HTTPJsonPath Data adapter type
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java
Labels: blocker, bug, ready-for-review

#6096 Bring back content pack autoload
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
  graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java
  misc/graylog.conf
Labels: content-packs, feature, ready-for-review

#6943 Fall back to first search type result to extract effective timerange.
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.test.jsx
Labels: ready-for-review, search

#6492 Scratchpad implemented
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/components/common/InteractableModal.jsx
  graylog2-web-interface/src/components/common/InteractableModal.test.jsx
  graylog2-web-interface/src/components/common/Scratchpad.jsx
  graylog2-web-interface/src/components/common/Scratchpad.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/InteractableModal.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Scratchpad.test.jsx.snap
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/graylog/Navbar.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/ScratchpadToggle.jsx
  graylog2-web-interface/src/providers/ScratchpadProvider.jsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/routing/AppWithGlobalNotifications.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, ux

#6945 Make aggregation field clearable
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
Labels: ready-for-review

#6940 Update to netty 4.1.43 and netty-tcnative-boringssl 2.0.28
  pom.xml
Labels: ready-for-review

#6948 Remove "tests have passed" option from PR template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-review

#6938 Fix typo in package name: contenpacks -> contentpacks
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceService.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/CatalogIndexResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/CatalogResolveRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/CatalogResolveResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/ContentPackInstallationRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/ContentPackInstallationsResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/ContentPackList.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/ContentPackMetadata.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/ContentPackResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/contentpacks/responses/ContentPackRevisions.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/CatalogResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
  graylog2-server/src/test/java/org/graylog2/rest/models/system/contentpacks/responses/ContentPackInstallationRequestTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/CatalogResourceTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java
Labels: content-packs, ready-for-review

#6947 Improve flow config: exclude `node_modules`, include `test` completely.
  graylog2-web-interface/.flowconfig
Labels: ready-for-review

#6932 Remove legacy views permissions
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/LegacyViewsPermissions.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20180817120900_AddViewsUsers.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20181220133700_AddViewsAdminRole.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191204000000_RemoveLegacyViewsPermissions.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsRestPermissions.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20190304102700_MigrateMessageListStructureTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191204000000_RemoveLegacyViewsPermissionsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20190304102700_MigrateMessageListStructureTest.json
Labels: search

#6958 Dont append a dot if exception ends with an exclamation mark
  graylog2-server/src/main/java/org/graylog2/shared/utilities/ExceptionUtils.java
Labels: ready-for-review

#6957 Do not limit terms size when determining stream ids contained in index.
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
Labels: ready-for-review

#6873 Allow pipelines connected to "All messages" in content packs
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/EntityDescriptorIds.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java
  graylog2-server/src/main/java/org/graylog2/plugin/streams/Stream.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/pipeline_processor_pipelines_default_stream.json
Labels: content-packs, ready-for-review

#6956 Security update to jackson 2.9.10.20191020
  pom.xml
Labels: dependencies, ready-for-review, security

#6955 Improve API browser for several resources
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorParameters.java
  graylog2-server/src/main/java/org/graylog/events/rest/AvailableEntityTypesResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchParameters.java
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchResult.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/processing/ProcessingStatusSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbackHistoryResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbacksResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/StreamAlarmCallbackResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alerts/AlertResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/AlertConditionsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertResource.java
Labels: ready-for-review

#6967 Do not limit terms size when determining stream ids contained in index
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
Labels: backport, ready-for-review

#6890 Render events in timebased bar, line and scatter charts
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AggregationConfigDTO.java
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.jsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.js
  graylog2-web-interface/src/views/logic/aggregationbuilder/WidgetFormattingSettings.js
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.test.js
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/__snapshots__/PivotConfigGenerator.test.js.snap
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.js
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.test.js
  graylog2-web-interface/src/views/logic/searchtypes/events/__snapshots__/EventHandler.test.js.snap
Labels: ready-for-review, search

#6852 Fix DataTable filter to reapply filter after data updates
  graylog2-web-interface/src/components/common/DataTable.jsx
  graylog2-web-interface/src/components/common/TypeAheadDataFilter.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntityConfig.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
Labels: ready-for-review

#6959 Update styled-components flow typing to latest
  graylog2-web-interface/flow-typed/npm/styled-components_v4.x.x.js
Labels: ready-for-review

#6962 Update Trend render and test
  graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
  graylog2-web-interface/src/views/components/visualizations/number/Trend.test.jsx
Labels: ready-for-review, ux

#6934 Implement bootstrap grid component for extended search page
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/Query.jsx
  graylog2-web-interface/src/views/components/QueryTabs.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/SearchResult.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: ready-for-review, search

#6980 Add missing test for MigrationHelpers class
  graylog2-server/src/test/java/org/graylog2/migrations/MigrationHelpersTest.java
Labels: ready-for-review

#6984 Build list result for reverse dns lookups
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java
Labels: ready-for-review

#6925 Migrating Saved Searches to Views.
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViews.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/AbsoluteTimeRangeQuery.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/KeywordTimeRangeQuery.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/Query.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/RelativeTimeRangeQuery.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/SavedSearch.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/SavedSearchService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/AutoInterval.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/BucketInterval.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/MessagesSearchType.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/Pivot.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/Query.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/SearchService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/SearchType.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/SeriesSpec.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/Time.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/AbsoluteRange.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/AggregationConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/AggregationWidget.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/AutoInterval.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/ElasticsearchQueryString.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/Interval.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/KeywordRange.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/MessagesWidget.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/MessagesWidgetConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/Pivot.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/Position.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/RandomObjectIdProvider.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/RandomUUIDProvider.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/RelativeRange.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/Series.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/TimeHistogramConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/TimeRange.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/Titles.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/View.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/ViewService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/ViewState.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/ViewWidget.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/ViewWidgetPosition.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute-expected_searches.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword-expected_searches.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative-expected_searches.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative.json
Labels: ready-for-review, search

#6897 Add support for lookup table backed parameters
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationResult.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/ValueParameter.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/EmptyParameterError.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/ParameterExpansionError.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTable.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/QualifyingViewsServiceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/RequiresParameterSupportTest.java
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EditQueryParameterModal.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/logic/parameters/LookupTableParameter.js
  graylog2-web-interface/src/views/logic/parameters/Parameter.js
  graylog2-web-interface/src/views/logic/parameters/ParameterBinding.js
  graylog2-web-interface/src/views/logic/parameters/ValueParameter.js
  graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.Dashboard-Search.fixture.json
  graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.js
  graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.Search.fixture.json
  graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.js
Labels: ready-for-review

#6994 Reimplementing page showing single message ("permalink") using views components.
  graylog2-web-interface/src/pages/ShowMessagePage.fixtures.js
  graylog2-web-interface/src/pages/ShowMessagePage.jsx
  graylog2-web-interface/src/pages/ShowMessagePage.test.jsx
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/views/components/CustomPropTypes.js
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Value.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageActions.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageMetadata.jsx
Labels: ready-for-review

#6964 Migrate search page field charts
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/MigrateFieldCharts.jsx
  graylog2-web-interface/src/views/components/__tests__/MigrateFieldCharts.fixtures.js
  graylog2-web-interface/src/views/components/__tests__/MigrateFieldCharts.test.jsx
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/TransformKeys.js
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
Labels: ready-for-review, search

#6992 Add pluggable elements rendered in widget edit mode.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/QueryResult.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
  graylog2-web-interface/src/routing/AppErrorBoundary.test.jsx
  graylog2-web-interface/src/views/components/WidgetOverrideElements.jsx
  graylog2-web-interface/src/views/components/WidgetOverrideElements.test.jsx
  graylog2-web-interface/src/views/components/contexts/QueryEditModeContext.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
  graylog2-web-interface/src/views/logic/QueryResult.js
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
  graylog2-web-interface/test/helpers/suppressConsole.js
  graylog2-web-interface/test/integration-environment.js
Labels: ready-for-review

#6995 Support existing search URLs in new search page
  graylog2-web-interface/src/views/Constants.js
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.js
  graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.js
  graylog2-web-interface/src/views/logic/views/View.js
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/pages/index.js
Labels: ready-for-review, search

#7007 Including optional stream from saved searches when generating query.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViews.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/AbsoluteTimeRangeQuery.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/KeywordTimeRangeQuery.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/Query.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/RelativeTimeRangeQuery.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/Query.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/StreamFilter.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream-expected_searches.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream.json
Labels: ready-for-review, search

#6998 Defaulting to new search.
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/views/bindings.jsx
Labels: ready-for-review, search

#7010 Mapping months to `M` instead of `m` for time pivots.
  graylog2-web-interface/src/views/Constants.js
  graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/TimeUnitTimeHistogramPivot.jsx
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.test.js
Labels: bug, ready-for-review, search

#7008 Consolidating different handling of query strings in searches/dashboards.
  graylog2-web-interface/src/stores/StoreTypes.js
  graylog2-web-interface/src/views/components/actions/ActionHandler.jsx
  graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.js
  graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.js
  graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/QueryManipulationHandler.js
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.js
  graylog2-web-interface/src/views/stores/QueriesStore.js
  graylog2-web-interface/src/views/stores/ViewStore.js
Labels: bug, ready-for-review, search

#7011 Only show field chart migration info on search page
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/MigrateFieldCharts.jsx
Labels: ready-for-review, search

#6966 Supporting decorators in new views-based Search.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageList.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/messagelist/MessageListConfigDTO.java
  graylog2-server/src/main/java/org/graylog2/decorators/DecoratorProcessor.java
  graylog2-server/src/main/java/org/graylog2/decorators/DecoratorProcessorImpl.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageListTest.java
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/configurations/DecoratorsConfig.jsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsConfigUpdate.jsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsUpdater.js
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsUpdater.test.jsx
  graylog2-web-interface/src/components/configurations/decorators/FormatDecorator.jsx
  graylog2-web-interface/src/components/configurations/decorators/StreamSelect.jsx
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
  graylog2-web-interface/src/stores/streams/StreamsStore.js
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/DecoratorValue.jsx
  graylog2-web-interface/src/views/components/TypeSpecificValue.jsx
  graylog2-web-interface/src/views/components/Value.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageField.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx
  graylog2-web-interface/src/views/components/messagelist/Types.js
  graylog2-web-interface/src/views/components/messagelist/decorators/AddDecoratorButton.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorList.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSidebar.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSummary.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/InlineForm.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/PopoverHelp.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/Types.js
  graylog2-web-interface/src/views/components/messagelist/decorators/decoratorStyles.css
  graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx
  graylog2-web-interface/src/views/components/widgets/EditMessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/src/views/logic/NewQueryActionHandler.js
  graylog2-web-interface/src/views/logic/Widgets.js
  graylog2-web-interface/src/views/logic/fieldtypes/FieldType.js
  graylog2-web-interface/src/views/logic/searchtypes/MessageConfigGenerator.js
  graylog2-web-interface/src/views/logic/searchtypes/MessageConfigGenerator.test.jsx
  graylog2-web-interface/src/views/logic/searchtypes/SearchTypesGenerator.js
  graylog2-web-interface/src/views/logic/valueactions/UseInNewQueryHandler.js
  graylog2-web-interface/src/views/logic/views/ViewGenerator.js
  graylog2-web-interface/src/views/logic/views/ViewStateGenerator.js
  graylog2-web-interface/src/views/logic/views/ViewStateGenerator.test.jsx
  graylog2-web-interface/src/views/logic/views/ViewTransformer.test.js
  graylog2-web-interface/src/views/logic/widgets/MessagesWidgetConfig.js
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/stores/SearchStore.test.js
  graylog2-web-interface/src/views/stores/ViewStore.js
Labels: ready-for-review

#7027 Roll back complete widget when pressing cancel in widget edit modal.
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
Labels: bug, ready-for-review, search

#7029 Include time range type when changing time range parameter for widget.
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
Labels: bug, ready-for-review, search

#7026 Mention missing support for old dashboards in content packs
  UPGRADING.rst
Labels: content-packs, documentation, ready-for-review, search

#6982 Theme FormGroup
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/common/JSONValueInput.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/FormControl.md
  graylog2-web-interface/src/components/graylog/FormGroup.jsx
  graylog2-web-interface/src/components/graylog/InputGroup.jsx
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/styles/FormControlValidationStyles.jsx
  graylog2-web-interface/src/theme/styles/formControlValidationStyles.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/TimeUnitTimeHistogramPivot.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: ready-for-review

#6986 Update styled-components flow typing
  graylog2-web-interface/flow-typed/npm/styled-components_v4.x.x.js
Labels: ready-for-review

#7036 Ignore case when deserializing dashboard widgets in migration.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/Widget.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/WidgetConfigResolver.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard_installed_from_content_pack.json
Labels: bug, ready-for-review, search

#7034 Mark dashboards exported from search as 'isNew'
  graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
  graylog2-web-interface/src/views/stores/ViewStore.js
  graylog2-web-interface/src/views/stores/ViewStore.test.js
Labels: bug, ready-for-review, search

#7033 Change `Show documents for value` to use widget query instead of filter
  graylog2-web-interface/src/views/logic/queries/Query.js
  graylog2-web-interface/src/views/logic/queries/QueryGenerator.js
  graylog2-web-interface/src/views/logic/queries/QueryHelper.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
Labels: bug, ready-for-review, search

#7041 Copy time range & streams of widget for "Show documents" on dashboard.
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
Labels: bug, ready-for-review, search

#7043 Register search type generator for default widget.
  graylog2-web-interface/src/views/bindings.jsx
Labels: bug, ready-for-review, search

#7037 Handle optional fields when migrating widgets.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/FieldChartConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultChartConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultCountConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_searches.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget.json
Labels: bug, ready-for-review, search

#7042 Allow queries with empty search types.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTest.java
Labels: bug, ready-for-review, search

#7039 Handle orphaned widget positions in migration properly.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViews.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard.json
Labels: bug, ready-for-review, search

#7047 Fix version check of content packs in development
  graylog2-server/src/main/java/org/graylog2/contentpacks/constraints/GraylogVersionConstraintChecker.java
Labels: content-packs, ready-for-review

#7053 Resize plotly visualizations correctly when changing their width
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
Labels: bug, ready-for-review, search

#7046 Update StreamSearchPage when current stream id changes
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx
Labels: bug, ready-for-review, search

#7030 Enable 'Add to Table' action for message list widget
  graylog2-web-interface/src/views/logic/fieldactions/AddToTableActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromTableActionHandler.js
  graylog2-web-interface/src/views/logic/widgets/MessagesWidget.js
Labels: bug, ready-for-review, search

#7025 Fix message list edit modal scrolling
  graylog2-web-interface/src/views/components/widgets/EditMessageList.css
  graylog2-web-interface/src/views/components/widgets/EditMessageList.jsx
Labels: bug, ready-for-review, search

#7024 Add content pack to install Source Page as Dashboard
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20191219090834_AddSourcesPage.java
  graylog2-server/src/main/resources/org/graylog2/migrations/V20191219090834_AddSourcesPage_Content_Pack.json
  graylog2-server/src/test/java/org/graylog2/migrations/V20191219090834_AddSourcesPageTest.java
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/sources/SourceDataTable.jsx
  graylog2-web-interface/src/components/sources/SourceLineChart.jsx
  graylog2-web-interface/src/components/sources/SourceOverview.jsx
  graylog2-web-interface/src/components/sources/SourcePieChart.jsx
  graylog2-web-interface/src/components/sources/SourceTitle.jsx
  graylog2-web-interface/src/pages/SourcesPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: ready-for-review, search
