Repository Graylog2/graylog2-server, pull requests merged in 2019-07, with the labels that each got.

#6003 Add support for nested maps in list for Content Packs
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtils.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtilsTest.java
Labels: backport, bug, content-packs, ready-for-review

#6062 Add support for nesed maps in list for Content Packs (#6003)
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtils.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtilsTest.java
Labels: backport, content-packs, ready-for-review

#6026 Handle missing field type of selected field in MessageTableEntry.
  graylog2-web-interface/src/views/components/TypeSpecificValue.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageFields.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.test.jsx
Labels: ready-for-review

#6027 Modify index mappings for receive and processing timestamps
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesClusterConfig.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/plugin/journal/RawMessage.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
Labels: 3.1 Alerting - 3 release, alerting, elasticsearch

#6045 Do not refresh search if query input is blurred, but query is unchanged.
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
Labels: ready-for-review

#6048 Extracting `onZoom` function, using `tozero` for y axis's `rangemode`
  graylog2-web-interface/src/views/components/visualizations/OnZoom.js
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
Labels: ready-for-review

#6035 Updating OkHttp from 3.11.0 to 3.14.2.
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
  pom.xml
Labels: ready-for-review, security

#6034 Updating retrofit from 2.4.0 to 2.6.0.
  pom.xml
Labels: ready-for-review, security

#6052 Splitting out fat dependencies from main bundle.
  graylog2-web-interface/flow-typed/npm/react-overlays_vx.x.x.js
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/searchbar/AsyncQueryInput.js
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.jsx
  graylog2-web-interface/src/views/components/visualizations/plotly/AsyncPlot.js
  graylog2-web-interface/src/views/components/visualizations/plotly/Plot.js
  graylog2-web-interface/src/views/components/widgets/Histogram.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetFilterMenu.jsx
Labels: ready-for-review

#6053 Including `c3` and `d3` in vendor module.
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#6022 Implement receive & processing time tracking
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/processing/ProcessingStatusSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/processing/ClusterProcessingStatusResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/processing/RemoteSystemProcessingStatusResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/processing/SystemProcessingStatusResource.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericInitializerBindings.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/DirectMessageHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/RawMessageEncoderHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/RawMessageEvent.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
  graylog2-server/src/main/java/org/graylog2/system/processing/InMemoryProcessingStatusRecorder.java
  graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusConfig.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusDto.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusRecorder.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
  graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status.json
  misc/graylog.conf
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6066 Updating yarn lockfile.
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#6055 Event Definitions UI
  graylog2-web-interface/src/actions/event-definitions/AvailableEventDefinitionTypesActions.js
  graylog2-web-interface/src/actions/event-definitions/EventDefinitionsActions.js
  graylog2-web-interface/src/components/common/EmptyEntity.css
  graylog2-web-interface/src/components/common/EmptyEntity.jsx
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/event-definitions/common/commonStyles.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/event-definition-types/FilterAggregationFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/event-definition-types/FilterForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/event-definition-types/index.js
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/index.js
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/logic/alerts/AggregationExpressionParser.js
  graylog2-web-interface/src/logic/alerts/AggregationExpressionParser.test.js
  graylog2-web-interface/src/logic/alerts/EventDefinitionPriorityEnum.js
  graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/event-definitions/AvailableEventDefinitionTypesStore.js
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Labels: alerting, ready-for-review

#6072 Adding react hooks rules to ESLint config.
  graylog2-web-interface/packages/eslint-config-graylog/index.js
  graylog2-web-interface/packages/eslint-config-graylog/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#6087 Mocking FetchProvider globally for tests.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.jsx
  graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.test.jsx
  graylog2-web-interface/src/components/widgets/WidgetCreationModal.jsx
  graylog2-web-interface/src/stores/nodes/NodesStore.js
  graylog2-web-interface/test/mock-FetchProvider.js
Labels: ready-for-review

#6091 Improvements in Event Definitions page
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
  graylog2-server/src/main/java/org/graylog2/rest/models/PaginatedResponse.java
  graylog2-web-interface/src/actions/event-definitions/EventDefinitionsActions.js
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/index.js
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.css
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Labels: alerting, ready-for-review

#5982 Use GrokPatternRegistry to reload saved grok patterns
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/ExtractorFactory.java
  graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
Labels: bug, ready-for-review

#6078 Rename and add fields in EventIndexMapping
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
  graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6092 Reduce processing_status_persist_interval default value to 1 second
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusConfig.java
  misc/graylog.conf
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6095 Adapt to schema changes
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Labels: alerting, ready-for-review

#6089 Add migration to create events and system-events index sets and streams
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20190705071400_AddEventIndexSetsMigration.java
  graylog2-server/src/main/java/org/graylog2/plugin/streams/Stream.java
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6099 Add UI for Event Notifications filter
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
Labels: alerting, ready-for-review

#6100 Adapt frontend to changes in Event Processor actions
  graylog2-web-interface/src/components/event-definitions/event-definition-form/AddNotificationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationList.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/CommonNotificationSummary.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationSummary.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Labels: alerting, ready-for-review

#5958 Fix support for TLS input trusted certs directories
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/util/KeyUtil.java
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/util/KeyUtilTest.java
  graylog2-server/src/test/resources/org/graylog2/plugin/inputs/transports/util/certs/server.crt.ecdsa
  graylog2-server/src/test/resources/org/graylog2/plugin/inputs/transports/util/certs/server.crt.rsa
Labels: bug, inputs, ready-for-review

#6101 Change path in EventDefinitionsStore
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6102 Fix support for TLS input trusted certs directories
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/util/KeyUtil.java
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/util/KeyUtilTest.java
  graylog2-server/src/test/resources/org/graylog2/plugin/inputs/transports/util/certs/server.crt.ecdsa
  graylog2-server/src/test/resources/org/graylog2/plugin/inputs/transports/util/certs/server.crt.rsa
Labels: backport, bug, ready-for-review

#6105 Removing static message table artifacts.
  graylog2-web-interface/src/views/components/SearchResult.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: ready-for-review

#6090 Dynamic pager in message lists
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
Labels: improvement, ready-for-review, search

#6103 Using custom `instanceOf` prop-type in views.
  graylog2-web-interface/src/views/components/CustomPropTypes.js
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilderPropTypes.js
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.jsx
  graylog2-web-interface/src/views/components/views/View.jsx
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetPropTypes.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: ready-for-review

#6098 Apply custom highlighting only if field value matches configured value exactly.
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx
  graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.jsx.snap
Labels: ready-for-review, search

#6106 Removing `StopPropagation` wrapper from widget editing modal.
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
Labels: ready-for-review

#6109 Event grace period UI
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationList.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Labels: alerting, ready-for-review

#6111 Updating yarn lockfile.
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#6074 Generate a value for the "gl2_message_id" field for each new message
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
  pom.xml
Labels: 3.1 Alerting - 2 beta, ready-for-review

#6124 Events beta readiness
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationSummary.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6125 Completely remove customizable HttpNotification body
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
Labels: ready-for-review

#6126 Reset Event Definition configuration when type changes
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6128 Events overview page
  graylog2-web-interface/src/actions/events/EventsActions.js
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.css
  graylog2-web-interface/src/components/events/events/Events.css
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/events/events/EventsContainer.jsx
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
  graylog2-web-interface/src/pages/EventNotificationsPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
  graylog2-web-interface/src/stores/events/EventsStore.js
Labels: alerting, ready-for-review

#6131 Fields form improvements
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderForm.jsx
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6113 Using function instead of `arrayMove` from `react-sortable-hoc`.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/views/components/aggregationbuilder/SortableSelect.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, search

#6132 Add "gl2_message_id" field to MessageFieldsFilter in the UI
  graylog2-web-interface/src/logic/message/MessageFieldsFilter.js
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6130 Add more configuration options to email notification form
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
Labels: 3.1 Alerting - 2 beta, alerting, ready-for-review

#6134 Add description and help link in Events page
  graylog2-web-interface/src/pages/EventsPage.jsx
Labels: alerting, ready-for-review

#6136 Display all email configuration options in summary
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.css
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.jsx
Labels: alerting, ready-for-review

#6137 Display deleted Notifications in Event Definition form
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationList.jsx
Labels: alerting, ready-for-review

#6139 Show the event key in the event/alerts overview
  graylog2-web-interface/src/components/events/events/Events.jsx
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6135 Making `field` & `value` action handlers work consistently.
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Value.jsx
  graylog2-web-interface/src/views/components/Value.test.jsx
  graylog2-web-interface/src/views/components/actions/FieldActions.jsx
  graylog2-web-interface/src/views/components/actions/ValueActions.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageField.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
Labels: ready-for-review, search

#6150 Prefix plugin navigation item path with app prefix.
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
Labels: ready-for-review

#6144 Update code name for 3.1
  graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
Labels: ready-for-review

#5966 Set Modals to only close with ESC key or Cancel & X buttons (#5823)
  graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
Labels: backport, ready-for-review

#6156 Fix rendering of events in single message view.
  graylog2-web-interface/src/pages/ShowMessagePage.jsx
  graylog2-web-interface/src/pages/ShowMessagePage.test.jsx
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap
Labels: ready-for-review

#5981 Set default value for email sender to empty value
  graylog2-server/src/main/java/org/graylog2/alarmcallbacks/EmailAlarmCallback.java
Labels: ready-for-review

#6147 Check for Plugin inputConfiguration before opening Inputs modal
  graylog2-web-interface/src/components/inputs/CreateInputControl.jsx
Labels: ready-for-review, ux

#6165 Common Unload Confirmation
  graylog2-web-interface/src/components/common/ConfirmLeaveDialog.jsx
  graylog2-web-interface/src/components/common/ConfirmLeaveDialog.test.jsx
  graylog2-web-interface/src/views/components/common/WindowLeaveMessage.jsx
  graylog2-web-interface/src/views/components/common/WindowLeaveMessage.test.jsx
Labels: ready-for-review

#6176 Adding styleguidist comments to ConfirmLeaveDialog
  graylog2-web-interface/src/components/common/ConfirmLeaveDialog.jsx
Labels: ready-for-review

#6166 Add UI for legacy notification support
  graylog2-web-interface/src/actions/event-notifications/EventNotificationsActions.js
  graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationFormField.jsx
  graylog2-web-interface/src/components/configurationforms/index.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.css
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationSummary.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationSummaryContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#5909 Add JDK 11 support
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/rest/models/system/responses/LocalesResponse.java
  pom.xml
Labels: infrastructure, ready-for-review

#6171 Updating Flow to 0.103.0.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/views/actions/QueriesActions.js
  graylog2-web-interface/src/views/actions/SearchActions.js
  graylog2-web-interface/src/views/components/HeaderElements.jsx
  graylog2-web-interface/src/views/components/QueryBar.jsx
  graylog2-web-interface/src/views/components/QueryBarElements.jsx
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/SearchResult.jsx
  graylog2-web-interface/src/views/components/actions/ValueActions.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitle.test.jsx
  graylog2-web-interface/src/views/components/sidebar/AddWidgetButton.jsx
  graylog2-web-interface/src/views/components/sidebar/SearchDetails.test.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.test.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
  graylog2-web-interface/src/views/logic/fieldactions/AddToAllTablesActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.test.jsx
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/FieldActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromAllTablesActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromTableActionHandler.js
  graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/UseInNewQueryHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/ValueActionHandler.js
  graylog2-web-interface/src/views/logic/views/ViewLoader.test.js
  graylog2-web-interface/src/views/logic/withPluginEntities.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
  graylog2-web-interface/src/views/stores/ChartColorRulesStore.js
  graylog2-web-interface/src/views/stores/CurrentViewStateStore.js
  graylog2-web-interface/src/views/stores/CurrentViewStateStore.test.js
  graylog2-web-interface/src/views/stores/FieldTypesStore.js
  graylog2-web-interface/src/views/stores/HighlightingRulesStore.js
  graylog2-web-interface/src/views/stores/SearchExecutionStateStore.js
  graylog2-web-interface/src/views/stores/SearchJobStore.js
  graylog2-web-interface/src/views/stores/SearchMetadataStore.js
  graylog2-web-interface/src/views/stores/StoreTypes.js
  graylog2-web-interface/src/views/stores/TitlesStore.js
  graylog2-web-interface/src/views/stores/ViewManagementStore.js
  graylog2-web-interface/src/views/stores/ViewSharingStore.js
  graylog2-web-interface/src/views/stores/ViewStatesStore.js
  graylog2-web-interface/src/views/stores/ViewStore.js
  graylog2-web-interface/src/views/stores/WidgetStore.js
  graylog2-web-interface/test/helpers/mocking/AsMock.js
  graylog2-web-interface/test/helpers/mocking/MockAction.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#6179 Add Event Definition previews
  graylog2-web-interface/src/actions/event-definitions/FilterPreviewActions.js
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderPreview.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderPreview.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.css
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/stores/event-definitions/FilterPreviewStore.js
Labels: alerting, ready-for-review

#6172 Fix closing of widget filter menu.
  graylog2-web-interface/src/views/components/widgets/WidgetFilterMenu.jsx
Labels: ready-for-review

#6184 Header throughput value context
  graylog2-web-interface/src/components/throughput/GlobalThroughput.css
  graylog2-web-interface/src/components/throughput/GlobalThroughput.jsx
Labels: ready-for-review, ux

#6186 Improve handling of default configurations in Event Definitions and Notifications
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/index.js
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
Labels: alerting, ready-for-review

#6191 Unset default sender
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
Labels: alerting, ready-for-review

#6190 Set Select options prop in QuickValuesConfiguration
  graylog2-web-interface/src/components/widgets/configurations/QuickValuesConfiguration.jsx
Labels: ready-for-review

#6193 Add backlog size config to Event UI
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx
Labels: ready-for-review

#6143 Improve shutdown handling of processing status recorder
  graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6170 Use stream ids for blacklisting in stream router engine.
  graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
Labels: ready-for-review

#6198 Several UI improvements in Events
  graylog2-web-interface/src/components/event-definitions/common/HelpPanel.css
  graylog2-web-interface/src/components/event-definitions/common/HelpPanel.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsList.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationList.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.css
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/index.js
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/events/events/EventsContainer.jsx
  graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx
Labels: alerting, ready-for-review

#6183 Updating react-select styles
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/components/common/Select.jsx
Labels: ready-for-review

#6188 Update netty to 4.1.38
  pom.xml
Labels: inputs, ready-for-review

#6199 Fix error when opening legacy notifications and the plugin is missing
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6214 Clean up completed OnceJobSchedule triggers after one day
  graylog2-server/src/main/java/org/graylog/scheduler/DBJobTriggerService.java
  graylog2-server/src/main/java/org/graylog/scheduler/periodicals/ScheduleTriggerCleanUp.java
  graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
  graylog2-server/src/test/java/org/graylog/scheduler/DBJobTriggerServiceTest.java
  graylog2-server/src/test/resources/org/graylog/scheduler/job-triggers.json
Labels: alerting, ready-for-review

#6219 Replacing uglify with Terser for better ES6 support
  graylog2-web-interface/package.json
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/webpack.vendor.js
  graylog2-web-interface/yarn.lock
Labels: bug, ready-for-review

#6200 Updating Throughput component in Header bar styles
  graylog2-web-interface/src/components/throughput/GlobalThroughput.css
  graylog2-web-interface/src/components/throughput/GlobalThroughput.jsx
Labels: ready-for-review

#6215 Add alerts manager role and enforce permissions
  graylog2-server/src/main/java/org/graylog/events/notifications/DBNotificationService.java
  graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20190730100900_AddAlertsManagerRole.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Labels: alerting, ready-for-review

#6210 Add refresh button to Events page
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/events/events/EventDetails.jsx
  graylog2-web-interface/src/components/events/events/Events.css
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/events/events/EventsContainer.jsx
  graylog2-web-interface/src/components/events/events/EventsSearchBar.css
  graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx
Labels: alerting, ready-for-review
