Repository Graylog2/graylog2-server, pull requests merged in 2019-06, with the labels that each got.

#5984 Replace `react-ace` with `react-ace-builds`.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
  graylog2-web-interface/src/components/common/webpack-resolver.js
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, web

#5986 Align package versions between views and core.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/routing/__snapshots__/AppErrorBoundary.test.jsx.snap
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5681 Also return ES "caused_by" error message for failed searches
  graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchFailure.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchFailureTest.java
Labels: elasticsearch, ready-for-review

#5987 Migrating `react-select` from v1 to v2.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#5999 Avoid collisions when merging `InputsStore` state into components state.
  graylog2-web-interface/src/components/inputs/CreateInputControl.jsx
  graylog2-web-interface/src/pages/CreateExtractorsPage.jsx
  graylog2-web-interface/src/pages/EditExtractorsPage.jsx
  graylog2-web-interface/src/pages/ExportExtractorsPage.jsx
  graylog2-web-interface/src/pages/ImportExtractorsPage.jsx
Labels: ready-for-review

#6000 Fixing `displayKey`/`valueKey` props in `Select` component.
  graylog2-web-interface/src/components/common/Select.jsx
Labels: ready-for-review

#6001 Fixing Multiple Navigation Concerns
  graylog2-web-interface/public/stylesheets/bootstrap-config.json
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/components/navigation/HelpMenu.jsx
  graylog2-web-interface/src/components/navigation/Navigation.css
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/UserMenu.jsx
  graylog2-web-interface/src/components/throughput/GlobalThroughput.css
  graylog2-web-interface/src/components/throughput/GlobalThroughput.jsx
  graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js
Labels: bug, improvement, ux

#6007 Merging jdot & streamex dependencies required by views into core.
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  pom.xml
Labels: ready-for-review

#6008 Cleaning up JS Warnings
  graylog2-web-interface/src/components/navigation/Navigation.css
  graylog2-web-interface/src/components/navigation/Navigation.jsx
Labels: bug, ux

#5998 Wizard component style customization
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/common/Wizard.md
  graylog2-web-interface/src/components/common/Wizard.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
Labels: alerting, ready-for-review

#6023 Using ObjectId in test fixtures instead of string.
  graylog2-server/src/test/resources/org/graylog/plugins/views/search/db/mixedExpiredNonExpiredReferencedAndNonReferencedSearches.json
Labels: ready-for-review

#5957 Create Pipeline Rules syntax highlighting mode for Ace
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
  graylog2-web-interface/src/components/common/webpack-resolver.js
  graylog2-web-interface/src/components/rules/RuleForm.jsx
  graylog2-web-interface/src/components/rules/mode-pipeline-hax.js
  graylog2-web-interface/src/components/rules/mode-pipeline.js
Labels: improvement, ready-for-review, ux

#6010 Implement events index template
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingTemplate.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/indexset/IndexSetConfigTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/IndexSetsResourceTest.java
  graylog2-server/src/test/java/org/graylog2/streams/StreamMock.java
  graylog2-server/src/test/resources/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.json
Labels: alerting, ready-for-review

#6047 Establish abstract InputsResource class to allow method reuse
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
Labels: ready-for-review

#6046 Fix styling differences for react select.
  graylog2-web-interface/src/components/common/Select.css
  graylog2-web-interface/src/components/common/Select.jsx
Labels: ready-for-review

#6039 Index mapping changes
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
  graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
Labels: 3.1 Alerting - 2 beta, alerting, elasticsearch, ready-for-review
