Repository Graylog2/graylog2-server, pull requests merged in 2019-10, with the labels that each got.

#6512 Render `null` for message field if its value is `undefined`.
  graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.jsx
  graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.test.jsx
Labels: ready-for-review, search

#6500 Update to netty 4.1.42
  pom.xml
Labels: ready-for-review

#6472 Add journaling_enabled field to processing status
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusDto.java
  graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-disabled-journal.json
Labels: alerting, bug, ready-for-review

#6521 Fixing issue with Sidecar Configuration
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationVariablesHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/EditConfigurationVariableModal.jsx
Labels: bug, ready-for-review

#6469 Relax the journal metrics constraint for the processing status
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
  graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-single-active-node.json
Labels: alerting, bug, ready-for-review

#6526 Render `null` for message field if its value is `undefined` (3.1).
  graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.jsx
  graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.test.jsx
Labels: ready-for-review, search

#6522 Notification test button improvements
  graylog2-web-interface/src/actions/event-notifications/EventNotificationsActions.js
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.jsx
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
Labels: alerting, ready-for-review

#6513 Hide Event Streams from Pipelines
  graylog2-web-interface/src/pages/PipelineDetailsPage.jsx
  graylog2-web-interface/src/pages/SimulatorPage.jsx
Labels: alerting, ready-for-review

#6535 Refactoring to unify handling of field/value action handlers/conditions.
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/actions/ActionHandler.jsx
  graylog2-web-interface/src/views/components/actions/ActionHandler.test.jsx
  graylog2-web-interface/src/views/components/actions/FieldActions.jsx
  graylog2-web-interface/src/views/components/actions/ValueActions.jsx
  graylog2-web-interface/src/views/components/actions/__snapshots__/ActionHandler.test.jsx.snap
  graylog2-web-interface/src/views/logic/fieldactions/AddMessageCountActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/AddToAllTablesActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/AddToAllTablesActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/AddToTableActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/AddToTableActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.test.jsx
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/FieldActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromAllTablesActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromAllTablesActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromTableActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromTableActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldtypes/FieldType.js
  graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.js
  graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.js
  graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/HighlightValueHandler.js
  graylog2-web-interface/src/views/logic/valueactions/QueryManipulationHandler.js
  graylog2-web-interface/src/views/logic/valueactions/SelectExtractorType.jsx
  graylog2-web-interface/src/views/logic/valueactions/SelectExtractorType.test.jsx
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/UseInNewQueryHandler.js
  graylog2-web-interface/src/views/logic/valueactions/UseInNewQueryHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/ValueActionHandler.js
  graylog2-web-interface/src/views/stores/QueriesStore.js
Labels: ready-for-review, search

#6442 Themed SplitButton
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Button.jsx
  graylog2-web-interface/src/components/graylog/DropdownButton.jsx
  graylog2-web-interface/src/components/graylog/SplitButton.jsx
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/graylog/props/button.js
  graylog2-web-interface/src/components/graylog/styles/button.js
  graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
  graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
Labels: ready-for-review

#6548 Relax the journal metrics constraint for the processing status (#6469)
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
  graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-single-active-node.json
Labels: backport, ready-for-review

#6544 Remove Event indices from global search default (#6413)
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/main/java/org/graylog2/indexer/TestIndexSet.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
Labels: backport, ready-for-review

#6546 Set the loglevel for org.graylog2 AND org.graylog (#6423)
  graylog2-server/src/main/java/org/graylog2/rest/models/system/loggers/responses/SingleSubsystemSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
Labels: backport, ready-for-review

#6545 Hide Event Streams from Pipelines (#6513)
  graylog2-web-interface/src/pages/PipelineDetailsPage.jsx
  graylog2-web-interface/src/pages/SimulatorPage.jsx
Labels: backport, ready-for-review

#6547 Add journaling_enabled field to processing status (#6472)
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusDto.java
  graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-disabled-journal.json
Labels: backport, ready-for-review

#6551 Fix saving searches
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewStateDTO.java
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx
Labels: ready-for-review, search

#6549 Implement Notification Test button (#6366) (#6522) (3.1 backport)
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlarmCallbackSender.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationContext.java
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationResourceHandler.java
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationTestData.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java
  graylog2-server/src/test/java/org/graylog/events/notifications/NotificationResourceHandlerTest.java
  graylog2-web-interface/src/actions/event-notifications/EventNotificationsActions.js
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.jsx
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
Labels: backport, ready-for-review

#6554 Fix height of Select component
  graylog2-web-interface/src/components/common/Select.jsx
Labels: backport, ready-for-review

#6555 Do not render empty string for `0` value in number visualization.
  graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx
Labels: ready-for-review, search

#6550 Adding Webpack stats analyzer
  graylog2-web-interface/.gitignore
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#6534 Migrating App.jsx to functional component
  graylog2-web-interface/src/routing/App.jsx
Labels: ready-for-review

#6558 Adding flow types for `styled-components`.
  graylog2-web-interface/flow-typed/npm/styled-components_v4.x.x.js
Labels: ready-for-review

#6467 Redesign sidebar for dashboard and search
  graylog2-web-interface/flow-typed/npm/react-sizeme_vx.x.x.js
  graylog2-web-interface/package.json
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/AppWithExtendedSearchBar.jsx
  graylog2-web-interface/src/routing/AppWithoutSearchBar.jsx
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/Query.jsx
  graylog2-web-interface/src/views/components/Query.test.jsx
  graylog2-web-interface/src/views/components/SearchResult.jsx
  graylog2-web-interface/src/views/components/WidgetGrid.jsx
  graylog2-web-interface/src/views/components/WidgetGrid.test.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/AddWidgetButton.jsx
  graylog2-web-interface/src/views/components/sidebar/AddWidgetButton.test.jsx
  graylog2-web-interface/src/views/components/sidebar/FieldList.jsx
  graylog2-web-interface/src/views/components/sidebar/NavItem.jsx
  graylog2-web-interface/src/views/components/sidebar/SearchDetails.css
  graylog2-web-interface/src/views/components/sidebar/SearchDetails.jsx
  graylog2-web-interface/src/views/components/sidebar/SearchDetails.test.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.css
  graylog2-web-interface/src/views/components/sidebar/SideBar.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx
  graylog2-web-interface/src/views/spec/CreateNewView.test.jsx
  graylog2-web-interface/src/views/stores/ViewMetadataStore.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, search

#6563 Update yarn.lock after sidebar-merge
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, search

#6569 Updating Button reference issue
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackUploadControls.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Button.jsx
  graylog2-web-interface/src/components/graylog/DropdownButton.jsx
  graylog2-web-interface/src/components/graylog/SplitButton.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
  graylog2-web-interface/src/components/widgets/__snapshots__/WidgetFooter.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkForm.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
  graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
Labels: bug, ux

#6574 Fix the bookmark button to clear current view
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx
Labels: ready-for-review, search

#6581 Fix default Filebeat config for Windows hosts
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
Labels: ready-for-review, sidecar

#6565 Showing indicator if global filter is set when editing dashboard widget.
  graylog2-web-interface/flow-typed/npm/react-select-event_v2.x.x.js
  graylog2-web-interface/package.json
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx
  graylog2-web-interface/src/views/components/searchbar/RelativeTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.jsx
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#6585 Adding "Full Screen" action to dashboards configuring tv mode.
  graylog2-web-interface/flow-typed/npm/@testing-library/jest-dom_v4.x.x.js
  graylog2-web-interface/flow-typed/npm/react-router_vx.x.x.js
  graylog2-web-interface/src/views/Constants.js
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/DebugOverlay.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx
  graylog2-web-interface/src/views/components/dashboard/__snapshots__/BigDisplayModeConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/logic/queries/QueryTitle.js
  graylog2-web-interface/src/views/logic/views/ViewState.js
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.jsx
Labels: ready-for-review, search

#6590 Fix widget width alignment for search and dashboard page
  graylog2-web-interface/src/components/common/ReactGridContainer.css
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
Labels: ready-for-review, search

#6594 Allow bootstrap component style overwrite
  graylog2-web-interface/public/stylesheets/graylog2.less
  graylog2-web-interface/src/components/bootstrap/Badge.css
  graylog2-web-interface/src/components/graylog/SplitButton.jsx
  graylog2-web-interface/src/components/graylog/styles/button.js
  graylog2-web-interface/src/components/graylog/styles/buttonStyles.js
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.css
  graylog2-web-interface/src/views/components/widgets/Widget.css
  graylog2-web-interface/webpack.config.js
Labels: ready-for-review

#6602 Showing dashboards in non-interactive big display/tv mode.
  graylog2-web-interface/src/routing/AppErrorBoundary.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Field.test.jsx
  graylog2-web-interface/src/views/components/Query.jsx
  graylog2-web-interface/src/views/components/Query.test.jsx
  graylog2-web-interface/src/views/components/Value.jsx
  graylog2-web-interface/src/views/components/Value.test.jsx
  graylog2-web-interface/src/views/components/contexts/InteractiveContext.js
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeHeader.jsx
  graylog2-web-interface/src/views/components/dashboard/IfInteractive.jsx
  graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.jsx
  graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.test.jsx
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
  graylog2-web-interface/src/views/logic/queries/QueryTitle.js
  graylog2-web-interface/src/views/logic/queries/QueryTitle.test.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.jsx
  graylog2-web-interface/src/views/stores/ViewStore.js
Labels: ready-for-review, search

#6607 Fixing root route in `AppRouter`.
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/AppRouter.test.jsx
Labels: ready-for-review

#6572 Implement function for transforming search view to dashboard view
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx
  graylog2-web-interface/src/views/logic/search/Search.js
  graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.test.js
  graylog2-web-interface/src/views/logic/views/View.js
  graylog2-web-interface/src/views/logic/views/ViewTransformer.js
  graylog2-web-interface/src/views/logic/views/ViewTransformer.search.fixture.json
  graylog2-web-interface/src/views/logic/views/ViewTransformer.test.js
  graylog2-web-interface/src/views/logic/views/ViewTransformer.view.fixture.json
  graylog2-web-interface/src/views/logic/views/__snapshots__/ViewTransformer.test.js.snap
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx
  graylog2-web-interface/src/views/stores/ViewStore.js
Labels: ready-for-review, search

#6611 Add bash script to execute linting in the same way the CI does
  graylog2-web-interface/dev/lintChanges.sh
  graylog2-web-interface/package.json
Labels: ready-for-review

#6608 Make searchbar reponsive and add refresh controls to dashboard searchbar
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/horizontalspacer/HorizontalSpacer.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/RefreshControls.css
  graylog2-web-interface/src/views/components/searchbar/RefreshControls.jsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.css
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
Labels: ready-for-review, search

#6622 Simplify implementation of isNew
  graylog2-web-interface/src/views/stores/ViewStore.js
  graylog2-web-interface/src/views/stores/ViewStore.test.js
Labels: ready-for-review, search

#6624 Generate unique aggregation ids for multiple percentile metrics
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/Percentile.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/searchtypes/pivot/series/PercentileTest.java
Labels: ready-for-review, search

#6623 Support MaxMind ASN geo ip database
  graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterDocumentation.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
Labels: feature

#6631 Add support for MaxMind ASN geo ip database (#6623)
  graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterDocumentation.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
Labels: backport, ready-for-review

#6567 Introduce a cluster global API browser button
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java
  graylog2-server/src/main/resources/swagger/css/screen.css
  graylog2-server/src/main/resources/swagger/index.html.template
  graylog2-server/src/main/resources/swagger/swagger-ui.js
  graylog2-web-interface/src/components/nodes/NodesList.jsx
  graylog2-web-interface/src/pages/NodesPage.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: bug, ready-for-review

#6599 Add icon on search page to create dashboard from current search
  graylog2-web-interface/flow-typed/npm/react-router_vx.x.x.js
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap
  graylog2-web-interface/src/views/logic/views/ViewLoader.js
  graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
  graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/__snapshots__/NewDashboardPage.test.jsx.snap
Labels: search

#6638 Generate unique aggregation ids for multiple percentile metrics
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/Percentile.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/searchtypes/pivot/series/PercentileTest.java
Labels: backport, ready-for-review, search

#6617 Themed Alert
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/graylog/styles/button.js
  graylog2-web-interface/src/components/graylog/variants/bsStyle.js
  graylog2-web-interface/src/theme/GraylogThemeContext.jsx
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/index.test.js
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.test.jsx
Labels: ready-for-review, ux

#6636 Introduce a cluster global API browser button (#6567)
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java
  graylog2-server/src/main/resources/swagger/css/screen.css
  graylog2-server/src/main/resources/swagger/index.html.template
  graylog2-server/src/main/resources/swagger/swagger-ui.js
  graylog2-web-interface/src/components/nodes/NodesList.jsx
  graylog2-web-interface/src/pages/NodesPage.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: backport, ready-for-review

#6634 Ensure index clean up runs before index creation
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20190905114400_RemoveOldProcessingStatusIndex.java
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Labels: alerting, bug, ready-for-review

#6642 Fix prop-types in NodesList component
  graylog2-web-interface/src/components/nodes/NodesList.jsx
  graylog2-web-interface/src/pages/NodesPage.jsx
Labels: ready-for-review

#6633 Add metric_counter_inc pipeline function
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/MetricCounterIncrement.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/metricCounter.txt
Labels: ready-for-review

#6635 Add length function for determining strings
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Length.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringLength.txt
Labels: ready-for-review

#6641 Pipeline function to retrieve message size for accounting purposes
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/TrafficAccountingSize.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/accountingSize.txt
Labels: ready-for-review

#6580 Report actual configured backlog size in LegacyAlertCondition
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlertCondition.java
Labels: alerting, ready-for-review

#6647 Report actual configured backlog size in LegacyAlertCondition (#6580)
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlertCondition.java
Labels: backport, ready-for-review

#6643 Ensure index clean up runs before index creation (#6634)
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20190905114400_RemoveOldProcessingStatusIndex.java
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Labels: backport, ready-for-review

#6573 Checking streams permissions for synchronous searches.
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchExecutionGuard.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/MissingCapabilitiesException.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/MissingCapabilitiesExceptionMapper.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/filter/StreamFilter.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PermittedStreams.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchExecutionGuardTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/TestData.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/errors/MissingCapabilitiesExceptionMapperTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/PermittedStreamsTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourcePermissionsTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceStreamPermissionsTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
Labels: ready-for-review, search

#6568 Improving `UserPreferencesButton` tests usage of mocks and snapshots.
  graylog2-web-interface/src/components/users/UserPreferencesButton.test.jsx
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
Labels: ready-for-review

#6644 Add metric_counter_inc pipeline function (#6633)
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/MetricCounterIncrement.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/metricCounter.txt
Labels: backport, ready-for-review

#6645 Add length function for determining strings (#6635)
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Length.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringLength.txt
Labels: backport, ready-for-review

#6627 Tying themeable components into styleguide library
  graylog2-web-interface/src/components/graylog/Alert.md
  graylog2-web-interface/src/components/graylog/Button.md
  graylog2-web-interface/src/components/graylog/DropdownButton.md
  graylog2-web-interface/src/components/graylog/SplitButton.md
  graylog2-web-interface/styleguide.config.js
Labels: ready-for-review, ux

#6655 Sorting streams options in streams filter.
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.test.jsx
Labels: ready-for-review, search

#6656 Don't loose the IndexSet TemplateType when updating
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java
Labels: alerting, bug, ready-for-review

#6662 Don't loose the IndexSet TemplateType when updating (#6656)
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java
Labels: backport, ready-for-review

#6657 Sorting streams options in streams filter.
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.test.jsx
Labels: backport, ready-for-review

#6652 Provide optional render completion callback to views widgets.
  graylog2-web-interface/src/views/components/aggregationbuilder/EmptyAggregationContent.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/EmptyAggregationContent.test.jsx
  graylog2-web-interface/src/views/components/contexts/InteractiveContext.js
  graylog2-web-interface/src/views/components/datatable/DataTable.jsx
  graylog2-web-interface/src/views/components/datatable/DataTable.test.jsx
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.jsx
  graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx
  graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
  graylog2-web-interface/src/views/components/widgets/RenderCompletionCallback.jsx
  graylog2-web-interface/src/views/logic/singleton.js
Labels: ready-for-review, search

#6666 Publish GrokPatternsUpdatedEvent on pattern import
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
Labels: processing, ready-for-review

#6670 Check if old index exists before dropping it
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Labels: bug, ready-for-review

#6673 Publish GrokPatternsUpdatedEvent on pattern import (#6666)
  graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
  graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
Labels: backport, ready-for-review

#6674 Check if old index exists before dropping it (#6670)
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Labels: backport, bug, ready-for-review

#6675 Increase ES client HTTP connection limits
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
  misc/graylog.conf
Labels: elasticsearch, ready-for-review

#6293 Implement pipeline rule timers that can be enabled/disabled at runtime
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/audit/PipelineProcessorAuditEventTypes.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/RuleMetricsConfigDto.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/RuleMetricsConfigService.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/events/RuleMetricsConfigChangedEvent.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdater.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/InterpreterListener.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/NoopInterpreterListener.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/RuleMetricsListener.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/RuleResource.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/simulator/SimulatorInterpreterListener.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  graylog2-web-interface/src/actions/rules/RulesActions.jsx
  graylog2-web-interface/src/components/rules/RuleList.jsx
  graylog2-web-interface/src/components/rules/RuleMetricsConfig.jsx
  graylog2-web-interface/src/components/rules/RuleMetricsConfigContainer.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/rules/RulesStore.js
Labels: processing, ready-for-review

#6672 Check stream permission on search creation
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchExecutionGuard.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/MissingCapabilitiesExceptionMapper.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchExecutionGuardTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
Labels: ready-for-review, search

#6648 Contrasting Color Generator Utility
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/components/graylog/Button.jsx
  graylog2-web-interface/src/components/graylog/DropdownButton.jsx
  graylog2-web-interface/src/components/graylog/SplitButton.jsx
  graylog2-web-interface/src/components/graylog/props/button.js
  graylog2-web-interface/src/components/graylog/styles/alert.js
  graylog2-web-interface/src/components/graylog/styles/button.js
  graylog2-web-interface/src/components/graylog/variants/bsStyle.js
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/theme/GraylogThemeContext.jsx
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/index.test.js
  graylog2-web-interface/src/util/contrastingColor.js
  graylog2-web-interface/src/util/contrastingColor.test.js
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
  graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, ux

#6621 Adjust query tab title editing
  graylog2-web-interface/src/views/components/QueryBar.jsx
  graylog2-web-interface/src/views/components/QueryTabs.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitle.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitle.test.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.test.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
Labels: ready-for-review, search

#6679 Increase ES client HTTP connection limits (#6675)
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
  misc/graylog.conf
Labels: backport, ready-for-review

#6659 Updated vendor-modules from build
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#6680 Implement pipeline rule timers that can be enabled/disabled at runtime
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/audit/PipelineProcessorAuditEventTypes.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/RuleMetricsConfigDto.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/RuleMetricsConfigService.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/events/RuleMetricsConfigChangedEvent.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdater.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/InterpreterListener.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/NoopInterpreterListener.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/RuleMetricsListener.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/RuleResource.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/simulator/SimulatorInterpreterListener.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  graylog2-web-interface/src/actions/rules/RulesActions.jsx
  graylog2-web-interface/src/components/rules/RuleList.jsx
  graylog2-web-interface/src/components/rules/RuleMetricsConfig.jsx
  graylog2-web-interface/src/components/rules/RuleMetricsConfigContainer.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/rules/RulesStore.js
Labels: backport, ready-for-review

#6653 Themed Badge Component
  graylog2-web-interface/src/components/bootstrap/Badge.css
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Badge.jsx
  graylog2-web-interface/src/components/graylog/Badge.md
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/graylog/styles/badge.js
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/NotificationBadge.jsx
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Labels: ready-for-review

#6681 Do not set state in `Footer` if already unmounted.
  graylog2-web-interface/src/components/layout/Footer.jsx
Labels: ready-for-review, search

#6684 Cleaning up render completion callback handling in some places.
  graylog2-web-interface/src/components/visualizations/RenderCompletionObserver.jsx
  graylog2-web-interface/src/components/widgets/WidgetVisualizationNotFound.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/Direction.js
  graylog2-web-interface/src/views/logic/widgets/Widget.js
Labels: ready-for-review, search

#6683 Adding service to retrieve mapped field types per stream.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PermittedStreams.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/FieldTypesResourceTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java
Labels: ready-for-review, search

#6307 Reset loading state when loading field statistics fails
  graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx
Labels: ready-for-review

#6629 Deduplicating query/search type errors before returning them.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/JestUtils.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendErrorHandlingTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendMultiSearchTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTestBase.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/errorhandling/failureOnQueryLevel.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/errorhandling/failureOnSearchTypeLevel.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/errorhandling/numericFailureOnSearchTypeLevel.json
Labels: ready-for-review, search

#6687 Filter searches for only permitted ones when GET /views/search is requested
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/ViewPermissions.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/PermissionException.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/exceptionmappers/MissingCapabilitiesExceptionMapper.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/exceptionmappers/PermissionExceptionMapper.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/ViewSharingService.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchDomainTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/ViewPermissionsTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/exceptionmappers/MissingCapabilitiesExceptionMapperTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/exceptionmappers/PermissionExceptionMapperTest.java
Labels: ready-for-review, search

#6658 Themed ControlLabel component
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/ControlLabel.jsx
  graylog2-web-interface/src/components/graylog/ControlLabel.md
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
Labels: ready-for-review

#6665 Themed HelpBlock Component
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/graylog/HelpBlock.jsx
  graylog2-web-interface/src/components/graylog/HelpBlock.md
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
Labels: ready-for-review
