Repository Graylog2/graylog2-server, pull requests merged in 2019-04, with the labels that each got.

#5821 Make `Timestamp` accept seconds from epoch.
  graylog2-web-interface/src/components/common/Timestamp.jsx
  graylog2-web-interface/src/components/common/Timestamp.md
Labels: ready-for-review

#5823 Set Modals to only close with ESC key or Cancel & X buttons
  graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
Labels: ready-for-review, ux

#5842 Renovating ESLint config for core and plugins.
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/eslint-config-graylog/index.js
  graylog2-web-interface/packages/eslint-config-graylog/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/yarn.lock
Labels: infrastructure, ready-for-review

#5632 Add metrics for sidecar resources
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
Labels: improvement, performance, ready-for-review, sidecar

#5684 Add reporting to docs helper
  graylog2-web-interface/src/util/DocsHelper.js
Labels: documentation, feature, ready-for-review, web

#5699 Add new pipeline function "grok_exists"
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/GrokExists.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok_exists.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok_exists_not.txt
Labels: feature, improvement, ready-for-review

#5867 Allow kafka group.id to be configured
  graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java
Labels: feature

#5853 Move web build and cache directory into target/
  graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml
  graylog-plugin-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-web-interface/packages/graylog-web-plugin/src/PluginWebpackConfig.js
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/webpack.vendor.js
Labels: ready-for-review, web

#5390 Add "test-jar" goal to maven-jar-plugin configuration
  graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml
  graylog2-server/pom.xml
Labels: ready-for-review
