Repository Graylog2/graylog2-server, pull requests merged in 2019-08, with the labels that each got.

#6213 Add "source_streams" to event and index mapping
  graylog2-server/src/main/java/org/graylog/events/event/Event.java
  graylog2-server/src/main/java/org/graylog/events/event/EventDto.java
  graylog2-server/src/main/java/org/graylog/events/event/EventImpl.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationResult.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
  graylog2-server/src/test/java/org/graylog/events/event/EventTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
  graylog2-server/src/test/java/org/graylog/events/search/MoreSearchTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6231 Change findPaginatedWithQueryFilterAndSort limit semantics
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Labels: alerting, ready-for-review

#6225 Cleanup stale job trigger on server startup
  graylog2-server/src/main/java/org/graylog/scheduler/DBJobTriggerService.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobExecutionEngine.java
  graylog2-server/src/test/java/org/graylog/scheduler/DBJobTriggerServiceTest.java
  graylog2-server/src/test/resources/org/graylog/scheduler/stale-job-triggers.json
Labels: ready-for-review, scheduler

#6227 Remove hardcoded write index for event indexing
  graylog2-server/src/main/java/org/graylog/events/indices/MoreIndices.java
Labels: alerting, ready-for-review

#6226 Change JobSchedulerConfig interface
  graylog2-server/src/main/java/org/graylog/scheduler/DefaultJobSchedulerConfig.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerConfig.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java
Labels: ready-for-review, scheduler

#6222 Fix issue showing unknown legacy type warning when creating notification
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6232 Validate forms
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlarmCallbackEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationDto.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationResult.java
  graylog2-server/src/test/java/org/graylog/events/notifications/NotificationDtoTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionDtoTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfigTest.java
  graylog2-web-interface/src/components/event-definitions/common/commonStyles.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionValidationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/index.js
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
Labels: alerting, ready-for-review

#6233 Fix error for missing legacy notification plugins in Event Definition form
  graylog2-web-interface/src/components/event-notifications/event-notification-types/CommonNotificationSummary.css
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationCommonStyles.css
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationSummary.jsx
Labels: alerting, ready-for-review

#6223 Events system configuration
  graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfiguration.java
  graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfigurationProvider.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationExecutionJob.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationService.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20190730000000_CreateDefaultEventsConfiguration.java
  graylog2-server/src/test/java/org/graylog/events/EventsConfigurationTestProvider.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
  graylog2-web-interface/src/actions/configurations/ConfigurationActions.js
  graylog2-web-interface/src/components/configurations/EventsConfig.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
Labels: ready-for-review

#6229 Avoid logging excessive exceptions in ProxiedResource
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java
Labels: ready-for-review

#6180 Remove -XX:+UseParNewGC option from jdk
  bin/graylogctl
Labels: ready-for-review

#6230 Content Pack Integration for EventDefintions
  graylog2-server/src/main/java/org/graylog/events/EventsModule.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationSeriesEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventDefinitionEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventNotificationHandlerConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventProcessorConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackable.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/NativeEntityConverter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ValueReference.java
  graylog2-server/src/test/java/org/graylog/events/TestEventProcessorConfig.java
Labels: 3.1 Alerting - 3 release, alerting, content-packs, ready-for-review

#6234 Adjust UI for new alerting
  graylog2-web-interface/src/components/alertconditions/AlertConditionsComponent.jsx
  graylog2-web-interface/src/components/alertnotifications/AlertNotificationsComponent.jsx
  graylog2-web-interface/src/components/alerts/AlertsHeaderToolbar.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/events/events/EventDetails.jsx
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/events/events/EventsContainer.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/pages/AlertConditionsPage.jsx
  graylog2-web-interface/src/pages/AlertNotificationsPage.jsx
  graylog2-web-interface/src/pages/AlertsPage.jsx
  graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/CreateEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EditAlertConditionPage.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
  graylog2-web-interface/src/pages/EventNotificationsPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
  graylog2-web-interface/src/pages/NewAlertConditionPage.jsx
  graylog2-web-interface/src/pages/NewAlertNotificationPage.jsx
  graylog2-web-interface/src/pages/ShowAlertPage.jsx
  graylog2-web-interface/src/pages/StreamAlertsOverviewPage.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: alerting, ready-for-review

#6224 Improve job scheduler responsiveness
  graylog2-server/src/main/java/org/graylog/scheduler/JobExecutionEngine.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerConfiguration.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerModule.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java
  graylog2-server/src/main/java/org/graylog/scheduler/eventbus/JobCompletedEvent.java
  graylog2-server/src/main/java/org/graylog/scheduler/eventbus/JobSchedulerEventBus.java
  graylog2-server/src/main/java/org/graylog/scheduler/eventbus/JobSchedulerEventBusProvider.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/test/java/org/graylog/scheduler/JobSchedulerServiceTest.java
Labels: ready-for-review, scheduler

#6240 Disable legacy AlertScannerThread
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
  graylog2-server/src/main/java/org/graylog2/periodical/AlarmCallbacksMigrationPeriodical.java
  graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java
  misc/graylog.conf
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6244 Check stream permissions in aggregation event definition
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinition.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfigTest.java
  graylog2-server/src/test/resources/org/graylog/events/processor/aggregation/aggregation-processors.json
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6246 Remove notification action from event definition on notification delete
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationResourceHandler.java
  graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
  graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java
Labels: ready-for-review

#6243 Add metrics support for Events, Notifications and scheduler
  graylog2-server/src/main/java/org/graylog/events/EventsModule.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationExecutionJob.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationExecutionMetrics.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorEngine.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorExecutionMetrics.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobExecutionEngine.java
  graylog2-server/src/main/java/org/graylog/scheduler/worker/JobWorkerPool.java
  graylog2-server/src/main/java/org/graylog2/shared/metrics/MetricUtils.java
  graylog2-server/src/test/java/org/graylog2/shared/metrics/MetricUtilsTest.java
Labels: ready-for-review

#6248 Authorize Event pages in UI
  graylog2-web-interface/src/components/event-definitions/common/HelpPanel.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/AddNotificationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/events/events/EventDetails.jsx
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/events/events/EventsContainer.jsx
  graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/CreateEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
  graylog2-web-interface/src/pages/EventNotificationsPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
Labels: alerting

#6251 Add "ij_continuation_indent_size" setting to .editorconfig
  .editorconfig
Labels: ready-for-review

#6257 Give visual feedback on disabled inputs
  graylog2-web-interface/public/stylesheets/bootstrap-config.json
Labels: ready-for-review

#6249 Fix rendering of LDAP page
  graylog2-web-interface/src/components/ldap/LdapComponent.jsx
Labels: ready-for-review

#6256 Avoid using `Stream#peek` for counting items in paginated result set.
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Labels: ready-for-review

#6253 Hide unsupported Streams from Filter Select
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx
Labels: alerting, ready-for-review

#6250 Implement permission check for events search
  graylog2-server/src/main/java/org/graylog/events/event/EventDto.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/IndexRangeContainsOneOfStreams.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6245 Implement dependency Resolution for Notification and Streams in EventDefinitions.
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EmailEventNotificationConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventDefinitionEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventNotificationConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventNotificationHandlerConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/HttpEventNotificationConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/LegacyAlarmCallbackEventNotificationConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/NotificationEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/NotificationFacade.java
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlarmCallbackEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationHandler.java
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationDto.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackable.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/NativeEntityConverter.java
  graylog2-server/src/test/java/org/graylog/events/TestEventProcessorConfig.java
Labels: 3.1 Alerting - 3 release, alerting, content-packs, ready-for-review

#6262 Fix wizard layot design for content packs
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
Labels: content-packs, ready-for-review, ux, web

#6264 More Events UI improvements
  graylog2-web-interface/src/components/common/ConfirmLeaveDialog.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderPreview.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderPreview.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.css
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/withStreams.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.css
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.css
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx
  graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/CreateEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: alerting, ready-for-review

#6272 Implement new getPackageName function for versionConstraints
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackable.java
Labels: 3.1 Alerting - 3 release, alerting, content-packs, ready-for-review

#6252 Improve processing status handling to avoid blocking event processing
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorDependencyCheck.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
  graylog2-server/src/main/java/org/graylog2/system/processing/InMemoryProcessingStatusRecorder.java
  graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusConfig.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusDto.java
  graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusRecorder.java
  graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-node-selection-test.json
  graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status.json
  misc/graylog.conf
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6275 Migrate Legacy Alerts and Notifications without title
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlertConditionMigrator.java
  graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java
  graylog2-server/src/test/resources/org/graylog/events/legacy/legacy-alert-conditions.json
Labels: alerting, ready-for-review

#6263 Prevent closing of UDP channel in input for messages with bogus GELF header.
  graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/EnvelopeMessageAggregationHandler.java
Labels: ready-for-review

#6277 Handle 404s in Event Definitions and Notifications
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
Labels: alerting, ready-for-review

#6281 Security update to jackson-databind 2.8.11.4
  pom.xml
Labels: blocker, ready-for-review, security

#6279 Disable content pack entity creation for legacy conditions and callbacks
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
Labels: 3.1 Alerting - 3 release, alerting, ready-for-review

#6285 Text improvements in Alerting
  graylog2-web-interface/src/components/event-definitions/event-definition-form/AddNotificationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsList.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
Labels: alerting, ready-for-review

#6286 Dont throw exception on misconfigured email notification
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
Labels: alerting, ready-for-review

#6284 Improve Event processor exceptions
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationSearch.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
Labels: alerting, ready-for-review

#6288 Sort entities in alerting forms
  graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
Labels: alerting, ready-for-review

#6297 Warn the user about missing streams in event definitions
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
Labels: ready-for-review

#6287 Add default filebeat collector config for windows
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
Labels: ready-for-review

#6292 Add EventDefinitionFacade and NotificationFacade Test
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EmailEventNotificationConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/HttpEventNotificationConfigEntity.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java
  graylog2-server/src/test/resources/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.json
  graylog2-server/src/test/resources/org/graylog/events/contentpack/facade/NotificationFacadeTest.json
Labels: 3.1 Alerting - 3 release, alerting, content-packs, ready-for-review

#6294 Fix bytes formatting after numeral major update.
  graylog2-web-interface/src/components/cluster/TrafficGraph.jsx
  graylog2-web-interface/src/util/NumberUtils.js
Labels: ready-for-review, ux

#6300 Remove ability to add parameters to long typed fields
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
Labels: alerting, content-packs, ready-for-review

#6301 Security update to netty-4.1.39
  pom.xml
Labels: ready-for-review, security

#6157 Prefix plugin navigation item path with app prefix. (3.0)
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
Labels: ready-for-review

#6320 Fix mvn test / sync versions between server and enterprise
  graylog2-server/pom.xml
  pom.xml
Labels: infrastructure, ready-for-review

#6329 Increase height of navigation to show collapsable content
  graylog2-web-interface/public/stylesheets/bootstrap-config.json
  graylog2-web-interface/src/components/throughput/GlobalThroughput.css
Labels: bug, ready-for-review

#6333 Use custom name for the compound index in DBProcessingStatusService
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Labels: ready-for-review

#6305 Don't block server shutdown in FakeHttpMessageInput
  graylog2-server/src/main/java/org/graylog2/inputs/transports/RandomMessageTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/GeneratorTransport.java
Labels: bug, inputs, ready-for-review

#6349 Update graylog.conf
  misc/graylog.conf
Labels: ready-for-review

#6350 Add events index prefix settings to graylog.conf
  misc/graylog.conf
Labels: ready-for-review

#6352 Wait for `ViewActions.load` in promise chain and still return view.
  graylog2-web-interface/src/views/logic/views/ViewDeserializer.js
Labels: ready-for-review

#6267 Adding settings class for display mode to view/query state class.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/DisplayModeSettings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewStateDTO.java
Labels: ready-for-review

#6325 Update jackson to 2.9.9 and allow trailing comma in GELF Input
  graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/JsonParse.java
  graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java
  graylog2-server/src/main/java/org/graylog2/plugin/Tools.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/jackson/ValueTypeDeserializerTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/codecs/GelfCodecTest.java
  pom.xml
Labels: inputs, ready-for-review

#6344 Use custom name for the compound index in DBProcessingStatusService
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Labels: backport, ready-for-review

#6268 Replacing existing search page with extended search, removing query bar.
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: ready-for-review

#6271 Fix retrieval of registered plugin routes.
  graylog2-web-interface/src/routing/Routes.jsx
Labels: ready-for-review

#6269 Replace stream search with new extended search.
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/stores/QueryFiltersStore.js
Labels: ready-for-review

#6360 Adding fixture-helpers for view-related tests.
  graylog2-web-interface/src/views/test/ViewFixtures.js
Labels: ready-for-review

#6363 Fix mvn test / sync versions between server and enterprise (#6320)
  graylog2-server/pom.xml
  pom.xml
Labels: ready-for-review

#6361 Wait for `ViewActions.load` in promise chain and still return view
  graylog2-web-interface/src/views/logic/views/ViewDeserializer.js
Labels: bug, ready-for-review, search

#6367 Allowing to enable (experimental) frontend features for development.
  graylog2-web-interface/src/util/AppConfig.js
  graylog2-web-interface/webpack.config.js
Labels: ready-for-review

#6368 Hide replacing search/dashboard functionality behind feature flag.
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/views/bindings.jsx
Labels: ready-for-review
