Repository Graylog2/graylog2-server, pull requests merged in 2020-07, with the labels that each got.

#8397 Support Forwarder wizard
  graylog2-web-interface/flow-typed/npm/react-router_vx.x.x.js
  graylog2-web-interface/src/stores/inputs/InputTypesStore.js
  graylog2-web-interface/src/util/DocsHelper.js
Labels: ready-for-review

#8448 Issue 8420 bugfix
  graylog2-web-interface/src/components/graylog/ProgressBar.jsx
  graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap
Labels: bug, ready-for-review

#8455 Table & DataTable styles & colors
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/common/DataTable.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntityConfig.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Table.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/theme/colors.js
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
Labels: improvement, ready-for-review

#8396 Save sidebar isPinned setting as a user preference
  graylog2-web-interface/src/components/users/UserPreferencesModal.jsx
  graylog2-web-interface/src/contexts/UserPreferencesContext.js
  graylog2-web-interface/src/stores/users/PreferencesStore.js
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutContext.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.test.jsx
  graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.jsx
Labels: ready-for-review, search

#8472 Rename "role" to "capability"
  graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
  graylog2-server/src/main/java/org/graylog/security/CapabilityDTO.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/DefaultGrantPermissionResolver.java
  graylog2-server/src/main/java/org/graylog/security/GrantDTO.java
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareRequest.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareResponse.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntityShareRequest.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/main/java/org/graylog2/utilities/GRNRegistry.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/resources/org/graylog/security/grants.json
Labels: ready-for-review

#8477 Pagination Rebuild w/ Theming
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/common/Pagination.jsx
  graylog2-web-interface/src/components/common/Pagination.md
  graylog2-web-interface/src/components/common/Pagination.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/content-packs/ContentPacksList.css
  graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPacksList.test.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Pagination.jsx
  graylog2-web-interface/src/components/graylog/Pagination.md
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/systemmessages/SystemMessagesComponent.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review

#8485 Exclude sharing user from active shares and refactor capabilities
  graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
  graylog2-server/src/main/java/org/graylog/security/Capability.java
  graylog2-server/src/main/java/org/graylog/security/CapabilityDescriptor.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/DefaultGrantPermissionResolver.java
  graylog2-server/src/main/java/org/graylog/security/GrantDTO.java
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareRequest.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareResponse.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntityShareRequest.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/main/java/org/graylog2/utilities/GRNRegistry.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/resources/org/graylog/security/grants.json
Labels: ready-for-review

#8294 Add option to display the search sidebar inline
  graylog2-web-interface/.stylelintrc
  graylog2-web-interface/src/components/users/UserPreferencesModal.jsx
  graylog2-web-interface/src/contexts/UserPreferencesContext.js
  graylog2-web-interface/src/stores/users/PreferencesStore.js
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutContext.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.test.jsx
  graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
  graylog2-web-interface/src/views/components/sidebar/FieldTypeIcon.css
  graylog2-web-interface/src/views/components/sidebar/NavItem.jsx
  graylog2-web-interface/src/views/components/sidebar/NavItem.styles.jsx
  graylog2-web-interface/src/views/components/sidebar/SectionInfo.jsx
  graylog2-web-interface/src/views/components/sidebar/SectionSubheadline.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.jsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.jsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.styles.jsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.test.jsx
  graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.jsx
  graylog2-web-interface/src/views/components/sidebar/ViewDescription.jsx
  graylog2-web-interface/src/views/components/sidebar/create/AddWidgetButton.jsx
  graylog2-web-interface/src/views/components/sidebar/create/AddWidgetButton.test.jsx
  graylog2-web-interface/src/views/components/sidebar/description/SearchResultOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/description/ViewDescription.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldTypeIcon.css
  graylog2-web-interface/src/views/components/sidebar/fields/FieldTypeIcon.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/ListItem.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx
  graylog2-web-interface/src/views/components/sidebar/index.jsx
  graylog2-web-interface/src/views/components/sidebar/sidebarSections.jsx
  graylog2-web-interface/src/views/logic/creatoractions/CreateCustomAggregation.js
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
  graylog2-web-interface/test/setup-jest.js
Labels: ready-for-review, search

#8394 Write facility_num to facilitate direct translation of facility
  graylog2-server/src/main/java/org/graylog2/inputs/codecs/SyslogCodec.java
  graylog2-server/src/test/java/org/graylog2/inputs/codecs/SyslogCodecTest.java
Labels: ready-for-review

#8471 Add new Vendor fields to the Graylog Schema
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Labels: Graylog Schema, ready-for-review

#8499 Add missing CountsAdapterProvider
  graylog2-server/src/main/java/org/graylog2/storage/VersionAwareStorageModule.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/CountsAdapterProvider.java
Labels: bug, elasticsearch, ready-for-review

#8494 Add new Vendor fields to the Graylog Schema (#8471)
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Labels: Graylog Schema, ready-for-review

#8505 Table styles update
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntityConfig.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Table.jsx
  graylog2-web-interface/src/theme/colors.js
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
Labels: improvement, ready-for-review

#8511 Return permissions from Grants to the frontend
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: ready-for-review

#8451 Implement `MessagesAdapter` for ES7.
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6Test.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/FixtureImporterES6.java
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchException.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/MessagesES7IT.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchExceptionTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/ChunkedBulkIndexer.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/MessagesAdapter.java
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBulkIndexRetryingTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesRetryWaitTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesTest.java
Labels: elasticsearch, ready-for-review

#8515 Use correct ES exception class in storage adapter.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
Labels: elasticsearch, ready-for-review

#8516 Use correct setting name for ES template target.
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping7.java
Labels: elasticsearch, ready-for-review

#8517 Add mockito-junit-jupiter dependency
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
Labels: infrastructure, ready-for-review

#8520 Add new endpoint to retrive a paginated list of users
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java
  graylog2-server/src/main/java/org/graylog2/users/RoleService.java
  graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java
Labels: ready-for-review, users

#8459 Implement `ClusterAdapter` for ES7.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ClusterES6IT.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PlainJsonApi.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/CatApi.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/NodeResponse.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterES7IT.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/ClusterAdapter.java
  graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
Labels: elasticsearch, ready-for-review

#8478 Implement `NodeAdapter` for ES7.
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/NodeES6IT.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/NodeAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/NodeES7IT.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/NodeIT.java
Labels: elasticsearch, ready-for-review

#8530 Merge latest server 3.3 changes into cloud-3.3
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
  graylog2-web-interface/flow-typed/npm/react-router_vx.x.x.js
  graylog2-web-interface/src/stores/inputs/InputTypesStore.js
  graylog2-web-interface/src/util/DocsHelper.js
Labels: ready-for-review

#8526 Update Nav & Wizard Nav color usage
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
  graylog2-web-interface/src/components/graylog/Nav.jsx
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/components/grok-patterns/DeleteGrokPattern.jsx
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
Labels: improvement, ready-for-review

#8440 Add MongoDB extension for JUnit 5
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBContainer.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBExtension.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBExtensionTest.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBExtensionWithRegistrationAsStaticFieldTest.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBFixtures.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBInstance.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBTestService.java
  graylog2-server/src/test/resources/org/graylog/testing/mongodb/MongoDBExtensionTest-1.json
  graylog2-server/src/test/resources/org/graylog/testing/mongodb/MongoDBExtensionTest-2.json
Labels: ready-for-review

#8469 Reuse `Messages#bulkIndex` for event indexing.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/EventIndexerAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6Test.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/MessagesES7IT.java
  graylog2-server/src/main/java/org/graylog/events/event/Event.java
  graylog2-server/src/main/java/org/graylog/events/event/EventImpl.java
  graylog2-server/src/main/java/org/graylog/events/indices/EventIndexer.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Indexable.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexingRequest.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/storage/VersionAwareStorageModule.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/EventIndexerAdapterProvider.java
  graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
Labels: elasticsearch, ready-for-review

#8532 Enabling integration tests for storage driver modules.
  full-backend-tests/pom.xml
  graylog-project-parent/pom.xml
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterES7IT.java
  graylog2-server/pom.xml
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Labels: elasticsearch

#8538 Create a basic AuthzRole resource
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRoleDTO.java
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
  graylog2-server/src/main/java/org/graylog/security/authzroles/PaginatedAuthzRolesService.java
Labels: ready-for-review, users

#8482 Implement `IndicesAdapter` for ES7.
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/CatApi.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cluster/ClusterStateApi.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/stats/StatsApi.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/IndicesES7IT.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/IndicesGetAllMessageFieldsES7IT.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/FixtureImporterES7.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Labels: elasticsearch, ready-for-review

#8534 Create user detail and edit page for new user management.
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/common/TextLabel.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/users/LegacyTimeoutInput.jsx
  graylog2-web-interface/src/components/users/NewUserForm.jsx
  graylog2-web-interface/src/components/users/SectionComponent.jsx
  graylog2-web-interface/src/components/users/ShowConfigValue.jsx
  graylog2-web-interface/src/components/users/TimeoutInput.jsx
  graylog2-web-interface/src/components/users/UserDetails/MainDetailsGrid.jsx
  graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserDetails/index.js
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/UserEdit/index.js
  graylog2-web-interface/src/components/users/UserForm.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/UsersOverviewItem.jsx
  graylog2-web-interface/src/components/users/form/FormField.jsx
  graylog2-web-interface/src/components/users/form/FormFieldRead.jsx
  graylog2-web-interface/src/components/users/form/FormRow.jsx
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
  graylog2-web-interface/src/pages/UsersOverviewPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/theme/types.js
Labels: ready-for-review

#8529 Row content theme
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Row.jsx
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/layout/AppContentGrid.jsx
  graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap
  graylog2-web-interface/src/views/components/WidgetGrid.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/NavItem.jsx
  graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.jsx
  graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review, ux

#8535 Remove superfluous es 5 test
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java
Labels: elasticsearch, ready-for-review

#8548 Import UsersActions from UsersStore instead of actions/users/UsersActions
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersFilter.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/stores/users/UsersStore.test.js
Labels: ready-for-review

#8488 Implement `SearchesAdapter` for ES7.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Scroll.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ScrollResultES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ScrollResultES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Scroll.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ScrollResultES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchesAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SortOrderMapper.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/TimeRangeQueryFactory.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchesES7IT.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/ScrollResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/ScrollCommand.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
Labels: elasticsearch, ready-for-review

#8545 Improve user management ui
  graylog2-web-interface/src/components/common/TextLabel.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/users/LoggedInIcon.jsx
  graylog2-web-interface/src/components/users/ShowConfigValue.jsx
  graylog2-web-interface/src/components/users/TimeoutInput.jsx
  graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/ReadOnlyWarning.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/LoggedInCell.jsx
  graylog2-web-interface/src/components/users/form/FormField.jsx
  graylog2-web-interface/src/components/users/form/FormFieldRead.jsx
  graylog2-web-interface/src/components/users/form/FormRow.jsx
  graylog2-web-interface/src/components/users/form/ReadOnlyFormField.jsx
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
Labels: ready-for-review

#8549 Implement event searching/scrolling for ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ResultMessageFactory.java
Labels: elasticsearch, ready-for-review

#8557 Fixing remove alias action during deflector cycle for ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Labels: elasticsearch, ready-for-review

#8514 Implementing `IndexToolsAdapter` for ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndexToolsAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Scroll.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchCommand.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchesES7IT.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
Labels: elasticsearch, ready-for-review

#8551 Adding ES7 adapter for reopened indices migration.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cluster/ClusterStateApi.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/migrations/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateES7.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java
Labels: elasticsearch, ready-for-review

#8552 Implement `IndexFieldTypePollerAdapter` for ES7.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexFieldTypePollerAdapterES6.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndexFieldTypePollerAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/mapping/FieldMappingApi.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/IndexFieldTypePollerES7IT.java
Labels: elasticsearch, ready-for-review

#8427 Updating `testing-library` to most recent versions.
  graylog2-web-interface/flow-typed/npm/@testing-library/jest-dom_v5.5.x.js
  graylog2-web-interface/flow-typed/npm/@testing-library/react_v10.x.x.js
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/Delayed.test.jsx
  graylog2-web-interface/src/components/common/PaginatedList.test.jsx
  graylog2-web-interface/src/components/common/Spinner.test.jsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
  graylog2-web-interface/src/components/graylog/ProgressBar.test.jsx
  graylog2-web-interface/src/components/layout/Footer.test.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.jsx
  graylog2-web-interface/src/components/search/SurroundingSearchButton.test.jsx
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.jsx
  graylog2-web-interface/src/contexts/CurrentUserProvider.test.jsx
  graylog2-web-interface/src/pages/RuntimeErrorPage.test.jsx
  graylog2-web-interface/src/pages/ShowMessagePage.test.jsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.test.jsx
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/SearchResult.test.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.test.jsx
  graylog2-web-interface/src/views/components/ViewTypeLabel.test.jsx
  graylog2-web-interface/src/views/components/WidgetOverrideElements.test.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/__tests__/MigrateFieldCharts.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.test.jsx
  graylog2-web-interface/src/views/components/contexts/DefaultFieldTypesProvider.test.jsx
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.test.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx
  graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.test.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageActions.test.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.test.jsx
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.test.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.jsx
  graylog2-web-interface/src/views/components/widgets/CopyToDashboardForm.test.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortIcon.test.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortSelect.test.jsx
  graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.test.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.test.jsx
  graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx
  graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.test.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#8561 Clean up Indices class
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java
Labels: elasticsearch, ready-for-review

#8562 Remove remaining testing library cleanups
  graylog2-web-interface/src/components/common/Pagination.test.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.test.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx
Labels: ready-for-review

#8558 Implement new user management create page
  graylog2-web-interface/src/components/users/SectionComponent.jsx
  graylog2-web-interface/src/components/users/UserCreate/EmailFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/FullNameFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/PasswordFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/TimeoutFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/TimezoneFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserCreate/UsernameFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/index.js
  graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
  graylog2-web-interface/src/components/users/form/FieldError.jsx
  graylog2-web-interface/src/components/users/form/FormikFormGroup.jsx
  graylog2-web-interface/src/components/users/form/ReadOnlyFormGroup.jsx
  graylog2-web-interface/src/pages/UserCreatePage.jsx
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
  graylog2-web-interface/src/pages/UsersOverviewPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/util/ValidationsUtils.js
Labels: ready-for-review

#8571 Add missing semicolon for sidebar content column styling.
  graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
Labels: bug, ready-for-review

#8559 Implement change password section for new user edit page
  graylog2-web-interface/src/components/permissions/EntityShareModal.test.jsx
  graylog2-web-interface/src/components/users/UserCreate/PasswordFormGroup.jsx
  graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
Labels: ready-for-review

#8565 Implement edit tokens page for new user management
  graylog2-web-interface/src/components/users/UserManagementLinks.jsx
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
  graylog2-web-interface/src/pages/UserTokensEditPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: ready-for-review

#8553 Roles in user details
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/users/PaginatedItem.jsx
  graylog2-web-interface/src/components/users/PaginatedItemOverview.jsx
  graylog2-web-interface/src/components/users/SectionComponent.jsx
  graylog2-web-interface/src/components/users/UserDetails/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/logic/roles/Role.js
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/PaginationTypes.js
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/src/stores/users/UsersStore.js
Labels: ready-for-review, users

#8570 Fix `Field` component usage for `MessageTable` head
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Field.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx
Labels: bug, ready-for-review, search

#8572 Manage singleton for RestHighLevelClient
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
Labels: elasticsearch, ready-for-review

#8145 Add input selection for StreamRuleForm
  graylog2-server/src/main/java/org/graylog2/plugin/streams/StreamRuleType.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamRuleImpl.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamRuleMatcherFactory.java
  graylog2-server/src/main/java/org/graylog2/streams/matchers/InputMatcher.java
  graylog2-server/src/test/java/org/graylog2/streams/StreamRuleMatcherFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/streams/matchers/InputMatcherTest.java
  graylog2-web-interface/src/components/streamrules/HumanReadableStreamRule.jsx
  graylog2-web-interface/src/components/streamrules/StreamRule.jsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.test.jsx
  graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx
  graylog2-web-interface/src/components/streamrules/__snapshots__/StreamRuleForm.test.jsx.snap
  graylog2-web-interface/src/components/streams/Stream.jsx
Labels: processing, ready-for-review

#8577 Fix index stats retrieval for ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Labels: elasticsearch, ready-for-review

#8580 Reflect that ScrollChunk was turned into an interface in ScrollChunkWriter#isWritable
  graylog2-server/src/main/java/org/graylog2/rest/ScrollChunkWriter.java
Labels: bug, elasticsearch, ready-for-review

#8503 Styled-Components v5 update
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntityConfig.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackUploadControls.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/EditPatternModal.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
  graylog2-web-interface/src/components/streamrules/__snapshots__/StreamRuleForm.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap
  graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/visualizations/number/__snapshots__/NumberVisualization.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
  graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review

#8576 React AceEditor theme support and improved UI response
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
  graylog2-web-interface/src/components/common/ace/theme-graylog.js
  graylog2-web-interface/src/components/common/icon-fallback.js
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/styles/aceEditorStyles.js
  graylog2-web-interface/src/components/rules/PipelinesUsingRule.jsx
  graylog2-web-interface/src/components/rules/Rule.jsx
  graylog2-web-interface/src/components/rules/RuleContext.jsx
  graylog2-web-interface/src/components/rules/RuleForm.jsx
  graylog2-web-interface/src/components/rules/RuleHelper.jsx
  graylog2-web-interface/src/pages/RuleDetailsPage.jsx
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review, ux

#8579 Clean up es module poms
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch7/pom.xml
Labels: elasticsearch, ready-for-review

#8606 Unconditionally include time range filter in created search for ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchRequestFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
  graylog2-server/src/test/java/org/graylog2/utilities/AssertJsonPath.java
Labels: elasticsearch, ready-for-review

#8524 Add Input colors to theme & styles
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/FormControl.jsx
  graylog2-web-interface/src/components/graylog/FormGroup.jsx
  graylog2-web-interface/src/components/graylog/InputGroup.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap
  graylog2-web-interface/src/components/streamrules/__snapshots__/StreamRuleForm.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/theme/colors.js
  graylog2-web-interface/src/theme/docs/Colors.md
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: ready-for-review

#8569 Implementing SSL certificate validation for LDAP authentication.
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java
  graylog2-server/src/main/java/org/graylog2/security/realm/LdapUserAuthenticator.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorTest.java
  graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
  pom.xml
Labels: elasticsearch, ready-for-review

#8601 Bump shaded Elasticsearch versions to avoid logging errors
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
Labels: bug, elasticsearch

#8575 Fix `Field` component usage for `MessageTable` head (3.3)
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Field.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx
Labels: backport, ready-for-review, search, web

#8611 Improve naming
  graylog2-web-interface/src/components/ldap/LdapComponent.jsx
Labels: ready-for-review, ux

#8573 Roles in user edit
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/permissions/ShareableEnityURL.jsx
  graylog2-web-interface/src/components/users/PaginatedItem.jsx
  graylog2-web-interface/src/components/users/PaginatedItemOverview.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSelector.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/logic/roles/Role.js
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
Labels: users

#8527 Save system user sidebar pinning in local storage and differentiate setting for searches and dashboards
  graylog2-web-interface/src/contexts/UserPreferencesContext.js
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutContext.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.test.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutState.jsx
Labels: ready-for-review, search

#8622 Fix performance problems with react-select and formik
  graylog2-web-interface/src/components/users/UserCreate/TimezoneFormGroup.jsx
Labels: users

#8590 Teams edit
  graylog2-web-interface/src/components/users/UserDetails/TeamSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserEdit/TeamsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
Labels: ready-for-review, users

#8624 Enable hostname validation for SSL/TLS-backed LDAP connections.
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/security/DefaultX509TrustManager.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorTest.java
  graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/CA-cert.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/CA-cert.srl
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/CA-key.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/dhparam.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/server-cert.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/server-key.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/server-req.csr
  graylog2-server/src/test/resources/org/graylog2/security/ldap/single-ca.jks
Labels: ready-for-review, security

#8625 Enable hostname validation for SSL/TLS-backed LDAP connections. (3.3)
  UPGRADING.rst
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java
  graylog2-server/src/main/java/org/graylog2/security/DefaultX509TrustManager.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java
  graylog2-server/src/main/java/org/graylog2/security/realm/LdapUserAuthenticator.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorTest.java
  graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/CA-cert.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/CA-cert.srl
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/CA-key.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/dhparam.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/server-cert.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/server-key.pem
  graylog2-server/src/test/resources/org/graylog2/security/ldap/certs/server-req.csr
  graylog2-server/src/test/resources/org/graylog2/security/ldap/single-ca.jks
  pom.xml
Labels: blocker, ready-for-review, security

#8634 Find a better default for `enabled_tls_protocols`
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
  misc/graylog.conf
Labels: bug, inputs, ready-for-review

#8637 Find a better default for `enabled_tls_protocols` (3.3)
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
  misc/graylog.conf
Labels: backport, bug, ready-for-review

#8456 Register ownership for newly created dashboards / eventdefinitions
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlertConditionMigrator.java
  graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog/grn/GRNRegistry.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchExecutionGuard.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
  graylog2-server/src/main/java/org/graylog/security/GrantsAuthorizingRealm.java
  graylog2-server/src/main/java/org/graylog/security/UserContext.java
  graylog2-server/src/main/java/org/graylog/security/UserContextBinder.java
  graylog2-server/src/main/java/org/graylog/security/UserContextFactory.java
  graylog2-server/src/main/java/org/graylog/security/UserContextMissingException.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SearchFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardV1Facade.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/DBEventProcessorServiceTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionHandlerTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfigTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceUsesViewRequirementsTest.java
  graylog2-server/src/test/java/org/graylog/security/UserContextTest.java
  graylog2-server/src/test/java/org/graylog/security/entities/EntityOwnershipServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardV1FacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/ViewFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200102140000_UnifyEventSeriesIdTestIT.java
  graylog2-web-interface/src/pages/EventsPage.jsx
Labels: ready-for-review

#8648 Add function to PaginatedUserService to load users by username
  graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java
  graylog2-web-interface/src/logic/users/UserOverview.js
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
Labels: ready-for-review

#8574 Add tests for `UserCreate`, `UserDetails` and `UserEdit`
  graylog2-web-interface/src/components/common/TimezoneSelect.jsx
  graylog2-web-interface/src/components/users/PaginatedItemOverview.jsx
  graylog2-web-interface/src/components/users/TimeoutInput.jsx
  graylog2-web-interface/src/components/users/TimeoutUnitSelect.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
  graylog2-web-interface/src/components/users/UserDetails/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
Labels: ready-for-review

#8651 ContentPacksList pagination pageSizeSelector colors
  graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
Labels: improvement, ready-for-review

#8525 Scratchpad Colors
  graylog2-web-interface/src/components/common/InteractableModal.jsx
  graylog2-web-interface/src/components/common/Scratchpad.jsx
Labels: improvement, ready-for-review

#8542 Views select withtheme
  graylog2-web-interface/src/views/components/Select.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/BarVisualizationConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesSelect.test.jsx.snap
Labels: ready-for-review

#8589 Remove hex colors from Stream Rules Editor
  graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx
Labels: ready-for-review

#8605 theme code & pre elements
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Labels: ready-for-review

#8604 Panel styles with default bsStyle
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Panel.jsx
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
Labels: ready-for-review

#8635 Updating Pagination colors to prep for noire
  graylog2-web-interface/src/components/common/Pagination.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
Labels: improvement, ready-for-review

#8641 Updating Modal background and border colors
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackUploadControls.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Modal.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/EditPatternModal.test.jsx.snap
  graylog2-web-interface/src/components/streamrules/__snapshots__/StreamRuleForm.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: improvement, ready-for-review

#8640 Update colors & layout of SmallSupportLink
  graylog2-web-interface/src/components/support/SmallSupportLink.jsx
Labels: improvement, ready-for-review

#8638 Update Alert colors
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
Labels: improvement, ready-for-review

#8656 Display entities which got shared with the user on user details page
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/permissions/CapabilitySelect.jsx
  graylog2-web-interface/src/components/permissions/GranteesList.jsx
  graylog2-web-interface/src/components/permissions/GranteesListItem.jsx
  graylog2-web-interface/src/components/permissions/GranteesSelector.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesFilter.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesOverview.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesOverviewItem.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
  graylog2-web-interface/src/logic/permissions/ActiveShare.js
  graylog2-web-interface/src/logic/permissions/Capability.js
  graylog2-web-interface/src/logic/permissions/EntityShareState.js
  graylog2-web-interface/src/logic/permissions/Grantee.js
  graylog2-web-interface/src/logic/permissions/SharedEntity.js
  graylog2-web-interface/src/logic/permissions/mocked.js
  graylog2-web-interface/src/logic/permissions/types.js
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/permissions/EntityShareStore.js
  graylog2-web-interface/src/util/PaginationURL.js
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/test/fixtures/entityShareState.js
  graylog2-web-interface/test/fixtures/userEntityShares.js
Labels: ready-for-review

#8654 Update header of Sidecar Administration ListGroup
  graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.css
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
Labels: improvement, ready-for-review

#8659 Unregister entity ownersip upon delete
  graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
  graylog2-server/src/test/java/org/graylog/security/entities/EntityOwnershipServiceTest.java
Labels: ready-for-review

#8636 Updating Wizard nav color for noire
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Nav.jsx
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Labels: improvement, ready-for-review

#8619 Expose GRNPermissions to frontend
  graylog2-server/src/main/java/org/graylog/security/permissions/GRNPermission.java
  graylog2-server/src/main/java/org/graylog2/rest/models/users/responses/UserSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/shared/users/UserService.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: ready-for-review

#8662 Fix permissions linter warnings
  graylog2-web-interface/src/components/common/PageSizeSelect.jsx
  graylog2-web-interface/src/components/common/PaginatedList.test.jsx
  graylog2-web-interface/src/components/common/TimezoneSelect.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/users/LegacyTimeoutInput.jsx
  graylog2-web-interface/src/components/users/NewUserForm.jsx
  graylog2-web-interface/src/components/users/TimeoutUnitSelect.jsx
  graylog2-web-interface/src/components/users/UserForm.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: ready-for-review

#8663 Further improvements for user management ui and entity share modal
  graylog2-web-interface/src/actions/permissions/EntityShareActions.js
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/permissions/EntityShareModal.jsx
  graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx
  graylog2-web-interface/src/components/users/PaginatedItem.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesOverview.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/stores/permissions/EntityShareStore.js
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: ready-for-review
