Repository Graylog2/graylog2-server, pull requests merged in 2020-06, with the labels that each got.

#8222 Backport: Add support for more verbose authentication failure
  graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultSecurityManagerProvider.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/AuthenticationServiceUnavailableException.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ThrowingFirstSuccessfulStrategy.java
  graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java
Labels: ready-for-review

#8187 Extract interface from `Searches` class, isolate ES-specific details
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesAdapter.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexHelperTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
Labels: ready-for-review

#8188 Fix adding a new header to Http Json Path Data Adapter
  graylog2-web-interface/src/components/common/KeyValueTable.jsx
  graylog2-web-interface/src/components/common/URLWhiteListInput.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap
Labels: backport, ready-for-review, web

#8245 Retry messages if target index is read-only
  graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexBlockRetryAttempt.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesRetryWaitTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
Labels: backport, elasticsearch

#8197 Extract interface from `MoreSearch` class, isolate ES-specific details.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MultiSearch.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Scroll.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearchAdapter.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesAdapter.java
Labels: ready-for-review

#8266 Fix adding a new header to Http Json Path Data Adapter (Backport of #8188 for 3.3.1)
  graylog2-web-interface/src/components/common/KeyValueTable.jsx
  graylog2-web-interface/src/components/common/URLWhiteListInput.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.jsx
  graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap
Labels: backport, ready-for-review, web

#8272 Clear exception in auth strategy before all attempts
  graylog2-server/src/main/java/org/graylog2/shared/security/ThrowingFirstSuccessfulStrategy.java
  graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java
Labels: ready-for-review

#8268 Allow alert conditions with floating numbers
  graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js
Labels: alerting, bug, ready-for-review

#8232 Replace the GraylogSchemaFields class
  graylog2-server/src/main/java/org/graylog/schema/AlertFields.java
  graylog2-server/src/main/java/org/graylog/schema/ApplicationFields.java
  graylog2-server/src/main/java/org/graylog/schema/AssociatedFields.java
  graylog2-server/src/main/java/org/graylog/schema/AutonomousSystemFields.java
  graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java
  graylog2-server/src/main/java/org/graylog/schema/EmailFields.java
  graylog2-server/src/main/java/org/graylog/schema/EventFields.java
  graylog2-server/src/main/java/org/graylog/schema/FileFields.java
  graylog2-server/src/main/java/org/graylog/schema/GeoFields.java
  graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
  graylog2-server/src/main/java/org/graylog/schema/HostFields.java
  graylog2-server/src/main/java/org/graylog/schema/HttpFields.java
  graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java
  graylog2-server/src/main/java/org/graylog/schema/ProcessFields.java
  graylog2-server/src/main/java/org/graylog/schema/ServiceFields.java
  graylog2-server/src/main/java/org/graylog/schema/SessionFields.java
  graylog2-server/src/main/java/org/graylog/schema/SourceFields.java
  graylog2-server/src/main/java/org/graylog/schema/ThreatFields.java
  graylog2-server/src/main/java/org/graylog/schema/TraceFields.java
  graylog2-server/src/main/java/org/graylog/schema/UserFields.java
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Labels: ready-for-review

#8050 Remove elasticsearch_request_timeout config option
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
  misc/graylog.conf
Labels: elasticsearch, ready-for-review

#8275 Unmount rendered components in `HTTPJSONPathAdapterFieldSet` test to fix test failure
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.jsx
Labels: bug, ready-for-review

#8256 Removing legacy `DashboardService`.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/DashboardService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
  graylog2-server/src/main/java/org/graylog2/dashboards/Dashboard.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardService.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/DateValidator.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/FilledStringValidator.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/Migration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/MigrationDashboard.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/MigrationDashboardService.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/OptionalStringValidator.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/WidgetPosition.java
  graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/MigrationDashboardServiceTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/V20180214093600_AdjustDashboardPositionToNewResolutionTest.java
  graylog2-server/src/test/resources/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution/singleDashboard.json
Labels: ready-for-review

#8192 Add verbose failure support to LDAP authentication
  graylog2-server/src/main/java/org/graylog2/security/realm/LdapUserAuthenticator.java
  graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
Labels: improvement, ready-for-review

#8269 Retry messages if target index is read-only - 3.3 (#8245)
  graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexBlockRetryAttempt.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesRetryWaitTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
Labels: backport, elasticsearch

#8277 Fix unconditional warning
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
Labels: backport, bug, elasticsearch

#8281 Fix LdapUserAuthenticatorTest
  graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
Labels: ready-for-review

#8276 Create separate context for highlighting rules
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesContext.jsx
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.jsx
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.test.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx
  graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.test.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: improvement, ready-for-review, search

#8280 Backport: Clear exception in auth strategy before all attempts (#8272)
  graylog2-server/src/main/java/org/graylog2/shared/security/ThrowingFirstSuccessfulStrategy.java
  graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java
Labels: ready-for-review

#8064 Unify styling of widget action icons
  graylog2-web-interface/src/components/common/IconButton.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/errors/ErrorPage.jsx
  graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.css
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetActionDropdown.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.css
  graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.jsx
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
Labels: ready-for-review, search

#8247 Check only data nodes in Elasticsearch disk usage stats
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
Labels: ready-for-review

#8279 Fixing erroneous imports.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200204122000_MigrateUntypedViewsToDashboards/Widget.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/SearchAfterTest.java
  graylog2-server/src/test/java/org/graylog2/system/urlwhitelist/UrlWhitelistServiceTest.java
Labels: ready-for-review

#8052 Give search input focus when saved search list is opening
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
Labels: ready-for-review, search, ux

#8290 Allow alert conditions with floating numbers (#8268)
  graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js
Labels: backport, ready-for-review

#8282 Check only data nodes in Elasticsearch disk usage stats (3.3)
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
Labels: backport, ready-for-review

#8133 Use Bouncy Castle to decrypt PKCS#8 Keys
  graylog2-server/src/main/java/org/graylog2/shared/security/tls/PemKeyStore.java
  graylog2-server/src/test/java/org/graylog2/shared/security/tls/PemKeyStoreTest.java
  graylog2-server/src/test/java/org/graylog2/shared/security/tls/PemReaderTest.java
  graylog2-server/src/test/resources/org/graylog2/shared/security/tls/key-enc-pbe1.p8
  graylog2-server/src/test/resources/org/graylog2/shared/security/tls/key-enc-pbe2-sha256.p8
Labels: bug, ready-for-review, security

#5675 Add pagination to stream overview page
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/rest/models/streams/alerts/AlertConditionSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/StreamPageListResponse.java
  graylog2-server/src/main/java/org/graylog2/streams/PaginatedStreamService.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/streams/StreamComponent.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/lookup-tables/LookupTablesStore.js
  graylog2-web-interface/src/stores/streams/StreamsStore.js
  graylog2-web-interface/src/util/PaginationURL.js
  graylog2-web-interface/src/util/PaginationURL.test.js
Labels: feature, ux, web

#8144 Update DocsHelper.js
  graylog2-web-interface/src/util/DocsHelper.js
Labels: ready-for-review

#8190 Change Input names (fix 7345 issue)
  graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFAmqpInput.java
  graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFKafkaInput.java
  graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFTCPInput.java
  graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFUDPInput.java
Labels: ready-for-review

#8274 Fix NPE in MongoProbe if MongoDB doesn't run with MMAPv1
  graylog2-server/src/main/java/org/graylog2/system/stats/mongo/MongoProbe.java
Labels: ready-for-review

#8287 Remove not needed tab index from `WidgetHorizontalStretch`
  graylog2-web-interface/src/components/common/IconButton.jsx
  graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.jsx
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
Labels: bug, search

#8258 Post event when dashboard is deleted.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
Labels: ready-for-review

#8240 Extract interface from `Counts` class to encapsulate ES-specifics
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/CountsAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/CountsES6IT.java
  graylog2-server/src/main/java/org/graylog2/indexer/counts/Counts.java
  graylog2-server/src/main/java/org/graylog2/indexer/counts/CountsAdapter.java
  graylog2-server/src/test/java/org/graylog2/indexer/counts/CountsIT.java
Labels: ready-for-review

#8233 Extract interface from `Cluster` class.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ClusterES6IT.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/ClusterAdapter.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactory.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerClusterResource.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
Labels: ready-for-review

#8302 Log the rejected URL within RestrictToMasterFilter
  graylog2-server/src/main/java/org/graylog2/shared/security/RestrictToMasterFilter.java
Labels: improvement, ready-for-review

#8174 Monospace Font Family - Roboto Mono
  graylog2-web-interface/package.json
  graylog2-web-interface/public/stylesheets/bootstrap-config.json
  graylog2-web-interface/src/components/common/Scratchpad.jsx
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.css
  graylog2-web-interface/src/components/extractors/ExtractorExampleMessage.jsx
  graylog2-web-interface/src/components/graylog/MessageDetailsDefinitionList.jsx
  graylog2-web-interface/src/components/inputs/InputThroughput.jsx
  graylog2-web-interface/src/components/metrics/MetricsList.jsx
  graylog2-web-interface/src/components/navigation/Navigation.styles.jsx
  graylog2-web-interface/src/components/outputs/Output.jsx
  graylog2-web-interface/src/components/search/MessageFieldDescription.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationHelper.css
  graylog2-web-interface/src/components/simulator/SimulationChanges.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/theme/fonts.js
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/types.js
  graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/messagelist/MessageFields.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review, ux

#8041 Define less strict configuration for ESlint rule `jsx-a11y/label-has-associated-control`
  graylog2-web-interface/packages/eslint-config-graylog/index.js
Labels: ready-for-review

#8177 Breakpoint to breakpoints
  graylog2-web-interface/src/components/graylog/Navbar.jsx
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/theme/breakpoints.js
  graylog2-web-interface/src/theme/docs/Utilities.md
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
Labels: ready-for-review, ux

#8314 Spa is nice, but span works better
  graylog2-web-interface/src/components/search/MessageFieldDescription.jsx
Labels: bug, ready-for-review

#8313 Allow alert conditions with floating numbers
  graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js
Labels: backport, ready-for-review

#8312 Retry messages if target index is read-only
  graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexBlockRetryAttempt.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesRetryWaitTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
Labels: backport, ready-for-review

#8323 Mark legacy aggregation API as deprecated.
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/sources/SourcesResource.java
Labels: ready-for-review

#8331 Merge Graylog Schema changes from 4.0 back to 3.3
  graylog2-server/src/main/java/org/graylog/schema/AlertFields.java
  graylog2-server/src/main/java/org/graylog/schema/ApplicationFields.java
  graylog2-server/src/main/java/org/graylog/schema/AssociatedFields.java
  graylog2-server/src/main/java/org/graylog/schema/AutonomousSystemFields.java
  graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java
  graylog2-server/src/main/java/org/graylog/schema/EmailFields.java
  graylog2-server/src/main/java/org/graylog/schema/EventFields.java
  graylog2-server/src/main/java/org/graylog/schema/FileFields.java
  graylog2-server/src/main/java/org/graylog/schema/GeoFields.java
  graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
  graylog2-server/src/main/java/org/graylog/schema/HostFields.java
  graylog2-server/src/main/java/org/graylog/schema/HttpFields.java
  graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java
  graylog2-server/src/main/java/org/graylog/schema/ProcessFields.java
  graylog2-server/src/main/java/org/graylog/schema/ServiceFields.java
  graylog2-server/src/main/java/org/graylog/schema/SessionFields.java
  graylog2-server/src/main/java/org/graylog/schema/SourceFields.java
  graylog2-server/src/main/java/org/graylog/schema/ThreatFields.java
  graylog2-server/src/main/java/org/graylog/schema/TraceFields.java
  graylog2-server/src/main/java/org/graylog/schema/UserFields.java
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Labels: ready-for-review

#8084 Support editing title, description and summary of a saved search
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
  graylog2-web-interface/src/views/components/sidebar/ViewDescription.jsx
  graylog2-web-interface/src/views/components/views/ViewPropertiesModal.jsx
Labels: ready-for-review, search

#8326 Minor cleanups to encapsulate ES-specifics in storage module.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexHelper.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SortOrderMapper.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/ElasticsearchExportBackend.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndexHelperTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Sorting.java
Labels: ready-for-review

#8325 Replacing usage of `ByteSizeValue` with own, stripped-down class.
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/AbsoluteValueWatermarkSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ByteSize.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactory.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/SIUnitParser.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/SIUnitParserTest.java
  graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
Labels: ready-for-review

#8236 Move widget to tab
  graylog2-web-interface/src/views/components/widgets/MoveWidgetToTabModal.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/logic/views/AddNewWidgetsToPositions.js
  graylog2-web-interface/src/views/logic/views/AddNewWidgetsToPositions.test.js
  graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.js
  graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.js
  graylog2-web-interface/src/views/logic/views/FindWidgetAndQueryIdInView.js
  graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.Dashboard.fixture.json
  graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.Search.fixture.json
  graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.js
  graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.test.js
  graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.js
  graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.js
  graylog2-web-interface/src/views/logic/views/__snapshots__/AddNewWidgetsToPositions.test.js.snap
  graylog2-web-interface/src/views/logic/views/__snapshots__/CopyWidgetToDashboard.test.js.snap
  graylog2-web-interface/src/views/logic/views/__snapshots__/MoveWidgetToTab.test.js.snap
  graylog2-web-interface/src/views/logic/views/__snapshots__/UpdateSearchForWidgets.test.js.snap
  graylog2-web-interface/src/views/logic/views/types.js
  graylog2-web-interface/src/views/stores/CurrentViewStateStore.js
Labels: ready-for-review, search, ux

#8291 Prevent single number widget flickering
  graylog2-web-interface/src/views/components/visualizations/number/AutoFontSizer.jsx
Labels: bug, ready-for-review, search

#8329 Removing legacy Aggregation API.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/DateHistogramResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/FieldHistogramResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/HistogramResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/TermsHistogramResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/TermsResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/TermsStatsResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesAdapter.java
  graylog2-server/src/main/java/org/graylog2/rest/models/search/responses/FieldStatsResult.java
  graylog2-server/src/main/java/org/graylog2/rest/models/sources/responses/SourcesList.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/sources/SourcesResource.java
  graylog2-server/src/main/java/org/graylog2/utilities/SearchUtils.java
  graylog2-server/src/test/java/org/graylog2/indexer/results/FieldHistogramResultTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
  graylog2-server/src/test/resources/org/graylog2/indexer/searches/SearchesIT-terms_stats.json
  graylog2-web-interface/src/routing/ApiRoutes.js
Labels: ready-for-review

#8339 Generalising `scroll` method by introducing a `ScrollCommand`.
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/ScrollCommand.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesAdapter.java
Labels: ready-for-review

#8342 Moving creation of `FieldStatsResult` to storage module.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6Test.java
  graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/FieldStatsResult.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/test/java/org/graylog2/alerts/types/FieldValueAlertConditionTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/results/FieldStatsResultTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
Labels: ready-for-review

#8349 Bind IndexToolsAdapter to ES6 implementation
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
Labels: ready-for-review

#8341 Prevent single number widget flickering (Backport of #8291 for 3.3)
  graylog2-web-interface/src/views/components/visualizations/number/AutoFontSizer.jsx
Labels: backport, bug, ready-for-review, search

#8357 Extract jestclient dependency from migration
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/migrations/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateES6.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java
Labels: elasticsearch, infrastructure

#8343 Create separate context for highlighting rules (Backport of #8276 for 3.3)
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesContext.jsx
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.jsx
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.test.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx
  graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.test.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: backport, ready-for-review, search

#8347 Minor cleanups for ES-specifics in core code.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/TimeRangeQueryFactory.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/cluster/GetAllocationDiskSettings.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/ElasticsearchExportBackend.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ClusterES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/TimeRangeQueryFactoryTest.java
  graylog2-server/src/main/java/org/graylog2/bindings/ElasticsearchModule.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
Labels: ready-for-review

#8352 Support bulk indexing through test client in integration tests.
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/BulkIndexRequest.java
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java
  graylog2-server/src/test/java/org/graylog2/indexer/counts/CountsIT.java
Labels: ready-for-review

#8363 Merge latest 3.3 changes into cloud-3.3
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog/schema/AlertFields.java
  graylog2-server/src/main/java/org/graylog/schema/ApplicationFields.java
  graylog2-server/src/main/java/org/graylog/schema/AssociatedFields.java
  graylog2-server/src/main/java/org/graylog/schema/AutonomousSystemFields.java
  graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java
  graylog2-server/src/main/java/org/graylog/schema/EmailFields.java
  graylog2-server/src/main/java/org/graylog/schema/EventFields.java
  graylog2-server/src/main/java/org/graylog/schema/FileFields.java
  graylog2-server/src/main/java/org/graylog/schema/GeoFields.java
  graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
  graylog2-server/src/main/java/org/graylog/schema/HostFields.java
  graylog2-server/src/main/java/org/graylog/schema/HttpFields.java
  graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java
  graylog2-server/src/main/java/org/graylog/schema/ProcessFields.java
  graylog2-server/src/main/java/org/graylog/schema/ServiceFields.java
  graylog2-server/src/main/java/org/graylog/schema/SessionFields.java
  graylog2-server/src/main/java/org/graylog/schema/SourceFields.java
  graylog2-server/src/main/java/org/graylog/schema/ThreatFields.java
  graylog2-server/src/main/java/org/graylog/schema/TraceFields.java
  graylog2-server/src/main/java/org/graylog/schema/UserFields.java
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/sources/SourcesResource.java
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesContext.jsx
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.jsx
  graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.test.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx
  graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.test.jsx
  graylog2-web-interface/src/views/components/visualizations/number/AutoFontSizer.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: ready-for-review

#8336 Extracting interface from `ScrollResult` to encapsulate ES-specifics.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Scroll.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ScrollResultES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ScrollResultES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java
  graylog-storage-elasticsearch6/src/test/resources/org/graylog/storage/elasticsearch6/ScrollResultIT.json
  graylog2-server/src/main/java/org/graylog2/indexer/IndexerBindings.java
  graylog2-server/src/main/java/org/graylog2/indexer/results/ScrollResult.java
Labels: elasticsearch, ready-for-review

#8299 Unify visualization prop types
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilderPropTypes.js
  graylog2-web-interface/src/views/components/visualizations/ChartData.js
  graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.jsx
Labels: improvement, ready-for-review, search

#8344 Refactor field list component
  graylog2-web-interface/flow-typed/npm/react-window_vx.x.x.js
  graylog2-web-interface/src/views/components/sidebar/FieldList.css
  graylog2-web-interface/src/views/components/sidebar/FieldList.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldGroup.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.test.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/ListItem.jsx
  graylog2-web-interface/src/views/components/sidebar/index.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: improvement, ready-for-review, search

#8375 Fixing `ScrollResultES6` factory's assisted injection annotations.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ScrollResultES6.java
Labels: ready-for-review

#8298 Update font awesome icon names regarding font awesome v5
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/Icon.jsx
  graylog2-web-interface/src/components/common/Icon.md
  graylog2-web-interface/src/components/common/LinkToNode.jsx
  graylog2-web-interface/src/components/common/Scratchpad.jsx
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
  graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/configurations/TimeRangeOptionsForm.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx
  graylog2-web-interface/src/components/indexers/IndexerClusterHealthSummary.jsx
  graylog2-web-interface/src/components/loggers/NodeLoggers.jsx
  graylog2-web-interface/src/components/lookup-tables/ErrorPopover.jsx
  graylog2-web-interface/src/components/metrics/Metric.jsx
  graylog2-web-interface/src/components/navigation/UserMenu.jsx
  graylog2-web-interface/src/components/nodes/SystemOverviewDetails.jsx
  graylog2-web-interface/src/components/pipelines/Stage.jsx
  graylog2-web-interface/src/components/search/MessageDetail.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatusFileList.jsx
  graylog2-web-interface/src/components/streamrules/StreamRule.jsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx
  graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx
  graylog2-web-interface/src/components/support/SmallSupportLink.jsx
  graylog2-web-interface/src/components/support/SupportSources.jsx
  graylog2-web-interface/src/pages/LoadingPage.jsx
  graylog2-web-interface/src/pages/LoginPage.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/BarVisualizationConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/messagelist/NodeName.jsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/FieldTypeIcon.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx
  graylog2-web-interface/src/views/components/widgets/EmptyResultWidget.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx
  graylog2-web-interface/src/views/components/widgets/LoadingWidget.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.jsx
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review, ux

#8378 Adding import/order rule to eslint config
  graylog2-web-interface/packages/eslint-config-graylog/index.js
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review

#8334 Add min width for data table columns
  graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
Labels: ready-for-review, search

#8383 Adding missing binding for `CountsAdapter`.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
Labels: ready-for-review

#8381 Use an openjdk docker image with a fixed debian version
  graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
Labels: infrastructure, ready-for-review

#8382 Update `/rebase` action.
  .github/workflows/rebase.yml
Labels: ready-for-review

#8389 Fix OperationSytemIcon icon props
  graylog2-web-interface/src/components/sidecars/common/OperatingSystemIcon.jsx
Labels: bug, ready-for-review

#8300 Fixing `ViewActionsMenu` and `EntityListItem` prop type errors
  graylog2-web-interface/src/components/common/EntityListItem.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
Labels: improvement, ready-for-review, search

#8398 Define dynamic width for search loading indicator
  graylog2-web-interface/src/components/common/LoadingIndicator.css
  graylog2-web-interface/src/components/common/LoadingIndicator.jsx
Labels: bug, ready-for-review, search

#8366 Don't reset grace period timer while in grace period
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationGracePeriodService.java
  graylog2-server/src/test/java/org/graylog/events/processor/notification/NotificationGracePeriodServiceTest.java
Labels: bug, ready-for-review

#7836 Create separate context for current user
  graylog2-web-interface/src/contexts/CurrentUserContext.jsx
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.jsx
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.jsx
  graylog2-web-interface/src/contexts/CurrentUserProvider.jsx
  graylog2-web-interface/src/contexts/CurrentUserProvider.test.jsx
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/routing/AppRouter.test.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.test.jsx
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.jsx
  graylog2-web-interface/src/views/components/datatable/DataTable.test.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchForm.jsx
  graylog2-web-interface/src/views/components/sidebar/SearchResultOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.test.jsx
  graylog2-web-interface/src/views/components/views/View.jsx
  graylog2-web-interface/src/views/components/visualizations/OnZoom.js
  graylog2-web-interface/src/views/components/visualizations/TransformKeys.js
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/TransformKeys.test.js
  graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
  graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
  graylog2-web-interface/test/fixtures/users.js
Labels: improvement, ready-for-review

#8401 Dynamically center search page loading indicator
  graylog2-web-interface/src/components/common/LoadingIndicator.jsx
Labels: bug, ready-for-review, search

#8356 Replace direct imports of react-select select with custom select
  graylog2-web-interface/src/views/components/Select.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/NumberVisualizationConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SortSelect.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/BarVisualizationConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesSelect.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/SortDirectionSelect.jsx
Labels: improvement, ready-for-review, search

#8131 Fix getting started guide page scroll behaviour
  graylog2-web-interface/src/components/gettingstarted/GettingStarted.jsx
  graylog2-web-interface/src/pages/GettingStartedPage.jsx
Labels: improvement, ready-for-review, ux

#7929 Implement field types context for search pages
  graylog2-web-interface/src/views/components/SearchResult.jsx
  graylog2-web-interface/src/views/components/SearchResult.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.test.jsx
  graylog2-web-interface/src/views/components/contexts/DefaultFieldTypesProvider.jsx
  graylog2-web-interface/src/views/components/contexts/DefaultFieldTypesProvider.test.jsx
  graylog2-web-interface/src/views/components/contexts/FieldTypesContext.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.test.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/ListItem.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
  graylog2-web-interface/test/fixtures/fields.js
Labels: improvement, ready-for-review

#8354 Define bar width if bar chart contains only data for a single date
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx
  graylog2-web-interface/src/views/components/datatable/DataTable.test.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx
  graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx
  graylog2-web-interface/src/views/components/visualizations/number/__snapshots__/NumberVisualization.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/Pivot.js
Labels: bug, ready-for-review, search

#8364 Moving Jest infrastructure classes to storage module.
  full-backend-tests/pom.xml
  graylog-storage-elasticsearch6/assembly.xml
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/CountsAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexFieldTypePollerAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexToolsAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MultiSearch.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/NodeAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Scroll.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestClientProvider.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestUtils.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/migrations/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/JestWrapper.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ClusterES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ScrollResultES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/JestClientProviderTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/JestUtilsTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/bindings/ElasticsearchModule.java
Labels: elasticsearch, ready-for-review

#8391 Update Colors documentation
  graylog2-web-interface/src/theme/docs/Colors.md
  graylog2-web-interface/src/theme/docs/Utilities.md
Labels: bug, documentation, ready-for-review

#8402 Don't reset grace period timer while in grace period (#8366)
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationGracePeriodService.java
  graylog2-server/src/test/java/org/graylog/events/processor/notification/NotificationGracePeriodServiceTest.java
Labels: backport, bug, ready-for-review

#8385 Display message table head in non interactive mode
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Field.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
Labels: bug, ready-for-review, search

#8315 Theme modes removal
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/components/graylog/Badge.jsx
  graylog2-web-interface/src/components/graylog/Button.jsx
  graylog2-web-interface/src/components/graylog/DropdownButton.jsx
  graylog2-web-interface/src/components/graylog/FormGroup.jsx
  graylog2-web-interface/src/components/graylog/Label.jsx
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
  graylog2-web-interface/src/components/graylog/Panel.jsx
  graylog2-web-interface/src/components/graylog/ProgressBar.jsx
  graylog2-web-interface/src/components/graylog/SplitButton.jsx
  graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap
  graylog2-web-interface/src/components/graylog/props/button.js
  graylog2-web-interface/src/components/graylog/variants/bsStyle.js
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#8415 Display message table head in non interactive mode (Backport of #8385 for 3.3)
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Field.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
Labels: backport, bug, ready-for-review, search

#8372 Provision ES storage implementation based on configured ES version.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Plugin.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ViewsESBackendModule.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/views/providers/ExportBackendProvider.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
  graylog2-server/src/main/java/org/graylog2/plugin/VersionAwareModule.java
  graylog2-server/src/main/java/org/graylog2/storage/VersionAwareProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/VersionAwareStorageModule.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/ClusterAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/EventIndexerAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/IndexFieldTypePollerAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/IndexToolsAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/IndicesAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/MessagesAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/MoreSearchAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/NodeAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/SearchesAdapterProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider.java
Labels: ready-for-review

#8355 Reset aggregation builder sort and sort direction select when related row pivot gets removed
  graylog2-web-interface/src/views/components/aggregationbuilder/SortSelect.jsx
  graylog2-web-interface/src/views/components/widgets/SortDirectionSelect.jsx
Labels: bug, ready-for-review, search

#8369 Theming Select component
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/components/common/Select.test.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
Labels: ready-for-review, ux

#8422 Merge latest 3.3 changes into cloud-3.3
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationGracePeriodService.java
  graylog2-server/src/test/java/org/graylog/events/processor/notification/NotificationGracePeriodServiceTest.java
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Field.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  integration-tests/pom.xml
  pom.xml
Labels: ready-for-review

#8408 Use shaded Elasticsearch dependency in ES6 storage module
  full-backend-tests/pom.xml
  graylog-project-parent/pom.xml
  graylog-storage-elasticsearch6/assembly.xml
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/CountsAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexToolsAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SortOrderMapper.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/TimeRangeQueryFactory.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ESGeneratedQueryContext.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/ElasticsearchExportBackend.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/RequestStrategy.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/SearchAfter.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/ESMessageList.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/ESPivot.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/ESPivotBucketSpecHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/ESPivotSeriesSpecHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/buckets/ESDateRangeHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/buckets/ESTimeHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/buckets/ESValuesHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESAverageHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESCardinalityHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESCountHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESMaxHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESMinHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESPercentilesHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESStdDevHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESSumHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESSumOfSquaresHandler.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/series/ESVarianceHandler.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ScrollResultES6IT.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/TimeRangeQueryFactoryTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendErrorHandlingTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/searchtypes/ESMessageListTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivots/ESPivotTest.java
  graylog2-server/src/main/resources/plugin-descriptor.properties
  pom.xml
Labels: elasticsearch, ready-for-review

#8379 Adding padding-line-between-statements to eslint
  graylog2-web-interface/packages/eslint-config-graylog/index.js
  graylog2-web-interface/packages/eslint-config-graylog/package.json
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review

#8430 Starting Elasticsearch 7 storage driver module.
  distribution/pom.xml
  distribution/src/main/assembly/graylog.xml
  full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java
  graylog-storage-elasticsearch7/assembly.xml
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Metadata.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Plugin.java
  graylog-storage-elasticsearch7/src/main/resources/META-INF/services/org.graylog2.plugin.Plugin
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
  graylog2-server/src/test/resources/api-it-tests.properties
  pom.xml
Labels: elasticsearch, ready-for-review

#8429 Add GRN support
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java
  graylog2-server/src/main/java/org/graylog2/utilities/GRN.java
  graylog2-server/src/main/java/org/graylog2/utilities/GRNDeserializer.java
  graylog2-server/src/main/java/org/graylog2/utilities/GRNKeyDeserializer.java
  graylog2-server/src/main/java/org/graylog2/utilities/GRNRegistry.java
  graylog2-server/src/main/java/org/graylog2/utilities/GRNType.java
  graylog2-server/src/test/java/org/graylog2/utilities/GRNRegistryTest.java
  graylog2-server/src/test/java/org/graylog2/utilities/GRNTest.java
Labels: feature, ready-for-review

#8371 Display error message for search bar time range inputs
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx
Labels: ready-for-review, search

#8432 Pass env var GRAYLOG_ELASTICSEARCH_VERSION to NodeInstance
  full-backend-tests/src/test/java/org/graylog/storage/elasticsearch6/ElasticsearchInstanceES6Factory.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/ElasticsearchInstanceFactory.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java
Labels: elasticsearch, infrastructure

#8438 Add new permission backend
  graylog2-server/src/main/java/org/graylog/security/BuiltinRoles.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/DefaultGrantPermissionResolver.java
  graylog2-server/src/main/java/org/graylog/security/GrantDTO.java
  graylog2-server/src/main/java/org/graylog/security/GrantPermissionResolver.java
  graylog2-server/src/main/java/org/graylog/security/GrantsAuthorizingRealm.java
  graylog2-server/src/main/java/org/graylog/security/RoleDTO.java
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
  graylog2-server/src/main/java/org/graylog/security/permissions/GRNPermission.java
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/rest/RestResourceWithOwnerCheck.java
  graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareRequest.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareResponse.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntityShareRequest.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/main/java/org/graylog/security/shares/GranteeService.java
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthorizationOnlyRealmModule.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Labels: enterprise, feature, ready-for-review
