Repository Graylog2/graylog2-server, pull requests merged in 2020-11, with the labels that each got.

#9309 Clean-up ESLint configuration
  graylog2-web-interface/.eslintrc.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/eslint-config-graylog/index.js
  graylog2-web-interface/packages/eslint-config-graylog/package.json
  graylog2-web-interface/packages/graylog-web-plugin/.eslintrc
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review

#9307 Avoid using throw by displaying an Alert
  graylog2-web-interface/src/components/common/ErrorAlert.jsx
  graylog2-web-interface/src/components/common/ErrorAlert.test.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/permissions/RolesSelector.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
Labels: ready-for-review, users

#9324 Remove some stale TODOS from BuiltinCapabilities
  graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
Labels: ready-for-review

#9333 Add UserService#loadByIds to get all users for the given IDs
  graylog2-server/src/main/java/org/graylog/security/authzroles/PaginatedAuthzRolesService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
  graylog2-server/src/main/java/org/graylog2/shared/users/UserService.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog/security/authzroles/PaginatedAuthzRolesServiceTest.java
  graylog2-server/src/test/java/org/graylog/testing/TestUserService.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: ready-for-review

#9319 Show grok patterns to users with reader role
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
Labels: ready-for-review, web

#9330 Fix grid layout for user create form buttons
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
Labels: bug, ready-for-review

#9334 Missed a few places when converting username to userId
  graylog2-server/src/main/java/org/graylog/security/UserContext.java
  graylog2-server/src/main/java/org/graylog2/rest/RestTools.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/RestAccessLogFilter.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroAuthorizationFilter.java
Labels: ready-for-review

#9313 Add missing binding of GRNRegistry for journal decode command
  graylog2-server/src/main/java/org/graylog/grn/GRNModule.java
  graylog2-server/src/main/java/org/graylog/grn/GRNTypesModule.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/ObjectMapperModule.java
Labels: ready-for-review

#9335 Fix audit event types for auth service endpoints
  graylog2-server/src/main/java/org/graylog/security/SecurityAuditEventTypes.java
Labels: ready-for-review

#9332 Close active search sidebar section when clicking on its navigation item
  graylog2-web-interface/src/views/components/sidebar/Sidebar.jsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.test.jsx
  graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.jsx
Labels: ready-for-review, search

#8948 Add phone number to free enterprise license request
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeEnterpriseService.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseAPIRequest.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseRequest.java
  graylog2-web-interface/src/components/bootstrap/Input.jsx
  graylog2-web-interface/src/components/enterprise/EnterpriseFreeLicenseForm.jsx
  graylog2-web-interface/src/stores/enterprise/EnterpriseStore.js
Labels: ready-for-review

#9276 Fix z-index of the search loading indicator
  graylog2-web-interface/src/views/components/Search.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
Labels: bug, ready-for-review

#9329 Improve SearchForm, PageSizeSelect and PageHeader layout responsiveness
  graylog2-web-interface/src/components/common/PageHeader.jsx
  graylog2-web-interface/src/components/common/PageSizeSelect.jsx
  graylog2-web-interface/src/components/common/SearchForm.css
  graylog2-web-interface/src/components/common/SearchForm.jsx
Labels: bug, ready-for-review

#9336 Do not stop click events on `LinkContainer` if modifier-keys are used.
  graylog2-web-interface/src/components/graylog/LinkContainer.test.jsx
  graylog2-web-interface/src/components/graylog/router.jsx
Labels: bug, ready-for-review

#9337 Sync cloud with 3.3
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
Labels: ready-for-review

#9338 Retry indexing message if primary shard is not active for ES6.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6Test.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
Labels: ready-for-review

#9350 Define in eslint-config-graylog which file extensions should be included when running ESLint
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/eslint-config-graylog/index.js
Labels: ready-for-review

#9348 Refactor resource paths for consistency
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/rest/GrantsOverviewResource.java
  graylog2-web-interface/src/routing/ApiRoutes.js
Labels: ready-for-review

#9346 Publish events on authentication service activation and deletion
  graylog2-server/src/main/java/org/graylog/security/authservice/DBAuthServiceBackendService.java
  graylog2-server/src/main/java/org/graylog/security/authservice/GlobalAuthServiceConfig.java
  graylog2-server/src/main/java/org/graylog/security/events/ActiveAuthServiceBackendChangedEvent.java
  graylog2-server/src/main/java/org/graylog/security/events/AuthServiceBackendDeletedEvent.java
Labels: ready-for-review

#9271 Render conditionals for Cloud specific elements
  graylog2-web-interface/src/util/conditional/filterMenuItems.js
  graylog2-web-interface/src/util/conditional/filterMenuItems.test.js
  graylog2-web-interface/src/util/conditional/withHideOnCloud.jsx
Labels: ready-for-review

#9342 Add migration for legacy LDAP/AD configuration
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20201103145400_LegacyAuthServiceMigration.java
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
  graylog2-web-interface/src/util/DocsHelper.js
Labels: ready-for-review

#9356 Fix JDK TLS protocol detection
  graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
Labels: ready-for-review

#9316 Fail graciously when cannot get node metrics
  graylog2-web-interface/src/components/metrics/MetricsComponent.jsx
  graylog2-web-interface/src/pages/ShowMetricsPage.jsx
  graylog2-web-interface/src/stores/metrics/MetricsStore.js
Labels: ready-for-review

#9278 HTTP header authentication realm
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceCredentials.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/rest/HTTPHeaderAuthenticationConfigResource.java
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/security/StaticOrderedAuthenticatingRealms.java
  graylog2-server/src/main/java/org/graylog2/security/headerauth/HTTPHeaderAuthConfig.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthenticatingRealmModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/HTTPHeaderAuthenticationRealm.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
  graylog2-web-interface/src/actions/authentication/HTTPHeaderAuthConfigActions.js
  graylog2-web-interface/src/components/authentication/AuthenticationOverviewLinks.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorActionLinks.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsDetails/AuthenticatorsDetails.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsDetails/HTTPHeaderAuthConfigSection.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsDetails/HTTPHeaderAuthConfigSection.test.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsDetails/index.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsEdit/AuthenticatorsEdit.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsEdit/HTTPHeaderAuthConfigSection.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsEdit/HTTPHeaderAuthConfigSection.test.jsx
  graylog2-web-interface/src/components/authentication/AuthenticatorsEdit/index.jsx
  graylog2-web-interface/src/components/authentication/BackendActionLinks.jsx
  graylog2-web-interface/src/components/authentication/BackendOverviewLinks.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/WizardPageHeader.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/WizardPageHeader.jsx
  graylog2-web-interface/src/domainActions/authentication/HTTPHeaderAuthConfigDomain.js
  graylog2-web-interface/src/logic/authentication/HTTPHeaderAuthConfig.js
  graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.jsx
  graylog2-web-interface/src/pages/AuthenticationCreatePage.jsx
  graylog2-web-interface/src/pages/AuthenticationOverviewPage.jsx
  graylog2-web-interface/src/pages/AuthenticationPage.jsx
  graylog2-web-interface/src/pages/AuthenticatorsEditPage.jsx
  graylog2-web-interface/src/pages/AuthenticatorsPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/authentication/HTTPHeaderAuthConfigStore.js
  graylog2-web-interface/src/util/DocsHelper.js
Labels: ready-for-review

#9345 Adding "Click to Close" to UserNotification
  graylog2-web-interface/src/util/UserNotification.css
  graylog2-web-interface/src/util/UserNotification.js
Labels: improvement, ready-for-review, ux

#9355 Display an warning if a grantee was not found
  graylog2-web-interface/src/components/permissions/GranteeIcon.jsx
  graylog2-web-interface/src/components/permissions/GranteesListItem.jsx
  graylog2-web-interface/src/logic/permissions/EntityShareState.js
  graylog2-web-interface/src/logic/permissions/types.js
Labels: ready-for-review, users

#9365 Improve UserEdit and RoleEdit tests by splitting them up
  graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.test.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/TeamsSection.test.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/PasswordSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/TeamsSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
Labels: ready-for-review

#9352 Cleanup role and grant references
  graylog2-server/src/main/java/org/graylog/events/notifications/DBNotificationService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRoleDTO.java
  graylog2-server/src/main/java/org/graylog/security/authzroles/PaginatedAuthzRolesService.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
  graylog2-server/src/test/java/org/graylog/security/authzroles/PaginatedAuthzRolesServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/entities/EntityOwnershipServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
  graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
Labels: ready-for-review

#9344 Remove legacy LDAP and pluggable authentication realm code
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/cluster/LdapGroupMappingMigrationState.java
  graylog2-server/src/main/java/org/graylog2/periodical/LdapGroupMappingMigration.java
  graylog2-server/src/main/java/org/graylog2/plugin/DocsHelper.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/requests/LdapSettingsRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/requests/LdapTestConfigRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/responses/LdapSettingsResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/responses/LdapTestConfigResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/authentication/AuthenticationResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/security/AuthenticationConfig.java
  graylog2-server/src/main/java/org/graylog2/security/DynamicOrderedAuthenticatingRealms.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsService.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthenticatingRealmModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/LdapUserAuthenticator.java
  graylog2-server/src/main/java/org/graylog2/security/realm/PasswordAlgorithmCredentialsMatcher.java
  graylog2-server/src/main/java/org/graylog2/security/realm/PasswordAuthenticator.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ldap/LdapEntry.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ldap/LdapSettings.java
  graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStats.java
  graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java
  graylog2-server/src/main/java/org/graylog2/system/stats/LdapStats.java
  graylog2-server/src/main/java/org/graylog2/users/UserPermissionsCleanupListener.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorTest.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapSettingsServiceImplTest.java
  graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
  graylog2-server/src/test/java/org/graylog2/shared/security/ldap/LdapEntryTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserPermissionsCleanupListenerTest.java
  graylog2-server/src/test/resources/org/graylog2/security/ldap/LdapSettingsServiceImplTest-invalid-password.json
  graylog2-server/src/test/resources/org/graylog2/security/ldap/LdapSettingsServiceImplTest.json
Labels: ready-for-review

#9366 Remove unusual domain actions usage in auth backend edit and create component
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverviewItem.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx
  graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.js
Labels: ready-for-review

#9360 Hide edit profile and password section for external user
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
Labels: ready-for-review, users

#9306 Fix read handling of corrupted journal segments
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
  graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
Labels: ready-for-review

#9370 Change RolesSelector button type from submit to button
  graylog2-web-interface/src/components/permissions/RolesSelector.jsx
Labels: bug, ready-for-review

#9375 Revert "Fix read handling of corrupted journal segments"
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
  graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
Labels: ready-for-review

#9384 Enable sources build for ES storage modules
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch7/pom.xml
Labels: blocker, ready-for-review

#9379 Fix view type detection for user permission migration
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigration.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigrationTest.java
  graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_GrantsMigrations/MigrateUserPermissionsToGrantsTest.json
Labels: ready-for-review

#9377 Do not wrap group sync details plugin with a section component.
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/BackendDetailsActive.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedTeamsSection.jsx
  graylog2-web-interface/src/components/authentication/bindings.js
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/BackendConfigDetails.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/EditLinkButton.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/ServerConfigSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/UserSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/index.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ConnectionErrors.jsx
Labels: ready-for-review

#9367 Fix Input error color for Inputs which use the help prop to display errors
  graylog2-web-interface/src/components/common/InputDescription.jsx
Labels: ready-for-review

#9373 Add ESLint changes to plugin archetype.
  graylog-plugin-archetype/src/main/resources/archetype-resources/.eslintrc
  graylog-plugin-archetype/src/main/resources/archetype-resources/package.json
Labels: ready-for-review

#9383 Display explanation for share button why unsaved searches and dashboards can not be shared
  graylog2-web-interface/src/components/common/ShareButton.jsx
  graylog2-web-interface/src/components/common/ShareButton.test.jsx
  graylog2-web-interface/src/components/permissions/SharingDisabledPopover.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
Labels: ready-for-review

#9393 Update from RC to final version of testcontainers 1.15.0
  pom.xml
Labels: ready-for-review

#9358 Fail graciously when cannot get node metrics (#9316)
  graylog2-web-interface/src/components/metrics/MetricsComponent.jsx
  graylog2-web-interface/src/pages/ShowMetricsPage.jsx
  graylog2-web-interface/src/stores/metrics/MetricsStore.js
Labels: ready-for-review

#9394 Make sure to use the OSS ES container for tests
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
Labels: ready-for-review

#9374 Implement and enforce user account status
  graylog2-server/src/main/java/org/graylog/security/authservice/ProvisionerService.java
  graylog2-server/src/main/java/org/graylog/security/authservice/UserDetails.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/ADUserAccountControl.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/ADUserAccountControlFlags.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/LDAPUser.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
  graylog2-server/src/main/java/org/graylog2/plugin/database/users/User.java
  graylog2-server/src/main/java/org/graylog2/rest/models/users/responses/UserSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AccessTokenAuthenticator.java
  graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
  graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/ADUserAccountControlFlagsTest.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/ADUserAccountControlTest.java
  graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java
Labels: ready-for-review

#9390 Don't allow modifications of email and full name for external users
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Labels: ready-for-review

#9408 Exempt Illuminate Fields from Traffic Accounting.
  graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
Labels: ready-for-review

#9404 Create session when user can be authenticated based on trusted header
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
  graylog2-server/src/main/java/org/graylog2/security/realm/HTTPHeaderAuthenticationRealm.java
Labels: ready-for-review

#9410 Fix EventsSearchService to only filter for event messages
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java
Labels: ready-for-review

#9412 Display backend validation errors next to related input in directory service wizard
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/GroupSyncStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserSyncStep.jsx
  graylog2-web-interface/src/components/common/FormikInput.jsx
  graylog2-web-interface/src/components/common/InputDescription.jsx
Labels: ready-for-review

#9385 Display synced users section on every authentication service details page
  graylog2-server/src/main/java/org/graylog/security/authservice/rest/AuthServiceBackendsResource.java
  graylog2-server/src/main/java/org/graylog/security/authservice/rest/AuthServicesResource.java
  graylog2-web-interface/src/actions/authentication/AuthenticationActions.js
  graylog2-web-interface/src/components/authentication/BackendDetails/BackendDetails.jsx
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedTeamsSection.jsx
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersFilter.jsx
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersOverviewItem.jsx
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersSection.jsx
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/index.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/BackendDetailsActive.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/index.jsx
  graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.js
  graylog2-web-interface/src/pages/AuthenticationPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/authentication/AuthenticationStore.js
Labels: ready-for-review

#9416 Update code name for the upcoming release
  graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
Labels: ready-for-review

#9415 Register ownership for streams
  graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamService.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdaterTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
Labels: ready-for-review

#9391 Consistently Load the Proper Theme
  graylog2-web-interface/src/components/graylog/Popover.jsx
  graylog2-web-interface/src/components/graylog/Tooltip.jsx
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.jsx
  graylog2-web-interface/src/contexts/ThemeAndUserProvider.jsx
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/theme/UseCurrentThemeMode.jsx
Labels: bug, ready-for-review

#9417 Use List instead of Set to keep default sort order of grants
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/rest/GrantsOverviewResource.java
Labels: ready-for-review

#9414 Allow configuring title and description of an authentication backend
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.jsx
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverviewItem.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/ServerConfigSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/PrepareInitialWizardValues.js
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
  graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.js
Labels: ready-for-review

#9386 We put new selections to the top of selected grantees
  graylog2-web-interface/src/logic/permissions/EntityShareState.fixtures.json
  graylog2-web-interface/src/logic/permissions/EntityShareState.js
  graylog2-web-interface/src/logic/permissions/EntityShareState.test.js
  graylog2-web-interface/src/logic/permissions/__snapshots__/EntityShareState.test.js.snap
Labels: ready-for-review

#8554 type check unary NOT operator
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/errors/IncompatibleType.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdater.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/notExpressionTypeCheck.txt
Labels: bug, processing

#9409 Show users in roles overview
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
  graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.test.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverviewItem.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/UsersCell.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/src/stores/users/RolesStore.js
Labels: ready-for-review

#9420 Create common TextOverflowEllipsis component and implement it for roles and auth backend overview
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverviewItem.jsx
  graylog2-web-interface/src/components/common/TextOverflowEllipsis.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverviewItem.jsx
Labels: ready-for-review

#9424 Fix condition for session extension
  graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java
Labels: blocker, ready-for-review

#9427 Do not create new component for plugin routes with parent on every AppRouter render
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: bug, ready-for-review

#9430 Use description instead of spinner in search sidebar description section
  graylog2-web-interface/src/views/components/sidebar/description/SearchResultOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/description/ViewDescription.jsx
Labels: bug, ready-for-review

#9428 Prevent search bar elements from overlaying search sidebar
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
Labels: bug, ready-for-review

#9426 Display and manage user account status in the frontend
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-web-interface/src/actions/authentication/AuthenticationActions.js
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersOverviewItem.jsx
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersSection.jsx
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.jsx
  graylog2-web-interface/src/components/users/LoggedInIcon.jsx
  graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/StatusCell.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/UsersOverviewItem.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
  graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.js
  graylog2-web-interface/src/domainActions/users/UsersDomain.js
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/logic/users/UserOverview.js
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/authentication/AuthenticationStore.js
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/test/fixtures/users.js
Labels: users

#9434 Terminate active sessions for disabled users
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationListener.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java
Labels: ready-for-review

#9436 Fix cluster stats endpoints.
  UPGRADING.rst
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/DashboardService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterStatsResource.java
  graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java
Labels: blocker, ready-for-review

#9441 Fix cluster stats endpoints. (4.0)
  UPGRADING.rst
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/DashboardService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterStatsResource.java
  graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java
Labels: bug, ready-for-review

#9440 Terminate active sessions for disabled users
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationListener.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java
Labels: backport, ready-for-review

#9446 Enable jdk.tls.acknowledgeCloseNotify by default
  bin/graylogctl
  graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
Labels: blocker, bug, ready-for-review

#9452 Enable jdk.tls.acknowledgeCloseNotify by default (#9446)
  bin/graylogctl
  graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
Labels: alerting, backport, blocker, ready-for-review

#9340 Fix behavior of Apply for new Pipeline Rules
  graylog2-web-interface/src/components/rules/RuleContext.jsx
  graylog2-web-interface/src/components/rules/RuleForm.jsx
  graylog2-web-interface/src/stores/rules/RulesStore.js
Labels: processing, ready-for-review, ux, web

#9453 Show missing menu items for Default Stream
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
Labels: backport, processing, ready-for-review, ux

#9437 Prevent disabling your own user account
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx
Labels: ready-for-review, users

#9458 Show missing menu items for Default Stream (Backport for 4.0)
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
Labels: backport, processing, ready-for-review, ux

#9456 Fix scoping of current page in system messages list.
  graylog2-web-interface/src/components/systemmessages/SystemMessagesComponent.jsx
Labels: ready-for-review

#9448 Add reset startpage button to profile section of user edit 4.0
  graylog2-web-interface/src/components/streams/StreamControls.jsx
  graylog2-web-interface/src/components/users/UserEdit/PreferencesSection.jsx
Labels: ready-for-review, users

#9463 Fix index field types update
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
Labels: blocker, ready-for-review

#9468 Fix index field types update (#9463)
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
Labels: blocker, ready-for-review

#9470 Fix scoping of current page in system messages list. (4.0)
  graylog2-web-interface/src/components/systemmessages/SystemMessagesComponent.jsx
Labels: ready-for-review

#9471 Update roles section on user edit page correctly when assigning or removing a role
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
Labels: backport, bug, ready-for-review

#9476 Remove unused endpoint
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
Labels: ready-for-review

#9474 Use the correct permission for role assignment
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
Labels: blocker, bug, ready-for-review

#9475 Use the correct permission for role assignment
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
Labels: backport, blocker, bug, ready-for-review

#9477 Update roles section on user edit page correctly when assigning or removing a role (Backport for 4.0)
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
Labels: backport, bug, ready-for-review

#9483 Fix error in authentication service details group sync section which occurs without an enterprise plugin
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.test.jsx
  graylog2-web-interface/test/fixtures/authenticationBackends.js
Labels: backport, bug, ready-for-review

#9486 Fix error in authentication service details group sync section which occurs without an enterprise plugin (Backport for 4.0)
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.test.jsx
  graylog2-web-interface/test/fixtures/authenticationBackends.js
Labels: bug, ready-for-review

#9372 Port cloud-3.3 to cloud-4.0
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
  graylog2-server/src/main/java/org/graylog2/periodical/ClusterHealthCheckThread.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
  graylog2-server/src/main/resources/web-interface/config.js.template
  graylog2-web-interface/config.js
  graylog2-web-interface/src/components/navigation/DevelopmentHeaderBadge.jsx
  graylog2-web-interface/src/util/AppConfig.js
  graylog2-web-interface/src/util/conditional/filterMenuItems.js
  graylog2-web-interface/src/util/conditional/filterMenuItems.test.js
  graylog2-web-interface/src/util/conditional/withHideOnCloud.jsx
  graylog2-web-interface/webpack.combined.config.js
  graylog2-web-interface/webpack.config.js
Labels: ready-for-review

#9411 Enable TypeScript in webpack build.
  graylog2-server/pom.xml
  graylog2-web-interface/babel.config.js
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/tsconfig.json
  graylog2-web-interface/webpack.combined.config.js
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/yarn.lock
Labels: infrastructure, ready-for-review

#9490 Remove logging config for apache ldap client
  graylog2-server/src/main/resources/log4j2.xml
Labels: ready-for-review

#9423 Hide indices on cloud
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
  graylog2-web-interface/src/pages/SystemOverviewPage.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/util/conditional/HideOnCloud.js
  graylog2-web-interface/src/util/conditional/withHideOnCloud.jsx
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
Labels: ready-for-review

#9509 Some more license fixes for SSPL
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
Labels: ready-for-review

#9510 Some more license fixes for SSPL
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
Labels: ready-for-review

#9511 Make sure jest-environment pragma is at the top of the file
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
Labels: ready-for-review

#9512 Make sure jest-environment pragma is at the top of the file
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
Labels: ready-for-review

#9449 Support TypeScript in ESLint.
  graylog2-web-interface/packages/eslint-config-graylog/index.js
  graylog2-web-interface/packages/eslint-config-graylog/package.json
Labels: ready-for-review

#9450 Support TypeScript in Jest.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.test.tsx
  graylog2-web-interface/test/setup-jest.js
  graylog2-web-interface/tsconfig.json
Labels: ready-for-review

#9498 Hide ES cluster info and system jobs on systems overview page
  graylog2-web-interface/src/pages/SystemOverviewPage.jsx
Labels: ready-for-review

#9523 Fix badges in README
  README.markdown
Labels: ready-for-review

#9516 Fix incorrect Commercial support link
  graylog2-server/src/main/java/org/graylog2/shared/UI.java
Labels: ready-for-review

#9520 A few minor wording adjustments for the new Users pages
  graylog2-web-interface/src/components/users/PermissionsUpdateInfo.tsx
  graylog2-web-interface/src/components/users/TimeoutInput.tsx
  graylog2-web-interface/src/components/users/UserCreate/EmailFormGroup.tsx
  graylog2-web-interface/src/components/users/UserCreate/FullNameFormGroup.tsx
  graylog2-web-interface/src/components/users/UsersOverview/SystemAdministratorOverview.tsx
  graylog2-web-interface/src/pages/RolesOverviewPage.jsx
Labels: ready-for-review

#9533 Migrate roles components to typescript
  graylog2-web-interface/src/components/roles/RoleDetails/ProfileSection.tsx
  graylog2-web-interface/src/components/roles/RoleDetails/RoleDetails.test.tsx
  graylog2-web-interface/src/components/roles/RoleDetails/RoleDetails.tsx
  graylog2-web-interface/src/components/roles/RoleDetails/TeamsSection.tsx
  graylog2-web-interface/src/components/roles/RoleDetails/UsersSection.tsx
  graylog2-web-interface/src/components/roles/RoleDetails/index.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.test.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/TeamsSection.test.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/TeamsSection.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.test.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.test.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesFilter.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.test.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverviewItem.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/UsersCell.tsx
  graylog2-web-interface/src/components/roles/RolesQueryHelper.tsx
  graylog2-web-interface/src/components/roles/navigation/RoleActionLinks.tsx
  graylog2-web-interface/src/logic/roles/Role.ts
Labels: ready-for-review

#9527 Backport: Fix incorrect Commercial support link
  graylog2-server/src/main/java/org/graylog2/shared/UI.java
Labels: backport, ready-for-review

#9540 Update UPGRADING for 4.0 (#9472)
  UPGRADING.rst
Labels: ready-for-review

#9544 Include TypeScript files in `lintChanges` script.
  graylog2-web-interface/dev/lintChanges.sh
Labels: ready-for-review

#9536 Migrating contexts to TypeScript.
  graylog2-web-interface/src/contexts/CurrentUserContext.tsx
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.tsx
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.tsx
  graylog2-web-interface/src/contexts/CurrentUserProvider.test.tsx
  graylog2-web-interface/src/contexts/CurrentUserProvider.tsx
  graylog2-web-interface/src/contexts/CustomizationContext.ts
  graylog2-web-interface/src/contexts/CustomizationProvider.tsx
  graylog2-web-interface/src/contexts/StreamsContext.tsx
  graylog2-web-interface/src/contexts/StreamsProvider.tsx
  graylog2-web-interface/src/contexts/UserPreferencesContext.ts
  graylog2-web-interface/src/stores/customizations/CustomizationsStore.ts
Labels: ready-for-review

#9457 Improve `IndicesIT` test by using delta when comparing dates.
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Labels: ready-for-review

#9493 Implement token-based authentication
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceAuthenticator.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceResult.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceToken.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthenticationDetails.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/security/StaticOrderedAuthenticatingRealms.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthenticatingRealmModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/BearerTokenRealm.java
  graylog2-server/src/main/java/org/graylog2/security/realm/UsernamePasswordRealm.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java
  graylog2-server/src/main/java/org/graylog2/shared/security/TypedBearerToken.java
Labels: ready-for-review

#9553 Updating yarn lockfile after TS changes.
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9552 Enable Downlevel Iteration for TypeScript.
  graylog2-web-interface/tsconfig.json
Labels: ready-for-review

#9381 DateTimePicker Show Timezone
  graylog2-web-interface/src/logic/datetimes/DateTime.js
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.jsx
Labels: ready-for-review

#9548 Create jest-preset-graylog package to centralize and share basic jest configuration
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/jest-preset-graylog/console-warnings-fail-tests.js
  graylog2-web-interface/packages/jest-preset-graylog/console-warnings-fail-tests.test.js
  graylog2-web-interface/packages/jest-preset-graylog/css/useable-css-proxy.js
  graylog2-web-interface/packages/jest-preset-graylog/css/useable-css-proxy.test.js
  graylog2-web-interface/packages/jest-preset-graylog/fileMock.js
  graylog2-web-interface/packages/jest-preset-graylog/helpers/mocking/c3_mock.jsx
  graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
  graylog2-web-interface/packages/jest-preset-graylog/mock-FetchProvider.js
  graylog2-web-interface/packages/jest-preset-graylog/mock-Version.js
  graylog2-web-interface/packages/jest-preset-graylog/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9549 Migrate permissions related parts to Typescript
  graylog2-web-interface/src/components/common/IconButton.tsx
  graylog2-web-interface/src/components/permissions/EntityShareModal.tsx
  graylog2-web-interface/src/logic/permissions/EntityShareState.tsx
  graylog2-web-interface/src/logic/permissions/Grantee.tsx
  graylog2-web-interface/src/logic/permissions/SharedEntity.tsx
  graylog2-web-interface/src/logic/permissions/__snapshots__/EntityShareState.test.tsx.snap
Labels: ready-for-review

#9539 Change eslint-config-graylog package.json license to SSPL
  graylog2-web-interface/packages/eslint-config-graylog/package.json
Labels: ready-for-review

#9573 Migrate util directory to typescript
  graylog2-web-interface/src/util/AuthenticationService.ts
  graylog2-web-interface/src/util/CreateEvent.test.tsx
  graylog2-web-interface/src/util/CreateEvent.ts
  graylog2-web-interface/src/util/MessagesExportUtils.ts
  graylog2-web-interface/src/util/PaginationURL.ts
Labels: ready-for-review

#9562 Migrating non-auth components to TypeScript.
  graylog2-web-interface/src/components/cluster/TrafficGraph.tsx
  graylog2-web-interface/src/components/common/IconButton.tsx
  graylog2-web-interface/src/components/common/PageHeader.tsx
  graylog2-web-interface/src/components/configurations/DecoratorsConfig.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.test.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListForm.test.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListForm.tsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsConfigUpdate.tsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsUpdater.test.tsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsUpdater.ts
  graylog2-web-interface/src/components/configurations/decorators/FormatDecorator.tsx
  graylog2-web-interface/src/components/configurations/decorators/StreamSelect.tsx
  graylog2-web-interface/src/components/errors/ErrorPage.tsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.tsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.tsx
  graylog2-web-interface/src/components/errors/RouterErrorBoundary.test.tsx
  graylog2-web-interface/src/components/errors/RuntimeErrorBoundary.test.tsx
  graylog2-web-interface/src/components/errors/RuntimeErrorBoundary.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.tsx
  graylog2-web-interface/src/components/graylog/Alert.tsx
  graylog2-web-interface/src/components/graylog/DropdownMenu.tsx
  graylog2-web-interface/src/components/graylog/DropdownSubmenu.tsx
  graylog2-web-interface/src/components/graylog/ProgressBar.tsx
  graylog2-web-interface/src/components/graylog/Row.tsx
  graylog2-web-interface/src/components/graylog/router.tsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatternQueryHelper.tsx
  graylog2-web-interface/src/components/inputs/NodeOrGlobalSelect.tsx
  graylog2-web-interface/src/components/layout/AppContentGrid.tsx
  graylog2-web-interface/src/components/layout/Footer.tsx
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.tsx
  graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.tsx
  graylog2-web-interface/src/components/metrics/MetricContainer.tsx
  graylog2-web-interface/src/components/navigation/DevelopmentHeaderBadge.tsx
  graylog2-web-interface/src/components/navigation/Navigation.tsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.tsx
  graylog2-web-interface/src/components/navigation/ThemeModeToggle.tsx
  graylog2-web-interface/src/components/navigation/UserMenu.tsx
  graylog2-web-interface/src/components/roles/RoleEdit/index.ts
  graylog2-web-interface/src/components/roles/RolesOverview/index.ts
  graylog2-web-interface/src/components/search/SearchLink.test.tsx
  graylog2-web-interface/src/components/search/SearchLink.ts
  graylog2-web-interface/src/components/search/SurroundingSearchButton.test.tsx
  graylog2-web-interface/src/components/search/SurroundingSearchButton.tsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.test.tsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.tsx
  graylog2-web-interface/src/components/support/SmallSupportLink.tsx
  graylog2-web-interface/src/components/support/SupportLink.tsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/index.ts
  graylog2-web-interface/src/components/widgets/WidgetVisualizationNotFound.tsx
  graylog2-web-interface/src/types.d.ts
Labels: ready-for-review

#9576 Migrate user and roles pages to Typescript
  graylog2-web-interface/src/components/common/PageHeader.tsx
  graylog2-web-interface/src/components/support/SupportLink.tsx
  graylog2-web-interface/src/pages/LoadingPage.tsx
  graylog2-web-interface/src/pages/RoleDetailsPage.tsx
  graylog2-web-interface/src/pages/RoleEditPage.tsx
  graylog2-web-interface/src/pages/RolesOverviewPage.tsx
  graylog2-web-interface/src/pages/UserCreatePage.tsx
  graylog2-web-interface/src/pages/UserEditPage.tsx
  graylog2-web-interface/src/pages/UserTokensEditPage.tsx
  graylog2-web-interface/src/pages/UsersOverviewPage.tsx
Labels: ready-for-review

#9565 Implement token-based authentication #9493 (ported)
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceAuthenticator.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceResult.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceToken.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthenticationDetails.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/security/StaticOrderedAuthenticatingRealms.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthenticatingRealmModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/BearerTokenRealm.java
  graylog2-server/src/main/java/org/graylog2/security/realm/UsernamePasswordRealm.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java
  graylog2-server/src/main/java/org/graylog2/shared/security/TypedBearerToken.java
Labels: ready-for-review

#9583 Migrating `test` directory to TypeScript.
  graylog2-web-interface/src/components/authentication/BackendDetails/BackendDetails.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.test.tsx
  graylog2-web-interface/src/logic/authentication/AuthenticationBackend.ts
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
  graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.tsx
  graylog2-web-interface/src/views/logic/NewQueryActionHandler.test.ts
  graylog2-web-interface/src/views/logic/fieldactions/AddToAllTablesActionHandler.test.ts
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.ts
  graylog2-web-interface/src/views/logic/fieldactions/RemoveFromAllTablesActionHandler.test.ts
  graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.test.ts
  graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.test.ts
  graylog2-web-interface/src/views/logic/views/View.ts
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.ts
  graylog2-web-interface/src/views/stores/QueriesStore.test.tsx
  graylog2-web-interface/test/fixtures/authenticationBackends.ts
  graylog2-web-interface/test/fixtures/entityShareState.ts
  graylog2-web-interface/test/fixtures/fields.ts
  graylog2-web-interface/test/fixtures/permissions.ts
  graylog2-web-interface/test/fixtures/roles.ts
  graylog2-web-interface/test/fixtures/sharedEntities.ts
  graylog2-web-interface/test/fixtures/userOverviews.tsx
  graylog2-web-interface/test/fixtures/users.ts
  graylog2-web-interface/test/helpers/mocking/AsMock.ts
  graylog2-web-interface/test/helpers/mocking/MockAction.ts
  graylog2-web-interface/test/helpers/mocking/StoreMock.ts
  graylog2-web-interface/test/helpers/suppressConsole.ts
  graylog2-web-interface/test/wrappedEnzyme.tsx
  graylog2-web-interface/test/wrappedTestingLibrary.tsx
  graylog2-web-interface/tsconfig.json
Labels: ready-for-review

#9558 Avoid NPE when resolving broken dependencies
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
  graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
  graylog2-server/src/test/resources/org/graylog/security/entities/EntityDependencyResolverTest.json
Labels: bug, ready-for-review

#9589 DateTimePicker: Add updated TimeRangeDisplay to WidgetQueryControls
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
Labels: ready-for-review

#9586 Migrate rest of pages and logic to Typescript
  graylog2-web-interface/src/components/authentication/BackendDetails/BackendDetails.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.tsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.tsx
  graylog2-web-interface/src/logic/authentication/AuthenticationBackend.ts
  graylog2-web-interface/src/logic/errors/FetchError.ts
  graylog2-web-interface/src/logic/errors/ReportedErrors.ts
  graylog2-web-interface/src/logic/metrics/MetricsExtractor.ts
  graylog2-web-interface/src/logic/rest/FetchProvider.js
  graylog2-web-interface/src/pages/AuthenticationBackendCreatePage.tsx
  graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.tsx
  graylog2-web-interface/src/pages/AuthenticationBackendEditPage.tsx
  graylog2-web-interface/src/pages/AuthenticationCreatePage.tsx
  graylog2-web-interface/src/pages/AuthenticationOverviewPage.tsx
  graylog2-web-interface/src/pages/AuthenticationPage.tsx
  graylog2-web-interface/src/pages/AuthenticatorsEditPage.tsx
  graylog2-web-interface/src/pages/AuthenticatorsPage.tsx
  graylog2-web-interface/src/pages/GettingStartedPage.tsx
  graylog2-web-interface/src/pages/RuntimeErrorPage.test.tsx
  graylog2-web-interface/src/pages/ShowMessagePage.test.tsx
  graylog2-web-interface/src/pages/ShowMessagePage.tsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.tsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.tsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.tsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.tsx
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.tsx
  graylog2-web-interface/src/pages/ViewEventDefinitionPage.tsx
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.tsx.snap
  graylog2-web-interface/src/routing/AppWithoutSearchBar.tsx
  graylog2-web-interface/src/routing/withParams.tsx
  graylog2-web-interface/test/fixtures/authenticationBackends.ts
Labels: ready-for-review

#9455 Updating Layout Styles, Adding Error Styles, Other Styles
  graylog2-web-interface/src/views/components/__snapshots__/SearchBar.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.jsx
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.test.jsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteRangeField.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.jsx.snap
Labels: ready-for-review

#9596 Handle missing `host` field in ES' nodes API response.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7Test.java
  graylog-storage-elasticsearch7/src/test/resources/nodes-response-without-host-field.json
Labels: ready-for-review

#9599 Handle missing `host` field in ES' nodes API response. (4.0)
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7Test.java
  graylog-storage-elasticsearch7/src/test/resources/nodes-response-without-host-field.json
Labels: ready-for-review

#9594 Avoid NPE when resolving broken dependencies (#9558)
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
  graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
  graylog2-server/src/test/resources/org/graylog/security/entities/EntityDependencyResolverTest.json
Labels: backport, ready-for-review

#9534 Backport: A few minor wording adjustments for the new Users pages
  graylog2-web-interface/src/components/users/PermissionsUpdateInfo.jsx
  graylog2-web-interface/src/components/users/TimeoutInput.jsx
  graylog2-web-interface/src/components/users/UserCreate/EmailFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/FullNameFormGroup.jsx
  graylog2-web-interface/src/components/users/UsersOverview/SystemAdministratorOverview.jsx
  graylog2-web-interface/src/pages/RolesOverviewPage.jsx
Labels: backport, ready-for-review

#9603 Fix event definitions share button permissions check and add tests
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.jsx
Labels: backport, bug, ready-for-review

#9606 Fix pagination of synced users overview on authentication service details page
  graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersSection.jsx
Labels: backport, bug, ready-for-review

#9602 Extend `PaginatedDataTable` and `FormikFormGroup` prop type definitions
  graylog2-web-interface/src/components/common/FormikFormGroup.tsx
  graylog2-web-interface/src/components/common/PaginatedDataTable/PaginatedDataTable.tsx
Labels: ready-for-review

#9605 Fix link for graylog-sidecar user tokens on sidecars page.
  graylog2-web-interface/src/pages/SidecarsPage.jsx
Labels: bug, ready-for-review

#9537 Hide inputs and related on cloud
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/nodes/NodeOverview.jsx
  graylog2-web-interface/src/components/nodes/NodesActions.jsx
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/util/conditional/filterMenuItems.js
  graylog2-web-interface/src/util/conditional/filterValueActions.js
  graylog2-web-interface/src/util/conditional/filterValueActions.test.js
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/bindings.routes.test.jsx
  graylog2-web-interface/src/views/bindings.valueActions.test.jsx
Labels: ready-for-review

#9608 Unify basic `<textarea />`styles with bootstrap text area styles
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Labels: bug, ready-for-review

#9613 Fix link for graylog-sidecar user tokens on sidecars page (4.0)
  graylog2-web-interface/src/pages/SidecarsPage.jsx
Labels: backport, bug, ready-for-review

#9614 Unify basic `<textarea />`styles with bootstrap text area styles (4.0)
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Labels: backport, bug, ready-for-review

#9615 Fixing minor flow remainders.
  graylog2-web-interface/src/actions/authentication/AuthenticationActions.ts
  graylog2-web-interface/src/views/components/actions/ActionHandler.tsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SortableSelect.jsx
  graylog2-web-interface/src/views/logic/fieldactions/AddMessageCountActionHandler.ts
  graylog2-web-interface/src/views/logic/fieldactions/FieldActionHandler.ts
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.ts
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.ts
  graylog2-web-interface/src/views/logic/widgets/Widget.ts
Labels: ready-for-review

#9621 Ignore generated web-modules.json file in the web interface
  graylog2-web-interface/.gitignore
Labels: ready-for-review

#9609 Add tests for event definitions share button
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.tsx
  graylog2-web-interface/test/fixtures/eventDefinition.ts
Labels: ready-for-review

#9626 Sync cloud branch after bump to 4.0.2-SNAPSHOT
  distribution/pom.xml
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch7/pom.xml
  graylog2-server/pom.xml
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/pages/SidecarsPage.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  pom.xml
Labels: ready-for-review

#9635 Use empty EventSearchParameters in EventsResource by default
  graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchParameters.java
Labels: ready-for-review

#9622 Ignore generated web-modules.json file in the web interface (#9621)
  graylog2-web-interface/.gitignore
Labels: ready-for-review

#9623 Ignore generated web-modules.json file in the web interface (#9621)
  graylog2-web-interface/.gitignore
Labels: ready-for-review

#9628 Remove no longer needed `FetchProvider` unmocking in error pages tests
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.tsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.tsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.tsx
Labels: ready-for-review

#9631 Updating `yarn.lock` regarding flow removal.
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9593 Hide authentication pages on cloud
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: ready-for-review

#9600 Hide logging page on cloud
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/nodes/NodeMaintenanceDropdown.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: ready-for-review

#9616 Load cloud plugin and display ForwarderReceivedBy
  graylog2-web-interface/src/views/components/messagelist/MessageDetail.jsx
Labels: ready-for-review

#9641 Use plugins from web modules file in dev build.
  graylog2-web-interface/webpack.combined.config.js
Labels: ready-for-review
