Repository Graylog2/graylog2-server, pull requests merged in 2020-09, with the labels that each got.

#8818 Skip execution of field types poller if server is not running.
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
Labels: ready-for-review

#8833 Fix invalid options for force merge request during index optimization.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
Labels: elasticsearch, ready-for-review

#8896 Return correct total number in PaginatedList
  graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
Labels: ready-for-review

#8882 Wrap app with GlobalStylesProvider to amend global css in-flight
  graylog2-web-interface/src/components/common/Scratchpad.jsx
  graylog2-web-interface/src/components/common/Scratchpad.test.jsx
  graylog2-web-interface/src/components/errors/ErrorPage.jsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
  graylog2-web-interface/src/components/errors/RouterErrorBoundary.test.jsx
  graylog2-web-interface/src/components/navigation/ScratchpadToggle.jsx
  graylog2-web-interface/src/contexts/GlobalStylesProvider.jsx
  graylog2-web-interface/src/contexts/ScratchpadProvider.jsx
  graylog2-web-interface/src/index.jsx
  graylog2-web-interface/src/pages/LoadingPage.jsx
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/pages/LoginPage.jsx
  graylog2-web-interface/src/pages/RuntimeErrorPage.test.jsx
  graylog2-web-interface/src/pages/ServerUnavailablePage.jsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.jsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.jsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/routing/AppFacade.jsx
Labels: improvement, ready-for-review

#8885 Prevent to remove last owner
  graylog2-web-interface/src/components/permissions/EntityShareModal.jsx
  graylog2-web-interface/src/components/permissions/EntityShareModal.test.jsx
  graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx
  graylog2-web-interface/src/components/permissions/ValidationError.jsx
  graylog2-web-interface/src/logic/permissions/EntityShareState.js
  graylog2-web-interface/src/logic/permissions/ValidationResult.js
  graylog2-web-interface/src/logic/permissions/__snapshots__/EntityShareState.test.js.snap
  graylog2-web-interface/test/fixtures/entityShareState.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, users

#8801 Migrate view sharing to grants
  graylog2-server/src/main/java/org/graylog/grn/GRN.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/ViewPermissions.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/AllUsersOfInstance.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/AllUsersOfInstanceStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/IsViewSharedForUser.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/SharingStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/SpecificRoles.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/SpecificRolesStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/SpecificUsers.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/SpecificUsersStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/UserShortSummary.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/ViewSharing.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/sharing/ViewSharingService.java
  graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/GrantDTO.java
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/RolesToGrantsMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnerShipToGrantsMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewSharingToGrantsMigration.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchDomainTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/ViewPermissionsTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/QualifyingViewsResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewSharingResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/migrations/ViewOwnershipToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog/security/migrations/ViewSharingToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/RolesToGrantsMigrationTest.java
  graylog2-server/src/test/resources/org/graylog/security/migrations/view-ownership.json
  graylog2-server/src/test/resources/org/graylog/security/migrations/view-sharings.json
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.test.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.test.jsx
  graylog2-web-interface/src/views/logic/views/sharing/AllUsersOfInstance.js
  graylog2-web-interface/src/views/logic/views/sharing/SpecificRoles.js
  graylog2-web-interface/src/views/logic/views/sharing/SpecificUsers.js
  graylog2-web-interface/src/views/logic/views/sharing/UserShortSummary.js
  graylog2-web-interface/src/views/logic/views/sharing/ViewSharing.js
  graylog2-web-interface/src/views/stores/ViewSharingStore.js
  graylog2-web-interface/src/views/stores/ViewSharingStore.test.js
Labels: ready-for-review

#8868 Search Popovers and Tooltips
  graylog2-web-interface/src/components/graylog/Popover.jsx
  graylog2-web-interface/src/components/graylog/Tooltip.jsx
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/theme/UseCurrentThemeMode.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchForm.jsx
Labels: bug, improvement, ready-for-review

#8859 Updating widget name edit input
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
Labels: improvement, ready-for-review

#8691 Implementing ES node discovery for ES7.
  graylog-storage-elasticsearch7/assembly.xml
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/FilteredElasticsearchNodesSniffer.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/FilteredElasticsearchNodesSnifferTest.java
Labels: elasticsearch, ready-for-review

#8897 Theming Typeahead autocomplete options
  graylog2-web-interface/src/components/common/TypeAheadFieldInput.jsx
  graylog2-web-interface/src/components/common/TypeAheadInput.jsx
  graylog2-web-interface/src/contexts/GlobalStylesProvider.jsx
Labels: bug, ready-for-review

#8911 react-dnd & react-dnd-html5-backend library updates
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/SortableList.jsx
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review

#8917 Remove permission check for Search Nav Item
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/pages/StartPage.jsx
Labels: bug, ready-for-review, search, users

#8902 Add hasAllPermission check to UserContext
  graylog2-server/src/main/java/org/graylog/security/UserContext.java
Labels: ready-for-review

#8929 Add unique index for grantee and entity
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/test/resources/org/graylog/security/shares/EntitySharesServiceTest.json
Labels: ready-for-review

#8937 Do not show `Enterprise` navigation if user is lacking permission
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
Labels: bug, ready-for-review

#8884 Add grants audit logs
  graylog2-server/src/main/java/org/graylog/security/SecurityAuditEventTypes.java
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog/security/events/EntitySharesUpdateEvent.java
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/main/java/org/graylog2/audit/AuditBindings.java
  graylog2-server/src/main/java/org/graylog2/audit/formatter/AuditEventFormatter.java
  graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
  graylog2-server/src/test/java/org/graylog2/audit/AuditCoverageTest.java
Labels: ready-for-review

#8928 Retrieve roles from GrantPermissionResolver
  graylog2-server/src/main/java/org/graylog/security/DefaultGrantPermissionResolver.java
  graylog2-server/src/main/java/org/graylog/security/GrantPermissionResolver.java
  graylog2-server/src/main/java/org/graylog/security/GrantsAuthorizingRealm.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: ready-for-review

#8947 Update to Netty 4.1.52 and netty-tcnative-boringssl-static to 2.0.34
  pom.xml
Labels: ready-for-review

#8933 Add flow type definitions for Wizard
  graylog2-web-interface/src/components/common/Wizard.jsx
Labels: improvement, ready-for-review

#8932 Add flow type definitions, create test and use styled-components for EmptyEntity
  graylog2-web-interface/src/components/common/EmptyEntity.css
  graylog2-web-interface/src/components/common/EmptyEntity.jsx
  graylog2-web-interface/src/components/common/EmptyEntity.test.jsx
Labels: improvement, ready-for-review

#8950 Use correct port for StartTLS
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
Labels: ready-for-review

#8910 Remove GlobalStylesProvider and use createGlobalStyles
  graylog2-web-interface/src/components/errors/ErrorPage.jsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
  graylog2-web-interface/src/components/errors/RouterErrorBoundary.test.jsx
  graylog2-web-interface/src/index.jsx
  graylog2-web-interface/src/pages/LoadingPage.jsx
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/pages/LoginPage.jsx
  graylog2-web-interface/src/pages/RuntimeErrorPage.test.jsx
  graylog2-web-interface/src/pages/ServerUnavailablePage.jsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.jsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Labels: bug, ready-for-review

#8966 Bind `IndexToolsAdapter` for ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
Labels: bug, ready-for-review

#8940 Add shared form helper components, e.g. to wrap the common Input with a formik Field.
  graylog2-web-interface/src/components/common/FormikFormGroup.jsx
  graylog2-web-interface/src/components/common/FormikInput.jsx
  graylog2-web-interface/src/components/common/FormikInput.test.jsx
  graylog2-web-interface/src/components/common/ReadOnlyFormGroup.jsx
  graylog2-web-interface/src/components/common/index.jsx
Labels: ready-for-review

#8976 Reduce auth image background size - 47% smaller
  graylog2-web-interface/public/images/auth/loginbg.jpg
  graylog2-web-interface/src/assets/not-found-bg.jpg
Labels: improvement, ready-for-review

#8977 Fix path traversal in swagger resource.
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
Labels: bug, ready-for-review, security

#8981 Reset Consumes annotation to accept everything for (un)schedule
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
Labels: ready-for-review

#8988 Fix path traversal in swagger resource. (3.3)
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
Labels: bug, ready-for-review, security

#8964 Fix moving widget if no titles have been set before.
  graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.js
  graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.test.js
  graylog2-web-interface/src/views/logic/views/__snapshots__/MoveWidgetToTab.test.js.snap
Labels: bug, ready-for-review

#8993 Reset Consumes annotation to accept everything for (un)schedule (3.3)
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
Labels: backport, ready-for-review

#8958 Show better error message when user has no stream permissions.
  graylog2-web-interface/src/contexts/StreamsContext.jsx
  graylog2-web-interface/src/contexts/StreamsProvider.jsx
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.jsx
  graylog2-web-interface/src/views/components/IfUserHasAccessToAnyStream.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
  graylog2-web-interface/src/views/stores/StreamsStore.js
Labels: ready-for-review

#9003 Remove mock for entities which got shared with a team
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/permissions/EntityShareStore.js
Labels: ready-for-review

#8969 Remove permission check for Search Nav Item (3.3)
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/pages/StartPage.jsx
Labels: bug, ready-for-review

#9018 Fix race conditions on system/configuration
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
Labels: backport, ready-for-review

#9019 Add new notification type to support failing Enterprise outputs
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
Labels: ready-for-review

#9020 Merge new notification type to 3.3
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
Labels: backport, ready-for-review

#9016 Adding title attr to Pipeline Title Link
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
Labels: bug, improvement, ready-for-review

#9017 Adding title attr to Pipeline Title Link (3.3)
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
Labels: backport, bug, improvement, ready-for-review

#8975 Request tracking exact number of search hits in requests.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/CountsAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
Labels: bug, ready-for-review, search

#9000 Allow specifying default user/password for discovered ES nodes.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestClientProvider.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/JestClientProviderTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/client/ESCredentialsProvider.java
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
Labels: elasticsearch, ready-for-review

#9011 Show better error message when user has no stream permissions. (3.3)
  graylog2-web-interface/src/contexts/StreamsContext.jsx
  graylog2-web-interface/src/contexts/StreamsProvider.jsx
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.jsx
  graylog2-web-interface/src/views/components/IfUserHasAccessToAnyStream.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
  graylog2-web-interface/src/views/stores/StreamsStore.js
Labels: backport, ready-for-review, search

#9015 Quote search query values for regexp operators
  graylog2-server/src/main/java/org/graylog2/search/SearchQueryOperator.java
  graylog2-server/src/test/java/org/graylog2/search/SearchQueryOperatorTest.java
Labels: ready-for-review

#9009 DropdownMenu component w/ styles
  graylog2-web-interface/src/components/graylog/DropdownMenu.jsx
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/views/components/OverlayDropdown.css
  graylog2-web-interface/src/views/components/OverlayDropdown.jsx
  graylog2-web-interface/src/views/components/common/ActionDropdown.jsx
Labels: bug, improvement, ready-for-review, ux

#9031 Add PATCH HTTP verb support to our API documentation generator
  graylog2-server/src/main/java/org/graylog2/shared/rest/documentation/generator/Generator.java
Labels: ready-for-review

#8985 Submit widget query form before saving edit widget modal.
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.jsx
  graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
Labels: bug, ready-for-review, search

#5683 Paginated grok patterns
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/grok/GrokPattern.java
  graylog2-server/src/main/java/org/graylog2/grok/PaginatedGrokPatternService.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/responses/GrokPatternPageList.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/GrokResource.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/GrokResourceTest.java
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatternQueryHelper.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatterns.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/grok-patterns/GrokPatternsStore.js
Labels: feature, ux, web

#9038 Enable ESLint Rules of Hooks.
  graylog2-web-interface/packages/eslint-config-graylog/index.js
Labels: ready-for-review

#9044 Input Status Labels
  graylog2-web-interface/src/components/inputs/InputStateBadge.jsx
Labels: improvement, ready-for-review, ux

#9043 Submit widget query form before saving edit widget modal. (Backport of #8985 for 3.3)
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.jsx
  graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
Labels: backport, bug, ready-for-review, search

#9045 Sync cloud branch with current 3.3. branch
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
  graylog2-web-interface/src/contexts/StreamsContext.jsx
  graylog2-web-interface/src/contexts/StreamsProvider.jsx
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.jsx
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/pages/StartPage.jsx
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.jsx
  graylog2-web-interface/src/views/components/IfUserHasAccessToAnyStream.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.jsx
  graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
  graylog2-web-interface/src/views/stores/StreamsStore.js
  integration-tests/pom.xml
  pom.xml
Labels: ready-for-review

#9041 Remove `add-module-exports` babel plugin.
  graylog2-web-interface/babel.config.js
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/NotificationBadge.test.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
  graylog2-web-interface/src/routing/Routes.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SeriesFunctionsSuggester.test.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.jsx
  graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.test.js
  graylog2-web-interface/src/views/logic/views/OnSaveViewAction.test.js
  graylog2-web-interface/src/views/pages/ViewManagementPage.test.jsx
Labels: ready-for-review

#8979 Run analysers in production mode
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/webpack.vendor.js
Labels: ready-for-review

#9026 Add support for multipart server uploads
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
Labels: ready-for-review

#9028 Fix empty search result in stream
  graylog2-web-interface/src/components/streams/StreamComponent.jsx
Labels: bug, ready-for-review, ux, web

#9042 Fix authentication service configuration updates
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/DBAuthServiceBackendService.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/rest/AuthServiceBackendsResource.java
  graylog2-server/src/main/java/org/graylog2/security/encryption/EncryptedValue.java
  graylog2-server/src/main/java/org/graylog2/security/encryption/EncryptedValueDeserializer.java
  graylog2-server/src/main/java/org/graylog2/security/encryption/EncryptedValueService.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/exceptionmappers/JsonMappingExceptionMapper.java
  graylog2-server/src/test/java/org/graylog2/security/encryption/EncryptedValueDeserializerTest.java
  graylog2-server/src/test/java/org/graylog2/security/encryption/EncryptedValueSerializerTest.java
  graylog2-server/src/test/java/org/graylog2/security/encryption/EncryptedValueTest.java
Labels: ready-for-review

#9034 Move Teams share url to enterprise
  graylog2-web-interface/src/actions/permissions/EntityShareActions.js
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverview.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/domainActions/permissions/EntityShareDomain.js
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/permissions/EntityShareStore.js
Labels: ready-for-review
