Repository Graylog2/graylog2-server, pull requests merged in 2020-04, with the labels that each got.

#7799 Ignore `OkHttpClientProviderTest` test suite.
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
Labels: ready-for-review

#7770 FA5 bugfix
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/Icon.jsx
  graylog2-web-interface/src/components/graylog/Navbar.jsx
  graylog2-web-interface/src/components/navigation/HelpMenu.jsx
  graylog2-web-interface/src/components/navigation/Navigation.css
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.styles.jsx
  graylog2-web-interface/src/components/navigation/ScratchpadToggle.jsx
  graylog2-web-interface/src/components/navigation/UserMenu.jsx
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
  graylog2-web-interface/src/components/sidecars/common/CommonSidecarStyles.css
  graylog2-web-interface/src/components/sidecars/common/OperatingSystemIcon.jsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx
  graylog2-web-interface/src/components/support/SupportSources.jsx
  graylog2-web-interface/src/views/components/widgets/EmptyResultWidget.jsx
  graylog2-web-interface/yarn.lock
Labels: bug, ready-for-review, ux

#7778 Trigger event upon search job creation.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryString.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/events/SearchJobExecutionEvent.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryStringTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
Labels: ready-for-review, search

#7816 Reverting to stock lucene mode for `react-ace`.
  graylog2-web-interface/src/views/components/searchbar/queryinput/ace.js
  graylog2-web-interface/src/views/components/searchbar/queryinput/webpack-resolver.js
Labels: bug, ready-for-review, search

#7819 Prevent read timeout exception
  graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/ExceptionLoggingChannelHandler.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
Labels: improvement, inputs, ready-for-review

#7820 Revert html-webpack-plugin to version 3.2.0 in graylog-web-plugin
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#7817 Allow view deletion for users with view edit permissions
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
Labels: ready-for-review, search

#7804 Clean up legacy/current dashboards API endpoints.
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardService.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/DashboardWidgetCreator.java
  graylog2-server/src/main/java/org/graylog2/rest/models/dashboards/requests/AddWidgetRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/dashboards/requests/CreateDashboardRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/dashboards/responses/CreateDashboardResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/DashboardWidgetsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/LegacyDashboardWidgetsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/LegacyDashboardsResource.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/dashboards/DashboardsResourceTest.java
  graylog2-web-interface/src/views/stores/DashboardsStore.js
Labels: ready-for-review, search

#7808 Prevent default action for form submit event in `PivotConfiguration`.
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetHeader.jsx
Labels: bug, ready-for-review, search

#7813 Enable support for optional chaining & nullish coalescing in flow.
  graylog2-web-interface/.flowconfig
Labels: ready-for-review

#7815 Prevent default action for form submit event in `PivotConfiguration`. (3.2)
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
Labels: bug, ready-for-review, search

#7798 Pinning `eslint-plugin-flowtype` version.
  graylog2-web-interface/packages/eslint-config-graylog/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#7824 Add stages to result of parse pipeline api endpoint result
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResourceTest.java
Labels: backport, ready-for-review

#7830 Add stages to result of parse pipeline api endpoint result
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResourceTest.java
Labels: backport, ready-for-review

#7793 Only show dashboard delete button for users with correct permissions
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-web-interface/src/views/components/views/ViewList.jsx
Labels: bug, ready-for-review, search

#7827 Improve field name completion performance by caching field names.
  graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.js
  graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.jsx
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js
  graylog2-web-interface/src/views/stores/FieldTypesStore.js
  graylog2-web-interface/src/views/stores/ViewMetadataStore.js
Labels: ready-for-review, search

#7821 Migrating InputStatusService
  graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
  graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStateData.java
  graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStatusRecord.java
  graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStatusService.java
  graylog2-server/src/test/java/org/graylog2/inputs/persistence/InputStatusServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/inputs/persistence/input-status.json
Labels: ready-for-review

#7722 Global Styles Cleanup Act 4
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Tab.jsx
  graylog2-web-interface/src/components/graylog/Tooltip.jsx
  graylog2-web-interface/src/components/graylog/bootstrap-import.js
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
  graylog2-web-interface/src/components/rules/RuleHelper.jsx
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/pages/ShowDashboardPage.css
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/views/components/Query.jsx
  graylog2-web-interface/src/views/components/QueryTabs.jsx
  graylog2-web-interface/src/views/components/WidgetGrid.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap
  graylog2-web-interface/src/views/components/queries/QueryTitle.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetFrame.jsx
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
Labels: ready-for-review

#7832 Handle `query` fields being `null` for all legacy dashboard widgets.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesHistogramConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedSeries.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_searches.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes.json
Labels: bug, ready-for-review, search

#7833 Remove not needed SizeMe container from WidgetGrid
  graylog2-web-interface/src/views/components/WidgetGrid.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap
Labels: bug, ready-for-review, search

#7837 Add required id for dashboard pages tabs menu
  graylog2-web-interface/src/views/components/QueryTabs.jsx
Labels: ready-for-review, search

#7840 Handle `query` fields being `null` for all legacy dashboard widgets. (3.2)
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesHistogramConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedSeries.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_searches.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_views.json
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes.json
Labels: bug, ready-for-review, search

#7839 Reactivate module that turns console.error/warn to test failures.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/routing/AppRouter.test.jsx
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
  graylog2-web-interface/test/console-warnings-fail-tests.js
  graylog2-web-interface/test/console-warnings-fail-tests.test.js
Labels: ready-for-review

#7847 Extract interface of input status service
  graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
  graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStatusService.java
  graylog2-server/src/main/java/org/graylog2/inputs/persistence/MongoInputStatusService.java
  graylog2-server/src/test/java/org/graylog2/inputs/persistence/MongoInputStatusServiceTest.java
Labels: ready-for-review

#7704 Provide `useStore` React hook to sync functional component with store state
  graylog2-web-interface/src/stores/__tests__/connect.test.jsx
  graylog2-web-interface/src/stores/connect.jsx
Labels: ready-for-review

#7844 Show view type specific description for dashboard and saved searches share modal.
  graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.jsx
  graylog2-web-interface/src/views/components/ViewTypeLabel.js
  graylog2-web-interface/src/views/components/ViewTypeLabel.test.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.test.jsx
Labels: bug, ready-for-review, search

#7859 Reimplement opensans-npm-webfont and remove self hosted fonts
  graylog2-web-interface/package.json
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/theme/fonts/OpenSans-Bold.woff
  graylog2-web-interface/src/theme/fonts/OpenSans-Bold.woff2
  graylog2-web-interface/src/theme/fonts/OpenSans-Italic.woff
  graylog2-web-interface/src/theme/fonts/OpenSans-Italic.woff2
  graylog2-web-interface/src/theme/fonts/OpenSans-Regular.woff
  graylog2-web-interface/src/theme/fonts/OpenSans-Regular.woff2
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review

#6740 Speed up event processing when it's lagging behind
  graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfiguration.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorExecutionJob.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationKeyResult.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationSeriesValue.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ESBackendModule.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/pivot/buckets/ESDateRangeHandler.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/DateRange.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/DateRangeBucket.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
  graylog2-server/src/test/java/org/graylog/scheduler/job/EventProcessorExecutionJobTest.java
  graylog2-web-interface/src/components/configurations/EventsConfig.jsx
Labels: alerting, bug, ready-for-review

#7868 Updating flow to v0.122.0.
  graylog2-web-interface/flow-typed/npm/react-dom_v16.x.x.js
  graylog2-web-interface/package.json
  graylog2-web-interface/src/stores/connect.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.js
  graylog2-web-interface/src/views/stores/QueriesStore.test.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#7867 Removing n+1's in `StreamService#loadAll` by consolidating external loads
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetService.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/MongoIndexSetService.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
Labels: ready-for-review

#7864 Replace mutating state inline in stores with new object creation.
  graylog2-web-interface/src/stores/indices/IndicesStore.js
  graylog2-web-interface/src/stores/nodes/NodesStore.js
  graylog2-web-interface/src/stores/systemjobs/SystemJobsStore.js
Labels: ready-for-review

#7846 Allow dashboard creation only permitted users
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
  graylog2-web-interface/src/views/pages/DashboardsPage.jsx
  graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
  graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
Labels: ready-for-review, search

#7880 Replacing usage of `Object.fromEntries` with `reduce`.
  graylog2-web-interface/src/stores/nodes/NodesStore.js
Labels: ready-for-review

#7878 Grok Pattern Filter
  graylog2-web-interface/src/components/grok-patterns/GrokPatternFilter.css
  graylog2-web-interface/src/components/grok-patterns/GrokPatternFilter.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatternFilter.test.jsx
  graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
Labels: ready-for-review

#7818 Ignore accents and case per default in autocompletion of `Select`.
  graylog2-web-interface/flow-typed/npm/react-select-event_v2.x.x.js
  graylog2-web-interface/flow-typed/npm/react-select_vx.x.x.js
  graylog2-web-interface/package.json
  graylog2-web-interface/src/views/components/Select.jsx
  graylog2-web-interface/src/views/components/Select.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/BarVisualizationConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesSelect.test.jsx.snap
  graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#7865 Improving runtime for field type retrieval endpoint.
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamService.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdaterTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java
Labels: ready-for-review, search

#7826 Reset pagination on page size change
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/common/PaginatedList.test.jsx
Labels: bug, ready-for-review

#7858 Ensure that dashboards have empty root query strings.
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200409083200_RemoveRootQueriesFromMigratedDashboards.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20200409083200_RemoveRootQueriesFromMigratedDashboardsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20200409083200_RemoveRootQueriesFromMigratedDashboards/sample.json
Labels: bug, ready-for-review, search

#7861 Provide global context for current user preferences.
  graylog2-web-interface/src/actions/users/PreferencesActions.js
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.jsx
  graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.jsx
  graylog2-web-interface/src/contexts/UserPreferencesContext.js
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/stores/users/CurrentUserStore.jsx
  graylog2-web-interface/src/stores/users/PreferencesStore.js
  graylog2-web-interface/test/helpers/mocking/CombinedProviderMock.js
  graylog2-web-interface/test/helpers/mocking/index.js
Labels: ready-for-review

#7756 Global Styles Cleanup Act 5
  graylog2-web-interface/src/components/common/EntityList.jsx
  graylog2-web-interface/src/components/common/EntityListItem.jsx
  graylog2-web-interface/src/components/graylog/MessageDetailsDefinitionList.jsx
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/search/MessageDetail.jsx
  graylog2-web-interface/src/components/search/MessageFields.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageFields.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageMetadata.jsx
Labels: ready-for-review

#7851 Fasterizing the Button render
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackUploadControls.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Button.jsx
  graylog2-web-interface/src/components/graylog/DropdownButton.jsx
  graylog2-web-interface/src/components/graylog/SplitButton.jsx
  graylog2-web-interface/src/components/graylog/styles/button.js
  graylog2-web-interface/src/components/graylog/styles/buttonStyles.js
  graylog2-web-interface/src/components/grok-patterns/EditPatternModal.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/EditPatternModal.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
Labels: bug, ready-for-review

#7879 Add minimal support for Beats > 7.0
  graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/beats/winlogbeat-v7.json
Labels: bug, inputs, ready-for-review, sidecar

#7894 Add minimal support for Beats > 7.0 (#7879)
  graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/beats/winlogbeat-v7.json
Labels: backport, inputs, ready-for-review

#7874 Supply position parameter to remaining configuration fields
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/AbstractConfigurationField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/DropdownField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/ListField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/NumberField.java
Labels: feature, ready-for-review

#7896 Supply position parameter to remaining configuration fields (#7874)
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/AbstractConfigurationField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/DropdownField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/ListField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/NumberField.java
Labels: backport, feature, ready-for-review

#7853 Show notifications when disk in the Elasticsearch nodes fills up
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/AbsoluteValueWatermarkSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactory.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeFileDescriptorStats.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/PercentageWatermarkSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/WatermarkSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/GetAllocationDiskSettings.java
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStatsTest.java
  graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
Labels: ready-for-review

#7892 Returning effective field name in non-interactive context.
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/Field.test.jsx
Labels: bug, ready-for-review, search

#7829 Improve triggering search executions from search bar.
  graylog2-web-interface/flow-typed/npm/formik_v2.x.x.js
  graylog2-web-interface/package.json
  graylog2-web-interface/src/logic/datetimes/DateTime.js
  graylog2-web-interface/src/views/Constants.js
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.test.jsx
  graylog2-web-interface/src/views/components/DashboardSearchBarForm.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/TimerangeForForm.js
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.jsx
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.test.jsx
  graylog2-web-interface/src/views/components/searchbar/DisabledTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
  graylog2-web-interface/src/views/components/searchbar/RelativeTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchButton.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideInput.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideTypeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeMenuItems.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/ace.js
  graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
  graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx
  graylog2-web-interface/src/views/logic/queries/Query.js
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.js
  graylog2-web-interface/src/views/stores/WidgetStore.js
  graylog2-web-interface/test/helpers/mocking/MockAction.js
  graylog2-web-interface/yarn.lock
Labels: bug, ready-for-review, search

#7885 Enable/disable auto-completion in query input based on user preference.
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/ace-queryinput.css
Labels: ready-for-review

#7888 Do not filter querys with empty search types
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
Labels: ready-for-review, search

#7923 Improving eslint rules for flow.
  graylog2-web-interface/packages/eslint-config-graylog/index.js
Labels: ready-for-review

#7905 Moving All Hex Colors breakdown 1/6
  graylog2-web-interface/src/components/authentication/AuthenticationComponent.css
  graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx
  graylog2-web-interface/src/components/common/ControlledTableListHeader.css
  graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx
  graylog2-web-interface/src/components/common/InteractableModal.jsx
  graylog2-web-interface/src/components/common/SortableList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.css
  graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
Labels: ready-for-review

#7925 Fixing linter hints automatically.
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/common/Spinner.jsx
  graylog2-web-interface/src/components/common/URLWhiteListFormModal.jsx
  graylog2-web-interface/src/components/common/URLWhiteListInput.jsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.jsx
  graylog2-web-interface/src/components/graylog/ProgressBar.jsx
  graylog2-web-interface/src/components/layout/AppContentGrid.jsx
  graylog2-web-interface/src/components/layout/Footer.jsx
  graylog2-web-interface/src/flow/css-useable-modules.js
  graylog2-web-interface/src/routing/AppWithoutSearchBar.jsx
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
  graylog2-web-interface/src/stores/metrics/MetricsStore.js
  graylog2-web-interface/src/stores/streams/StreamsStore.js
  graylog2-web-interface/src/stores/users/RolesStore.js
  graylog2-web-interface/src/views/bindings.enterpriseWidgets.test.jsx
  graylog2-web-interface/src/views/components/DebugOverlay.jsx
  graylog2-web-interface/src/views/components/Field.jsx
  graylog2-web-interface/src/views/components/MigrateFieldCharts.jsx
  graylog2-web-interface/src/views/components/QueryTabs.jsx
  graylog2-web-interface/src/views/components/ViewTypeLabel.js
  graylog2-web-interface/src/views/components/actions/ActionHandler.jsx
  graylog2-web-interface/src/views/components/actions/FieldActions.jsx
  graylog2-web-interface/src/views/components/actions/ValueActions.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/BarVisualizationConfiguration.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeHeader.jsx
  graylog2-web-interface/src/views/components/messagelist/NodeName.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.jsx
  graylog2-web-interface/src/views/components/sidebar/NavItem.jsx
  graylog2-web-interface/src/views/components/visualizations/ChartData.js
  graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortIcon.test.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortSelect.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/SeriesConfig.js
  graylog2-web-interface/src/views/logic/fieldtypes/FieldType.js
  graylog2-web-interface/src/views/logic/fieldtypes/FieldTypeMapping.js
  graylog2-web-interface/src/views/logic/parameters/LookupTableParameter.js
  graylog2-web-interface/src/views/logic/parameters/Parameter.js
  graylog2-web-interface/src/views/logic/search/GlobalOverride.js
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.js
  graylog2-web-interface/src/views/logic/searchtypes/messages/MessageSortConfig.js
  graylog2-web-interface/src/views/logic/searchtypes/pivot/PivotHandler.js
  graylog2-web-interface/src/views/logic/views/View.js
  graylog2-web-interface/src/views/logic/widgets/WidgetPosition.js
  graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/stores/TitlesStore.js
Labels: ready-for-review

#7909 Moving All Hex Colors breakdown 3/6
  graylog2-web-interface/src/components/notifications/Notification.jsx
  graylog2-web-interface/src/components/outputs/Output.jsx
  graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx
  graylog2-web-interface/src/components/sidecars/common/ColorLabel.css
  graylog2-web-interface/src/components/sidecars/common/ColorLabel.jsx
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/systemjobs/SystemJobsList.jsx
  graylog2-web-interface/src/components/systemmessages/SystemMessagesList.jsx
Labels: ready-for-review

#7908 Show meaningful error message on missing permissions instead of redirecting to not found page
  graylog2-web-interface/src/actions/errors/ErrorsActions.js
  graylog2-web-interface/src/components/common/PageErrorOverview.jsx
  graylog2-web-interface/src/components/errors/ErrorJumbotron.jsx
  graylog2-web-interface/src/components/errors/ErrorPage.jsx
  graylog2-web-interface/src/components/errors/ReportedError.jsx
  graylog2-web-interface/src/components/errors/ReportedError.test.jsx
  graylog2-web-interface/src/components/errors/RouterErrorBoundary.jsx
  graylog2-web-interface/src/components/errors/RouterErrorBoundary.test.jsx
  graylog2-web-interface/src/components/errors/RuntimeErrorBoundary.jsx
  graylog2-web-interface/src/components/errors/RuntimeErrorBoundary.test.jsx
  graylog2-web-interface/src/logic/errors/ReportedErrors.js
  graylog2-web-interface/src/logic/rest/FetchProvider.js
  graylog2-web-interface/src/pages/ErrorPage.css
  graylog2-web-interface/src/pages/ErrorPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
  graylog2-web-interface/src/pages/NotFoundPage.jsx
  graylog2-web-interface/src/pages/RuntimeErrorPage.jsx
  graylog2-web-interface/src/pages/RuntimeErrorPage.test.jsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.jsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.jsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/routing/AppErrorBoundary.jsx
  graylog2-web-interface/src/routing/AppErrorBoundary.test.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/AppRouter.test.jsx
  graylog2-web-interface/src/routing/__snapshots__/AppErrorBoundary.test.jsx.snap
Labels: improvement, ready-for-review

#7900 Typing wrapped enzyme/testing-library functions again.
  graylog2-web-interface/flow-typed/npm/@testing-library/react_v8.x.x.js
  graylog2-web-interface/flow-typed/npm/@testing-library/react_v9.x.x.js
  graylog2-web-interface/flow-typed/npm/enzyme_v3.x.x.js
  graylog2-web-interface/src/components/configurations/UrlWhiteListForm.test.jsx
  graylog2-web-interface/src/components/search/SurroundingSearchButton.test.jsx
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
  graylog2-web-interface/src/views/components/actions/ActionHandler.jsx
  graylog2-web-interface/src/views/components/actions/ActionHandler.test.jsx
  graylog2-web-interface/src/views/components/actions/FieldActions.jsx
  graylog2-web-interface/src/views/components/actions/ValueActions.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.styles.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.test.jsx
  graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.test.jsx
  graylog2-web-interface/test/wrappedEnzyme.jsx
  graylog2-web-interface/test/wrappedTestingLibrary.jsx
Labels: ready-for-review

#7910 Moving All Hex Colors breakdown 4/6
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/views/components/OverlayDropdown.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
  graylog2-web-interface/src/views/components/common/ActionDropdown.jsx
  graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
Labels: ready-for-review

#7933 Remove waitForElementToBeRemoved from ReportedError test
  graylog2-web-interface/src/components/errors/ReportedError.test.jsx
Labels: bug

#7913 Moving All Hex Colors breakdown 5/6
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/messagelist/MessageField.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageFields.css
  graylog2-web-interface/src/views/components/messagelist/MessageFields.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/decoratorStyles.css
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.css
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/DisabledTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/RelativeTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/TimerangeSelector.jsx
Labels: ready-for-review

#7893 Enforce Unix newlines for Ace editor
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
Labels: bug, ready-for-review

#7904 Removing remaining TypeScript code and dependencies.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/stores/search/SearchStore.test.jsx
  graylog2-web-interface/src/stores/search/SearchStore.ts
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
  graylog2-web-interface/tsconfig.json
  graylog2-web-interface/webpack.config.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#7943 ReactGridContainer styles
  graylog2-web-interface/src/components/common/ReactGridContainer.css
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Labels: ready-for-review

#7907 Moving All Hex Colors breakdown 2/6
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackUploadControls.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Modal.jsx
  graylog2-web-interface/src/components/graylog/ProgressBar.jsx
  graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/EditPatternModal.test.jsx.snap
  graylog2-web-interface/src/components/indices/ShardRoutingOverview.jsx
  graylog2-web-interface/src/components/inputs/InputThroughput.jsx
  graylog2-web-interface/src/components/layout/Footer.jsx
  graylog2-web-interface/src/components/metrics/MetricsList.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: ready-for-review

#7782 Show helpful message on dashboard page for missing stream permission
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchExecutionGuard.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java
  graylog2-server/src/main/java/org/graylog2/plugin/rest/MissingStreamPermissionError.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/exceptionmappers/MissingStreamPermissionExceptionMapper.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/exceptions/MissingStreamPermissionException.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchExecutionGuardTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/FieldTypesResourceTest.java
  graylog2-web-interface/src/components/errors/ErrorPage.jsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.jsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
  graylog2-web-interface/src/logic/errors/ReportedErrors.js
  graylog2-web-interface/src/logic/rest/FetchProvider.js
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.jsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.jsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.jsx
  graylog2-web-interface/src/routing/App.jsx
Labels: ready-for-review, search

#7934 Updating Theme documentation
  graylog2-web-interface/src/theme/docs/Colors.jsx
  graylog2-web-interface/src/theme/docs/Colors.md
  graylog2-web-interface/src/theme/docs/Details.md
  graylog2-web-interface/src/theme/docs/ThemeProvider.md
  graylog2-web-interface/src/theme/docs/Utilities.md
  graylog2-web-interface/styleguide.config.js
Labels: ready-for-review

#7947 Make `FieldSortSelect` use our `Select` wrapper.
  graylog2-web-interface/src/views/components/widgets/FieldSortSelect.jsx
Labels: bug, ready-for-review, search

#7951 Work around non-existing `Event` constructor in IE11.
  graylog2-web-interface/src/util/CreateEvent.js
  graylog2-web-interface/src/util/CreateEvent.test.jsx
  graylog2-web-interface/src/util/FormsUtils.js
  graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
Labels: bug, ready-for-review, search

#7938 Don't truncate Messages in ProcessBuffer Dumper
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/ProcessBuffer.java
Labels: ready-for-review

#7954 Update netty to 4.1.49 and netty-tcnative to 2.0.30
  pom.xml
Labels: ready-for-review, security

#7953 Jackson security update from 2.9.10.2 to 2.9.10.4 (2.9.10.20200411)
  pom.xml
Labels: ready-for-review, security

#7949 Prevent form submit event leaking out of `SavedSearchForm`.
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchForm.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
Labels: bug, ready-for-review, search

#7855 String Interpolation for Pipeline Rules
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/expressions/AdditionExpression.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringConcat.txt
Labels: ready-for-review

#7965 Restore proper error returned by `FetchProvider`.
  graylog2-web-interface/src/logic/rest/FetchProvider.js
Labels: bug, ready-for-review, search

#7942 ExpandableListItem styles
  graylog2-web-interface/src/components/common/ExpandableListItem.css
  graylog2-web-interface/src/components/common/ExpandableListItem.jsx
  graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
Labels: ready-for-review

#7916 Add firstNonNull function to pipeline processor
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/FirstNonNull.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/firstNonNull.txt
Labels: ready-for-review

#7966 Updating yarn lockfile due to dependency updates.
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#7969 update codename for 3.3-beta
  graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
Labels: ready-for-review

#7962 Add version property for gRPC and bump protobuf version
  pom.xml
Labels: ready-for-review

#7957 Create a common list of field names for the Graylog Schema.
  graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
Labels: ready-for-review

#7898 Add Jenkinsfile for new Jenkins server
  jenkins.groovy
Labels: ready-for-review

#7971 Color variant adjust
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
Labels: ready-for-review

#7974 EventDefinitionForm styles
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/common/Wizard.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.css
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
Labels: ready-for-review

#7975 Enforce Unix newlines for Ace editor (#7893)
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
Labels: backport, bug, ready-for-review

#7899 Show notifications when disk in the Elasticsearch nodes fills up
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/AbsoluteValueWatermarkSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactory.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeFileDescriptorStats.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/PercentageWatermarkSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/WatermarkSettings.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/GetAllocationDiskSettings.java
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStatsTest.java
  graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
Labels: backport, ready-for-review

#7983 use consistent spelling for "Content Packs"
  graylog2-web-interface/src/pages/ContentPacksPage.jsx
Labels: improvement, ready-for-review

#7973 ContentPackStatus styles
  graylog2-web-interface/src/components/content-packs/ContentPackStatus.css
  graylog2-web-interface/src/components/content-packs/ContentPackStatus.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Badge.jsx
Labels: ready-for-review

#7978 Sidecar style tweaks
  graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Table.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarList.css
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarList.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
Labels: bug, ready-for-review, ux

#7988 Search Result data darken
  graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
Labels: ready-for-review, ux

#7982 Global Text Color using Theme
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Labels: ready-for-review

#7991 Add missing mapping for chunk size
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java
Labels: ready-for-review, search

#8000 Fix assignment of default timerange for export requests
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/MessagesRequest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/MessagesRequestTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/TestData.java
Labels: bug, ready-for-review, search

#7999 Unify naming for `QueryEditModal` description
  graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.jsx
  graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.test.jsx
Labels: improvement, search

#7993 Add workaround for input event problems in MongoInputStatusService
  graylog2-server/src/main/java/org/graylog2/inputs/persistence/MongoInputStatusService.java
  graylog2-server/src/test/java/org/graylog2/inputs/persistence/MongoInputStatusServiceTest.java
Labels: inputs, ready-for-review

#7981 ProcessingTimelineComponent styles
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.css
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
Labels: ready-for-review

#7992 Allow free license request from the Enterprise overview page
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeEnterpriseConfiguration.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeEnterpriseModule.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeEnterpriseResource.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeEnterpriseService.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseAPIClient.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseAPIRequest.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseAPIResponse.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseInfo.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseRequest.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseRequestException.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/StagedFreeEnterpriseLicense.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
  graylog2-web-interface/src/actions/enterprise/EnterpriseActions.js
  graylog2-web-interface/src/components/cluster/GraylogClusterOverview.jsx
  graylog2-web-interface/src/components/enterprise/EnterpriseFreeLicenseForm.jsx
  graylog2-web-interface/src/components/enterprise/PluginList.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/NavigationLink.jsx
  graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
  graylog2-web-interface/src/components/support/SupportLink.jsx
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/pages/EnterprisePage.jsx
  graylog2-web-interface/src/stores/enterprise/EnterpriseStore.js
Labels: enterprise, ready-for-review

#8009 Provide a different IndexHtmlGenerator for development
  graylog2-server/src/main/java/org/graylog2/shared/bindings/RestApiBindings.java
  graylog2-server/src/main/java/org/graylog2/web/DevelopmentIndexHtmlGenerator.java
  graylog2-server/src/main/java/org/graylog2/web/IndexHtmlGenerator.java
  graylog2-server/src/main/java/org/graylog2/web/ProductionIndexHtmlGenerator.java
  graylog2-server/src/main/resources/web-interface/index.html.development.template
Labels: ready-for-review

#7902 Add option to enable/disable event definitions
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventDefinitionEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java
  graylog2-server/src/main/java/org/graylog/events/context/EventDefinitionContextService.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog/scheduler/DBJobDefinitionService.java
  graylog2-server/src/main/java/org/graylog/scheduler/DBJobTriggerService.java
  graylog2-server/src/main/java/org/graylog/scheduler/JobExecutionEngine.java
  graylog2-server/src/main/java/org/graylog2/rest/models/PaginatedResponse.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionHandlerTest.java
  graylog2-server/src/test/java/org/graylog/scheduler/DBJobDefinitionServiceTest.java
  graylog2-server/src/test/java/org/graylog/scheduler/DBJobTriggerServiceTest.java
  graylog2-server/src/test/java/org/graylog2/rest/models/PaginatedResponseTest.java
  graylog2-server/src/test/resources/org/graylog/events/processor/event-processors-without-schedule.json
  graylog2-server/src/test/resources/org/graylog/scheduler/job-definitions-with-triggers.json
  graylog2-web-interface/src/actions/event-definitions/EventDefinitionsActions.js
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionDescription.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Labels: alerting, feature, ready-for-review

#7984 Extract styles from `ExtendedSearchPage`
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/SearchButton.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideTypeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/TopRow.jsx
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: bug, ready-for-review, search
