Repository Graylog2/graylog2-server, pull requests merged in 2020-08, with the labels that each got.

#8673 Avoid deletion of old index in ES7 index alias cycling
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/IndicesES7IT.java
Labels: elasticsearch, ready-for-review

#8646 Remove duplicate method call in MoreSearch
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
Labels: bug, elasticsearch, ready-for-review

#8668 Unify navigation dropdown text color with navigation text color
  graylog2-web-interface/src/components/graylog/Navbar.jsx
Labels: ready-for-review

#8671 Stop pinned sidebar from overlapping header
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: bug, ready-for-review

#8678 Move components
  graylog2-web-interface/src/components/common/PaginatedItemOverview/PaginatedItem.jsx
  graylog2-web-interface/src/components/common/PaginatedItemOverview/PaginatedItemOverview.jsx
  graylog2-web-interface/src/components/common/PaginatedItemOverview/index.jsx
  graylog2-web-interface/src/components/common/ReadOnlyFormGroup.jsx
  graylog2-web-interface/src/components/common/Section/SectionComponent.jsx
  graylog2-web-interface/src/components/common/Section/SectionGrid.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/TeamSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/TeamsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/pages/UserTokensEditPage.jsx
Labels: ready-for-review

#8588 Suppressing deprecation notices
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/components/common/JSONValueInput.jsx
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/common/SelectPopover.jsx
  graylog2-web-interface/src/components/common/SelectableList.jsx
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/common/TypeAheadInput.jsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/configurationforms/DropdownField.jsx
  graylog2-web-interface/src/components/configurationforms/ListField.jsx
  graylog2-web-interface/src/components/configurationforms/TextField.jsx
  graylog2-web-interface/src/components/configurations/EventsConfig.jsx
  graylog2-web-interface/src/components/configurations/SidecarConfig.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/extractors/EditExtractor.jsx
  graylog2-web-interface/src/components/extractors/extractors_configuration/JSONExtractorConfiguration.jsx
  graylog2-web-interface/src/components/extractors/extractors_configuration/SplitAndIndexExtractorConfiguration.jsx
  graylog2-web-interface/src/components/extractors/extractors_configuration/SubstringExtractorConfiguration.jsx
  graylog2-web-interface/src/components/ldap/TestLdapConnection.jsx
  graylog2-web-interface/src/components/lookup-tables/LookupTableForm.jsx
  graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.jsx
  graylog2-web-interface/src/components/metrics/CounterRate.jsx
  graylog2-web-interface/src/components/metrics/MetricsComponent.jsx
  graylog2-web-interface/src/components/metrics/MetricsMapper.jsx
  graylog2-web-interface/src/components/nodes/BufferUsage.jsx
  graylog2-web-interface/src/components/nodes/JournalState.jsx
  graylog2-web-interface/src/components/search/MessageFieldExtractorActions.jsx
  graylog2-web-interface/src/components/search/MessageShow.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/streams/StreamThroughput.jsx
  graylog2-web-interface/src/components/throughput/NodeThroughput.jsx
  graylog2-web-interface/src/components/users/UserForm.jsx
  graylog2-web-interface/src/pages/EditTokensPage.jsx
  graylog2-web-interface/src/pages/EditUsersPage.jsx
  graylog2-web-interface/src/pages/PipelineDetailsPage.jsx
  graylog2-web-interface/src/pages/ShowNodePage.jsx
  graylog2-web-interface/src/views/components/common/ScrollToHint.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetConfigModal.jsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#8680 Make IndicesAdapterES7#indexCreationDate return UTC timestamps
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
  graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
Labels: bug, elasticsearch

#8682 Making LDAP TLS/SSL tests faster and more reliable.
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
Labels: ready-for-review

#8684 Theme PropTypes
  graylog2-web-interface/src/theme/breakpoints.js
  graylog2-web-interface/src/theme/colors.js
  graylog2-web-interface/src/theme/fonts.js
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/utils/index.js
Labels: improvement, ready-for-review

#8683 Display loading spinner for search sidebar execution info, during execution
  graylog2-web-interface/src/views/components/sidebar/description/SearchResultOverview.jsx
Labels: ready-for-review

#8689 Add Java version to the issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ready-for-review

#8649 Fix ES7 event processing for event definitions without streams
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/test/java/org/graylog/events/search/MoreSearchTest.java
Labels: bug, elasticsearch, ready-for-review

#8652 Use GRNs instead of Strings in AvailableGrantee model
  graylog2-server/src/main/java/org/graylog/grn/GRNRegistry.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntityShareResponse.java
Labels: ready-for-review

#8693 Making LDAP TLS/SSL tests faster and more reliable. (3.3)
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
Labels: ready-for-review

#8672 Enable Search After for ES7 exports by adding a field alias for gl2_message_id in event indices
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsES6.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ViewsESBackendModule.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackend.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/RequestStrategy.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/Scroll.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/SearchAfter.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendIT.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendScrollingIT.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendSearchAfterIT.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/SearchAfterTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsES7IT.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEvents.java
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping7.java
  graylog2-server/src/main/java/org/graylog2/storage/VersionAwareStorageModule.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsTest.java
Labels: elasticsearch, improvement, ready-for-review

#8661 Implement EntityShareModal for saved searches
  graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java
  graylog2-web-interface/src/views/components/ViewTypeLabel.js
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
  graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
Labels: ready-for-review

#8681 Implement UsersActions and User class
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationFormContainer.jsx
  graylog2-web-interface/src/components/users/EditRolesForm.jsx
  graylog2-web-interface/src/components/users/NewUserForm.jsx
  graylog2-web-interface/src/components/users/UserForm.jsx
  graylog2-web-interface/src/components/users/UserList.jsx
  graylog2-web-interface/src/contexts/CurrentUserContext.jsx
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/pages/CreateUsersPage.jsx
  graylog2-web-interface/src/pages/EditTokensPage.jsx
  graylog2-web-interface/src/pages/EditUsersPage.jsx
  graylog2-web-interface/src/stores/users/RolesStore.js
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
  graylog2-web-interface/test/fixtures/users.js
Labels: ready-for-review

#8563 Fix scroll arguments in old search resources
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
Labels: bug, elasticsearch, ready-for-review

#8679 Add get a single role from the AuthzRolesResource
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
Labels: ready-for-review

#8608 Providing credentials for ES7 connections requiring authentication.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/client/ESCredentialsProvider.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
Labels: elasticsearch, ready-for-review

#8632 Consolidate index mappings and associated tests
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping6.java
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping7.java
  graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMapping5Test.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMapping6Test.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingTest.java
  graylog2-server/src/test/resources/org/graylog2/indexer/expected_template7.json
Labels: elasticsearch, ready-for-review

#8705 Remove state from UsersStore
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersFilter.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
  graylog2-web-interface/src/pages/UserTokensEditPage.jsx
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/stores/users/UsersStore.test.js
Labels: ready-for-review

#8690 Extract Users query helper
  graylog2-web-interface/src/components/users/UsersOverview/UsersFilter.jsx
  graylog2-web-interface/src/components/users/UsersQueryHelper.jsx
Labels: ready-for-review

#8723 Fix users overview when the user has no roles
  graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java
Labels: ready-for-review

#8725 Merge 3.3.4 release into cloud-3.3
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  integration-tests/pom.xml
  pom.xml
Labels: ready-for-review

#8701 Fix SearchQueryParser for null queries
  graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java
  graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java
Labels: ready-for-review

#8726 Add Share Button to streams
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
Labels: ready-for-review

#8736 Updated SourceCodeEditor toolbar button colors
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
Labels: improvement, ready-for-review

#8734 Popover listgroupitem styles
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
  graylog2-web-interface/src/components/graylog/Popover.jsx
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: improvement, ready-for-review

#8703 Construct jest client provider lazily instead of eager.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
Labels: elasticsearch, ready-for-review

#8733 SupportLink IconStack colors & flow-typing
  graylog2-web-interface/src/components/support/SupportLink.jsx
Labels: improvement, ready-for-review

#8712 Add missing routes to AuthzRolesResource
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
  graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java
Labels: ready-for-review, users

#8702 Bumping ES dependencies to allow using relocated source jars.
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch7/pom.xml
Labels: elasticsearch, ready-for-review

#8732 Global input Styles
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Labels: improvement, ready-for-review

#8730 Update styles in TimeoutInput for User Auth
  graylog2-web-interface/src/components/users/TimeoutInput.jsx
  graylog2-web-interface/src/components/users/TimeoutUnitSelect.jsx
  graylog2-web-interface/src/components/users/timeoutConstants.js
Labels: improvement, ready-for-review

#8729 Graph Theming
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
Labels: improvement, ready-for-review

#8741 Distinguish ownership registration between dashboard and saved search
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
Labels: ready-for-review

#8740 Reorder Header Badge in Navigation
  graylog2-web-interface/src/components/navigation/Navigation.jsx
Labels: ready-for-review, ux

#8751 Revert "Construct jest client provider lazily instead of eager. (#8703)"
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
Labels: bug, elasticsearch, ready-for-review

#8719 Add endpoint to list shares for a user
  graylog2-server/src/main/java/org/graylog/grn/GRNDescriptorService.java
  graylog2-server/src/main/java/org/graylog/grn/GRNModule.java
  graylog2-server/src/main/java/org/graylog/grn/providers/DashboardGRNDescriptorProvider.java
  graylog2-server/src/main/java/org/graylog/grn/providers/StreamGRNDescriptorProvider.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyPermissionChecker.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDescriptor.java
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntityShareResponse.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
  graylog2-server/src/main/java/org/graylog2/rest/PaginationParameters.java
  graylog2-server/src/test/java/org/graylog/grn/GRNDescriptorServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyPermissionCheckerTest.java
  graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
  graylog2-server/src/test/java/org/graylog/testing/GRNExtension.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoJackExtension.java
  graylog2-server/src/test/resources/org/graylog/security/shares/dashboard-and-stream-shares.json
Labels: ready-for-review

#8766 Fix Header Nav Badge background hover
  graylog2-web-interface/src/components/navigation/InactiveNavItem.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Labels: bug, ready-for-review

#8775 Add saved search GRNDescriptorProvider
  graylog2-server/src/main/java/org/graylog/grn/GRNModule.java
  graylog2-server/src/main/java/org/graylog/grn/providers/ViewGRNDescriptorProvider.java
Labels: ready-for-review

#8771 Update yarn.lock
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review

#8711 Implement new roles overview
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesFilter.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverviewItem.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/index.js
  graylog2-web-interface/src/components/roles/RolesQueryHelper.jsx
  graylog2-web-interface/src/pages/RolesOverviewPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
Labels: ready-for-review

#8772 Fix UsersOverview pagination reset
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
Labels: ready-for-review

#8776 User profile link
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/UserMenu.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
  graylog2-web-interface/src/components/users/UserManagementLinks.jsx
  graylog2-web-interface/src/components/users/navigation/UserOverviewLinks.jsx
Labels: users

#8718 Graylog Noir
  graylog2-web-interface/src/components/common/Scratchpad.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Well.jsx
  graylog2-web-interface/src/components/graylog/__mocks__/Popover.jsx
  graylog2-web-interface/src/components/login/LoginBox.jsx
  graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap
  graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx
  graylog2-web-interface/src/components/navigation/ThemeModeToggle.jsx
  graylog2-web-interface/src/components/navigation/UserMenu.jsx
  graylog2-web-interface/src/components/streamrules/__snapshots__/StreamRuleForm.test.jsx.snap
  graylog2-web-interface/src/contexts/UserPreferencesContext.js
  graylog2-web-interface/src/hooks/usePrefersColorScheme.js
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/pages/ShowMessagePage.test.jsx
  graylog2-web-interface/src/routing/AppFacade.jsx
  graylog2-web-interface/src/stores/users/PreferencesStore.js
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/theme/colors.js
  graylog2-web-interface/src/theme/constants.js
  graylog2-web-interface/src/theme/docs/Colors.md
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/types.js
  graylog2-web-interface/src/theme/utils/colorLevel.js
  graylog2-web-interface/src/theme/utils/index.js
  graylog2-web-interface/src/theme/utils/readableColor.js
  graylog2-web-interface/src/theme/variants/noir.js
  graylog2-web-interface/src/theme/variants/teint.js
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/theme/variants/util.js
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/BarVisualizationConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesSelect.test.jsx.snap
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.test.jsx
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutState.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.jsx
  graylog2-web-interface/test/WrappingContainer.jsx
Labels: improvement, ready-for-review

#8787 Unify sidebar field list line-height with default line-height
  graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
Labels: ready-for-review, ux

#8778 Fix race conditions on system/configuration
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
Labels: bug, ready-for-review

#8789 Update title colors for Graphs
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
Labels: improvement, ready-for-review

#8715 Implement role details and role edit for new role management
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/components/roles/RoleDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/roles/RoleDetails/RoleDetails.jsx
  graylog2-web-interface/src/components/roles/RoleDetails/UsersSection.jsx
  graylog2-web-interface/src/components/roles/RoleDetails/index.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/index.js
  graylog2-web-interface/src/components/roles/navigation/RoleActionLinks.jsx
  graylog2-web-interface/src/pages/RoleDetailsPage.jsx
  graylog2-web-interface/src/pages/RoleEditPage.jsx
  graylog2-web-interface/src/pages/RolesOverviewPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
Labels: ready-for-review

#8799 Fix error for users overview which occurred when there is no root admin
  graylog2-web-interface/src/components/common/ReadOnlyFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/logic/users/UserOverview.js
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/stores/users/UsersStore.test.js
  graylog2-web-interface/test/fixtures/permissions.js
  graylog2-web-interface/test/fixtures/userOverviews.jsx
  graylog2-web-interface/test/fixtures/users.js
Labels: ready-for-review

#8808 Update button styles on Notification
  graylog2-web-interface/src/components/notifications/Notification.jsx
Labels: improvement, ready-for-review

#8807 Show Spinner while Theme is loading
  graylog2-web-interface/src/components/navigation/ThemeModeToggle.jsx
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/theme/types.js
Labels: improvement, ready-for-review, ux

#8806 Add unique compound index on "grants" table
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
Labels: ready-for-review

#8777 Make the admin owner of every entity
  graylog2-server/src/main/java/org/graylog/security/permissions/GRNPermission.java
  graylog2-server/src/main/java/org/graylog/security/rest/RestResourceWithOwnerCheck.java
  graylog2-server/src/main/java/org/graylog2/plugin/database/users/User.java
  graylog2-server/src/main/java/org/graylog2/security/InMemoryRolePermissionResolver.java
  graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
  graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
  graylog2-server/src/test/java/org/graylog2/users/UserImplTest.java
Labels: ready-for-review

#8810 Unifications for management frontend
  graylog2-web-interface/src/actions/permissions/EntityShareActions.js
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/permissions/RolesSelector.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
  graylog2-web-interface/src/components/users/UserDetails/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
  graylog2-web-interface/src/components/users/UserList.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/permissions/EntityShareStore.js
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/stores/users/UsersStore.test.js
Labels: ready-for-review

#8804 Implement HasOwnership which checks for sharing
  graylog2-web-interface/src/components/common/HasOwnership.jsx
  graylog2-web-interface/src/components/common/HasOwnership.test.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
  graylog2-web-interface/test/fixtures/users.js
Labels: ready-for-review, users

#8824 Caching singleton instance of `JestClient` in `JestClientProvider`.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestClientProvider.java
Labels: ready-for-review

#8825 Merge webpack overrides from plugin into core config
  graylog2-web-interface/webpack.combined.config.js
  graylog2-web-interface/webpack.config.js
Labels: frontend, ready-for-review

#8813 Jest styled components
  graylog2-web-interface/src/components/common/Wizard.test.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap
  graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap
  graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/visualizations/number/Trend.test.jsx
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
  graylog2-web-interface/test/wrappedEnzyme.jsx
  graylog2-web-interface/test/wrappedTestingLibrary.jsx
Labels: improvement, ready-for-review

#8822 Sync cloud branch after 3.3.5 release
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  integration-tests/pom.xml
  pom.xml
Labels: ready-for-review

#8774 Remove shared entities mock from EntityShareStore
  graylog2-web-interface/src/actions/permissions/EntityShareActions.js
  graylog2-web-interface/src/components/common/HasOwnership.jsx
  graylog2-web-interface/src/components/common/HasOwnership.test.jsx
  graylog2-web-interface/src/components/permissions/EntityShareModal.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverview.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/OwnersCell.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/SharedEntitiesOverviewItem.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/index.jsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/index.js
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesOverviewItem.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/logic/permissions/GRN.js
  graylog2-web-interface/src/logic/permissions/GRN.test.js
  graylog2-web-interface/src/logic/permissions/mocked.js
  graylog2-web-interface/src/stores/permissions/EntityShareStore.js
  graylog2-web-interface/test/fixtures/userEntityShares.js
Labels: ready-for-review

#8830 Add share button to Dashboard LIst
  graylog2-web-interface/src/views/components/views/ViewList.jsx
Labels: ready-for-review, search, users

#8600 Prevent the last owner to be removed
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntityShareRequest.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntityShareResponse.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
  graylog2-server/src/test/resources/org/graylog/security/shares/EntitySharesServiceTest.json
Labels: ready-for-review

#8853 Fix darkmode color of tableheader of data tables
  graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx
Labels: ready-for-review, search

#8487 Solved the problem of running scripts that set up and use environment…
  graylog2-web-interface/package.json
Labels: ready-for-review

#8707 Migrate dashboard and stream roles to grants
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_MigrateRolesToGrants.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java
  graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java
  graylog2-server/src/main/java/org/graylog2/users/RoleService.java
  graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_MigrateRolesToGrantsTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
  graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_MigrateRolesToGrantsTest.json
Labels: ready-for-review

#8846 Add user preferences section for UserDetails and UserEdit page
  graylog2-web-interface/src/components/common/ReadOnlyFormGroup.jsx
  graylog2-web-interface/src/components/users/UserDetails/PreferencesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/TeamsSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserEdit/PreferencesSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/form/FormikFormGroup.jsx
  graylog2-web-interface/src/contexts/UserPreferencesContext.js
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/logic/users/UserOverview.js
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/src/stores/users/PreferencesStore.js
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/theme/constants.js
  graylog2-web-interface/src/views/components/contexts/SearchPageLayoutState.jsx
  graylog2-web-interface/test/fixtures/users.js
Labels: ready-for-review

#8856 Show confirmation dialog on role delete with info about assigned users
  graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.jsx
Labels: ready-for-review

#8840 Use correct interval type for time bucketing.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESTimeHandler.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivots/buckets/ESTimeHandlerTest.java
Labels: ready-for-review

#8870 Enabling flow declarations for `node_modules`.
  graylog2-web-interface/.flowconfig
  graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
Labels: frontend, ready-for-review

#8848 Set font size defined in theme for query input
  graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
Labels: bug, ready-for-review, search

#8866 Update styled-components flow interface definition from v4 to v5
  graylog2-web-interface/flow-typed/npm/styled-components_v5.x.x.js
  graylog2-web-interface/src/components/graylog/DropdownSubmenu.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageFields.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/ListItem.jsx
Labels: ready-for-review

#8832 Serialize body of new messages using object mapper for ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
Labels: bug, ready-for-review

#8877 Don't validate initial share requests // provide validation context
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationResult.java
  graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
Labels: ready-for-review

#8878 Add type definition for user create and update payload
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
  graylog2-web-interface/src/stores/users/UsersStore.js
Labels: ready-for-review
