Repository Graylog2/graylog2-server, pull requests merged in 2020-05, with the labels that each got.

#8002 Include message field as initial field when using CSV export modal widget select.
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx
Labels: bug, ready-for-review, search

#8023 Export `ChartColorContext` as singleton.
  graylog2-web-interface/src/views/components/visualizations/ChartColorContext.js
Labels: bug, ready-for-review, search

#8018 Fix sidebar highlighting rules layout for field values with a long name
  graylog2-web-interface/src/views/components/sidebar/highlighting/ColorBox.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/ColorPreview.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.css
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.test.jsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/__snapshots__/HighlightingRules.test.jsx.snap
Labels: ready-for-review, search

#7995 Update panel usage
  graylog2-web-interface/src/components/event-definitions/common/HelpPanel.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx
  graylog2-web-interface/src/components/graylog/Panel.jsx
  graylog2-web-interface/src/components/graylog/Panel.md
Labels: ready-for-review

#8031 Mask passwords in input config returned from /system/inputstates
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputStatesResource.java
Labels: inputs, ready-for-review, security

#8037 Mask passwords in input config returned from /system/inputstates (#8031)
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputStatesResource.java
Labels: ready-for-review

#8028 Define key prop for `MapVisualization` to update map on dimension change
  graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
Labels: bug, ready-for-review, search

#8019 GlobalThroughput Styles
  graylog2-web-interface/src/components/common/ExternalLink.jsx
  graylog2-web-interface/src/components/common/ExternalLinkButton.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/throughput/GlobalThroughput.css
  graylog2-web-interface/src/components/throughput/GlobalThroughput.jsx
  graylog2-web-interface/src/routing/AppRouter.test.jsx
  graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js
Labels: ready-for-review

#8033 Remove sort and sort direction select from CSV export modal
  graylog2-web-interface/src/util/MessagesExportUtils.js
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportSettings.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/startDownload.js
Labels: ready-for-review, search

#8010 Only cancel default event action on widget title change if event is defined
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
Labels: ready-for-review, search

#8040 Adhere allow_leading_wildcard_searches setting
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendErrorHandlingTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendGeneratedRequestTestBase.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendUsingCorrectIndicesTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/QueryPlanTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/overridesInSearchTypeAreIncorporatedIntoGeneratedQueries.request.ndjson
  graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/timerangeOverridesAffectIndicesSelection.request.ndjson
Labels: bug, ready-for-review, search

#8006 Migrating Search Input colors to Theme
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/ace-queryinput.css
  graylog2-web-interface/src/views/components/searchbar/queryinput/ace-queryinput.js
  graylog2-web-interface/src/views/components/searchbar/queryinput/ace.js
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
Labels: ready-for-review

#8036 Use Scrolling instead of Search After in new export
  full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceIT.java
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/MessagesRequest.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ResultFormat.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackend.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/JestWrapper.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/RequestStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/Scroll.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/SearchAfter.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/JestUtils.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/MessagesRequestTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendITBase.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendScrollingIT.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendSearchAfterIT.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendTest.java
Labels: ready-for-review, search

#8049 Hide export to CSV action in widget action menu for aggregations
  graylog2-web-interface/src/views/components/common/ActionDropdown.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
Labels: ready-for-review, search

#8051 Extract method to generate new salt for encryption.
  graylog2-server/src/main/java/org/graylog2/security/AESTools.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java
Labels: ready-for-review

#8030 Add calculated height for search area to fix scrolling with safari
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Labels: bug, ready-for-review, search

#8005 Sidecar Clone Configuration option
  graylog2-web-interface/src/components/sidecars/common/CloneMenuItem.jsx
  graylog2-web-interface/src/components/sidecars/configurations/CopyCollectorModal.jsx
  graylog2-web-interface/src/components/sidecars/configurations/CopyConfigurationModal.jsx
  graylog2-web-interface/src/components/sidecars/configurations/CopyModal.css
Labels: ready-for-review

#7970 SimulationChanges styles
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/simulator/SimulationChanges.css
  graylog2-web-interface/src/components/simulator/SimulationChanges.jsx
  graylog2-web-interface/src/components/users/UserList.css
  graylog2-web-interface/src/components/users/UserList.jsx
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/Field.css
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/actions/FieldActions.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/SearchButton.jsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
Labels: ready-for-review

#8042 List all message lists from all dashboard pages in CSV export widget select
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportSettings.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/ExportStrategy.js
Labels: bug, ready-for-review, search

#8054 Sort CSV export widget select options alphabetically
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx
Labels: ready-for-review, search

#8061 standardize graylog schema field names
  graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
Labels: security

#8047 Allow writing cluster config object with custom key.
  graylog2-server/src/main/java/org/graylog2/cluster/ClusterConfigServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/plugin/cluster/ClusterConfigService.java
  graylog2-server/src/test/java/org/graylog2/cluster/ClusterConfigServiceImplTest.java
Labels: ready-for-review

#8071 remove unused fields
  graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
Labels: ready-for-review

#8068 mostly cosmetic changes to free trial license request page
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeEnterpriseService.java
  graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseAPIClient.java
  graylog2-web-interface/src/pages/EnterprisePage.jsx
Labels: ready-for-review

#8060 Reset job trigger on EventDefinition updates
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorExecutionJob.java
  graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionHandlerTest.java
Labels: alerting, bug, ready-for-review

#8067 Always update NotificationGracePeriodService cache
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationGracePeriodService.java
  graylog2-server/src/test/java/org/graylog/events/event/TestEvent.java
  graylog2-server/src/test/java/org/graylog/events/processor/notification/NotificationGracePeriodServiceTest.java
Labels: alerting, bug, ready-for-review

#8073 Sanitize Hyperlink String Decorator links
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/decorators/LinkFieldDecorator.java
  graylog2-server/src/test/java/org/graylog2/decorators/LinkFieldDecoratorTest.java
  pom.xml
Labels: ready-for-review

#8057 Extract method to generate new salt for encryption. (3.2)
  graylog2-server/src/main/java/org/graylog2/security/AESTools.java
  graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java
Labels: ready-for-review

#8089 Moving All Hex Breakdown FINAL
  graylog2-web-interface/src/components/common/ScrollButton.css
  graylog2-web-interface/src/components/common/ScrollButton.jsx
  graylog2-web-interface/src/components/common/SourceCodeEditor.css
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
  graylog2-web-interface/src/components/common/Wizard.css
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/events/events/Events.css
  graylog2-web-interface/src/components/events/events/Events.jsx
Labels: ready-for-review, ux

#8072 Sanitize Content Pack URLs
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackDetails.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/util/URLUtils.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, security

#8096 Don't throw error in event wizard when query has no result
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx
Labels: bug, ready-for-review

#8083 Improve rendering performance of field selects in event definition UI.
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
Labels: ready-for-review

#8100 Allow writing cluster config object with custom key. (3.2)
  graylog2-server/src/main/java/org/graylog2/cluster/ClusterConfigServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/plugin/cluster/ClusterConfigService.java
  graylog2-server/src/test/java/org/graylog2/cluster/ClusterConfigServiceImplTest.java
Labels: ready-for-review

#8098 Allow arbitrary key sizes for AESTools.encrypt/decrypt. (3.2)
  graylog2-server/src/main/java/org/graylog2/security/AESTools.java
  graylog2-server/src/test/java/org/graylog2/security/AESToolsTest.java
Labels: ready-for-review

#7979 Moving All Hex Breakdown-7
  graylog2-web-interface/src/components/search/MessageTableEntry.css
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.css
Labels: ready-for-review

#8074 Query ace styles
  graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/theme/docs/Colors.jsx
  graylog2-web-interface/src/theme/docs/Colors.md
  graylog2-web-interface/src/theme/variants/teinte.js
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
Labels: bug, ready-for-review

#8086 Export API Docs
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/MessagesRequest.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ResultFormat.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java
Labels: documentation, ready-for-review, search

#8104 Sanitize Content Pack URLs
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackDetails.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
  graylog2-web-interface/src/util/URLUtils.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, security

#7980 TestLdapLogin styles & ES6 Class conversion
  graylog2-web-interface/src/components/ldap/TestLdapLogin.css
  graylog2-web-interface/src/components/ldap/TestLdapLogin.jsx
Labels: ready-for-review

#8112 Add source streams to the default email notification template
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java
Labels: alerting, improvement, ready-for-review

#7928 DropdownSubmenu component
  graylog2-web-interface/public/stylesheets/bootstrap-submenus.less
  graylog2-web-interface/src/components/graylog/DropdownSubmenu.jsx
  graylog2-web-interface/src/components/graylog/index.js
  graylog2-web-interface/src/components/nodes/NodesActions.jsx
  graylog2-web-interface/src/routing/AppFacade.jsx
  graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.jsx
  graylog2-web-interface/styleguide.config.js
Labels: ready-for-review

#8122 Update netty to 4.1.50
  pom.xml
Labels: inputs, ready-for-review

#8115 Add API description on MessagesResource
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java
Labels: documentation, ready-for-review, search

#8125 Render event annotations with timezone setting of the user
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.js
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.test.js
  graylog2-web-interface/src/views/logic/searchtypes/events/__snapshots__/EventHandler.test.js.snap
Labels: ready-for-review, search

#8160 Fix EventsConfiguration migration error
  graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfiguration.java
Labels: bug, ready-for-review

#8165 Fix EventsConfiguration migration error (#8160)
  graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfiguration.java
Labels: backport, ready-for-review

#8151 Make UrlValidator a Singleton
  graylog2-server/src/main/java/org/graylog2/decorators/LinkFieldDecorator.java
Labels: ready-for-review

#8167 Added upgrade notes for export
  UPGRADING.rst
Labels: documentation, search

#8169 Added upgrade notes for export (#8167)
  UPGRADING.rst
Labels: backport, documentation, ready-for-review, search

#8166 Create separate module for ES-specific implementations.
  graylog-project-parent/pom.xml
  graylog-storage-elasticsearch6/pom.xml
Labels: ready-for-review

#8119 Preselect node if only one node exists
  graylog2-web-interface/src/components/inputs/NodeOrGlobalSelect.jsx
Labels: inputs, ready-for-review, ux

#8184 Fix summing up individual node throughput metrics.
  graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js
  graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.test.js
Labels: bug, ready-for-review

#8185 Fix summing up individual node throughput metrics. (3.3)
  graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js
  graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.test.js
Labels: bug, ready-for-review

#8136 Add support for more verbose authentication failure
  graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultSecurityManagerProvider.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/AuthenticationServiceUnavailableException.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ThrowingFirstSuccessfulStrategy.java
  graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java
Labels: ready-for-review

#8092 Moving theme utils to GraylogThemeProvider
  graylog2-web-interface/src/components/content-packs/ContentPackStatus.jsx
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/components/graylog/Badge.jsx
  graylog2-web-interface/src/components/graylog/FormGroup.jsx
  graylog2-web-interface/src/components/graylog/Label.jsx
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
  graylog2-web-interface/src/components/graylog/Navbar.jsx
  graylog2-web-interface/src/components/graylog/Pagination.jsx
  graylog2-web-interface/src/components/graylog/Panel.jsx
  graylog2-web-interface/src/components/graylog/Popover.jsx
  graylog2-web-interface/src/components/graylog/ProgressBar.jsx
  graylog2-web-interface/src/components/graylog/Tab.jsx
  graylog2-web-interface/src/components/graylog/Table.jsx
  graylog2-web-interface/src/components/graylog/Tooltip.jsx
  graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap
  graylog2-web-interface/src/components/graylog/styles/buttonStyles.js
  graylog2-web-interface/src/components/graylog/styles/menuItem.js
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/components/indices/ShardRoutingOverview.jsx
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
  graylog2-web-interface/src/components/sidecars/common/CloneMenuItem.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
  graylog2-web-interface/src/components/simulator/SimulationChanges.jsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
  graylog2-web-interface/src/theme/docs/Colors.jsx
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/utils/index.js
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
  graylog2-web-interface/src/views/components/sidebar/NavItem.styles.jsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.styles.jsx
  graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
Labels: improvement, ready-for-review, ux

#8124 Introduce pluggable authorization realms
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultSecurityManagerProvider.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
  graylog2-server/src/main/java/org/graylog2/security/OrderedAuthenticatingRealms.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthorizationOnlyRealmModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
Labels: enterprise, feature, ready-for-review

#8070 Don't enable CORS by default
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/CORSFilter.java
  misc/graylog.conf
Labels: bug, ready-for-review, security

#8179 Theme utils typing
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/utils/colorLevel.js
  graylog2-web-interface/src/theme/utils/contrastingColor.js
  graylog2-web-interface/src/theme/utils/index.js
  graylog2-web-interface/src/theme/utils/opacify.js
  graylog2-web-interface/src/theme/utils/readableColor.js
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
Labels: ready-for-review, ux

#8126 Add an end-to-end test for indexing and searching a message
  full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2E.java
  full-backend-tests/src/test/java/org/graylog/testing/backenddriver/SearchDriver.java
  full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/ApiIntegrationTest.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackendExtension.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/Lifecycle.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java
Labels: elasticsearch, ready-for-review, search

#8201 Remove legacy redirects for dashboards & saved searches.
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsRedirectResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesRedirectResource.java
Labels: ready-for-review

#8130 Migrate PaginatedList from class to functional component
  graylog2-web-interface/src/components/common/PaginatedList.jsx
Labels: improvement, ready-for-review

#8199 Removing legacy saved searches API.
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/LegacySavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog2/savedsearches/SavedSearch.java
  graylog2-server/src/main/java/org/graylog2/savedsearches/SavedSearchImpl.java
  graylog2-server/src/main/java/org/graylog2/savedsearches/SavedSearchService.java
  graylog2-server/src/main/java/org/graylog2/savedsearches/SavedSearchServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/savedsearches/SavedSearchServiceImplTest.java
Labels: ready-for-review

#8102 Do not redirect to `/notfound` when viewing a saved search or dashboard which does not exist.
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.jsx
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
  graylog2-web-interface/src/logic/errors/ReportedErrors.js
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.jsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.jsx
  graylog2-web-interface/src/views/logic/views/ViewLoader.js
  graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
Labels: ready-for-review, search

#8198 Removing legacy Dashboards API.
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog/plugins/map/MapWidgetModule.java
  graylog2-server/src/main/java/org/graylog/plugins/map/rest/MapDataResource.java
  graylog2-server/src/main/java/org/graylog/plugins/map/search/MapDataSearch.java
  graylog2-server/src/main/java/org/graylog/plugins/map/search/MapDataSearchRequest.java
  graylog2-server/src/main/java/org/graylog/plugins/map/search/MapDataSearchResult.java
  graylog2-server/src/main/java/org/graylog/plugins/map/widget/strategy/MapWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/map/widget/strategy/MapWidgetStrategyConfiguration.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/WidgetStrategyBindings.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/dashboards/Dashboard.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardBindings.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardImpl.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardService.java
  graylog2-server/src/main/java/org/graylog2/dashboards/DashboardServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/DashboardWidget.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/DashboardWidgetCreator.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/InvalidWidgetConfigurationException.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/WidgetCacheTime.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/WidgetEventsListener.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/WidgetResultCache.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/WidgetStrategyFactory.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/events/WidgetUpdatedEvent.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/ChartWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/FieldChartWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesBaseWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesHistogramWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/SearchResultChartWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/SearchResultCountWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/StackedChartWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/StatisticalCountWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/StreamSearchResultCountWidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/dashboards/widgets/WidgetStrategy.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/LegacyDashboardWidgetsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/LegacyDashboardsResource.java
  graylog2-server/src/main/java/org/graylog2/timeranges/TimeRangeFactory.java
  graylog2-server/src/test/java/org/graylog2/dashboards/DashboardServiceImplTest.java
  graylog2-server/src/test/java/org/graylog2/dashboards/widgets/DashboardWidgetTest.java
  graylog2-server/src/test/java/org/graylog2/dashboards/widgets/WidgetCacheTimeTest.java
  graylog2-server/src/test/java/org/graylog2/dashboards/widgets/WidgetEventsListenerTest.java
  graylog2-server/src/test/resources/org/graylog2/dashboards/DashboardServiceImplTest.json
Labels: ready-for-review

#8088 Display user notification after sharing a view
  graylog2-web-interface/src/views/components/ViewTypeLabel.js
  graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
Labels: improvement, search

#8203 Include storage module in server assembly.
  distribution/pom.xml
  distribution/src/main/assembly/graylog.xml
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  pom.xml
Labels: ready-for-review

#8069 Create flow type definition for search types
  graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
  graylog2-web-interface/src/views/components/searchbar/csvexport/ExportStrategy.js
  graylog2-web-interface/src/views/components/searchbar/csvexport/startDownload.js
  graylog2-web-interface/src/views/logic/queries/Query.js
  graylog2-web-interface/src/views/logic/queries/SearchType.js
  graylog2-web-interface/src/views/logic/searchtypes/messages/MessageSortConfig.js
  graylog2-web-interface/src/views/logic/views/View.js
Labels: ready-for-review, search

#8066 Use StringUtils to capitalize view type label
  graylog2-web-interface/src/views/components/ViewTypeLabel.js
Labels: ready-for-review, search

#8210 Include storage module in Graylog setup of integration tests.
  graylog-storage-elasticsearch6/pom.xml
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
  graylog2-server/src/test/resources/api-it-tests.properties
Labels: ready-for-review

#8213 Wire Elasticsearch 6 storage module as plugin.
  full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Metadata.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Plugin.java
  graylog-storage-elasticsearch6/src/main/resources/META-INF/services/org.graylog2.plugin.Plugin
Labels: ready-for-review

#8113 Refactor index mapping templates for ES5 & 6.
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMapping5Test.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMapping6Test.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingTestBase.java
  graylog2-server/src/test/resources/org/graylog2/indexer/expected_template5.json
  graylog2-server/src/test/resources/org/graylog2/indexer/expected_template6.json
Labels: ready-for-review

#8058 Workarounds to allow exporting events with Search After
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackend.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/RequestStrategy.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/SearchAfter.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/SearchAfterTest.java
Labels: elasticsearch, ready-for-review, search

#8135 Fix search widget grid width when its content results in a scrollbar
  graylog2-web-interface/src/views/components/WidgetGrid.jsx
  graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap
Labels: bug, ready-for-review

#8004 Log warn/error before throwing an error in console-warnings-fail-tests.js
  graylog2-web-interface/test/console-warnings-fail-tests.js
Labels: ready-for-review

#8235 Fixed import
  graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/SearchAfter.java
Labels: ready-for-review, search
