Repository Graylog2/graylog2-server, pull requests merged in 2020-01, with the labels that each got.

#7063 Organizing theme utilities
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/components/graylog/FormGroup.jsx
  graylog2-web-interface/src/components/graylog/Label.jsx
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
  graylog2-web-interface/src/components/graylog/Nav.jsx
  graylog2-web-interface/src/components/graylog/Panel.jsx
  graylog2-web-interface/src/components/graylog/Popover.jsx
  graylog2-web-interface/src/components/graylog/ProgressBar.jsx
  graylog2-web-interface/src/components/graylog/Table.jsx
  graylog2-web-interface/src/components/graylog/styles/badge.js
  graylog2-web-interface/src/components/graylog/styles/button.js
  graylog2-web-interface/src/components/graylog/styles/menuItem.js
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/components/graylog/variants/bsStyle.js
  graylog2-web-interface/src/theme/index.js
  graylog2-web-interface/src/theme/util/contrastingColor.js
  graylog2-web-interface/src/theme/util/contrastingColor.test.js
  graylog2-web-interface/src/theme/util/index.js
  graylog2-web-interface/src/theme/util/readableColor.js
  graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
Labels: ready-for-review

#7075 Security update to jackson-2.9.10.20200103
  pom.xml
Labels: ready-for-review

#7072 Update to netty-4.1.44
  pom.xml
Labels: ready-for-review

#7038 Execute search after resetting global filter inside widget edit modal
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
Labels: bug, ready-for-review, search

#7057 Generate specific link for each entity on dashboard list.
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/views/View.jsx
Labels: bug, ready-for-review

#7077 Destructure result from `SystemStore` properly in `Footer`.
  graylog2-web-interface/src/components/layout/Footer.jsx
  graylog2-web-interface/src/components/layout/Footer.test.jsx
Labels: bug, ready-for-review

#6854 URL whitelist service
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
  graylog2-server/src/main/java/org/graylog2/alarmcallbacks/HTTPAlarmCallback.java
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/UrlWhitelistFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/DSVHTTPDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/LookupDataAdapterValidationContext.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetriever.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20191129134600_CreateInitialUrlWhitelist.java
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupDataAdapterConfiguration.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/urlwhitelist/WhitelistCheckRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/urlwhitelist/WhitelistCheckResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/models/tools/responses/RegexValidationResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/UrlWhitelistResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/RegexTesterResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/LiteralWhitelistEntry.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/RegexWhitelistEntry.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlNotWhitelistedException.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlWhitelist.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlWhitelistNotificationService.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlWhitelistService.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/WhitelistEntry.java
  graylog2-server/src/test/java/org/graylog2/alarmcallbacks/HTTPAlarmCallbackTest.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetrieverTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20191129134600_CreateInitialUrlWhitelistTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/tools/RegexTesterResourceTest.java
  graylog2-server/src/test/java/org/graylog2/system/urlwhitelist/UrlWhitelistServiceTest.java
  graylog2-server/src/test/java/org/graylog2/system/urlwhitelist/UrlWhitelistTest.java
Labels: ready-for-review

#6879 Support multiple conditions in aggregation event definitions
  graylog2-server/src/main/java/org/graylog/events/conditions/BooleanNumberConditionsVisitor.java
  graylog2-server/src/main/java/org/graylog/events/conditions/Expr.java
  graylog2-server/src/main/java/org/graylog/events/conditions/Expression.java
  graylog2-server/src/main/java/org/graylog/events/conditions/ExpressionVisitor.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationFunction.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200102140000_UnifyEventSeriesId.java
  graylog2-server/src/test/java/org/graylog/events/conditions/BooleanNumberConditionsVisitorTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200102140000_UnifyEventSeriesIdTestIT.java
  graylog2-server/src/test/resources/org/graylog/events/conditions/condition-grouped.json
  graylog2-server/src/test/resources/org/graylog2/migrations/V20200102140000_UnifyEventSeriesIdTestIT.json
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpression.css
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpression.test.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/BooleanExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/BooleanOperatorSelector.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/ComparisonExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/GroupExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.test.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/logic/alerts/AggregationExpressionConfig.js
  graylog2-web-interface/src/logic/alerts/AggregationExpressionParser.js
  graylog2-web-interface/src/logic/alerts/AggregationExpressionParser.test.js
  graylog2-web-interface/src/logic/alerts/AggregationExpressionTypes.js
Labels: alerting, ready-for-review

#7084 Update code name for 3.2
  graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
Labels: ready-for-review

#7085 Reducing remounting/-rendering of `MessageDetail` component.
  graylog2-web-interface/src/pages/ShowMessagePage.jsx
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap
  graylog2-web-interface/src/views/components/messagelist/MessageDetail.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx
  graylog2-web-interface/src/views/components/messagelist/NodeName.jsx
Labels: bug, ready-for-review, search

#7070 Fix event aggregation with empty field strings
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationSeries.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
Labels: bug, ready-for-review

#7102 Fix horizontal scrolling for datatable widget
  graylog2-web-interface/src/views/components/aggregationbuilder/FullSizeContainer.jsx
Labels: bug, ready-for-review, search

#6996 Scratchpad browser resize
  graylog2-web-interface/src/components/common/InteractableModal.jsx
  graylog2-web-interface/src/components/common/Scratchpad.jsx
  graylog2-web-interface/src/components/common/Scratchpad.test.jsx
  graylog2-web-interface/src/components/navigation/ScratchpadToggle.jsx
  graylog2-web-interface/src/providers/ScratchpadProvider.jsx
  graylog2-web-interface/src/routing/App.jsx
Labels: ready-for-review

#7106 Add missing leaflet css import for MapVisualization
  graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
Labels: bug, ready-for-review, search

#7112 Save world map widget viewport on widget save
  graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.jsx
  graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.test.jsx
Labels: bug, ready-for-review, search

#7087 Add Listfield option in ConfigurationRequest
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/Configuration.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/ConfigurationRequest.java
  graylog2-server/src/test/java/org/graylog2/plugin/configuration/ConfigurationRequestTest.java
Labels: bug, ready-for-review

#7116 Update to testcontainers-1.12.4
  pom.xml
Labels: infrastructure, ready-for-review

#7114 Make configuration section layout in AggregationBuilder more responsive
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
Labels: bug, ready-for-review, search

#7120 Fix horizontal datatable scrolling for safari
  graylog2-web-interface/src/views/components/datatable/DataTable.css
  graylog2-web-interface/src/views/components/datatable/DataTable.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
Labels: bug, ready-for-review, search

#7123 Disabling field actions if not applicable to current field/function.
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/bindings.test.jsx
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js
Labels: bug, ready-for-review, search

#7124 Remove "Use in new Query" action.
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/logic/valueactions/UseInNewQueryHandler.js
  graylog2-web-interface/src/views/logic/valueactions/UseInNewQueryHandler.test.js
Labels: bug, ready-for-review, search

#7122 Use Urlwhitelist API instead of clusterConfig API
  graylog2-web-interface/src/actions/configurations/ConfigurationActions.js
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
Labels: ready-for-review

#7135 Fix error message wording from #7122
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
Labels: ready-for-review

#7093 Resolve field types correctly for renamed series.
  graylog2-web-interface/src/views/components/aggregationbuilder/SeriesConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SeriesConfiguration.test.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
  graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx
  graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.jsx
  graylog2-web-interface/src/views/components/datatable/Headers.jsx
  graylog2-web-interface/src/views/components/datatable/Headers.test.jsx
Labels: bug, ready-for-review, search

#7140 Convert week/month bucket interval to days if value is bigger than 1.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/TimeUnitInterval.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/TimeUnitIntervalTest.java
Labels: bug, ready-for-review, search

#7136 Rename view to dashboard for all dashboard related info text
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
  graylog2-web-interface/src/views/components/views/ViewPropertiesModal.jsx
Labels: bug, ready-for-review, search

#7108 Add current function to value path.
  graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
  graylog2-web-interface/src/views/logic/aggregationbuilder/Series.js
  graylog2-web-interface/src/views/logic/queries/QueryHelper.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
Labels: bug, ready-for-review, search

#7071 Handle Request Entity Too Large errors in ElasticSearchOutput
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/JestUtils.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
  misc/graylog.conf
Labels: bug, ready-for-review

#7131 Display "Create extractor" action only in the context of a message
  graylog2-web-interface/src/views/bindings.fieldActions.test.jsx
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/bindings.test.jsx
  graylog2-web-interface/src/views/bindings.valueActions.test.jsx
Labels: bug, ready-for-review, search

#7155 Use explicit index for MessagesIT
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
Labels: ready-for-review

#7157 Improve API browser for several resources (#6955)
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorParameters.java
  graylog2-server/src/main/java/org/graylog/events/rest/AvailableEntityTypesResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchParameters.java
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchResult.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/processing/ProcessingStatusSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbackHistoryResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbacksResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/StreamAlarmCallbackResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/alerts/AlertResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/AlertConditionsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertResource.java
Labels: backport, ready-for-review

#7115 Duplicate query/timerange/streams/filter for specific field/value actions.
  graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.test.jsx
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js
  graylog2-web-interface/src/views/logic/fieldactions/DuplicateCommonWidgetSettings.js
  graylog2-web-interface/src/views/logic/fieldactions/DuplicateCommonWidgetSettings.test.jsx
  graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.js
  graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.test.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
Labels: bug, ready-for-review, search

#7148 Handle Request Entity Too Large errors in ElasticSearchOutput (#7071)
  graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/JestUtils.java
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
  graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
  graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
  misc/graylog.conf
Labels: backport, ready-for-review

#7130 Enforce system wide TLS protocol settings
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsTransport.java
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/SyslogTcpTransport.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/TcpTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportTest.java
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
  misc/graylog.conf
Labels: bug, ready-for-review, security

#7160 Fix Swagger annotations in Views resources
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
Labels: search

#7125 Complete migration to React Select v2
  graylog2-web-interface/src/components/common/Select.jsx
  graylog2-web-interface/src/components/common/Select.test.jsx
  graylog2-web-interface/src/components/configurations/decorators/StreamSelect.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/BooleanOperatorSelector.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/ComparisonExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/streams/StreamForm.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/AddDecoratorButton.jsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
Labels: ready-for-review

#7110 Add URL whitelist service (#6854 and #6915)
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
  graylog2-server/src/main/java/org/graylog2/alarmcallbacks/HTTPAlarmCallback.java
  graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/UrlWhitelistFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/DSVHTTPDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/LookupDataAdapterValidationContext.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetriever.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20191129134600_CreateInitialUrlWhitelist.java
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupDataAdapterConfiguration.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/urlwhitelist/WhitelistCheckRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/urlwhitelist/WhitelistCheckResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/models/tools/responses/RegexValidationResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/UrlWhitelistResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/tools/RegexTesterResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/LiteralWhitelistEntry.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/RegexWhitelistEntry.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlNotWhitelistedException.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlWhitelist.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlWhitelistNotificationService.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/UrlWhitelistService.java
  graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/WhitelistEntry.java
  graylog2-server/src/test/java/org/graylog2/alarmcallbacks/HTTPAlarmCallbackTest.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetrieverTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20191129134600_CreateInitialUrlWhitelistTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/tools/RegexTesterResourceTest.java
  graylog2-server/src/test/java/org/graylog2/system/urlwhitelist/UrlWhitelistServiceTest.java
  graylog2-server/src/test/java/org/graylog2/system/urlwhitelist/UrlWhitelistTest.java
  graylog2-web-interface/src/actions/configurations/ConfigurationActions.js
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.jsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.test.jsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListForm.jsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListForm.test.jsx
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
  graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppWithSearchBar.jsx
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
  graylog2-web-interface/src/stores/tools/ToolsStore.js
  graylog2-web-interface/src/stores/tools/ToolsStore.ts
Labels: backport, ready-for-review

#7164 Update to netty 4.1.45
  pom.xml
Labels: ready-for-review

#7138 Use global override time range as reference for offset time ranges.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/timeranges/DerivedTimeRange.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/timeranges/OffsetRange.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryEffectiveTimeRangeTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/timeranges/DerivedTimeRangeTest.java
Labels: bug, ready-for-review, search

#7145 Zoom global override when zooming in timeline chart on dashboard.
  graylog2-web-interface/src/views/components/visualizations/OnZoom.js
  graylog2-web-interface/src/views/components/visualizations/OnZoom.test.jsx
  graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.js
Labels: bug, ready-for-review, search

#7133 Fixing effective time range in pivot search type results.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/pivot/ESPivot.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/pivot/ESPivotTest.java
Labels: bug, ready-for-review, search

#7147 Avoid using PathConfiguration#getDataDir() for default path configs
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java
  graylog2-server/src/main/java/org/graylog2/plugin/KafkaJournalConfiguration.java
Labels: ready-for-review

#7161 Update upgrading instructions
  UPGRADING.rst
Labels: documentation, ready-for-review

#7163 Backport: Use Urlwhitelist API instead of clusterConfig API
  graylog2-web-interface/src/actions/configurations/ConfigurationActions.js
  graylog2-web-interface/src/pages/ConfigurationsPage.jsx
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
Labels: ready-for-review

#7172 Allow PermittedStreams to load empty lists
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PermittedStreams.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/PermittedStreamsTest.java
Labels: ready-for-review, search

#7171 Rename default search sidebar title from 'New Search' to 'Untitled Search'
  graylog2-web-interface/src/views/components/sidebar/SideBar.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
Labels: ready-for-review, search

#7184 Do not show `Empty Value` for deduplicated values.
  graylog2-web-interface/src/views/components/EmptyValue.jsx
  graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx
  graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.jsx
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
Labels: bug, ready-for-review, search

#7182 Improving `CycleQueryTab` test by using fake timers.
  graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.test.jsx
Labels: bug, ready-for-review, search

#7200 Do not parse empty value of from/to field as date for absolute ranges.
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.test.jsx
Labels: bug, ready-for-review, search

#7196 Validating value for interval to be an integer and greater than 0.
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/TimeUnitTimeHistogramPivot.jsx
Labels: bug, ready-for-review, search

#7187 Add "gl2_accounted_message_size" field to indexed messages
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
  graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
  graylog2-web-interface/src/logic/message/MessageFieldsFilter.js
Labels: ready-for-review

#7178 Clean up naming of views endpoints in api browser
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PivotSeriesFunctionsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/DashboardWidgetsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/SavedSearchesResource.java
Labels: ready-for-review, search

#7141 Remove widget position from view state, on widget delete
  graylog2-web-interface/src/views/stores/CurrentViewStateStore.js
  graylog2-web-interface/src/views/stores/CurrentViewStateStore.test.js
Labels: bug, ready-for-review, search

#7177 Synchronize timerange & query with URL on search page.
  graylog2-web-interface/src/views/actions/QueriesActions.js
  graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.js
  graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.js
  graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
  graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx
  graylog2-web-interface/src/views/logic/queries/Query.js
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
  graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/stores/QueriesStore.js
  graylog2-web-interface/src/views/stores/QueriesStore.test.jsx
Labels: bug, ready-for-review, search

#7183 Display view type specific default sidebar title
  graylog2-web-interface/src/views/components/sidebar/SideBar.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
Labels: ready-for-review, search

#7159 Implement overlay for select menu
  graylog2-web-interface/src/views/components/Select.jsx
Labels: bug, ready-for-review, search

#7170 Fix placeholder overflow for SortDirectionSelect
  graylog2-web-interface/src/views/components/aggregationbuilder/SortDirectionSelect.jsx
Labels: bug, ready-for-review, search

#7216 Increase sidebar field list width
  graylog2-web-interface/src/views/components/sidebar/NavItem.styles.jsx
Labels: bug, ready-for-review, search

#7225 Redirect to dashboard route instead of view route after saving new dashboard
  graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.js
  graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.test.js
Labels: bug, ready-for-review, search

#7222 Reset time in SearchesCleanUpJobWithDBServicesTest teardown method
  graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryEffectiveTimeRangeTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendUsingCorrectIndicesTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/pivot/ESPivotTest.java
Labels: ready-for-review

#7188 Adding backup note & known missing functionality for search to upgrade notes.
  UPGRADING.rst
Labels: ready-for-review, search

#7220 Fix Alerting Lookup Table Parameters UI
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EditQueryParameterModal.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
Labels: ready-for-review

#7221 Persist Alert search timerange and type
  graylog2-web-interface/src/components/events/events/EventsContainer.jsx
Labels: ready-for-review

#7219 Add validation to multiple aggregation condition
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/BooleanExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/ComparisonExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/GroupExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionsFormSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
  graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js
Labels: ready-for-review

#7073 Fix issue when clicking on Roles menu after clicking "Create role" button
  graylog2-web-interface/src/components/users/EditRole.jsx
Labels: ready-for-review

#7238 Remove not needed header from search bookmark list items
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkList.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
Labels: bug, ready-for-review, search

#7069 Frontend Styleguide docs
  graylog2-web-interface/src/components/common/DataTable.jsx
  graylog2-web-interface/src/components/common/PaginatedList.md
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
  graylog2-web-interface/src/components/graylog/Alert.md
  graylog2-web-interface/src/components/graylog/Badge.md
  graylog2-web-interface/src/components/graylog/Button.md
  graylog2-web-interface/src/components/graylog/DropdownButton.md
  graylog2-web-interface/src/components/graylog/FormControl.md
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
  graylog2-web-interface/src/components/graylog/ListGroupItem.md
  graylog2-web-interface/src/components/graylog/NavDropdown.md
  graylog2-web-interface/src/components/graylog/Popover.md
  graylog2-web-interface/src/components/graylog/SplitButton.md
  graylog2-web-interface/src/components/graylog/Tabs.md
  graylog2-web-interface/src/components/graylog/Tooltip.md
  graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
  graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Labels: ready-for-review

#7079 Set focus on title field on Cache and DataAdapters forms
  graylog2-web-interface/src/components/lookup-tables/CacheForm.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx
Labels: ready-for-review

#7215 Improve form validation for dashboard full screen config modal
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.jsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx
Labels: bug, ready-for-review, search

#7202 Cleaning up search/views-based migrations.
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20180817120900_AddViewsUsers.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20181220133700_AddViewsAdminRole.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191204000000_RemoveLegacyViewsPermissions.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationHelpers.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191204000000_RemoveLegacyViewsPermissionsTest.java
Labels: bug, ready-for-review, search

#7189 Add pipeline functions to modify lookup tables
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupAddStringList.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupClearKey.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupRemoveStringList.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupSetStringList.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupSetValue.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupStringList.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTable.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupDataAdapter.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupAddStringList.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupClearKey.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupRemoveStringList.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupSetStringList.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupSetValue.txt
Labels: alerting, ready-for-review

#7228 Hide Pagination in PaginatedList when context is not interactive
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/common/PaginatedList.test.jsx
Labels: bug, ready-for-review, search

#7199 Add support to dump the current ProcessBuffer state
  graylog2-server/src/main/java/org/graylog2/rest/models/system/responses/SystemProcessBufferDumpResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemResource.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/ProcessBuffer.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/RemoteSystemResource.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/SystemResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
  graylog2-web-interface/src/components/nodes/NodeMaintenanceDropdown.jsx
  graylog2-web-interface/src/components/nodes/NodesActions.jsx
  graylog2-web-interface/src/pages/ProcessBufferDumpPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/cluster/ClusterOverviewStore.js
Labels: feature, ready-for-review

#7237 Add CSV export to new search
  graylog2-web-interface/src/views/components/searchbar/CSVExportModal.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx
  graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap
  graylog2-web-interface/src/views/logic/NewViewLoaderContext.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
Labels: blocker, search

#7252 Update current view title, summary and description on view edit
  graylog2-web-interface/src/views/logic/views/OnSaveViewAction.js
  graylog2-web-interface/src/views/logic/views/OnSaveViewAction.test.js
  graylog2-web-interface/src/views/stores/ViewStore.js
  graylog2-web-interface/src/views/stores/ViewStore.test.js
Labels: bug, ready-for-review, search

#7255 Monospace Scratchpad
  graylog2-web-interface/src/components/common/Scratchpad.jsx
Labels: ready-for-review, ux

#7268 Clear MessageList error on search execution
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
Labels: bug, ready-for-review, search

#7250 Fix GlobalOverride behavior
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryTest.java
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.js
Labels: ready-for-review, search

#7214 Improving search controls by adding text and dropdown, fixing reset.
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/logic/queries/Query.js
  graylog2-web-interface/src/views/logic/queries/QueryGenerator.js
  graylog2-web-interface/src/views/logic/views/ViewGenerator.js
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/stores/QueryFiltersStore.js
Labels: bug, ready-for-review, search

#7186 Dashboard v1 facade
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/Position.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/Titles.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AggregationConfigDTO.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AutoIntervalDTO.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/PivotDTO.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/TimeHistogramConfigDTO.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/ValueConfigDTO.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardV1Facade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardWidgetConverter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/EntityConverter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/AbsoluteRangeEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/DashboardEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/DashboardWidgetEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/KeywordRangeEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/RelativeRangeEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/TimeRangeEntity.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetConfig.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetEntity.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardV1FacadeTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/facades/DashboardV1FacadeTest.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/facades/dashboardV1/content-pack-dashboard-v1.json
Labels: content-packs, dashboards, ready-for-review, search

#7259 Introduce MongoDBUpsertRetryer
  graylog2-server/src/main/java/org/graylog/events/processor/DBEventProcessorStateService.java
  graylog2-server/src/main/java/org/graylog2/database/MongoDBUpsertRetryer.java
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java
  graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Labels: bug, ready-for-review

#7277 Fix server startup
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/EntityConverter.java
Labels: blocker, bug, ready-for-review

#7234 Bump set-value to 2.0.1
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, security

#7272 Remove not needed CSV export info from upgrading doc
  UPGRADING.rst
Labels: search

#7260 Remove search message count from sidebar
  UPGRADING.rst
  graylog2-web-interface/src/views/components/sidebar/SearchResultOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
Labels: bug, ready-for-review, search

#7278 Close nav item section when clicking on nav item title
  graylog2-web-interface/src/views/components/sidebar/SideBar.jsx
  graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
Labels: improvement, ready-for-review, search

#7274 Avoid global override time range reset on dashboard search execution
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.js
Labels: bug, ready-for-review, search

#7270 Use effective time range from related search type instead of query in MessageList
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageList.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
  graylog2-web-interface/src/views/logic/searchtypes/MessageListHandler.js
Labels: bug, ready-for-review, search

#7290 Conditionally set "gl2_message_id" and use message timestamp
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
Labels: ready-for-review

#7283 Improvements in rendering reports
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/datatable/DataTable.css
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
Labels: ready-for-review

#7293 Use inclusive language in UI for content packs
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
  graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
Labels: ready-for-review

#7045 Bugfix proper Event Notification creation using Content Pack
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/NotificationFacade.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java
Labels: alerting

#7292 Trigger changing widget title on blur.
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
Labels: bug, ready-for-review, search

#7297 Only set data adapters / cache form focus, when related type changes
  graylog2-web-interface/src/components/lookup-tables/CacheForm.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx
Labels: bug

#7291 Unify search and dashboard sidebar
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/QueryBar.jsx
  graylog2-web-interface/src/views/components/QueryTabs.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
Labels: improvement, ready-for-review, search

#7066 Alert variants
  graylog2-web-interface/src/components/graylog/Alert.jsx
  graylog2-web-interface/src/components/graylog/Alert.md
Labels: ready-for-review

#7301 Reload search/dashboard again if id props changes.
  graylog2-web-interface/src/views/pages/ShowViewPage.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
Labels: bug, ready-for-review, search

#7307 Ignore unknown legacy dashboard widget properties.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/FieldChartConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesHistogramConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultChartConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultCountConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedChartConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedSeries.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_superfluous_widget_attributes.json
Labels: bug, ready-for-review, search

#7308 Mock Version.js to avoid failing snaphot tests after version change
  graylog2-web-interface/package.json
  graylog2-web-interface/src/util/DocsHelper.js
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
  graylog2-web-interface/test/mock-Version.js
Labels: bug

#7309 Use HTTPS for documentation links
  graylog2-web-interface/src/util/DocsHelper.js
  graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
Labels: improvement

#7321 Remove incorrect line from UPGRADING.rst
  UPGRADING.rst
Labels: bug, content-packs, good first issue, improvement, ready, ready-for-review, search

#7323 Rotate UPGRADING.rst for 3.3
  UPGRADING.rst
Labels: ready-for-review

#7319 Add JUnit 5 with vintage engine alongside JUnit 4
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  pom.xml
Labels: improvement, infrastructure

#7305 Dashboard widget action dropdown position
  graylog2-web-interface/src/views/components/OverlayDropdown.jsx
  graylog2-web-interface/src/views/components/Value.css
  graylog2-web-interface/src/views/components/Value.jsx
  graylog2-web-interface/src/views/components/actions/ValueActions.jsx
  graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
Labels: search, ux

#7300 Bump serialize-javascript to 2.1.2
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, security

#7320 Increasing jest timeout for integration test.
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
Labels: bug, ready-for-review, search

#7302 Fix default selection for stream output assignment
  graylog2-web-interface/src/components/outputs/AssignOutputDropdown.jsx
Labels: ready-for-review

#7325 Fix blocking issue in DNS lookup data adapter
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClient.java
  graylog2-server/src/main/java/org/graylog2/shared/utilities/ExceptionUtils.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/dnslookup/DnsClientTest.java
  graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java
Labels: ready-for-review

#7327 Show/use view-based dashboards in user/role permissions editor.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/ViewPermissions.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewParameterSummaryDTO.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/ViewPermissionsTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/QualifyingViewsResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/QualifyingViewsServiceTest.java
  graylog2-web-interface/src/components/users/RolesComponent.jsx
  graylog2-web-interface/src/components/users/UserForm.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
Labels: bug, ready-for-review, search

#7328 Show/use view-based dashboards in user/role permissions editor. (3.2)
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/ViewPermissions.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewParameterSummaryDTO.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/ViewPermissionsTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/QualifyingViewsResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/QualifyingViewsServiceTest.java
  graylog2-web-interface/src/components/users/RolesComponent.jsx
  graylog2-web-interface/src/components/users/UserForm.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
Labels: bug, ready-for-review, search

#7333 Backport: Fix blocking issue in DNS lookup data adapter (#7325)
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClient.java
  graylog2-server/src/main/java/org/graylog2/shared/utilities/ExceptionUtils.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/dnslookup/DnsClientTest.java
  graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java
Labels: backport, ready-for-review

#7336 Handling `null` attributes when migrating quickvalues widgets.
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardWidgetConverter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetConfig.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_missing_quickvalues_attributes.json
Labels: bug, ready-for-review, search

#7335 Allow *Create Extractor* for all types
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/bindings.valueActions.test.jsx
Labels: ready-for-review, search, web

#7337 Handling `null` attributes when migrating quickvalues widgets. (3.2)
  graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardWidgetConverter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetConfig.java
  graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_missing_quickvalues_attributes.json
Labels: bug, ready-for-review, search

#7340 Allow *Create Extractor* for all types (3.2)
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/bindings.valueActions.test.jsx
Labels: ready-for-review, search, web

#7068 Update AppFacade to functional component
  graylog2-web-interface/src/routing/AppFacade.jsx
Labels: ready-for-review

#7332 Guard against empty cluster jobs response
  graylog2-web-interface/src/components/systemjobs/SystemJobsComponent.jsx
Labels: ready-for-review
