Repository Graylog2/graylog2-server, pull requests merged in 2020-12, with the labels that each got.

#9506 Extend license formatter for TypeScript
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.test.tsx
  graylog2-web-interface/src/routing/ApiRoutes.d.ts
  graylog2-web-interface/src/stores/StoreTypes.ts
  graylog2-web-interface/src/types.d.ts
  pom.xml
Labels: ready-for-review

#9500 Provide verbose failure support through new AuthServiceRealm
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceAuthenticator.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog2/security/realm/UsernamePasswordRealm.java
Labels: ready-for-review

#9678 Fix missing buttons on SidecarsPage
  graylog2-web-interface/src/pages/SidecarsPage.jsx
Labels: bug, ready-for-review

#9649 Typing `loadAsync` and `react-plotly.js`.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/routing/loadAsync.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
  graylog2-web-interface/src/views/components/SearchBar.tsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
  graylog2-web-interface/src/views/components/searchbar/QueryInput.tsx
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9485 Finish support for multiple LDAP / AD servers
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackendConfig.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackendConfig.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/LDAPConnectorConfig.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
  graylog2-server/src/main/java/org/graylog2/security/DefaultX509TrustManager.java
  graylog2-server/src/main/java/org/graylog2/security/TrustManagerProvider.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTest.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTestTLSIT.java
Labels: ready-for-review

#9632 Removing remaining `$FlowFixMe` comments.
  graylog2-web-interface/src/components/common/Pagination.tsx
  graylog2-web-interface/src/components/graylog/ProgressBar.tsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx
  graylog2-web-interface/src/components/users/UserDetails/RolesSection.tsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.tsx
  graylog2-web-interface/src/theme/colors.ts
  graylog2-web-interface/src/views/bindings.enterpriseWidgets.test.tsx
  graylog2-web-interface/src/views/bindings.fieldActions.test.tsx
  graylog2-web-interface/src/views/bindings.valueActions.test.tsx
  graylog2-web-interface/src/views/components/Search.test.tsx
  graylog2-web-interface/src/views/components/actions/ActionHandler.test.tsx
  graylog2-web-interface/src/views/components/actions/ValueActions.tsx
  graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.tsx
  graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.test.tsx
  graylog2-web-interface/src/views/components/datatable/DataTable.tsx
  graylog2-web-interface/src/views/components/datatable/Headers.test.tsx
  graylog2-web-interface/src/views/components/sidebar/create/AddWidgetButton.tsx
  graylog2-web-interface/src/views/components/views/MissingRequirements.tsx
  graylog2-web-interface/src/views/components/views/View.tsx
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.ts
  graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.tsx
  graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.test.tsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/WidgetFormattingSettings.ts
  graylog2-web-interface/src/views/logic/fieldtypes/FieldTypeFor.test.ts
  graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.test.ts
  graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.ts
  graylog2-web-interface/src/views/logic/parameters/LookupTableParameter.ts
  graylog2-web-interface/src/views/logic/queries/QueryTitle.test.tsx
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.ts
  graylog2-web-interface/src/views/logic/searchtypes/messages/MessageConfigGenerator.test.tsx
  graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.ts
  graylog2-web-interface/src/views/pages/DashboardsPage.tsx
  graylog2-web-interface/src/views/pages/ViewManagementPage.tsx
  graylog2-web-interface/src/views/stores/QueriesStore.test.tsx
  graylog2-web-interface/test/helpers/suppressConsole.ts
Labels: ready-for-review

#9682 Fix missing buttons on SidecarsPage (4.0)
  graylog2-web-interface/src/pages/SidecarsPage.jsx
Labels: backport, bug, ready-for-review

#9686 Support DEVELOPMENT=false
  graylog2-server/src/main/java/org/graylog2/shared/bindings/RestApiBindings.java
Labels: infrastructure, ready-for-review

#9650 Typing `lodash`.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/StepTitleWarning.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/wizardSteps.tsx
  graylog2-web-interface/src/components/common/Wizard.tsx
  graylog2-web-interface/src/components/configurations/DecoratorsConfig.tsx
  graylog2-web-interface/src/routing/ApiRoutes.d.ts
  graylog2-web-interface/src/views/components/datatable/Headers.tsx
  graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.tsx
  graylog2-web-interface/src/views/logic/queries/Query.ts
  graylog2-web-interface/src/views/logic/queries/SearchType.ts
  graylog2-web-interface/src/views/logic/searchtypes/SearchTypesGenerator.test.ts
  graylog2-web-interface/src/views/logic/searchtypes/SearchTypesGenerator.ts
  graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.ts
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9630 Configure babel for `jest-preset-graylog` compilation on build
  graylog2-web-interface/packages/jest-preset-graylog/.babelrc
  graylog2-web-interface/packages/jest-preset-graylog/.gitignore
  graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
  graylog2-web-interface/packages/jest-preset-graylog/package.json
  graylog2-web-interface/packages/jest-preset-graylog/src/mocking/c3_mock.js
  graylog2-web-interface/packages/jest-preset-graylog/src/mocking/fileMock.js
  graylog2-web-interface/packages/jest-preset-graylog/src/mocking/useable-css-proxy.js
  graylog2-web-interface/packages/jest-preset-graylog/src/mocking/useable-css-proxy.test.js
  graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/console-warnings-fail-tests.js
  graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/console-warnings-fail-tests.test.js
  graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/mock-FetchProvider.js
  graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/mock-Version.js
Labels: ready-for-review

#9642 Include microseconds in timestamps.
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.jsx
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.test.tsx
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#9670 Handle Pulsar upstream connectivity issues
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueWriter.java
Labels: ready-for-review

#9699 Fix missing license header in newly commited file
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.test.tsx
Labels: ready-for-review

#9698 Include microseconds in timestamps.
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.jsx
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.test.jsx
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: backport, elasticsearch

#9644 Handling unavailable `searchesClusterConfig`.
  graylog2-web-interface/src/views/components/Search.tsx
Labels: bug, ready-for-review

#9700 Use MessageQueueAcknowledger instead of Journal
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java
  graylog2-server/src/main/java/org/graylog2/outputs/BenchmarkOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/DiscardMessageOutput.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/kafka/KafkaMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  graylog2-server/src/test/java/org/graylog2/messageprocessors/MessageFilterChainProcessorTest.java
Labels: ready-for-review

#9648 Hide sidecars on cloud
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: ready-for-review

#9693 Simplify pulsar processing
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java
  graylog2-server/src/main/java/org/graylog2/outputs/BenchmarkOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/DiscardMessageOutput.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/plugin/journal/RawMessage.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueue.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/kafka/KafkaMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/kafka/KafkaMessageQueueEntry.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/kafka/KafkaMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/kafka/KafkaMessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueEntry.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueWriter.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  graylog2-server/src/test/java/org/graylog2/messageprocessors/MessageFilterChainProcessorTest.java
Labels: ready-for-review

#9459 Verify session against http auth header
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
  graylog2-server/src/main/java/org/graylog2/security/realm/HTTPHeaderAuthenticationRealm.java
  graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java
Labels: ready-for-review, security

#9444 Add startpage to the Settings Section of a user
  graylog2-web-interface/src/actions/streams/StreamsActions.jsx
  graylog2-web-interface/src/components/configurations/DecoratorsConfig.tsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
  graylog2-web-interface/src/components/users/StartpageFormGroup.tsx
  graylog2-web-interface/src/components/users/UserDetails/SettingsSection.tsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.tsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.tsx
  graylog2-web-interface/src/stores/streams/StreamsStore.ts
  graylog2-web-interface/src/stores/users/StartpageStore.js
  graylog2-web-interface/src/views/stores/DashboardsStore.ts
Labels: ready-for-review

#9701 Support for better integration of Token creation from Forwarder wizard
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/graylog/Panel.jsx
  graylog2-web-interface/src/components/users/CreateTokenForm.jsx
  graylog2-web-interface/src/components/users/TokenList.css
  graylog2-web-interface/src/components/users/TokenList.jsx
Labels: ready-for-review

#9717 Align message queue reader classes
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/kafka/KafkaMessageQueueModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessagequeueModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
Labels: ready-for-review

#9566 Implement token-based authentication #9493 (ported)
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceAuthenticator.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceResult.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceToken.java
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthenticationDetails.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/security/StaticOrderedAuthenticatingRealms.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthenticatingRealmModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/BearerTokenRealm.java
  graylog2-server/src/main/java/org/graylog2/security/realm/UsernamePasswordRealm.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java
  graylog2-server/src/main/java/org/graylog2/shared/security/TypedBearerToken.java
Labels: ready-for-review

#9543 DateRange Absolute Limits & Errors
  graylog2-web-interface/src/components/common/DatePicker.jsx
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.jsx
  graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.test.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.jsx.snap
Labels: ready-for-review

#9712 Simplify `TimeoutUnitSelect` by removing no longer needed state handling
  graylog2-web-interface/src/components/users/TimeoutUnitSelect.tsx
Labels: ready-for-review

#9713 Refactor the way we access the `GranteesSelector` state in `EntityShareModal` on save.
  graylog2-web-interface/src/components/permissions/EntityShareModal.tsx
  graylog2-web-interface/src/components/permissions/EntityShareSettings.tsx
  graylog2-web-interface/src/components/permissions/GranteesSelector.test.tsx
  graylog2-web-interface/src/components/permissions/GranteesSelector.tsx
Labels: ready-for-review

#9652 DateTimePicker working and opening properly on Dashboard
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.jsx.snap
Labels: ready-for-review

#9679 Let devServer proxy all "/api" requests to the server API
  graylog2-web-interface/config.js
  graylog2-web-interface/devServer.js
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9731 Fixing user update notification.
  graylog2-web-interface/src/actions/users/UsersActions.ts
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.tsx
  graylog2-web-interface/src/domainActions/users/UsersDomain.ts
Labels: bug, ready-for-review

#9732 Improvements in Token list
  graylog2-web-interface/src/components/users/TokenList.jsx
  graylog2-web-interface/src/components/users/TokenList.test.jsx
  graylog2-web-interface/src/pages/UserTokensEditPage.jsx
Labels: ready-for-review

#9735 Lifecycle handling for Pulsar message queue reader
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/AbstractMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
Labels: ready-for-review

#9716 Make Pulsar service URL configurable
  graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarServiceUrlValidator.java
  graylog2-server/src/test/java/org/graylog2/shared/messageq/pulsar/PulsarServiceUrlValidatorTest.java
Labels: ready-for-review

#9729 Hide nodes page and disable navigation on cloud
  graylog2-web-interface/src/components/common/LinkToNode.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/components/search/MessageDetail.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
Labels: ready-for-review

#9747 Remove div wrapping GlobalThroughput in cloud
  graylog2-web-interface/src/components/navigation/Navigation.jsx
Labels: ready-for-review

#9733 Fixing user update notification
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/domainActions/users/UsersDomain.js
Labels: backport, bug, ready-for-review, users

#9754 Round traffic value on hover in Outgoing traffic chart
  graylog2-web-interface/src/components/cluster/TrafficGraph.tsx
Labels: ready-for-review

#9721 Improving `connect` type inference regarding component `propTypes` and `defaultProps`.
  graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.test.tsx
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.tsx
  graylog2-web-interface/src/stores/__tests__/connect.test.tsx
  graylog2-web-interface/src/stores/connect.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.tsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.tsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.tsx
Labels: ready-for-review

#9748 Date Time Picker variable renaming
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/visualizations/OnZoom.ts
  graylog2-web-interface/src/views/stores/GlobalOverrideStore.ts
  graylog2-web-interface/src/views/stores/QueriesStore.ts
Labels: ready-for-review

#8340 Fix `ActionDropdown` toggle on child select, if child is wrapped in another element
  graylog2-web-interface/src/views/components/common/ActionDropdown.test.tsx
  graylog2-web-interface/src/views/components/common/ActionDropdown.tsx
Labels: ready-for-review, search

#9757 Always show field sort icons in message table.
  graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx
  graylog2-web-interface/src/views/components/widgets/MessageList.tsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.test.tsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
Labels: ready-for-review

#9749 DateTimePicker Apply Button validation
  graylog2-web-interface/src/views/Constants.ts
  graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx
  graylog2-web-interface/src/views/components/SearchBar.tsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
  graylog2-web-interface/src/views/components/__snapshots__/SearchBar.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/DisabledTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteRangeField.test.jsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.jsx.snap
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
Labels: ready-for-review

#9764 Fixing `MessageList` constructor signature.
  graylog2-web-interface/src/views/components/widgets/MessageList.tsx
Labels: ready-for-review

#9763 Fix Docker bind mounts for resources inside of JAR files
  graylog2-server/src/test/java/org/graylog/testing/ResourceUtil.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/ResourceUtil.java
  graylog2-server/src/test/java/org/graylog/testing/ldap/LDAPTestUtils.java
  graylog2-server/src/test/java/org/graylog/testing/ldap/OpenLDAPContainer.java
Labels: ready-for-review

#9770 Fix version probe for ES snapshot versions
  graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java
Labels: ready-for-review

#9489 Move DEFAULT_PAGINATION to central point
  graylog2-web-interface/src/stores/PaginationTypes.ts
  graylog2-web-interface/src/util/URLUtils.js
Labels: ready-for-review, web

#9765 Date Time Picker DashboardSearchForm validation
  graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
Labels: ready-for-review

#9776 Always show field sort icons in message table. (3.3)
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx
Labels: ready-for-review

#9775 Always show field sort icons in message table. (4.0)
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx
Labels: ready-for-review

#9768 Only disable `SearchButton` when appropriate
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Labels: ready-for-review

#9785 Fix deserialization of incomplete AlertReceivers objects
  graylog2-server/src/main/java/org/graylog2/rest/models/alarmcallbacks/requests/AlertReceivers.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
Labels: ready-for-review

#9774 Remove remaining eslint-disable-camelcase comments
  graylog2-web-interface/src/stores/PaginationTypes.ts
  graylog2-web-interface/src/stores/nodes/NodesStore.ts
  graylog2-web-interface/src/stores/streams/StreamsStore.ts
Labels: ready-for-review

#9792 Sync cloud-4.0 branch with latest changes in 4.0
  graylog2-web-interface/.gitignore
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/domainActions/users/UsersDomain.js
  graylog2-web-interface/src/pages/SidecarsPage.jsx
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.jsx
  graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.jsx
  graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
  graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx
  graylog2-web-interface/webpack/vendor-module-ids.json
Labels: ready-for-review

#9783 Hide API browser and API docs when running on cloud
  graylog2-server/src/main/java/org/graylog2/jersey/PrefixAddingModelProcessor.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/HideOnCloud.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java
  graylog2-server/src/test/java/org/graylog2/jersey/PrefixAddingModelProcessorTest.java
Labels: ready-for-review

#9784 Update Absolute time inputs to use number instead of text
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteRangeField.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.tsx.snap
Labels: ready-for-review

#9805 Fix order of tabs in dashboard after install
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java
  graylog2-web-interface/src/views/stores/QueryIdsStore.js
  graylog2-web-interface/src/views/stores/ViewStore.test.ts
  graylog2-web-interface/src/views/stores/ViewStore.ts
Labels: ready-for-review, search

#9804 Unblock JobSchedulerService on shutdown
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java
  graylog2-server/src/main/java/org/graylog2/plugin/ServerStatus.java
Labels: ready-for-review

#9812 Fix order of tabs in dashboard after install
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java
  graylog2-web-interface/src/views/stores/QueryIdsStore.js
  graylog2-web-interface/src/views/stores/ViewStore.js
  graylog2-web-interface/src/views/stores/ViewStore.test.js
Labels: backport, ready-for-review, search

#9814 Show timezone setting to the user
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
Labels: ready-for-review, users

#9808 Add isCloud helper method on plugin module
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
Labels: ready-for-review

#9821 Add common Okta version to parent POM
  pom.xml
Labels: ready-for-review

#9711 Focus widget
  graylog2-web-interface/src/views/bindings.fieldActions.test.tsx
  graylog2-web-interface/src/views/bindings.tsx
  graylog2-web-interface/src/views/components/Query.test.jsx
  graylog2-web-interface/src/views/components/Query.tsx
  graylog2-web-interface/src/views/components/Search.test.tsx
  graylog2-web-interface/src/views/components/Search.tsx
  graylog2-web-interface/src/views/components/SearchResult.test.jsx
  graylog2-web-interface/src/views/components/SearchResult.tsx
  graylog2-web-interface/src/views/components/WidgetComponent.tsx
  graylog2-web-interface/src/views/components/WidgetGrid.jsx
  graylog2-web-interface/src/views/components/actions/ActionHandler.test.tsx
  graylog2-web-interface/src/views/components/actions/ActionHandler.tsx
  graylog2-web-interface/src/views/components/actions/FieldActions.tsx
  graylog2-web-interface/src/views/components/actions/ValueActions.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusContext.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.tsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.tsx
  graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.tsx
  graylog2-web-interface/src/views/components/defaultTitle.ts
  graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.tsx
  graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.tsx.snap
Labels: search

#9829 Modify text color to properly render readable text
  graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.tsx
  graylog2-web-interface/src/views/components/messagelist/Highlight.test.tsx
  graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.tsx
  graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.tsx.snap
  graylog2-web-interface/src/views/components/messagelist/__snapshots__/Highlight.test.tsx.snap
Labels: improvement, ready-for-review
