Repository Graylog2/graylog2-server, pull requests merged in 2020-10, with the labels that each got.

#9052 Update browserslist DB.
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9053 Update browserslist DB.
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9048 Unify wizard navigation style
  graylog2-web-interface/src/components/common/Wizard.jsx
  graylog2-web-interface/src/components/common/Wizard.test.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
Labels: improvement, ready-for-review

#9059 Add error prop for `Input` to be able to display an error message together with the input help text
  graylog2-web-interface/src/components/bootstrap/Input.jsx
  graylog2-web-interface/src/components/bootstrap/Input.test.jsx
  graylog2-web-interface/src/components/common/FormikInput.jsx
  graylog2-web-interface/src/components/common/InputDescription.jsx
  graylog2-web-interface/src/components/common/InputDescription.test.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx
Labels: improvement, ready-for-review

#9035 Implementing compression for Elasticsearch 7.
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
Labels: elasticsearch, ready-for-review

#9049 Install formik as a vendor module
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9085 Stop pivot config form submit event propagation.
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.test.jsx
Labels: bug, ready-for-review, search

#9067 Add ownership check to saved search/dashboard permission checks.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewPermissionChecksTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
Labels: bug, ready-for-review, search

#9095 Stop pivot config form submit event propagation.
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.test.jsx
Labels: bug, ready-for-review

#9088 Updating to @testing-library/react v11.0.4.
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9082 Check password length of user creation before submit
  graylog2-web-interface/src/components/users/UserCreate/PasswordFormGroup.jsx
Labels: ready-for-review, users, ux

#9096 Prevent unintended search bar form submit in widget edit modal
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.test.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx
Labels: bug, ready-for-review, search

#9101 Add ownership check to saved search/dashboard permission checks. (3.3)
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewPermissionChecksTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
Labels: bug, ready-for-review

#9032 Abstract all `params` usages in HOC.
  graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx
  graylog2-web-interface/src/pages/AuthenticationPage.jsx
  graylog2-web-interface/src/pages/CreateExtractorsPage.jsx
  graylog2-web-interface/src/pages/EditAlertConditionPage.jsx
  graylog2-web-interface/src/pages/EditContentPackPage.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EditExtractorsPage.jsx
  graylog2-web-interface/src/pages/EditTokensPage.jsx
  graylog2-web-interface/src/pages/EditUsersPage.jsx
  graylog2-web-interface/src/pages/ExportExtractorsPage.jsx
  graylog2-web-interface/src/pages/ExtractorsPage.jsx
  graylog2-web-interface/src/pages/ImportExtractorsPage.jsx
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
  graylog2-web-interface/src/pages/IndexSetPage.jsx
  graylog2-web-interface/src/pages/LUTCachesPage.jsx
  graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx
  graylog2-web-interface/src/pages/LUTTablesPage.jsx
  graylog2-web-interface/src/pages/NodeInputsPage.jsx
  graylog2-web-interface/src/pages/PipelineDetailsPage.jsx
  graylog2-web-interface/src/pages/ProcessBufferDumpPage.jsx
  graylog2-web-interface/src/pages/RuleDetailsPage.jsx
  graylog2-web-interface/src/pages/ShowAlertPage.jsx
  graylog2-web-interface/src/pages/ShowContentPackPage.jsx
  graylog2-web-interface/src/pages/ShowMessagePage.jsx
  graylog2-web-interface/src/pages/ShowMetricsPage.jsx
  graylog2-web-interface/src/pages/ShowNodePage.jsx
  graylog2-web-interface/src/pages/SidecarEditCollectorPage.jsx
  graylog2-web-interface/src/pages/SidecarEditConfigurationPage.jsx
  graylog2-web-interface/src/pages/SidecarStatusPage.jsx
  graylog2-web-interface/src/pages/StreamAlertsOverviewPage.jsx
  graylog2-web-interface/src/pages/StreamEditPage.jsx
  graylog2-web-interface/src/pages/StreamOutputsPage.jsx
  graylog2-web-interface/src/pages/ThreadDumpPage.jsx
  graylog2-web-interface/src/routing/withParams.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
Labels: ready-for-review

#9063 Refactor Search Page Components.
  graylog2-web-interface/src/views/Constants.js
  graylog2-web-interface/src/views/bindings.jsx
  graylog2-web-interface/src/views/components/Search.jsx
  graylog2-web-interface/src/views/components/Search.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.jsx
  graylog2-web-interface/src/views/logic/NewViewLoaderContext.jsx
  graylog2-web-interface/src/views/logic/ViewLoaderContext.jsx
  graylog2-web-interface/src/views/logic/usePluginEntities.jsx
  graylog2-web-interface/src/views/logic/views/Actions.js
  graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.js
  graylog2-web-interface/src/views/logic/views/UseLoadView.js
  graylog2-web-interface/src/views/logic/views/UseViewLoader.js
  graylog2-web-interface/src/views/logic/views/ViewState.js
  graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
  graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
  graylog2-web-interface/src/views/pages/NewSearchRedirectPage.jsx
  graylog2-web-interface/src/views/pages/SearchPage.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.test.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx
  graylog2-web-interface/src/views/pages/index.js
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
Labels: ready-for-review

#9114 Use abstraction instead of `browserHistory`.
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.jsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
  graylog2-web-interface/src/views/logic/views/Actions.js
Labels: ready-for-review

#9113 Add explanation for disabled share buttons
  graylog2-web-interface/src/components/common/HoverForHelp.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/permissions/SharingDisabledPopover.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/BarVisualizationConfiguration.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/HoverForHelp.jsx
  graylog2-web-interface/src/views/components/aggregationbuilder/NumberVisualizationConfiguration.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
  graylog2-web-interface/src/views/components/views/ViewList.jsx
Labels: ready-for-review

#9107 Bulk update roles
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/components/permissions/RolesSelector.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.test.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
  graylog2-web-interface/src/components/users/UserCreate/PasswordFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
  graylog2-web-interface/src/domainActions/roles/AuthzRolesDomain.js
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/test/fixtures/userOverviews.jsx
  graylog2-web-interface/test/fixtures/users.js
Labels: ready-for-review

#9115 Prevent unintended search bar form submit in widget edit modal (port of #9096)
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.test.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx
Labels: bug, ready-for-review, search

#9027 Fix Typeahead input background color
  graylog2-web-interface/src/components/common/TypeAheadInput.jsx
Labels: bug, improvement, ready-for-review

#8952 Add grants support for EventNotifications
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/NotificationFacade.java
  graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlertConditionMigrator.java
  graylog2-server/src/main/java/org/graylog/events/notifications/DBNotificationService.java
  graylog2-server/src/main/java/org/graylog/events/notifications/NotificationResourceHandler.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java
  graylog2-server/src/main/java/org/graylog/grn/providers/EventNotificationGRNDescriptorProvider.java
  graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
  graylog2-web-interface/src/pages/EventNotificationsPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
Labels: ready-for-review

#9065 Retry indexing message if primary shard is not active
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchException.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchExceptionTest.java
Labels: elasticsearch, ready-for-review

#9094 Fix handling for health of empty indices in ES7.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
Labels: elasticsearch, ready-for-review

#9116 Prevent NPEs if streams are referencing missing outputs.
  graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
Labels: bug, ready-for-review

#9070 Migrate user permissions into grants
  graylog2-server/src/main/java/org/graylog/security/Capability.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/RolesToGrantsMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnerShipToGrantsMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewSharingToGrantsMigration.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/RolesToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/TestUserService.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnershipToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewSharingToGrantsMigrationTest.java
  graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_GrantsMigrations/MigrateUserPermissionsToGrantsTest.json
  graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_GrantsMigrations/V20200803120800_MigrateRolesToGrantsTest.json
  graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_GrantsMigrations/view-ownership.json
  graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_GrantsMigrations/view-sharings.json
Labels: ready-for-review

#9121 Sync cloud branch with current 3.3 branch
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewPermissionChecksTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.jsx
  graylog2-web-interface/src/views/components/common/EditableTitle.test.jsx
  graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx
  integration-tests/pom.xml
  pom.xml
Labels: ready-for-review

#9122 Removing `deep-equal` from dependencies.
  graylog2-web-interface/package.json
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9109 Update LDAP auth service configuration
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackendConfig.java
  graylog2-web-interface/src/components/authentication/BackendWizard/BackendWizard.jsx
  graylog2-web-interface/src/components/authentication/BackendWizard/ServerConfigStep.jsx
  graylog2-web-interface/src/components/authentication/BackendWizard/contexts/BackendWizardContext.jsx
  graylog2-web-interface/src/components/authentication/activeDirectory/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/ldap/BackendConfigDetails/ServerConfigSection.jsx
  graylog2-web-interface/src/components/authentication/ldap/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/ldap/BackendEdit.jsx
  graylog2-web-interface/src/logic/authentication/ldap/LdapConfigParser.jsx
  graylog2-web-interface/src/logic/authentication/ldap/types.js
Labels: ready-for-review

#9118 Abstract `location` usage from `react-router`.
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/pages/AuthenticationPage.jsx
  graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/CreateEventNotificationPage.jsx
  graylog2-web-interface/src/pages/CreateExtractorsPage.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
  graylog2-web-interface/src/pages/GettingStartedPage.jsx
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
  graylog2-web-interface/src/pages/LUTCachesPage.jsx
  graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx
  graylog2-web-interface/src/pages/LUTTablesPage.jsx
  graylog2-web-interface/src/pages/NewAlertConditionPage.jsx
  graylog2-web-interface/src/pages/NewAlertNotificationPage.jsx
  graylog2-web-interface/src/pages/ShowMetricsPage.jsx
  graylog2-web-interface/src/pages/SidecarAdministrationPage.jsx
  graylog2-web-interface/src/pages/StreamEditPage.jsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.jsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.jsx
  graylog2-web-interface/src/routing/withLocation.js
  graylog2-web-interface/src/views/components/Search.jsx
  graylog2-web-interface/src/views/components/Search.test.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.test.jsx
  graylog2-web-interface/src/views/components/common/WindowLeaveMessage.jsx
  graylog2-web-interface/src/views/components/messagelist/HighlightMessageInQuery.jsx
  graylog2-web-interface/src/views/components/messagelist/HighlightMessageInQuery.test.jsx
  graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.js
  graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.test.js
  graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
  graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.jsx
  graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
  graylog2-web-interface/src/views/pages/SearchPage.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.jsx
  graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.test.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.jsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx
Labels: ready-for-review

#9105 Hide CSV Adapter in cloud instances
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
Labels: ready-for-review

#9144 Sync cloud branch after 3.3.8 release
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  integration-tests/pom.xml
  pom.xml
Labels: ready-for-review

#9145 Fixing dialog shown when abandoning changes on current page.
  graylog2-web-interface/src/components/common/ConfirmLeaveDialog.jsx
  graylog2-web-interface/src/components/common/ConfirmLeaveDialog.test.jsx
Labels: bug, ready-for-review

#9143 IdP management naming improvements
  graylog2-web-interface/src/actions/ldap/LdapActions.js
  graylog2-web-interface/src/actions/ldap/LdapGroupsActions.js
  graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedTeamsSection.jsx
  graylog2-web-interface/src/components/authentication/bindings.js
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ConnectionErrors.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/GroupSyncStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConnectionTest.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/Sidebar.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/StepTitleWarning.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserLoginTest.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserSyncStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/index.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/wizardSteps.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendEdit.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/WizardPageHeader.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/BackendConfigDetails.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/EditLinkButton.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/GroupSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/ServerConfigSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/UserSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/index.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/WizardPageHeader.jsx
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/logic/authentication/directoryServices/BackendConfigParser.jsx
  graylog2-web-interface/src/logic/authentication/directoryServices/types.js
  graylog2-web-interface/src/stores/ldap/LdapGroupsStore.js
  graylog2-web-interface/src/stores/ldap/LdapStore.js
  graylog2-web-interface/src/util/AuthenticationService.js
Labels: improvement, ready-for-review

#9146 Re-register authentication components.
  graylog2-web-interface/src/pages/AuthenticationPage.jsx
Labels: bug, ready-for-review

#9151 Revert "Bump webpack-merge (#9111)"
  graylog2-web-interface/packages/graylog-web-plugin/package.json
Labels: ready-for-review

#9152 Collection of improvements for permissions and authentication management
  graylog2-web-interface/src/components/authentication/BackendDetails/BackendDetails.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/BackendDetailsActive.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedTeamsSection.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedUsersSection/SyncedUsersOverviewItem.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedUsersSection/SyncedUsersSection.jsx
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverviewItem.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/GroupSyncStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserSyncStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/wizardSteps.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendEdit.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/BackendConfigDetails.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/GroupSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/UserSyncSection.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx
  graylog2-web-interface/src/components/common/EnterprisePluginNotFound.jsx
  graylog2-web-interface/src/components/common/Pagination.jsx
  graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/permissions/RolesCell.jsx
  graylog2-web-interface/src/components/users/UserDetails/TeamsSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/TeamsSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/UsersOverviewItem.jsx
  graylog2-web-interface/src/logic/users/UserOverview.js
  graylog2-web-interface/src/util/DocsHelper.js
  graylog2-web-interface/test/fixtures/userOverviews.jsx
Labels: ready-for-review

#9161 Don't create User objects with random objectIDs
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: blocker, ready-for-review

#9160 Only run GrantsMigrations once
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnerShipToGrantsMigration.java
Labels: ready-for-review

#9168 Fix JUnit5 vintage engine by updating to v5.7.0.
  pom.xml
Labels: ready-for-review

#9167 Prevent devision by 0 if PaginatedList pageSize prop is 0
  graylog2-web-interface/src/components/common/PaginatedList.jsx
  graylog2-web-interface/src/components/common/PaginatedList.test.jsx
Labels: bug, ready-for-review

#9169 Remove IntelliJ's `@NotNull` annotations.
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendQueryStringDecoratorsTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendQueryStringDecoratorsTest.java
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
  graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java
Labels: ready-for-review

#9170 Declare custom ES image as compatible w/ testcontainers.
  graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
Labels: ready-for-review

#9158 Updating `webpack-cli` to v4.
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9172 Correct typo on SystemAdminOverview page
  graylog2-web-interface/src/components/users/UsersOverview/SystemAdministratorOverview.jsx
Labels: bug, triaged, ux

#9164 Fix permissions UI console warnings
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx
  graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.jsx
  graylog2-web-interface/src/pages/AuthenticationOverviewPage.jsx
  graylog2-web-interface/src/pages/AuthenticationPage.jsx
Labels: ready-for-review

#9179 Merge GrantsAuthorizingRealm and MongoDbAuthorizationRealm
  graylog2-server/src/main/java/org/graylog/security/GrantsAuthorizingRealm.java
  graylog2-server/src/main/java/org/graylog2/security/realm/AuthorizationOnlyRealmModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
Labels: ready-for-review

#9166 Display Alert instead of plain text for empty lists and tables on permissions pages
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedUsersSection/SyncedUsersSection.jsx
  graylog2-web-interface/src/components/common/DataTable/DataTable.jsx
  graylog2-web-interface/src/components/common/EmptyResult.jsx
  graylog2-web-interface/src/components/common/EmptySearchResult.jsx
  graylog2-web-interface/src/components/common/PaginatedItemOverview/PaginatedItemOverview.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/roles/RoleDetails/UsersSection.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
  graylog2-web-interface/src/components/users/UserDetails/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersFilter.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Labels: improvement, ready-for-review

#9184 Add missing EventNotificationGRNDescriptorProvider
  graylog2-server/src/main/java/org/graylog/grn/GRNModule.java
  graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java
  graylog2-web-interface/src/logic/permissions/GRN.js
Labels: ready-for-review

#9189 Refactor repeated code block into method
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationModelData.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
Labels: improvement, ready-for-review

#9177 Skip scheduled index field type poller run if server is not running.
  graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
  graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
Labels: bug, ready-for-review

#9178 Fix message id field alias migration for non-existing indices.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsES7IT.java
Labels: bug, ready-for-review

#9198 Rename EventNotification GRNType
  graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java
Labels: bug, ready-for-review

#9188 Fix plugin routes with `null` parent components.
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/AppRouter.test.jsx
Labels: bug, ready-for-review

#9190 Avoid creating style component inline.
  graylog2-web-interface/src/components/errors/ErrorPage.jsx
Labels: bug, ready-for-review

#9165 Expose `isCloud` to frontend
  graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
  graylog2-server/src/main/resources/web-interface/config.js.template
  graylog2-web-interface/config.js
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/util/AppConfig.js
  graylog2-web-interface/webpack.combined.config.js
  graylog2-web-interface/webpack.config.js
Labels: ready-for-review

#9206 Rename EventNotification GRNType in frontend
  graylog2-web-interface/src/logic/permissions/GRN.js
Labels: ready-for-review

#9209 Use activeShares as a fallback for the dependency permission check
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyPermissionChecker.java
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
Labels: ready-for-review

#9136 Fix potential security vulnerabilities from JS dependencies
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9171 Remove permission from whitelist check
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/UrlWhitelistResource.java
  graylog2-web-interface/src/components/common/URLWhiteListFormModal.jsx
Labels: ready-for-review

#9210 Publish a UserDeletedEvent on user deletion
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/users/events/UserDeletedEvent.java
Labels: ready-for-review

#9202 Fix AuthenticationBackendEditPage url query handling
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/EditLinkButton.jsx
  graylog2-web-interface/src/pages/AuthenticationBackendEditPage.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: bug, ready-for-review

#9196 Fix vertical scrolling for search sidebar content column
  graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.jsx
  graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
Labels: bug, ready-for-review

#9205 Fix missing dependency warning in entity share modal
  graylog2-web-interface/src/components/permissions/DependenciesWarning.jsx
  graylog2-web-interface/src/components/permissions/EntityShareModal.test.jsx
  graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx
  graylog2-web-interface/src/logic/permissions/EntityShareState.js
  graylog2-web-interface/src/logic/permissions/EntityShareState.test.js
  graylog2-web-interface/src/logic/permissions/__snapshots__/EntityShareState.test.js.snap
Labels: bug, ready-for-review

#9218 Rename GrantPermissionResolver to PermissionAndRoleResolver
  graylog2-server/src/main/java/org/graylog/security/DefaultPermissionAndRoleResolver.java
  graylog2-server/src/main/java/org/graylog/security/PermissionAndRoleResolver.java
  graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
  graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: ready-for-review

#9220 Add /authz/grants-overview endpoint
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/rest/GrantsOverviewResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Labels: ready-for-review

#9221 Implement share dialog and details pages for event notifications
  graylog2-web-interface/src/components/event-notifications/event-notification-details/EmailNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-details/EventNotificationActionLinks.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-details/EventNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-details/LegacyNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
  graylog2-web-interface/src/pages/ShowEventNotificationPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: ready-for-review

#9216 Event definition share dialog
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionValidationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
  graylog2-web-interface/src/pages/EventNotificationsPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.jsx
  graylog2-web-interface/src/pages/ViewEventDefinitionPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
Labels: alerting, ready-for-review

#9226 Fix route to user tokens page
  graylog2-web-interface/src/pages/SidecarsPage.jsx
Labels: blocker, ready-for-review

#9227 Remove view userpermission
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/GrantChangedEvent.java
  graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/RolesToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnershipToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewSharingToGrantsMigrationTest.java
Labels: ready-for-review

#9230 Don't sign any artifacts in the distribution module
  distribution/pom.xml
Labels: ready-for-review

#9231 Revert jar -> pom packaging change in distribution
  distribution/pom.xml
Labels: ready-for-review

#9232 Downgrading webpack-cli to v3.3.12.
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9233 Fix field types of current query if no stream is selected.
  graylog2-web-interface/src/views/components/Search.jsx
  graylog2-web-interface/src/views/stores/FieldTypesStore.js
  graylog2-web-interface/src/views/stores/QueryFiltersStore.js
Labels: bug, ready-for-review

#9197 Update type definitions for AuthenticationActions, AuthzRolesActions, and UsersActions
  graylog2-web-interface/src/actions/authentication/AuthenticationActions.js
  graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/authentication/BackendDetails/BackendDetails.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/BackendDetailsActive.jsx
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedUsersSection/SyncedUsersSection.jsx
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserLoginTest.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx
  graylog2-web-interface/src/components/authentication/useActiveBackend.js
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationFormContainer.jsx
  graylog2-web-interface/src/components/permissions/RolesSelector.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/domainActions/notifyingAction.js
  graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.jsx
  graylog2-web-interface/src/pages/AuthenticationBackendEditPage.jsx
  graylog2-web-interface/src/pages/UserTokensEditPage.jsx
  graylog2-web-interface/src/stores/authentication/AuthenticationStore.js
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/src/stores/users/UsersStore.js
Labels: improvement, ready-for-review

#9097 Moving Date Picker to Popover
  graylog2-web-interface/.eslintrc.json
  graylog2-web-interface/flow-typed/npm/formik_v2.x.x.js
  graylog2-web-interface/src/stores/tools/ToolsStore.js
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/SearchBar.jsx
  graylog2-web-interface/src/views/components/TimerangeForForm.js
  graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
  graylog2-web-interface/src/views/components/searchbar/RefreshControls.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideTypeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeMenuItems.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/DisabledTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimerangeSelector.jsx
  graylog2-web-interface/src/views/logic/queries/Query.js
Labels: ready-for-review

#9255 Add a new notification type for input shutdown due to failures.
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
Labels: enterprise, feature, ready-for-review

#9269 Fix the shareable link copy button
  graylog2-web-interface/src/components/permissions/ShareableEnityURL.jsx
Labels: ready-for-review, users

#9257 Saved Search: Hide Save button for missing edit perissions
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
Labels: ready-for-review, search

#9125 DateTimePicker Live Preview
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.jsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.jsx
Labels: ready-for-review

#9223 Offer GIM as a template option for index set configs.
  graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping6.java
  graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping7.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
  graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java
  graylog2-server/src/test/java/org/graylog2/indexer/GIMMapping6Test.java
  graylog2-server/src/test/java/org/graylog2/indexer/GIMMapping7Test.java
  graylog2-server/src/test/java/org/graylog2/indexer/GIMMappingTest.java
  graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template6.json
  graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template7.json
Labels: ready-for-review

#9258 Display Finish & Save button for the directory service group sync step if no enterprise plugin exists
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/GroupSyncStep.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/wizardSteps.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendEdit.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx
Labels: bug, ready-for-review

#9204 Show friendlier page when user has no stream access.
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.jsx
  graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
Labels: ready-for-review

#9277 Fix active backend fetching on authentication pages
  graylog2-web-interface/src/components/authentication/useActiveBackend.js
Labels: bug, ready-for-review

#9272 Display correct sharable URL on entity overview pages
  graylog2-web-interface/src/components/permissions/EntityShareModal.test.jsx
  graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx
  graylog2-web-interface/src/components/permissions/ShareableEntityURL.jsx
  graylog2-web-interface/src/logic/permissions/GRN.js
Labels: bug, ready-for-review

#9279 Fix session activity indicator for users
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/security/MongoDbSession.java
Labels: ready-for-review

#9280 Deprecation notices for Legacy Alarm Callbacks
  graylog2-server/src/main/java/org/graylog2/alarmcallbacks/EmailAlarmCallback.java
  graylog2-server/src/main/java/org/graylog2/alarmcallbacks/HTTPAlarmCallback.java
  graylog2-server/src/test/java/org/graylog2/alarmcallbacks/HTTPAlarmCallbackTest.java
  graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
Labels: improvement, ready-for-review, ux

#9281 Use proper colors for pie chart outer labels
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
Labels: bug, ready-for-review

#9273 Prevent empty string in directory service update and create password payload
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
Labels: bug, ready-for-review

#9225 Implement PaginatedDataTable component
  graylog2-web-interface/src/components/common/DataTable/DataTable.jsx
  graylog2-web-interface/src/components/common/DataTable/Filter.jsx
  graylog2-web-interface/src/components/common/PaginatedDataTable/Filter.jsx
  graylog2-web-interface/src/components/common/PaginatedDataTable/PaginatedDataTable.jsx
  graylog2-web-interface/src/components/common/PaginatedDataTable/index.js
  graylog2-web-interface/src/components/common/TypeAheadDataFilter.jsx
  graylog2-web-interface/src/components/common/index.jsx
Labels: ready-for-review

#9256 Don't expose shares with invisible grantees
  graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
  graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
  graylog2-server/src/test/resources/org/graylog/security/shares/EntitySharesServiceTest.json
Labels: ready-for-review

#9289 Add deleteForGrantee() to DBGrantService
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
Labels: ready-for-review

#9275 Check periodically if running ES is compatible with initial ES version.
  graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
  graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
  graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java
  graylog2-server/src/main/java/org/graylog2/storage/VersionAwareProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/providers/ElasticsearchVersionProvider.java
  graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java
  graylog2-server/src/test/java/org/graylog2/periodical/ESVersionCheckPeriodicalTest.java
  graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
  graylog2-web-interface/src/util/DocsHelper.js
Labels: ready-for-review

#9285 Ensure a user has at least reader or admin role
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
Labels: ready-for-review, users

#9286 Provide active className for Buttons wrapped with LinkContainer if link target equals current pathname
  graylog2-web-interface/src/components/graylog/router.jsx
  graylog2-web-interface/src/components/rules/Rule.jsx
  graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
  graylog2-web-interface/src/pages/EventNotificationsPage.jsx
  graylog2-web-interface/src/pages/EventsPage.jsx
  graylog2-web-interface/src/pages/LUTCachesPage.jsx
  graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx
  graylog2-web-interface/src/pages/LUTTablesPage.jsx
  graylog2-web-interface/src/pages/PipelineDetailsPage.jsx
  graylog2-web-interface/src/pages/PipelinesOverviewPage.jsx
  graylog2-web-interface/src/pages/RulesPage.jsx
  graylog2-web-interface/src/pages/ShowAlertPage.jsx
  graylog2-web-interface/src/pages/SidecarAdministrationPage.jsx
  graylog2-web-interface/src/pages/SidecarConfigurationPage.jsx
  graylog2-web-interface/src/pages/SidecarsPage.jsx
  graylog2-web-interface/src/pages/SimulatorPage.jsx
Labels: bug, ready-for-review

#9292 Remove Jetbrains NotNull annotation
  graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
  graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java
Labels: ready-for-review

#9294 Return correct PaginatedList results
  graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
  graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
Labels: ready-for-review

#9287 Per request authorization cache
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/GrantChangedEvent.java
  graylog2-server/src/main/java/org/graylog/util/uuid/ConcurrentUUID.java
  graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
  graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/rest/RequestIdFilter.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroRequestHeadersBinder.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityContextFilter.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/RolesToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnershipToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewSharingToGrantsMigrationTest.java
Labels: ready-for-review

#9293 Do not disable user create submit button on server error
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
Labels: bug, ready-for-review

#9290 Display entity share buttons next to entity action menu
  graylog2-web-interface/src/components/common/HoverForHelp.jsx
  graylog2-web-interface/src/components/common/ShareButton.jsx
  graylog2-web-interface/src/components/common/ShareButton.test.jsx
  graylog2-web-interface/src/components/common/index.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/permissions/EntityShareModal.jsx
  graylog2-web-interface/src/components/permissions/SharingDisabledPopover.jsx
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/components/streams/StreamControls.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
  graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
  graylog2-web-interface/src/views/components/views/ViewList.jsx
Labels: improvement, ready-for-review

#9297 Display info about permissions update on user edit and details page
  graylog2-web-interface/src/components/users/PermissionsUpdateInfo.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/util/DocsHelper.js
Labels: improvement, ready-for-review

#9217 Use user ID instead of username for user management API calls
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/shared/users/UserService.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog/testing/TestUserService.java
  graylog2-web-interface/src/actions/permissions/EntityShareActions.js
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedUsersSection/SyncedUsersOverviewItem.jsx
  graylog2-web-interface/src/components/navigation/Navigation.jsx
  graylog2-web-interface/src/components/navigation/Navigation.test.jsx
  graylog2-web-interface/src/components/navigation/UserMenu.jsx
  graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
  graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
  graylog2-web-interface/src/components/users/UserManagementLinks.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/UsersOverviewItem.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
  graylog2-web-interface/src/components/users/navigation/UserActionLinks.jsx
  graylog2-web-interface/src/domainActions/permissions/EntityShareDomain.js
  graylog2-web-interface/src/domainActions/users/UsersDomain.js
  graylog2-web-interface/src/pages/UserDetailsPage.jsx
  graylog2-web-interface/src/pages/UserEditPage.jsx
  graylog2-web-interface/src/pages/UserTokensEditPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/Routes.jsx
  graylog2-web-interface/src/stores/permissions/EntityShareStore.js
  graylog2-web-interface/src/stores/users/CurrentUserStore.jsx
  graylog2-web-interface/src/stores/users/UsersStore.js
  graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
Labels: API change, ready-for-review

#9300 Display info about permissions update on roles overview page
  graylog2-web-interface/src/pages/RolesOverviewPage.jsx
Labels: improvement, ready-for-review

#9162 DateTimePicker Relative Time Range
  graylog2-web-interface/src/components/configurations/SearchesConfig.jsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.test.jsx
  graylog2-web-interface/src/views/components/SearchBar.test.jsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/DisabledTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.test.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.jsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimerangeSelector.jsx
Labels: ready-for-review

#9303 Add target as href to `LinkContainer` children.
  graylog2-web-interface/src/components/graylog/LinkContainer.test.jsx
  graylog2-web-interface/src/components/graylog/router.jsx
  graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.test.jsx
Labels: bug, ready-for-review

#9295 Make view permission check methods public.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
Labels: ready-for-review

#9311 Fixing logo floating away and failing test on master
  graylog2-web-interface/src/components/navigation/NavigationBrand.jsx
  graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
Labels: bug, improvement, ready-for-review

#9299 Trim string of username when creating a user
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
Labels: ready-for-review, users

#9314 Use gray to display a logged of user
  graylog2-web-interface/src/components/users/LoggedInIcon.jsx
Labels: ready-for-review, users, ux

#9288 Run against ES7 in full backend tests as well.
  full-backend-tests/pom.xml
  full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2E.java
  full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2EES6.java
  full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2EES7.java
  full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceES6IT.java
  full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceES7IT.java
  full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceIT.java
  full-backend-tests/src/test/java/org/graylog/storage/elasticsearch7/ElasticsearchInstanceES7Factory.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/FixtureImporterES7.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/MavenPackager.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
Labels: ready-for-review

#9310 Include grants for "everyone" in entities for user overview
  graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
  graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
  graylog2-server/src/main/java/org/graylog/security/shares/GranteeService.java
  graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
  graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
Labels: ready-for-review
