Repository Graylog2/graylog2-server, pull requests merged in 2021-09, with the labels that each got.

#11121 Clear grants when user is deleted
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
  graylog2-server/src/main/java/org/graylog2/users/GrantsCleanupListener.java
  graylog2-server/src/test/java/org/graylog2/users/GrantsCleanupListenerTest.java
Labels: ready-for-review

#11173 Allow null message queue ids
  graylog2-server/src/main/java/org/graylog2/shared/messageq/AbstractMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueAcknowledger.java
  graylog2-server/src/test/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueAcknowledgerTest.java
Labels: ready-for-review

#11195 Fix warning about receive buffer size
  graylog2-server/src/main/java/org/graylog2/inputs/transports/UdpTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
Labels: ready-for-review

#11241 Update forbiddenapis checker from 2.5 to 3.1
  pom.xml
Labels: ready-for-review

#11239 Fix exception being thrown for message details if plugin is missing.
  graylog2-web-interface/src/stores/nodes/NodesStore.ts
  graylog2-web-interface/src/views/components/messagelist/FormatReceivedBy.test.tsx
  graylog2-web-interface/src/views/components/messagelist/FormatReceivedBy.tsx
  graylog2-web-interface/src/views/components/messagelist/MessageDetail.tsx
  graylog2-web-interface/src/views/components/messagelist/NodeName.tsx
Labels: blocker

#11167 Remove ancient MessageTest duplicate
  graylog2-server/src/test/java/org/graylog2/logmessage/MessageTest.java
  graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
Labels: ready-for-review, improvement

#11265 Clear grants when user is deleted (#11121)
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
  graylog2-server/src/main/java/org/graylog2/users/GrantsCleanupListener.java
  graylog2-server/src/test/java/org/graylog2/users/GrantsCleanupListenerTest.java
Labels: bug, ready-for-review, backport

#11264 Clear grants when user is deleted (#11121)
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
  graylog2-server/src/main/java/org/graylog2/users/GrantsCleanupListener.java
  graylog2-server/src/test/java/org/graylog2/users/GrantsCleanupListenerTest.java
Labels: bug, ready-for-review, backport

#11228 Hide fallback login link when handling OIDC callback
  graylog2-web-interface/src/logic/authentication/constants.ts
  graylog2-web-interface/src/pages/LoginPage.jsx
  graylog2-web-interface/src/util/URLUtils.ts
Labels: ready-for-review

#11272 Simplify maven caching in GitHub action workflow
  .github/workflows/build.yml
Labels: ready-for-review

#11252 Improve performance when comparing React elements
  graylog2-web-interface/package.json
  graylog2-web-interface/src/stores/isDeepEqual.ts
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#11253 Fix potential race condition in traffic calculation
  graylog2-server/src/main/java/org/graylog2/periodical/TrafficCounterCalculator.java
Labels: ready-for-review

#11296 Make calculation fields of TrafficCounterCalculator volatile
  graylog2-server/src/main/java/org/graylog2/periodical/TrafficCounterCalculator.java
Labels: ready-for-review

#11295 Make calculation fields of TrafficCounterCalculator volatile
  graylog2-server/src/main/java/org/graylog2/periodical/TrafficCounterCalculator.java
Labels: ready-for-review

#11300 Improve error message wording in FilterPreviewStore.js
  graylog2-web-interface/src/stores/event-definitions/FilterPreviewStore.js
Labels: ready-for-review

#11232 Illuminate UI preparations
  graylog2-web-interface/src/components/common/ControlledTableListItem.tsx
  graylog2-web-interface/src/components/common/Section/SectionGrid.tsx
  graylog2-web-interface/src/components/common/TableList.css
  graylog2-web-interface/src/components/common/TableList.jsx
  graylog2-web-interface/src/components/common/index.tsx
Labels: ready-for-review

#11298 Adjustments to PipelineInterpreter.State for usage in Illuminate processor
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/StateTest.java
Labels: ready-for-review

#11318 Fixing issue in `BufferUsage` component when node metrics are missing.
  graylog2-web-interface/src/components/nodes/BufferUsage.jsx
  graylog2-web-interface/src/components/nodes/BufferUsage.tsx
Labels: bug

#11303 Ensure filter events have "source_streams" set
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
Labels: ready-for-review

#11330 Retrieve store state 2nd time after registration to avoid race condition
  graylog2-web-interface/src/components/permissions/EntityShareModal.test.tsx
  graylog2-web-interface/src/stores/connect.tsx
  graylog2-web-interface/src/views/components/widgets/TimerangeInfo.test.tsx
  graylog2-web-interface/src/views/pages/ViewManagementPage.test.tsx
Labels: bug, blocker

#11335 Linting Accordion.test.tsx
  graylog2-web-interface/src/components/graylog/Accordion.test.tsx
Labels: ready-for-review

#11337 Ensure filter events have "source_streams" set (#11303)
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
Labels: ready-for-review, backport

#11336 Ensure filter events have "source_streams" set (#11303)
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
Labels: ready-for-review, backport

#11319 Frontend Documentation Updates
  graylog2-web-interface/docs/tests.md
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/ClipboardButton.jsx
  graylog2-web-interface/src/components/common/ClipboardButton.test.jsx
  graylog2-web-interface/src/components/graylog/Tabs.md
  graylog2-web-interface/src/theme/docs/Colors.jsx
  graylog2-web-interface/styleguide.config.js
Labels: ready-for-review

#11360 Add a trace log for invalid GELF messages
  graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java
Labels: ready-for-review

#11357 Fix system stats with MongoDB >= 4.4
  graylog2-server/src/main/java/org/graylog2/system/stats/mongo/DatabaseStats.java
  graylog2-server/src/main/java/org/graylog2/system/stats/mongo/MongoProbe.java
Labels: ready-for-review

#11363 Fix system stats with MongoDB >= 4.4 (#11357)
  graylog2-server/src/main/java/org/graylog2/system/stats/mongo/DatabaseStats.java
  graylog2-server/src/main/java/org/graylog2/system/stats/mongo/MongoProbe.java
Labels: ready-for-review

#11374 Handle empty responses on plaintext requests
  graylog2-web-interface/src/logic/rest/FetchProvider.ts
Labels: ready-for-review

#11377 Updating stylelint browserslist
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#11321 Moving Scratchpad out of common components
  graylog2-web-interface/src/components/common/index.tsx
  graylog2-web-interface/src/components/scratchpad/Scratchpad.test.tsx
  graylog2-web-interface/src/components/scratchpad/Scratchpad.tsx
  graylog2-web-interface/src/routing/App.tsx
Labels: ready-for-review
