Repository Graylog2/graylog2-server, pull requests merged in 2021-03, with the labels that each got.

#10167 Fixing initial height of widget container in edit mode by removing lazy loaded css.
  graylog2-web-interface/src/components/graylog/Modal.jsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.global.lazy.css
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
Labels: search

#10154 Fix rendering of trend color in report generation
  graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
Labels: backport, ready-for-review, search

#10146 Update Kafka client to 2.7.0
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/commands/journal/JournalShow.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/system/NodeId.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/JournalResource.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
  graylog2-server/src/main/resources/log4j2.xml
  graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
  pom.xml
Labels: ready-for-review

#10157 Fix rendering of trend color in report generation
  graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
Labels: backport, elasticsearch, ready-for-review

#10162 Integrate User First/Last Name UI
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/common/ReadOnlyFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/FirstNameFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/LastNameFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
  graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileUpdateInfo.jsx
  graylog2-web-interface/src/domainActions/users/UsersDomain.js
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/test/fixtures/users.js
Labels: ready-for-review

#10158 Integrate User First/Last Name backend
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ProvisionerService.java
  graylog2-server/src/main/java/org/graylog/security/authservice/UserDetails.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationHelpers.java
  graylog2-server/src/main/java/org/graylog2/plugin/database/users/User.java
  graylog2-server/src/main/java/org/graylog2/rest/models/users/requests/ChangeUserRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/users/requests/CreateUserRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/models/users/responses/UserSummary.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
  graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ProvisionerServiceTest.java
  graylog2-server/src/test/java/org/graylog/security/authservice/UserDetailsTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/MigrationHelpersTest.java
  graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserImplTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
  graylog2-web-interface/src/actions/users/UsersActions.js
  graylog2-web-interface/src/components/common/ReadOnlyFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/FirstNameFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/LastNameFormGroup.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
  graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.test.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileUpdateInfo.jsx
  graylog2-web-interface/src/domainActions/users/UsersDomain.js
  graylog2-web-interface/src/logic/users/User.js
  graylog2-web-interface/test/fixtures/users.js
Labels: ready-for-review

#10189 Copy widget title when copying widget to dashboard
  graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.Search-View.fixture.json
  graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts
  graylog2-web-interface/src/views/logic/views/ViewState.ts
  graylog2-web-interface/src/views/logic/views/__snapshots__/CopyWidgetToDashboard.test.js.snap
Labels: ready-for-review, search

#10194 Update guice to 5.0.1
  pom.xml
Labels: java9, ready-for-review

#10183 Support IPinfo database files in GeoIP lookup data adapter
  graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPLocationDatabaseAdapter.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoASN.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoIPLocationDatabaseAdapter.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoStandardLocation.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxMindIPLocationDatabaseAdapter.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
Labels: ready-for-review

#10195 Style DataTableEntries for numeric values
  graylog2-web-interface/src/views/components/datatable/DataTableEntry.tsx
  graylog2-web-interface/src/views/components/datatable/Headers.tsx
Labels: ready-for-review, search, ux

#10202 Make webpack /api proxy host and port configurable
  graylog2-web-interface/devServer.js
  graylog2-web-interface/src/util/AppConfig.js
  graylog2-web-interface/webpack.config.js
Labels: ready-for-review

#10204 Backport: Support IPinfo database files in GeoIP lookup data adapter (#10183)
  graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPLocationDatabaseAdapter.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoASN.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoIPLocationDatabaseAdapter.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoStandardLocation.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxMindIPLocationDatabaseAdapter.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
Labels: ready-for-review

#10193 Preventing widget unmount on widget focus.
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
  graylog2-web-interface/src/views/components/Query.tsx
  graylog2-web-interface/src/views/components/WidgetComponent.tsx
  graylog2-web-interface/src/views/components/WidgetContainer.tsx
  graylog2-web-interface/src/views/components/WidgetGrid.jsx
  graylog2-web-interface/src/views/components/sidebar/ContentColumn.tsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx
Labels: search

#10211 Remove trailing parenthesis for IPInfo database types
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Labels: ready-for-review

#10184 Update Kafka client to 2.7.0 (#10146)
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/commands/journal/JournalShow.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/system/NodeId.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/JournalResource.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
  graylog2-server/src/main/resources/log4j2.xml
  graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
  pom.xml
Labels: backport, ready-for-review

#10215 Backport: Remove trailing parenthesis for DB types (#10183)
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Labels: ready-for-review

#10160 Add support for dynamic data from UI plugins to be included in generated config.js
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/PluginBindings.java
  graylog2-server/src/main/java/org/graylog2/web/PluginUISettingsProvider.java
  graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
  graylog2-server/src/main/resources/web-interface/config.js.template
Labels: feature, java, ready-for-review

#10220 Fixing name of `TimeRangeInput` test.
  graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx
Labels: search

#10186 Update Netty to the latest version
  pom.xml
Labels: ready-for-review

#10216 Fix content-pack auto installation
  graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java
Labels: content-packs, ready-for-review

#10237 Fix content-pack auto installation
  graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java
Labels: backport, content-packs, ready-for-review

#10248 Add an increasing sequence_nr to Random HTTP message generator
  graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java
Labels: feature, ready-for-review

#10266 Remove the Collector and AWS plugins from the list of expected Cloud plugins
  full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java
Labels: ready-for-review

#10221 Search not executing when form state is clean
  graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
  graylog2-web-interface/src/views/components/SearchBar.test.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchButton.test.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchButton.tsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.tsx
Labels: blocker, ready-for-review, search

#10271 Bump cloud web dependencies with security updates
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#10276 Fixes small resolution MessageTable scroll
  graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
Labels: bug, ready-for-review, ux

#10274 Remove workaround for apache commons vulnerability
  graylog2-server/pom.xml
Labels: ready-for-review

#10084 Make message queue implementations pluggable
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
  graylog2-server/src/main/java/org/graylog2/commands/journal/AbstractJournalCommand.java
  graylog2-server/src/main/java/org/graylog2/commands/journal/JournalDecode.java
  graylog2-server/src/main/java/org/graylog2/commands/journal/JournalShow.java
  graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java
  graylog2-server/src/main/java/org/graylog2/outputs/BenchmarkOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/BlockingBatchedESOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/DiscardMessageOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java
  graylog2-server/src/main/java/org/graylog2/periodical/ThrottleStateUpdaterThread.java
  graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/plugin/Plugin.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/journal/RawMessage.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/JournalResource.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/LocalKafkaJournal.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/LocalKafkaJournalModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/AbstractMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueException.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/plugins/PluginLoader.java
  graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
  graylog2-server/src/main/resources/log4j2.xml
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  graylog2-server/src/test/java/org/graylog2/messageprocessors/MessageFilterChainProcessorTest.java
  graylog2-server/src/test/java/org/graylog2/outputs/BlockingBatchedESOutputTest.java
  graylog2-server/src/test/java/org/graylog2/shared/journal/LocalKafkaJournalTest.java
  misc/graylog.conf
Labels: ready-for-review

#10264 Initialize ES7 client and sniffer lazily.
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
Labels: bug

#10197 Refactor configuration forms components
  graylog2-web-interface/src/components/configurationforms/BooleanField.jsx
  graylog2-web-interface/src/components/configurationforms/BooleanField.test.tsx
  graylog2-web-interface/src/components/configurationforms/BooleanField.tsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationFormField.jsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationFormField.tsx
  graylog2-web-interface/src/components/configurationforms/DropdownField.jsx
  graylog2-web-interface/src/components/configurationforms/DropdownField.test.tsx
  graylog2-web-interface/src/components/configurationforms/DropdownField.tsx
  graylog2-web-interface/src/components/configurationforms/FieldHelpers.tsx
  graylog2-web-interface/src/components/configurationforms/ListField.jsx
  graylog2-web-interface/src/components/configurationforms/ListField.test.tsx
  graylog2-web-interface/src/components/configurationforms/ListField.tsx
  graylog2-web-interface/src/components/configurationforms/NumberField.jsx
  graylog2-web-interface/src/components/configurationforms/NumberField.test.tsx
  graylog2-web-interface/src/components/configurationforms/NumberField.tsx
  graylog2-web-interface/src/components/configurationforms/TextField.jsx
  graylog2-web-interface/src/components/configurationforms/TextField.test.tsx
  graylog2-web-interface/src/components/configurationforms/TextField.tsx
  graylog2-web-interface/src/components/configurationforms/TitleField.jsx
  graylog2-web-interface/src/components/configurationforms/TitleField.test.tsx
  graylog2-web-interface/src/components/configurationforms/TitleField.tsx
  graylog2-web-interface/src/components/configurationforms/__snapshots__/BooleanField.test.tsx.snap
  graylog2-web-interface/src/components/configurationforms/__snapshots__/DropdownField.test.tsx.snap
  graylog2-web-interface/src/components/configurationforms/__snapshots__/ListField.test.tsx.snap
  graylog2-web-interface/src/components/configurationforms/__snapshots__/NumberField.test.tsx.snap
  graylog2-web-interface/src/components/configurationforms/__snapshots__/TextField.test.tsx.snap
  graylog2-web-interface/src/components/configurationforms/types.ts
  graylog2-web-interface/test/fixtures/configurationforms.ts
Labels: ready-for-review

#10300 Fix NPE in MongoProbe if MongoDB doesn't run with MMAPv1
  graylog2-server/src/main/java/org/graylog2/system/stats/mongo/MongoProbe.java
Labels: ready-for-review

#10091 Make message queue implementations pluggable (cloud-4.0)
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
  graylog2-server/src/main/java/org/graylog2/commands/journal/AbstractJournalCommand.java
  graylog2-server/src/main/java/org/graylog2/commands/journal/JournalDecode.java
  graylog2-server/src/main/java/org/graylog2/commands/journal/JournalShow.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java
  graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java
  graylog2-server/src/main/java/org/graylog2/outputs/BenchmarkOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/BlockingBatchedESOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/DiscardMessageOutput.java
  graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java
  graylog2-server/src/main/java/org/graylog2/periodical/ThrottleStateUpdaterThread.java
  graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/main/java/org/graylog2/plugin/Plugin.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/journal/RawMessage.java
  graylog2-server/src/main/java/org/graylog2/plugin/system/NodeId.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/JournalResource.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/LocalKafkaJournal.java
  graylog2-server/src/main/java/org/graylog2/shared/journal/LocalKafkaJournalModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/AbstractMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueException.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueModule.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessageQueueAcknowledger.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessageQueueReader.java
  graylog2-server/src/main/java/org/graylog2/shared/messageq/noop/NoopMessageQueueWriter.java
  graylog2-server/src/main/java/org/graylog2/shared/plugins/PluginLoader.java
  graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java
  graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
  graylog2-server/src/main/resources/log4j2.xml
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  graylog2-server/src/test/java/org/graylog2/messageprocessors/MessageFilterChainProcessorTest.java
  graylog2-server/src/test/java/org/graylog2/outputs/BlockingBatchedESOutputTest.java
  graylog2-server/src/test/java/org/graylog2/shared/journal/LocalKafkaJournalTest.java
  misc/graylog.conf
  pom.xml
Labels: ready-for-review

#10292 Initialize ES7 client and sniffer lazily. (4.0)
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
Labels: bug

#10278 Update tab styles and popover positioning for DateTimePicker
  graylog2-web-interface/src/components/graylog/Tab.jsx
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Labels: ready-for-review, ux

#10244 Add new Allowed Paths configuration parameter and use in CSV File adapter
  graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java
  graylog2-server/src/main/java/org/graylog2/configuration/converters/SortedPathSetConverter.java
  graylog2-server/src/main/java/org/graylog2/lookup/AllowedAuxiliaryPathChecker.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/test/java/org/graylog2/configuration/PathConfigurationTest.java
  graylog2-server/src/test/java/org/graylog2/configuration/converters/SortedPathSetConverterTest.java
  graylog2-server/src/test/java/org/graylog2/lookup/AllowedAuxiliaryPathCheckerTest.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Labels: ready-for-review

#10293 Support configuration of group by / row & column pivots in new aggregation controls.
  graylog2-web-interface/src/views/components/MigrateFieldCharts.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.test.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/FieldSelect.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/Direction.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/FieldComponent.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/Time.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Metric.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
  graylog2-web-interface/src/views/components/datatable/DataTable.test.tsx
  graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
  graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.tsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/Pivot.ts
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.ts
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotGenerator.test.ts
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotGenerator.ts
  graylog2-web-interface/src/views/logic/searchtypes/aggregation/__snapshots__/PivotConfigGenerator.test.ts.snap
Labels: search

#10321 Unset old group by form values when changing the type of the field
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/FieldComponent.tsx
Labels: ready-for-review, search

#10317 Restore ability to use the CSV File adapter in Cloud
  graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java
  graylog2-server/src/main/java/org/graylog2/configuration/converters/SortedPathSetConverter.java
  graylog2-server/src/main/java/org/graylog2/lookup/AllowedAuxiliaryPathChecker.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/test/java/org/graylog2/configuration/PathConfigurationTest.java
  graylog2-server/src/test/java/org/graylog2/configuration/converters/SortedPathSetConverterTest.java
  graylog2-server/src/test/java/org/graylog2/lookup/AllowedAuxiliaryPathCheckerTest.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Labels: ready-for-review

#10331 Add file bytes option to HTTPFileRetriever
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetriever.java
Labels: feature, java, ready-for-review

#10288 Support for displaying cloud version number
  graylog2-server/src/main/java/org/graylog2/plugin/Version.java
  graylog2-web-interface/src/components/layout/Footer.jsx
  graylog2-web-interface/src/components/layout/Footer.test.jsx
  graylog2-web-interface/src/components/layout/StandardFooter.jsx
  graylog2-web-interface/src/util/Version.js
  graylog2-web-interface/src/util/Version.test.jsx
Labels: ready-for-review

#10357 Rebuild & Type ColorLabel
  graylog2-web-interface/src/components/sidecars/common/ColorLabel.tsx
Labels: bug, ready-for-review, ux

#10354 Update Component usage to properly render Theme
  graylog2-web-interface/src/components/extractors/MessageLoader.jsx
  graylog2-web-interface/src/components/graylog/Label.jsx
  graylog2-web-interface/src/components/outputs/CreateOutputDropdown.jsx
  graylog2-web-interface/src/components/permissions/RolesCell.tsx
  graylog2-web-interface/src/components/systemjobs/SystemJob.jsx
Labels: bug, ready-for-review, ux
