Repository Graylog2/graylog2-server, pull requests merged in 2021-07, with the labels that each got.

#10951 Add allowed_auxiliary_paths to default server.conf file
  misc/graylog.conf
Labels: ready-for-review

#10953 Use protocol of current url for api browser, if scheme is missing.
  graylog2-server/src/main/resources/swagger/lib/shred.bundle.js
Labels: bug

#10978 Provide default if no visualization config was provided for Heatmap
  graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
Labels: search

#10954 Only restrict TLS to secure ciphers with TLS1.2 or greater
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsTransport.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/configuration/TLSProtocolsConfiguration.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/SyslogTcpTransport.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/TcpTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportTest.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTest.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTestTLSIT.java
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
Labels: ready-for-review

#10985 Only restrict TLS to secure ciphers with TLS1.2 or greater (4.1 backport)
  graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsTransport.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/configuration/TLSProtocolsConfiguration.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/SyslogTcpTransport.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/TcpTransport.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
  graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
  graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
  graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportTest.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTest.java
  graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTestTLSIT.java
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
Labels: backport, ready-for-review

#10934 Fix issue with duplicate Jackson JSON modules
  graylog2-server/pom.xml
Labels: ready-for-review

#10993 Fix issue with duplicate Jackson JSON modules
  graylog2-server/pom.xml
Labels: ready-for-review

#10987 Provide default if no visualization config was provided for Heatmap
  graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
Labels: backport, elasticsearch

#10986 Deprecate shutting a node down via the API
  graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemShutdownResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/RemoteSystemShutdownResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/SystemShutdownResource.java
  graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Labels: ready-for-review

#10886 Avoid global lookup cache purge on shared store update
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
Labels: ready-for-review

#9378 Fix read handling of corrupted journal segments
  graylog2-server/src/main/java/org/graylog2/shared/journal/LocalKafkaJournal.java
  graylog2-server/src/test/java/org/graylog2/shared/journal/LocalKafkaJournalTest.java
Labels: ready-for-review

#11004 Avoid global lookup cache purge on shared store update
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
Labels: ready-for-review

#10994 Make LookupTableService database independent
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/Debug.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableConfigService.java
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
  graylog2-server/src/main/java/org/graylog2/lookup/db/DBLookupTableConfigService.java
Labels: ready-for-review

#11023 Also exclude outputs from search dependencies
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
Labels: bug, ready-for-review

#11024 Add new fields needed for VPC flow logs
  graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java
  graylog2-server/src/main/java/org/graylog/schema/EventFields.java
  graylog2-server/src/main/java/org/graylog/schema/GeoFields.java
  graylog2-server/src/main/java/org/graylog/schema/HostFields.java
  graylog2-server/src/main/java/org/graylog/schema/SourceFields.java
Labels: ready-for-review

#11017 Do not set 'to' when setting TimeRange to 'All Time'
  graylog2-web-interface/src/views/logic/queries/IsAllMessagesRange.ts
Labels: search

#11027 Also exclude outputs from search dependencies (#11023)
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
Labels: backport, ready-for-review

#11010 Add new hook to CopyWidgetToDashboard
  graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts
  graylog2-web-interface/src/views/types.d.ts
Labels: search

#10941 Installing type definitions for `react-select`.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/MultiSelect.tsx
  graylog2-web-interface/src/components/common/Select.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListForm.tsx
  graylog2-web-interface/src/components/permissions/RolesSelector.tsx
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.tsx
  graylog2-web-interface/src/views/components/Select.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/visualization/VisualizationConfiguration.tsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.test.tsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.tsx
  graylog2-web-interface/src/views/logic/valueactions/SelectExtractorType.test.tsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#10977 Issue 10552 dashboard page context
  graylog2-web-interface/src/views/components/QueryBar.test.tsx
  graylog2-web-interface/src/views/components/QueryBar.tsx
  graylog2-web-interface/src/views/components/QueryTabs.tsx
  graylog2-web-interface/src/views/components/contexts/DashboardPageContext.tsx
  graylog2-web-interface/src/views/components/contexts/DashboardPageContextProvider.test.tsx
  graylog2-web-interface/src/views/components/contexts/DashboardPageContextProvider.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
  graylog2-web-interface/src/views/components/queries/QueryTitle.tsx
  graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx
  graylog2-web-interface/src/views/pages/SearchPage.tsx
  graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx
  graylog2-web-interface/src/views/stores/QueriesStore.ts
  graylog2-web-interface/src/views/stores/ViewStore.ts
Labels: ready-for-review, search

#11057 Fix retrying indexing when connection failed to elastic search 7
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
Labels: elasticsearch

#11053 Zero count for saved searches list
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Labels: search

#11052 Fix retrying indexing when connection failed to elastic search 7
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
Labels: elasticsearch, search

#10882 Add cluster wide Loggers endpoint
  graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterLoggersResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/RemoteLoggersResource.java
Labels: feature, ready-for-review

#11033 Flag failures and event streams as non-editable. Handle special IndexSets
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineConnectionsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PermittedStreams.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/EntityDescriptorIds.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
  graylog2-server/src/main/java/org/graylog2/plugin/streams/Stream.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/outputs/StreamOutputResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/StreamResponse.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/rules/StreamRuleResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/PermittedStreamsTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/IndexSetsResourceTest.java
Labels: ready-for-review

#11056 Create random http message timestamps early
  graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java
Labels: improvement, ready-for-review

#11078 Reimplement #10277: some JARs may not exist in a certain manifest
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
Labels: ready-for-review

#11080 Add service for user session termination
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationListener.java
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java
Labels: ready-for-review

#11081 Don't log session ID in DEBUG messages
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
  graylog2-server/src/main/java/org/graylog2/security/MongoDbSessionDAO.java
  graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java
Labels: ready-for-review

#11086 Handle expired sessions in UserSessionTerminationService
  graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
Labels: ready-for-review

#11088 Add is_editable field to StreamDTO
  graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
Labels: ready-for-review

#11034 Fix returning count and grand_total of views
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
Labels: search
