Repository Graylog2/graylog2-server, pull requests merged in 2021-06, with the labels that each got.

#10754 Fix sorting of stream overview page
  graylog2-web-interface/src/components/streams/StreamList.jsx
Labels: ready-for-review, ux, web

#10615 Public Notifications implementation into Login & Global
  graylog2-web-interface/config.js
  graylog2-web-interface/src/components/common/PublicNotifications.test.tsx
  graylog2-web-interface/src/components/common/PublicNotifications.tsx
  graylog2-web-interface/src/components/graylog/Alert.tsx
  graylog2-web-interface/src/components/login/LoginBox.jsx
  graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap
  graylog2-web-interface/src/components/notifications/WithGlobalAppNotifications.tsx
  graylog2-web-interface/src/theme/colors.ts
  graylog2-web-interface/src/theme/types.d.ts
  graylog2-web-interface/src/util/AppConfig.js
Labels: enterprise, feature, ready-for-review

#10771 Pull up query client provider in component tree.
  graylog2-web-interface/src/pages/LoggedInPage.jsx
  graylog2-web-interface/src/routing/App.tsx
Labels: bug

#10717 Prevent HTTPPollTransport from stopping on non 2XX
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpPollTransport.java
Labels: ready-for-review

#10593 Use ColorMapper for event annotations
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
  graylog2-web-interface/src/views/components/visualizations/ColorMapper.ts
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
  graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
  graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx
  graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx
  graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx
  graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.tsx
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.test.ts
  graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.ts
  graylog2-web-interface/src/views/logic/searchtypes/events/__snapshots__/EventHandler.test.ts.snap
Labels: ready-for-review, search

#10708 Migrate Okta auth backend to enterprise plugin
  graylog2-server/src/main/java/org/graylog/security/authservice/rest/AuthServiceBackendsResource.java
  graylog2-web-interface/checkProductionBuild.js
  graylog2-web-interface/src/actions/authentication/AuthenticationActions.ts
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/WizardPageHeader.tsx
  graylog2-web-interface/src/components/authentication/types.d.ts
  graylog2-web-interface/src/contexts/LoginQueryClientProvider.tsx
  graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.tsx
  graylog2-web-interface/src/logic/authentication/AuthenticationBackend.ts
  graylog2-web-interface/src/logic/authentication/okta/types.ts
  graylog2-web-interface/src/pages/LoginPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.js
  graylog2-web-interface/src/routing/AppFacade.jsx
  graylog2-web-interface/src/stores/authentication/AuthenticationStore.ts
Labels: ready-for-review

#10767 Add prometheus exporter
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporter.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporterConfiguration.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporterHTTPServer.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusMetricFilter.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusMetricsModule.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/ReplaceableCollectorRegistry.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/mapping/PrometheusMappingConfig.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/mapping/PrometheusMappingConfigLoader.java
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/mapping/PrometheusMappingFilesHandler.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/resources/prometheus-exporter.yml
  graylog2-server/src/test/java/org/graylog/metrics/prometheus/PrometheusExporterHTTPServerTest.java
  graylog2-server/src/test/java/org/graylog/metrics/prometheus/PrometheusMetricFilterTest.java
  graylog2-server/src/test/java/org/graylog/metrics/prometheus/mapping/PrometheusMappingConfigLoaderTest.java
  graylog2-server/src/test/java/org/graylog/metrics/prometheus/mapping/PrometheusMappingFilesHandlerTest.java
  misc/graylog.conf
  pom.xml
Labels: ready-for-review

#10783 Close response on all non-successful response codes
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetriever.java
Labels: bug, ready-for-review

#10797 Support PKCS#1 keys for Inputs
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/util/KeyUtil.java
  graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/util/KeyUtilNonParameterizedTest.java
  graylog2-server/src/test/resources/org/graylog2/plugin/inputs/transports/util/server.key.unprotected.pkcs1
Labels: bug, ready-for-review

#10796 Update Prometheus exporter default port
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporterConfiguration.java
  misc/graylog.conf
Labels: ready-for-review

#10812 Update bouncycastle to version 1.69
  pom.xml
Labels: ready-for-review

#10826 Return null when no encryptedValue is set
  graylog2-server/src/main/java/org/graylog2/security/encryption/EncryptedValueService.java
Labels: ready-for-review

#10850 Heatmap: Clear min and max on auto scale use
  graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
Labels: search

#10855 Decorator action menu cut off
  graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSummary.jsx
Labels: search

#10849 Do not render column roll-up label as value action in PlotLegend
  graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx
  graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
Labels: search

#10845 Do not hide legends for pie charts
  graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx
  graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
  graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
Labels: ready-for-review, search

#10862 Always close system menu when selecting link in system menu dropdown.
  graylog2-web-interface/src/util/conditional/HideOnCloud.test.tsx
  graylog2-web-interface/src/util/conditional/HideOnCloud.tsx
Labels: ready-for-review

#10865 Always update all widgets after unfocusing
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
Labels: search

#10856 Update Team sync backend types to use Okta related fields
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.tsx
  graylog2-web-interface/src/components/authentication/types.d.ts
  graylog2-web-interface/src/logic/authentication/AuthenticationBackend.ts
  graylog2-web-interface/src/logic/authentication/okta/types.ts
Labels: ready-for-review

#10880 Fixing shared entities overview filter for saved searches.
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.tsx
  graylog2-web-interface/src/logic/permissions/mocked.tsx
Labels: bug, ready-for-review

#10815 Fix race condition in lookup data adapter and cache lifecycle
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
  graylog2-server/src/main/java/org/graylog2/utilities/LatchUpdaterListener.java
Labels: ready-for-review

#10799 NO_LIMIT was 0 pre 4.x and is now -1 in Legacy API
  UPGRADING.rst
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
Labels: bug

#10889 Adjusting to changed error messages in ES7 for flood stage/missing alias target
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
Labels: blocker

#10890 Releasing objects retained by RawMessageEvents
  graylog2-server/src/main/java/org/graylog2/shared/buffers/DirectMessageHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/RawMessageEvent.java
Labels: blocker, ready-for-review

#10897 Adjusting to changed error messages in ES7 for flood stage/missing alias target (4.0)
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
Labels: blocker, bug

#10905 Replace hyphens with underscored in metric names
  graylog2-server/src/main/resources/prometheus-exporter.yml
Labels: ready-for-review

#10860 Add error boundary to plugin authentication form
  graylog2-web-interface/src/pages/LoginPage.jsx
Labels: ready-for-review

#10915 Improve error logging for auth service connection test
  graylog2-server/src/main/java/org/graylog/security/authservice/test/AuthServiceBackendTestService.java
Labels: ready-for-review

#10937 Remove unused byte code generator for the pipeline language
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/PipelineConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/Rule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/codegen/CodeGenerator.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/codegen/GeneratedRule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/codegen/PipelineClassloader.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/codegen/compiler/InMemoryFileManager.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/codegen/compiler/JavaCompiler.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/codegen/compiler/JavaSourceFromString.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/codegen/compiler/PipelineCompilationException.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdater.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/BaseParserTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/CodegenPipelineRuleParserTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParserTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/PrecedenceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdaterTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  pom.xml
Labels: ready-for-review

#10939 Set default value for matchingType in StreamDTO
  graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
Labels: ready-for-review

#10892 Fixing floating of `ListGroupItem`s in `ListGroup`.
  graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
Labels: test-day

#10893 Fixing shared entities overview filter for saved searches. (Backport of #10880 for 4.0)
  graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.jsx
  graylog2-web-interface/src/logic/permissions/mocked.js
Labels: backport

#10943 Set default value for matchingType in StreamDTO
  graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
Labels: backport

#10942 Set default value for matchingType in StreamDTO
  graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
Labels: backport

#10703 Fix permission check for notifications in event definitions for non alert managers
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
Labels: ready-for-review
