Repository Graylog2/graylog2-server, pull requests merged in 2021-04, with the labels that each got.

#10372 stylelint config-styled-components & processor-styled-components
  graylog2-web-interface/.stylelintrc.json
  graylog2-web-interface/package.json
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review

#10364 Fix HeatmapVisualization with empty data and smallest default value
  graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx
  graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
Labels: ready-for-review, search

#10377 Reducing height of widget configuration components in aggregation builder.
  graylog2-web-interface/src/components/common/FormikFormGroup.tsx
  graylog2-web-interface/src/components/common/FormikInput.tsx
  graylog2-web-interface/src/components/common/Select.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/FieldSelect.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Metric.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/InputField.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/SelectField.tsx
Labels: search

#10343 Add posibility to disable actions from plugin
  graylog2-web-interface/src/views/components/widgets/ExtraWidgetActions.test.tsx
  graylog2-web-interface/src/views/components/widgets/ExtraWidgetActions.tsx
  graylog2-web-interface/src/views/components/widgets/Types.ts
Labels: ready-for-review, search

#10380 Fix permission check for notifcations in event definitions
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
Labels: alerting, ready-for-review, users

#10366 Remove button for aggregation wizard section
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.test.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.test.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
Labels: ready-for-review, search

#10379 Always show elements configuration actions in aggregation builder, by positioning them as sticky.
  graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
  graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/mock-IntersectionObserver.js
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfigurationActions.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
Labels: search

#10399 Adding `lang="en"` to html tag, to declare the language of the web application.
  graylog2-web-interface/templates/index.html.template
Labels: improvement

#10388 Hide save and load controls when editing a widget
  graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
  graylog2-web-interface/src/views/components/SearchBar.test.tsx
  graylog2-web-interface/src/views/components/SearchBar.tsx
Labels: ready-for-review, search

#10384 Upgrading StyleLint
  graylog2-web-interface/.stylelintrc.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/packages/stylelint-config-graylog/index.js
  graylog2-web-interface/packages/stylelint-config-graylog/package.json
  graylog2-web-interface/src/components/inputs/InputDropdown.jsx
  graylog2-web-interface/src/components/users/UserEdit/RolesSection.tsx
  graylog2-web-interface/src/theme/docs/Colors.jsx
  graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
  graylog2-web-interface/src/views/components/sidebar/NavItem.tsx
  graylog2-web-interface/src/views/components/visualizations/number/Trend.tsx
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review

#10405 Defining theme input placeholder color for common `Select` component.
  graylog2-web-interface/src/components/common/Select.tsx
  graylog2-web-interface/src/components/configurationforms/__snapshots__/ListField.test.tsx.snap
Labels: improvement

#10387 Simplify identification of each aggregation element in aggregation builder.
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfigurationActions.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
Labels: search

#10280 Return only summary of existing searches/dashboards
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchSummary.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchesCleanUpJob.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryDTO.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceUsesViewRequirementsTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardV1FacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/ViewFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnershipToGrantsMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewSharingToGrantsMigrationTest.java
Labels: search

#10391 CSV File adapter: Use AllowedAuxiliaryPathChecker in File path UI validation
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/LookupDataAdapterValidationContext.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Labels: ready-for-review, security

#10406 Sync cloud 4.0
  distribution/pom.xml
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
  graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
  pom.xml
Labels: ready-for-review

#10390 Displaying aggregation element section actions in a row with section form to reduce section height.
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.tsx
Labels: search

#10425 Cloud port: Use AllowedAuxiliaryPathChecker in File path UI validation #10391
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/LookupDataAdapterValidationContext.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Labels: backport, ready-for-review

#10287 Reduce label size in MessageDetailsTitle
  graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx
Labels: ready-for-review

#10428 Fix case inconsistencies with ES cluster health status
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog2-web-interface/src/components/indexers/IndexerClusterHealthSummary.jsx
Labels: ready-for-review

#10421 Log failed messages and full stack trace on processing errors
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
Labels: ready-for-review

#10432 Log failed messages and full stack trace on processing errors (#10421)
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
Labels: ready-for-review

#10433 Log failed messages and full stack trace on processing errors (#10421)
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
Labels: ready-for-review

#10426 Execute search only for focused widget
  graylog2-web-interface/src/views/actions/SearchActions.ts
  graylog2-web-interface/src/views/components/Search.test.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
  graylog2-web-interface/src/views/stores/SearchStore.ts
Labels: ready-for-review, search

#10438 Don't run index jobs for missing indices
  graylog2-server/src/main/java/org/graylog2/indexer/SetIndexReadOnlyJob.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/jobs/OptimizeIndexJob.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/jobs/SetIndexReadOnlyAndCalculateRangeJob.java
  graylog2-server/src/main/java/org/graylog2/indexer/ranges/CreateNewSingleIndexRangeJob.java
Labels: ready-for-review

#10431 Fix case inconsistencies with ES cluster health status (#10428)
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog2-web-interface/src/components/indexers/IndexerClusterHealthSummary.jsx
Labels: ready-for-review

#10402 Restructure and unify aggregation element and aggregation element section naming.
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationElementSelect.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationElementSelect.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.test.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.test.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfigurationOptions.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/BooleanField.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/SelectField.tsx
Labels: search

#10443 Adjust entity dependency resolver to ignore outputs for dashboards
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
Labels: ready-for-review

#10446 Adjust entity dependency resolver to ignore outputs for dashboards (backport)
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
Labels: backport, ready-for-review

#10447 Fix fetch provider with empty response body
  graylog2-web-interface/src/logic/rest/FetchProvider.test.ts
  graylog2-web-interface/src/logic/rest/FetchProvider.ts
Labels: ready-for-review, web

#10437 Allow using the same LDAP attribute for different config settings
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
Labels: ready-for-review

#10466 Fix broken DTP layout on small resolutions
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Labels: bug, ready-for-review, search

#10450 Fix rendering of WorldMapVisualization in reports
  graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
Labels: ready-for-review, search

#10473 Fix rendering of WorldMapVisualization in reports
  graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
Labels: backport, ready-for-review, search

#10434 Refactor removal of aggregation elements and enable removal of sort elements.
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.test.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
Labels: search

#10404 Collection of smaller layout improvements for new aggregation builder.
  graylog2-web-interface/src/components/common/HoverForHelp.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/Time.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Metric.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfigurationOptions.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/BooleanField.tsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.tsx.snap
  graylog2-web-interface/src/views/components/visualizations/bar/bindings.tsx
Labels: search

#10474 Fix rendering of WorldMapVisualization in reports
  graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
Labels: backport, ready-for-review, search

#10436 Creating tests for aggregation sort configuration.
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
Labels: search

#10489 Adjust ADAuthServiceBackend login test output
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
Labels: ready-for-review

#10461 Replace `react-dnd` usage in `SortableList` with `react-beautiful-dnd` which is specifically built for sortable lists.
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/SortableList.jsx
  graylog2-web-interface/src/components/common/SortableList/List.tsx
  graylog2-web-interface/src/components/common/SortableList/ListItem.tsx
  graylog2-web-interface/src/components/common/SortableList/SortableList.md
  graylog2-web-interface/src/components/common/SortableList/SortableList.test.tsx
  graylog2-web-interface/src/components/common/SortableList/SortableList.tsx
  graylog2-web-interface/src/components/common/SortableList/SortableListItem.tsx
  graylog2-web-interface/src/components/common/SortableList/index.ts
  graylog2-web-interface/src/components/common/SortableListItem.css
  graylog2-web-interface/src/components/common/SortableListItem.jsx
  graylog2-web-interface/src/components/common/index.tsx
  graylog2-web-interface/src/components/configurations/MessageProcessorsConfig.jsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsConfigUpdate.tsx
  graylog2-web-interface/src/components/extractors/ExtractorSortModal.jsx
  graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
  graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorList.tsx
  graylog2-web-interface/yarn.lock
Labels: improvement, ready-for-review

#10483 Issue 6381
  graylog2-server/src/main/java/org/graylog/events/event/Event.java
  graylog2-server/src/main/java/org/graylog/events/event/EventDto.java
  graylog2-server/src/main/java/org/graylog/events/event/EventImpl.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
  graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
  graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
Labels: ready-for-review

#10392 Support + in index set prefixes.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
  graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
  graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
Labels: bug

#10462 Allow using the same LDAP attribute for different config settings (#10437)
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
Labels: backport, ready-for-review

#10468 weeks cause problems in new date & time picker
  graylog2-web-interface/package.json
  graylog2-web-interface/src/views/Constants.ts
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/index.d.ts
  graylog2-web-interface/yarn.lock
Labels: ready-for-review, search, ux

#10515 Make working with ValidationResults a bit more pleasant
  graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationResult.java
Labels: improvement, ready-for-review
