Repository Graylog2/graylog2-server, pull requests merged in 2021-08, with the labels that each got.

#11100 Fixing streams overview query handling.
  graylog2-web-interface/src/stores/streams/StreamsStore.ts
Labels: bug, ready-for-review

#11111 Fixing streams overview query handling (backport of #11100 for 4.1)
  graylog2-web-interface/src/stores/streams/StreamsStore.ts
Labels: backport, ready-for-review, search

#11106 Exclude non-data nodes from ES floodgate checks
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/CatApi.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/NodeResponse.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeRole.java
  graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStatsTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeRoleTest.java
  graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
Labels: ready-for-review

#11092 Add "match pass" guard for pipeline stages
  graylog2-server/src/main/antlr4/org/graylog/plugins/pipelineprocessor/parser/RuleLang.g4
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/Stage.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineSource.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/StageSource.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParserTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/StageIteratorTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineSourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/StageSourceTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
  graylog2-web-interface/src/components/pipelines/Stage.tsx
  graylog2-web-interface/src/components/pipelines/StageForm.tsx
  graylog2-web-interface/src/logic/pipelines/SourceGenerator.js
  graylog2-web-interface/src/stores/pipelines/PipelinesStore.ts
Labels: ready-for-review

#11090 Do not set 'to' when setting TimeRange to 'All Time' (4.1 backport)
  graylog2-web-interface/src/views/logic/queries/IsAllMessagesRange.ts
Labels: search

#11125 Exclude non-data nodes from ES floodgate checks (#11106)
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/CatApi.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/NodeResponse.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeRole.java
  graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStatsTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeRoleTest.java
  graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
Labels: ready-for-review

#11129 Remove node graceful shutdown menu entry in UI
  graylog2-web-interface/src/components/nodes/NodesActions.jsx
  graylog2-web-interface/src/injection/registerBuiltinStores.js
  graylog2-web-interface/src/stores/system-shutdown/SystemShutdownStore.js
Labels: ready-for-review

#11130 Display Tooltips by default
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/graylog/Tooltip.jsx
Labels: ready-for-review

#10998 Implement generic OIDC login
  graylog2-server/src/main/java/org/graylog/security/authservice/AuthenticationDetails.java
  graylog2-web-interface/src/components/authentication/directoryServices/ldap/WizardPageHeader.tsx
  graylog2-web-interface/src/logic/authentication/okta/types.ts
Labels: ready-for-review

#11020 Fix returning count of saved searches list
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
  graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
Labels: search

#11022 Feature flags v1
  graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
  graylog2-server/src/main/java/org/graylog2/featureflag/FeatureFlagStringUtil.java
  graylog2-server/src/main/java/org/graylog2/featureflag/FeatureFlags.java
  graylog2-server/src/main/java/org/graylog2/featureflag/FeatureFlagsFactory.java
  graylog2-server/src/main/java/org/graylog2/featureflag/FeatureFlagsResources.java
  graylog2-server/src/main/java/org/graylog2/featureflag/ImmutableFeatureFlags.java
  graylog2-server/src/main/java/org/graylog2/featureflag/ImmutableFeatureFlagsCollector.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericBindings.java
  graylog2-server/src/main/java/org/graylog2/shared/metrics/MetricRegistryFactory.java
  graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
  graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
  graylog2-server/src/main/resources/web-interface/config.js.template
  graylog2-server/src/test/java/org/graylog2/featureflag/ImmutableFeatureFlagsMetricsTest.java
  graylog2-server/src/test/java/org/graylog2/featureflag/ImmutableFeatureFlagsTest.java
  graylog2-server/src/test/resources/org/graylog2/featureflag/custom-feature-flag.config
Labels: ready-for-review

#11145 Provide default stage for new pipeline
  graylog2-web-interface/src/logic/pipelines/SourceGenerator.js
Labels: web

#11148 Fix open TODOS
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/Debug.java
  graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericBindings.java
Labels: ready-for-review

#11154 Fixing resolving alias target for index sets with plus in prefix on ES6 in 4.0 (backport of #11142)
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/indices/GetSingleAlias.java
  graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
  graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Labels: bug

#11139 Render Enterprise Failure overview with open source fallback
  graylog2-web-interface/src/components/indexers/IndexerSystemOverviewComponent.tsx
  graylog2-web-interface/src/components/indexers/types.d.ts
  graylog2-web-interface/src/components/support/SmallSupportLink.tsx
  graylog2-web-interface/src/pages/SystemOverviewPage.jsx
Labels: ready-for-review

#11138 Display Tooltips by default (#11130)
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/graylog/Tooltip.jsx
Labels: ready-for-review

#11197 Lazy initialize processingErrors list
  graylog2-server/src/main/java/org/graylog/failure/DefaultFailureHandler.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/test/java/org/graylog/failure/DefaultFailureHandlerTest.java
Labels: ready-for-review

#11182 Remove a trailing comma from 'SidecarStatus'.
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
Labels: bug, triaged

#11226 Fix race condition in message details related to uninitialized nodes store (backport of #11207 for 4.1)
  graylog2-web-interface/src/stores/nodes/NodesStore.ts
Labels: backport

#11209 Fix typo
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
Labels: ready-for-review
