Repository Graylog2/graylog2-server, pull requests merged in 2021-01, with the labels that each got.

#9811 DateTime Picker Keyword Tab Help Content
  graylog2-web-interface/src/util/DocsHelper.js
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.tsx
Labels: ready-for-review

#9788 DateTimePicker - capture Enter and Esc keys to submit or cancel range selection
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteDateInput.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9809 DateTime Picker - Updating error message styles
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.tsx.snap
Labels: ready-for-review

#9790 Add HTML emails compatibility for alerts notifications
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EmailEventNotificationConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
  graylog2-server/src/test/java/org/graylog/events/notifications/NotificationDtoTest.java
  graylog2-server/src/test/resources/org/graylog/events/contentpack/facade/NotificationFacadeTest.json
  graylog2-web-interface/src/components/event-notifications/event-notification-details/EmailNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.jsx
Labels: ready-for-review

#9836 Use plotlys colorscales for Heatmap Aggregation
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/HeatmapVisualizationConfigDTO.java
  graylog2-web-interface/src/views/bindings.tsx
  graylog2-web-interface/src/views/components/aggregationbuilder/HeatmapVisualizationConfiguration.tsx
  graylog2-web-interface/src/views/components/visualizations/ChartData.ts
  graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx
  graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
  graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.ts
  graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/HeatmapVisualizationConfig.ts
Labels: search

#9838 Save focused widget id in url
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
Labels: ready-for-review, search

#9874 Bump urijs to 1.19.5 in 4.0
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review, security

#9875 Fix page size change selector in Content Pack list
  graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
Labels: ready-for-review

#9877 Fix pattern used to identify parameters in search/dashboard query strings.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendErrorHandlingTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendGeneratedRequestTestBase.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendQueryStringDecoratorsTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendUsingCorrectIndicesTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/QueryPlanTest.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendErrorHandlingTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendGeneratedRequestTestBase.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendQueryStringDecoratorsTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendUsingCorrectIndicesTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/QueryPlanTest.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParser.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryParser.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParserTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/QueryParserTest.java
Labels: ready-for-review

#9886 Fix pattern used to identify parameters in search/dashboard query strings. (3.3)
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParser.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParserTest.java
Labels: ready-for-review

#9868 Cloud user management integration
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
  graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx
  graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
Labels: ready-for-review

#9892 Updating @testing-library/react to v11.2.3
  graylog2-web-interface/packages/jest-preset-graylog/package.json
  graylog2-web-interface/yarn.lock
Labels: dependencies, ready-for-review

#9887 Fix pattern used to identify parameters in search/dashboard query strings
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendErrorHandlingTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendGeneratedRequestTestBase.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendQueryStringDecoratorsTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendUsingCorrectIndicesTest.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/QueryPlanTest.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendErrorHandlingTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendGeneratedRequestTestBase.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendQueryStringDecoratorsTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendUsingCorrectIndicesTest.java
  graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/QueryPlanTest.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParser.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryParser.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParserTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/QueryParserTest.java
Labels: backport, ready-for-review, search

#9885 New Common `Accordion` Component
  graylog2-web-interface/src/components/bootstrap/BootstrapAccordion.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapAccordionGroup.jsx
  graylog2-web-interface/src/components/bootstrap/index.js
  graylog2-web-interface/src/components/graylog/Accordion.md
  graylog2-web-interface/src/components/graylog/Accordion.test.tsx
  graylog2-web-interface/src/components/graylog/Accordion.tsx
  graylog2-web-interface/src/components/graylog/AccordionItem.tsx
  graylog2-web-interface/src/components/graylog/Panel.jsx
  graylog2-web-interface/src/theme/docs/ThemeProvider.md
  graylog2-web-interface/src/theme/docs/Utilities.md
  graylog2-web-interface/styleguide.config.js
Labels: ready-for-review

#9900 Update to testcontainers 1.15.1
  pom.xml
Labels: ready-for-review

#9895 Update nodejs to 14.15.4 and yarn to 1.22.5
  pom.xml
Labels: ready-for-review

#9909 Cleanup page layout related components.
  graylog2-web-interface/src/components/errors/ErrorPage.tsx
  graylog2-web-interface/src/components/layout/Footer.tsx
  graylog2-web-interface/src/components/layout/PageContentLayout.test.tsx
  graylog2-web-interface/src/components/layout/PageContentLayout.tsx
  graylog2-web-interface/src/pages/UserHasNoStreamAccess.tsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/routing/AppWithExtendedSearchBar.jsx
  graylog2-web-interface/src/routing/AppWithoutSearchBar.tsx
  graylog2-web-interface/src/views/bindings.tsx
  graylog2-web-interface/src/views/components/Search.tsx
Labels: ready-for-review, search

#9882 Do not set invalid widget id as a focused widget
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
Labels: ready-for-review, search

#9810 DateTimePicker - Adding limitDuration config to Widget
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeInput.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteRangeField.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.tsx.snap
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#9910 Fix deserialization of incomplete AlertReceivers objects
  graylog2-server/src/main/java/org/graylog2/rest/models/alarmcallbacks/requests/AlertReceivers.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
Labels: ready-for-review

#9899 Supporting `from` and `to` properties in relative time ranges.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java
  graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/RelativeRange.java
Labels: ready-for-review

#9906 Fix csv export for shared dashboards.
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/MessagesResourceTest.java
Labels: ready-for-review, search, users

#9911 Do not allow selecting same pipeline stage twice
  graylog2-web-interface/src/components/pipelines/NewPipeline.tsx
  graylog2-web-interface/src/components/pipelines/Pipeline.css
  graylog2-web-interface/src/components/pipelines/Pipeline.jsx
  graylog2-web-interface/src/components/pipelines/Pipeline.tsx
  graylog2-web-interface/src/components/pipelines/PipelineConnectionsForm.jsx
  graylog2-web-interface/src/components/pipelines/PipelineConnectionsForm.tsx
  graylog2-web-interface/src/components/pipelines/PipelineConnectionsList.jsx
  graylog2-web-interface/src/components/pipelines/PipelineConnectionsList.tsx
  graylog2-web-interface/src/components/pipelines/PipelineDetails.jsx
  graylog2-web-interface/src/components/pipelines/PipelineDetails.tsx
  graylog2-web-interface/src/components/pipelines/PipelineForm.jsx
  graylog2-web-interface/src/components/pipelines/PipelineForm.tsx
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.tsx
  graylog2-web-interface/src/components/pipelines/Stage.jsx
  graylog2-web-interface/src/components/pipelines/Stage.tsx
  graylog2-web-interface/src/components/pipelines/StageForm.jsx
  graylog2-web-interface/src/components/pipelines/StageForm.tsx
  graylog2-web-interface/src/components/pipelines/StageRules.tsx
  graylog2-web-interface/src/stores/pipelines/PipelineConnectionsStore.ts
  graylog2-web-interface/src/stores/pipelines/PipelinesStore.ts
  graylog2-web-interface/src/stores/rules/RulesStore.ts
Labels: ready-for-review

#9901 DateTimePicker: moving live update
  graylog2-web-interface/src/views/components/SearchBar.tsx
  graylog2-web-interface/src/views/components/__snapshots__/SearchBar.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
Labels: ready-for-review

#9893 DateTimePicker : DateTimeProvider to pass static form values
  graylog2-web-interface/src/views/Constants.ts
  graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx
  graylog2-web-interface/src/views/components/SearchBar.tsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/DateTimeProvider.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
Labels: ready-for-review

#9840 Report system stats with OSHI instead of libsigar
  UPGRADING.rst
  bin/graylogctl
  distribution/src/main/assembly/graylog.xml
  full-backend-tests/src/test/java/org/graylog/shared/system/stats/SystemStatsIT.java
  graylog-project-parent/pom.xml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
  graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/OshiService.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/SigarService.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/SystemStatsModule.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/OshiFsProbe.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/SigarFsProbe.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/jvm/JvmStats.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/network/OshiNetworkProbe.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/network/SigarNetworkProbe.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/OshiOsProbe.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/SigarOsProbe.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/process/OshiProcessProbe.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/process/SigarProcessProbe.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
  graylog2-server/src/test/resources/api-it-tests.properties
  graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
  graylog2-server/src/test/resources/org/graylog/testing/graylognode/docker-entrypoint.sh
  lib/sigar-1.6.4/libsigar-amd64-freebsd-6.so
  lib/sigar-1.6.4/libsigar-amd64-linux.so
  lib/sigar-1.6.4/libsigar-amd64-solaris.so
  lib/sigar-1.6.4/libsigar-ia64-hpux-11.sl
  lib/sigar-1.6.4/libsigar-ia64-linux.so
  lib/sigar-1.6.4/libsigar-pa-hpux-11.sl
  lib/sigar-1.6.4/libsigar-ppc-aix-5.so
  lib/sigar-1.6.4/libsigar-ppc-linux.so
  lib/sigar-1.6.4/libsigar-ppc64-aix-5.so
  lib/sigar-1.6.4/libsigar-ppc64-linux.so
  lib/sigar-1.6.4/libsigar-s390x-linux.so
  lib/sigar-1.6.4/libsigar-sparc-solaris.so
  lib/sigar-1.6.4/libsigar-sparc64-solaris.so
  lib/sigar-1.6.4/libsigar-universal-macosx.dylib
  lib/sigar-1.6.4/libsigar-universal64-macosx.dylib
  lib/sigar-1.6.4/libsigar-x86-freebsd-5.so
  lib/sigar-1.6.4/libsigar-x86-freebsd-6.so
  lib/sigar-1.6.4/libsigar-x86-linux.so
  lib/sigar-1.6.4/libsigar-x86-solaris.so
  lib/sigar-1.6.4/sigar-amd64-winnt.dll
  lib/sigar-1.6.4/sigar-x86-winnt.dll
  lib/sigar-1.6.4/sigar-x86-winnt.lib
  lib/sigar-1.6.4/sigar.jar
  misc/graylog.conf
  pom.xml
Labels: improvement, ready-for-review

#9851 Retry read timeouts for Elasticsearch. (3.3)
  graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/GraylogJestRetryHandler.java
  graylog2-server/src/test/java/org/graylog2/indexer/cluster/jest/GraylogJestRetryHandlerTest.java
Labels: ready-for-review

#9924 Fix page size change selector in Content Pack list (4.0)
  graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
Labels: backport, ready-for-review

#9832 Add configured relative time range
  graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesClusterConfig.java
  graylog2-web-interface/src/components/configurations/SearchesConfig.jsx
  graylog2-web-interface/src/hooks/useSearchConfiguration.ts
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/ConfiguredRelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabRelativeTimeRange.tsx
Labels: ready-for-review

#9916 Do not allow selecting same pipeline stage twice
  graylog2-web-interface/src/components/pipelines/Pipeline.jsx
  graylog2-web-interface/src/components/pipelines/Stage.jsx
  graylog2-web-interface/src/components/pipelines/StageForm.jsx
Labels: ready-for-review

#9918 DateTimePicker limits for Absolute & Keyword
  graylog2-web-interface/src/components/common/DatePicker.jsx
  graylog2-web-interface/src/components/graylog/Accordion.tsx
  graylog2-web-interface/src/components/graylog/AccordionItem.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx
  graylog2-web-interface/src/views/components/__snapshots__/SearchBar.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteCalendar.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteCalendar.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteDatePicker.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteDatePicker.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeInput.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeInput.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimestamp.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/ConfiguredRelativeTimeRangeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabAbsoluteTimeRange.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabKeywordTimeRange.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabRelativeTimeRange.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/TabAbsoluteTimeRange.test.tsx.snap
Labels: ready-for-review

#9932 Creating separate form for date time picker.
  graylog2-web-interface/src/views/Constants.ts
  graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx
  graylog2-web-interface/src/views/components/SearchBar.tsx
  graylog2-web-interface/src/views/components/TimerangeForForm.ts
  graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteCalendar.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteCalendar.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimestamp.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabAbsoluteTimeRange.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabAbsoluteTimeRange.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabRelativeTimeRange.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabRelativeTimeRange.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.tsx
  graylog2-web-interface/src/views/logic/queries/Query.ts
Labels: ready-for-review

#9926 Avoid OSHI warnings with overlay and none fs types
  full-backend-tests/src/test/java/org/graylog/shared/system/stats/SystemStatsIT.java
  graylog2-server/src/main/java/org/graylog2/shared/system/stats/OshiService.java
  graylog2-server/src/main/java/org/graylog2/shared/utilities/DockerRuntimeDetection.java
Labels: ready-for-review

#9922 Retry read timeouts for Elasticsearch. (4.0)
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandler.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandlerTest.java
Labels: ready-for-review

#9852 Retry read timeouts for Elasticsearch.
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandler.java
  graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandlerTest.java
Labels: ready-for-review

#9942 DateTimePicker: Validate Keyword
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabKeywordTimeRange.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Labels: ready-for-review

#9968 Fixing stream rule form state update on input change.
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.tsx
Labels: bug, ready-for-review

#9937 DateTimePicker: Validate on Mount
  graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
  graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx
  graylog2-web-interface/src/views/components/SearchBar.tsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
Labels: ready-for-review

#9950 Add test for TimeRangeDropdown
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx
Labels: ready-for-review

#9960 Fix disk watermark notifications for multiple hosts.
  graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
Labels: bug

#9975 Fixing stream rule form state update on input change (4.0).
  graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx
Labels: backport, bug, ready-for-review

#9972 Retrying bulk indexing if target alias has invalid target(s). (3.3)
  graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
Labels: blocker, bug, elasticsearch

#9949 DateTimePicker: Updating remaining tests
  graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
  graylog2-web-interface/src/views/components/SearchBar.test.tsx
  graylog2-web-interface/src/views/components/SearchBar.tsx
  graylog2-web-interface/src/views/components/__snapshots__/SearchBar.test.tsx.snap
  graylog2-web-interface/src/views/components/searchbar/RefreshControls.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.test.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabAbsoluteTimeRange.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabAbsoluteTimeRange.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/TabAbsoluteTimeRange.test.tsx.snap
Labels: ready-for-review

#9923 Improving flexibility of app layout styling.
  graylog2-web-interface/src/components/gettingstarted/GettingStarted.jsx
  graylog2-web-interface/src/components/graylog/Navbar.jsx
  graylog2-web-interface/src/components/layout/Footer.tsx
  graylog2-web-interface/src/components/layout/PageContentLayout.tsx
  graylog2-web-interface/src/index.jsx
  graylog2-web-interface/src/pages/GettingStartedPage.tsx
  graylog2-web-interface/src/routing/App.jsx
  graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
  graylog2-web-interface/src/views/components/Search.tsx
Labels: improvement, ready-for-review

#9984 Adding more basic tests for `DashboardSearchBar`.
  graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
Labels: ready-for-review

#9990 Fix export to dashboard when graylog is behind a proxy
  graylog2-web-interface/src/views/logic/views/Actions.ts
Labels: ready-for-review, search

#9991 Fix export to dashboard when graylog is behind a proxy
  graylog2-web-interface/src/views/logic/views/Actions.js
Labels: backport, ready-for-review, search
