Repository Graylog2/graylog2-server, pull requests merged in 2021-05, with the labels that each got.

#10401 Expose limited indices information on Cloud
  graylog2-web-interface/src/components/indices/IndexDetails.jsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx
  graylog2-web-interface/src/components/indices/IndexSetDetails.css
  graylog2-web-interface/src/components/indices/IndexSetDetails.jsx
  graylog2-web-interface/src/components/navigation/SystemMenu.jsx
  graylog2-web-interface/src/pages/IndexSetPage.jsx
  graylog2-web-interface/src/routing/AppRouter.jsx
  graylog2-web-interface/src/stores/indexers/IndexerOverviewStore.js
  graylog2-web-interface/src/stores/indices/IndexRangesStore.js
  graylog2-web-interface/src/stores/indices/IndexSetsStore.jsx
  graylog2-web-interface/src/stores/indices/IndicesStore.js
Labels: ready-for-review

#10566 Encode usernames used in URLs
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.ts
  graylog2-web-interface/src/stores/users/PreferencesStore.ts
Labels: ready-for-review

#10567 Encode usernames used in URLs - 4.0
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/src/stores/users/PreferencesStore.js
Labels: ready-for-review

#10525 Implement Cancellable Promise
  graylog2-web-interface/src/logic/rest/CancellablePromise.test.ts
  graylog2-web-interface/src/logic/rest/CancellablePromise.ts
  graylog2-web-interface/src/logic/rest/FetchProvider.ts
Labels: ready-for-review, web

#10543 Add validation that a sort does not work on timebased charts
  graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/SortElement.test.ts
  graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/SortElement.ts
Labels: ready-for-review, search

#10528 Enhance error message for exception in pipeline rule
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-web-interface/src/components/simulator/SimulationResults.jsx
Labels: processing, ready-for-review

#10584 Blocked OutputBufferProcessor on Output update / removal
  graylog2-server/src/main/java/org/graylog2/buffers/processors/OutputBufferProcessor.java
Labels: bug, ready-for-review

#10512 Enable full backend tests for plugins
  full-backend-tests/pom.xml
  full-backend-tests/src/test/java/org/graylog/testing/backenddriver/SearchDriver.java
  full-backend-tests/src/test/java/org/graylog/testing/fullbackend/MongoDBFixturesWithClassLifecycleIT.java
  full-backend-tests/src/test/java/org/graylog/testing/fullbackend/MongoDBFixturesWithMethodLifecycleIT.java
  full-backend-tests/src/test/resources/org/graylog/testing/fullbackend/access-token.json
  graylog2-server/src/test/java/org/graylog/testing/completebackend/ApiIntegrationTest.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/DefaultMavenProjectDirProvider.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/DefaultPluginJarsProvider.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackendExtension.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/Lifecycle.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/MavenProjectDirProvider.java
  graylog2-server/src/test/java/org/graylog/testing/completebackend/PluginJarsProvider.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/MavenPackager.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
  graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBFixtureImporter.java
  graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBInstance.java
  graylog2-server/src/test/resources/api-it-tests.properties
Labels: ready-for-review

#10549 ClipboardButton button resize & update
  graylog2-web-interface/src/components/common/ClipboardButton.jsx
  graylog2-web-interface/src/components/graylog/Tooltip.jsx
  graylog2-web-interface/src/components/search/MessageDetail.jsx
  graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx
Labels: bug, ready-for-review

#10594 Sync cloud 4.0
  distribution/pom.xml
  full-backend-tests/pom.xml
  graylog-plugin-archetype/pom.xml
  graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
  graylog-plugin-parent/pom.xml
  graylog-project-parent/pom.xml
  graylog-storage-elasticsearch6/pom.xml
  graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
  graylog-storage-elasticsearch7/pom.xml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
  graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
  graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
  graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
  graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
  graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
  graylog2-web-interface/manifests/package.json
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/src/components/indexers/IndexerClusterHealthSummary.jsx
  graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
  graylog2-web-interface/src/stores/users/PreferencesStore.js
  graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
  graylog2-web-interface/yarn.lock
  pom.xml
Labels: ready-for-review

#10606 Use same colors for arrows on each side
  graylog2-web-interface/src/components/graylog/Popover.jsx
  graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Labels: ready-for-review, search

#10614 Change RequestFilter ordering (#10578)
  graylog2-server/src/main/java/org/graylog2/shared/rest/RequestIdFilter.java
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroRequestHeadersBinder.java
Labels: ready-for-review

#10621 Change back REQUEST_HEADERS access to public
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroRequestHeadersBinder.java
Labels: ready-for-review

#10620 Do not require a defaultValue to be set in Heatmap
  graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
  graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
Labels: ready-for-review, search

#10371 Adaptable Dashboard Tabs
  graylog2-web-interface/src/components/graylog/Nav.jsx
  graylog2-web-interface/src/components/graylog/NavDropdown.jsx
  graylog2-web-interface/src/components/graylog/styles/nav-tabs.js
  graylog2-web-interface/src/views/components/AdaptableQueryTabs.test.tsx
  graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx
  graylog2-web-interface/src/views/components/QueryBar.tsx
  graylog2-web-interface/src/views/components/QueryTabs.tsx
  graylog2-web-interface/src/views/components/Search.dashboard.test.tsx
Labels: dashboards, ready-for-review, ux

#10624 Style common `Select` based on `FormGroup` validation state.
  graylog2-web-interface/src/components/common/Select.tsx
  graylog2-web-interface/src/components/configurationforms/__snapshots__/ListField.test.tsx.snap
  graylog2-web-interface/src/components/graylog/FormGroup.jsx
Labels: improvement

#10636 Change back REQUEST_HEADERS access to public 4.0 backport (#10621)
  graylog2-server/src/main/java/org/graylog2/shared/security/ShiroRequestHeadersBinder.java
Labels: backport, ready-for-review

#10625 Configurations style
  graylog2-web-interface/src/components/configurations/ConfigurationStyles.lazy.css
  graylog2-web-interface/src/components/indices/IndicesConfiguration.jsx
  graylog2-web-interface/src/pages/ConfigurationsPage.tsx
  graylog2-web-interface/src/pages/configurations/ConfigletRow.tsx
  graylog2-web-interface/src/pages/configurations/PluginConfigRows.tsx
Labels: ready-for-review

#10664 Fix loading of Pipeline simulator page
  graylog2-web-interface/src/components/messageloaders/RawMessageLoader.tsx
  graylog2-web-interface/src/components/simulator/SimulationResults.jsx
Labels: ready-for-review

#10653 Use more secure TLS default ciphers
  graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/Main.java
  graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
Labels: ready-for-review

#10673 Prevent unnecessary search execution when unfocusing widget.
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
  graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
Labels: bug, search

#10667 Scratchpad Updates & Tests
  graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx
  graylog2-web-interface/src/components/common/InteractableModal.jsx
  graylog2-web-interface/src/components/common/Scratchpad.test.jsx
  graylog2-web-interface/src/components/common/Scratchpad.test.tsx
  graylog2-web-interface/src/components/common/Scratchpad.tsx
  graylog2-web-interface/src/components/common/__snapshots__/Scratchpad.test.jsx.snap
Labels: bug, ready-for-review

#10701 Don't skip assembly step in full backend tests
  graylog2-server/src/test/java/org/graylog/testing/graylognode/MavenPackager.java
Labels: ready-for-review

#10699 Feature/full backend tests/expose docker network
  graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
Labels: ready-for-review

#10537 Fix filtering for `id` on paginated resources
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRoleDTO.java
  graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/main/java/org/graylog2/search/SearchQueryField.java
  graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java
  graylog2-web-interface/src/components/common/QueryHelper.tsx
  graylog2-web-interface/src/components/common/index.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
  graylog2-web-interface/src/components/streams/StreamComponent.jsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.tsx
  graylog2-web-interface/src/views/components/views/ViewList.jsx
Labels: ready-for-review, web

#10692 Add cluster-wide lookup table cache purge
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
  graylog2-server/src/main/java/org/graylog2/lookup/events/AdapterSharedStoresUpdated.java
Labels: feature, java, ready-for-review

#10715 Reset page when searching on steam overview
  graylog2-web-interface/src/components/streams/StreamComponent.jsx
Labels: ready-for-review, web

#10731 Group selection on filtered content pack entities
  graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
Labels: content-packs, ready-for-review, web

#10619 Hide PlotLegend with only one element
  graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx
  graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
Labels: ready-for-review, search

#10702 Update fetchProvider and fetchError to handle error
  graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.tsx
  graylog2-web-interface/src/logic/errors/FetchError.ts
  graylog2-web-interface/src/logic/rest/FetchProvider.test.ts
  graylog2-web-interface/src/logic/rest/FetchProvider.ts
  graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.tsx
  graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.tsx
  graylog2-web-interface/src/stores/pipelines/PipelinesStore.ts
  graylog2-web-interface/src/stores/rules/RulesStore.ts
Labels: ready-for-review

#10730 Fix date format in outgoing traffic graphs
  graylog2-web-interface/src/components/cluster/TrafficGraph.tsx
Labels: ready-for-review, web

#10734 Fix request path matching in MessageExportFormatFilter
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessageExportFormatFilter.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/MessageExportFormatFilterTest.java
Labels: ready-for-review

#10719 Theme Spacings feature
  graylog2-web-interface/docs/StyleGuideWrapper.tsx
  graylog2-web-interface/src/@types/styled-components/index.d.ts
  graylog2-web-interface/src/components/common/ReactGridContainer.jsx
  graylog2-web-interface/src/components/graylog/Row.tsx
  graylog2-web-interface/src/components/layout/Footer.tsx
  graylog2-web-interface/src/components/layout/PageContentLayout.tsx
  graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap
  graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.tsx.snap
  graylog2-web-interface/src/theme/GraylogThemeProvider.tsx
  graylog2-web-interface/src/theme/constants.ts
  graylog2-web-interface/src/theme/docs/Spacings.md
  graylog2-web-interface/src/theme/fonts.ts
  graylog2-web-interface/src/theme/index.ts
  graylog2-web-interface/src/theme/spacings.ts
  graylog2-web-interface/styleguide.config.js
  graylog2-web-interface/test/WrappingContainer.jsx
Labels: frontend, ready-for-review, ux

#10687 Make all WildcardPermission case sensitive
  graylog2-server/src/main/java/org/graylog/security/DefaultPermissionAndRoleResolver.java
  graylog2-server/src/main/java/org/graylog/security/permissions/CaseSensitiveWildcardPermission.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java
  graylog2-server/src/main/java/org/graylog2/security/InMemoryRolePermissionResolver.java
  graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
  graylog2-server/src/main/java/org/graylog2/security/realm/RootAccountRealm.java
  graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
  graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
  graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserImplTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Labels: bug, ready-for-review
