Repository Graylog2/graylog2-server, pull requests merged in 2022-06, with the labels that each got.

#12753 Check permissions for EnterpriseTrafficGraph (4.3 backport)
  graylog2-web-interface/src/components/cluster/GraylogClusterOverview.tsx
Labels: ready-for-review

#12704 fix: don't render inactive notifications
  graylog2-web-interface/src/components/common/PublicNotifications.test.tsx
  graylog2-web-interface/src/components/common/PublicNotifications.tsx
Labels: bug, ready-for-review

#12764 refactoring of PrometheusExporter for graylog forwarder
  graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporter.java
  graylog2-server/src/test/java/org/graylog/metrics/prometheus/PrometheusExporterTest.java
Labels: ready-for-review

#12860 Fixing event definitions page when no event definitions exist.
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.test.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.tsx
Labels: bug

#12885 remove debug code JobSchedulerResource (#12874)
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerModule.java
  graylog2-server/src/main/java/org/graylog/scheduler/rest/JobSchedulerResource.java
Labels: backport

#12884 remove debug code JobSchedulerResource (#12874)
  graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerModule.java
  graylog2-server/src/main/java/org/graylog/scheduler/rest/JobSchedulerResource.java
Labels: backport

#12906 Added Graylog Schema Enforcement check to GeoIpResolverEngine when selecting field name prefix to add to message
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java
Labels: bug

#12914 Backport Show max retention period warning when it is set
  graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.jsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.test.tsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
  graylog2-web-interface/src/components/indices/Types.ts
  graylog2-web-interface/src/components/indices/retention/ClosingRetentionStrategyConfiguration.jsx
  graylog2-web-interface/src/components/indices/retention/ClosingRetentionStrategySummary.jsx
  graylog2-web-interface/src/components/indices/retention/DeletionRetentionStrategyConfiguration.jsx
  graylog2-web-interface/src/components/indices/retention/DeletionRetentionStrategySummary.jsx
  graylog2-web-interface/src/components/indices/retention/NoopRetentionStrategyConfiguration.jsx
  graylog2-web-interface/src/components/indices/retention/NoopRetentionStrategySummary.jsx
  graylog2-web-interface/src/components/indices/rotation/MessageCountRotationStrategyConfiguration.jsx
  graylog2-web-interface/src/components/indices/rotation/MessageCountRotationStrategySummary.jsx
  graylog2-web-interface/src/components/indices/rotation/SizeBasedRotationStrategyConfiguration.jsx
  graylog2-web-interface/src/components/indices/rotation/SizeBasedRotationStrategySummary.jsx
  graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
  graylog2-web-interface/src/pages/IndexSetCreationPage.tsx
  graylog2-web-interface/src/stores/indices/IndicesConfigurationStore.ts
Labels: ready-for-review
