Repository Graylog2/graylog2-server, pull requests merged in 2022-10, with the labels that each got.

#13620 Fix #13618: Entity lists do not refresh after deleting item
  graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.tsx
  graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.tsx
  graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.tsx
  graylog2-web-interface/src/views/components/views/DashboardList.tsx
  graylog2-web-interface/src/views/pages/DashboardsPage.tsx
Labels: ready-for-review

#13647 Use collector DB ID instead of entity ID when creating Sidecar Config…
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
Labels: backport

#13662 Sidecar Collector: Fix empty content pack export when optional fields are blank (Backport of #13645)
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorEntity.java
Labels: backport

#13664 Add include today count traffic option (4.3)
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/TrafficResource.java
  graylog2-server/src/main/java/org/graylog2/system/traffic/TrafficCounterService.java
  graylog2-server/src/test/java/org/graylog2/system/traffic/TrafficCounterServiceTest.java
Labels: backport

#13717 Adjust page size for pagination on event definitions
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.tsx
Labels: ready-for-review, frontend, needs-backport

#13707 default retention time & max value via config
  UPGRADING.md
  graylog2-server/src/main/java/org/graylog2/Configuration.java
Labels: feature, ready-for-review

#13433 Sidecar support for tags and collectors with multiple configurations
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/common/SidecarPluginConfiguration.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/CollectorStatus.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Configuration.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/ConfigurationSummary.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/NodeDetails.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Sidecar.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/requests/BulkActionRequest.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/requests/ConfigurationAssignment.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationVariableResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ActionService.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/EtagCacheInvalidation.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/EtagService.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/SidecarService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
  graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/ConfigurationServiceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/SidecarServiceImplTest.java
  graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/SidecarServiceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/rest/SidecarResourceTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/sidecar/collectors/collectorsSingleDataset.json
  graylog2-server/src/test/resources/org/graylog/plugins/sidecar/collectors/sidecars.json
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.test.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModalContainer.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationSelector.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorProcessControl.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorProcessControl.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.css
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationActions.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationActions.tsx
  graylog2-web-interface/src/components/sidecars/common/ColorLabel.tsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationTagsSelect.tsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.tsx
  graylog2-web-interface/src/components/sidecars/types.d.ts
  graylog2-web-interface/src/pages/SidecarEditConfigurationPage.jsx
  graylog2-web-interface/src/pages/SidecarEditConfigurationPage.tsx
  graylog2-web-interface/src/pages/SidecarNewConfigurationPage.jsx
  graylog2-web-interface/src/pages/SidecarNewConfigurationPage.tsx
Labels: ready-for-review, sidecar, ux

#13743 Reload Pipelines after Delete
  graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.tsx
Labels: ready-for-review

#13720 Backport adjust page sizes for Event Definitions
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
Labels: ready-for-review, backport, frontend

#13746 Fix search form width bug
  graylog2-web-interface/src/components/common/SearchForm.jsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.tsx
Labels: ready-for-review

#13663 Cannot install content pack with event definition that uses default stream (Backport 4.3 for #7212)
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
Labels: backport
