Repository Graylog2/graylog2-server, pull requests merged in 2022-08, with the labels that each got.

#13099 skip index rotation on empty index
  graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java
  graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyConfig.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20151210140600_ElasticsearchConfigMigration.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20190705071400_AddEventIndexSetsMigration.java
  graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyConfigTest.java
  graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.test.tsx
  graylog2-web-interface/src/components/indices/Types.ts
  graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx
Labels: feature

#13048 Add SystemEntity annotation and add to LookupTableService
  graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
  graylog2-server/src/main/java/org/graylog2/system/SystemEntity.java
Labels: immutable-entities

#13177 add flag ignore_migration_failures (#13137)
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
  misc/graylog.conf
Labels: backport

#13115 Adding frontend changes to event definitions
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.tsx
  graylog2-web-interface/src/hooks/useScopePermissions.ts
  graylog2-web-interface/src/routing/ApiRoutes.ts
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
  graylog2-web-interface/test/fixtures/eventDefinition.ts
Labels: immutable-entities

#13171 Properly register Event Notification config entity subtypes
  UPGRADING.md
  graylog2-server/src/main/java/org/graylog/events/EventsModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
Labels: ready-for-review

#13058 Immutable Event Definitions
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventDefinitionEntity.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java
  graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinition.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
  graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/DBEventProcessorServiceTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionHandlerTest.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfigTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20200102140000_UnifyEventSeriesIdTestIT.java
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.tsx
  graylog2-web-interface/src/hooks/useScopePermissions.ts
  graylog2-web-interface/src/routing/ApiRoutes.ts
  graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
  graylog2-web-interface/test/fixtures/eventDefinition.ts
Labels: immutable-entities

#13197 Backport: Properly register notification config entity subtypes
  UPGRADING.md
  graylog2-server/src/main/java/org/graylog/events/EventsModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
Labels: backport

#13069 Fix/#13066 Validate username without loading all the users
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.tsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx
  graylog2-web-interface/src/components/users/UserCreate/UsernameFormGroup.tsx
Labels: ready-for-review

#13193 Fix #12971 Event Definition broken find button
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.jsx
Labels: ready-for-review

#13187 align api for import/export extractor calls
  UPGRADING.md
  graylog2-server/src/main/java/org/graylog2/rest/models/system/inputs/extractors/requests/CreateExtractorRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java
  graylog2-web-interface/src/stores/extractors/ExtractorsStore.js
Labels: bug

#13269 Backport for 4.3: fix ConfirmDialog close behaviour via X button (or pressing ESC or clicking on the background)
  graylog2-web-interface/src/components/common/ConfirmDialog.tsx
  graylog2-web-interface/src/components/common/index.tsx
Labels: bug, backport, ux, frontend

#13264 Fix 3745 Trim whitespace on UI entry fields
  graylog2-web-interface/src/components/streams/Stream.jsx
  graylog2-web-interface/src/util/ObjectUtils.test.js
  graylog2-web-interface/src/util/ObjectUtils.ts
Labels: ready-for-review
