Repository Graylog2/graylog2-server, pull requests merged in 2022-07, with the labels that each got.

#12250 Add Custom Menu List with using react-window when more then 1000 options
  graylog2-web-interface/src/components/bootstrap/FormGroup.jsx
  graylog2-web-interface/src/components/common/Select/CustomMenuList.test.tsx
  graylog2-web-interface/src/components/common/Select/CustomMenuList.tsx
  graylog2-web-interface/src/components/common/Select/Select.test.jsx
  graylog2-web-interface/src/components/common/Select/Select.tsx
  graylog2-web-interface/src/components/common/Select/index.tsx
  graylog2-web-interface/yarn.lock
Labels: frontend

#13000 fix issue when editing indexSet from details
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
Labels: ready-for-review

#13027 add behaviour change descirption of FS archiving backend
  UPGRADING.md
Labels: ready-for-review

#13044 Backport the bugfix to consider active attribute on notification
  graylog2-web-interface/src/components/common/PublicNotifications.test.tsx
  graylog2-web-interface/src/components/common/PublicNotifications.tsx
Labels: bug, ready-for-review, backport

#13119 fix issue when editing indexSet from details 4.3 backport(#13000)
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
Labels: bug, backport, frontend

#13102 4.3 Backport: Use legacy Geo IP fields if GIM schema enforcement is disabled (#13094)
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java
  graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java
Labels: backport

#13080 Feature/immutable data adapters
  graylog2-web-interface/src/components/common/router.tsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapter.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapter.tsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterTableEntry.jsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterTableEntry.test.tsx
  graylog2-web-interface/src/components/lookup-tables/DataAdapterTableEntry.tsx
  graylog2-web-interface/src/components/lookup-tables/ErrorPopover.tsx
Labels: immutable-entities

#13132 Add default param to set_field function
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetField.java
Labels: bug

#13032 Core System Entity/Immutable Entities
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityWithExcerptFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/ScopedContentPackEntity.java
  graylog2-server/src/main/java/org/graylog2/database/entities/DefaultEntityScope.java
  graylog2-server/src/main/java/org/graylog2/database/entities/EntityScope.java
  graylog2-server/src/main/java/org/graylog2/database/entities/EntityScopeResource.java
  graylog2-server/src/main/java/org/graylog2/database/entities/EntityScopeResponse.java
  graylog2-server/src/main/java/org/graylog2/database/entities/EntityScopeService.java
  graylog2-server/src/main/java/org/graylog2/database/entities/EntityScopes.java
  graylog2-server/src/main/java/org/graylog2/database/entities/ScopedDbService.java
  graylog2-server/src/main/java/org/graylog2/database/entities/ScopedEntitiesModule.java
  graylog2-server/src/main/java/org/graylog2/database/entities/ScopedEntity.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/test/java/org/graylog2/database/entities/ScopedDbServiceTest.java
  graylog2-server/src/test/java/org/graylog2/database/entities/ScopedEntityTest.java
  graylog2-server/src/test/java/org/graylog2/database/entities/TestScopedEntity.java
  graylog2-server/src/test/java/org/graylog2/database/entities/TestScopedEntityDBService.java
Labels: immutable-entities

#13093 Added additional validation of email configuration
  graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
Labels: feature
