Repository Graylog2/graylog2-server, pull requests merged in 2022-02, with the labels that each got.

#12089 Add support for view resolvers for GET view API endpoint
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewResolver.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewResolverDecoder.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardEntityCreator.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewResolverDecoderTest.java
Labels: ready-for-review

#12122 Use current time per default for the `Timestamp`, `RelativeTime` and `BrowserTime` component when `dateTime` prop is not defined.
  graylog2-web-interface/src/components/common/BrowserTime.test.tsx
  graylog2-web-interface/src/components/common/BrowserTime.tsx
  graylog2-web-interface/src/components/common/RelativeTime.test.tsx
  graylog2-web-interface/src/components/common/RelativeTime.tsx
  graylog2-web-interface/src/components/common/Timestamp.test.tsx
  graylog2-web-interface/src/components/common/Timestamp.tsx
Labels: bug

#12110 Improve indexing field names performance for field name completion.
  graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.ts
  graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.ts
Labels: performance, bug

#12150 Add props onClick, onMouseEnter, onMouseLeave, onFocus, tabIndex, title to Icon component
  graylog2-web-interface/src/components/common/Icon.tsx
Labels: ready-for-review, frontend

#12181 Always register ViewResolvers as singletons
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
Labels: ready-for-review

#12113 Show traffic limit on cluster overview Traffic Graph
  graylog2-web-interface/src/components/cluster/GraylogClusterOverview.jsx
  graylog2-web-interface/src/components/cluster/GraylogClusterOverview.tsx
  graylog2-web-interface/src/components/cluster/TrafficGraph.tsx
  graylog2-web-interface/src/components/cluster/types.d.ts
  graylog2-web-interface/src/stores/cluster/ClusterTrafficStore.js
  graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
Labels: ready-for-review
