Repository Graylog2/graylog2-server, pull requests merged in 2023-01, with the labels that each got.

#14388 5.0 Backport: Add postBulkUpdate to cache, data adapter, and lookup table DB services
  graylog2-server/src/main/java/org/graylog2/lookup/db/DBCacheService.java
  graylog2-server/src/main/java/org/graylog2/lookup/db/DBDataAdapterService.java
  graylog2-server/src/main/java/org/graylog2/lookup/db/DBLookupTableService.java
Labels: backport

#13931 Add Replay Search link to expanded Event/Alert description
  changelog/unreleased/issue-9438.toml
  graylog2-server/src/main/java/org/graylog/events/event/Event.java
  graylog2-server/src/main/java/org/graylog/events/event/EventDto.java
  graylog2-server/src/main/java/org/graylog/events/event/EventImpl.java
  graylog2-server/src/main/java/org/graylog/events/event/EventReplayInfo.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionLink.tsx
  graylog2-web-interface/src/components/events/events/EventDetails.jsx
  graylog2-web-interface/src/components/events/events/EventDetails.tsx
  graylog2-web-interface/src/components/events/events/EventFields.tsx
  graylog2-web-interface/src/components/events/events/types.ts
  graylog2-web-interface/src/routing/Routes.ts
  graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.test.tsx
  graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx
Labels: secdev-cycle6

#14412 Set default grace_period to 5mn in Event Definition
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
Labels: ready-for-review

#13783 Make BootstrapModals (Wrapper / Form / Confirm) fully controllable
  graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.md
  graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.tsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.test.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.test.tsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.tsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx
  graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.tsx
  graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx
  graylog2-web-interface/src/components/configurations/DecoratorsConfig.tsx
  graylog2-web-interface/src/components/configurations/EventsConfig.jsx
  graylog2-web-interface/src/components/configurations/MessageProcessorsConfig.jsx
  graylog2-web-interface/src/components/configurations/SearchesConfig.jsx
  graylog2-web-interface/src/components/configurations/SidecarConfig.jsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.tsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsConfigUpdate.tsx
  graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackInstallations.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackParameters.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackUploadControls.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx
  graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EditQueryParameterModal.tsx
  graylog2-web-interface/src/components/extractors/ExtractorSortModal.jsx
  graylog2-web-interface/src/components/grok-patterns/BulkLoadPatternModal.jsx
  graylog2-web-interface/src/components/grok-patterns/EditPatternModal.jsx
  graylog2-web-interface/src/components/indices/IndexSetDeletionForm.jsx
  graylog2-web-interface/src/components/inputs/StaticFieldForm.jsx
  graylog2-web-interface/src/components/permissions/EntityShareModal.tsx
  graylog2-web-interface/src/components/pipelines/PipelineConnectionsForm.tsx
  graylog2-web-interface/src/components/pipelines/PipelineForm.tsx
  graylog2-web-interface/src/components/pipelines/StageForm.tsx
  graylog2-web-interface/src/components/rules/RuleMetricsConfig.jsx
  graylog2-web-interface/src/components/rules/RuleMetricsConfigContainer.jsx
  graylog2-web-interface/src/components/scratchpad/Scratchpad.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModalContainer.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorProcessControl.tsx
  graylog2-web-interface/src/components/sidecars/common/CloneMenuItem.tsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationVariablesHelper.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/EditConfigurationVariableModal.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/ImportsViewModal.jsx
  graylog2-web-interface/src/components/sidecars/configuration-forms/SourceViewModal.jsx
  graylog2-web-interface/src/components/sidecars/configurations/CopyCollectorModal.jsx
  graylog2-web-interface/src/components/sidecars/configurations/CopyConfigurationModal.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/VerboseMessageModal.jsx
  graylog2-web-interface/src/components/users/UserCreate/ServiceAccountFormGroup.tsx
  graylog2-web-interface/src/pages/ShowContentPackPage.jsx
  graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.tsx
  graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.tsx
  graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.tsx
  graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.tsx
  graylog2-web-interface/src/views/logic/valueactions/SelectExtractorType.tsx
Labels: ready-for-review

#14405 Fix filtering and loader on the Lookup Table pages
  changelog/unreleased/issue-14318.toml
  graylog2-web-interface/src/components/lookup-tables/CachesOverview.tsx
  graylog2-web-interface/src/components/lookup-tables/DataAdaptersOverview.tsx
  graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.tsx
  graylog2-web-interface/src/pages/LUTCachesPage.jsx
  graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx
  graylog2-web-interface/src/pages/LUTTablesPage.jsx
Labels: ready-for-review

#14439 Update Input configuration form to use controlled Modal
  graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx
Labels: ready-for-review

#14409 Reduce logging and add metric for stream warning
  changelog/unreleased/pr-14409.toml
  graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
  graylog2-server/src/main/resources/prometheus-exporter.yml
  graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
Labels: needs-backport

#14460 Reduce logging and add metric for stream warning (5.0)
  changelog/unreleased/pr-14409.toml
  graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
  graylog2-server/src/main/resources/prometheus-exporter.yml
  graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
Labels: backport

#14461 Reduce logging and add metric for stream warning (4.3)
  changelog/unreleased/pr-14409.toml
  graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
  graylog2-server/src/main/resources/prometheus-exporter.yml
  graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
Labels: backport

#14391 (Backport 5.0) Prevent changing unmodifiable Event Definition condition types
  changelog/unreleased/pr-14110.toml
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-server/src/test/java/org/graylog/events/rest/EventDefinitionsResourceTest.java
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.jsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.tsx
  graylog2-web-interface/src/components/event-definitions/types.d.ts
Labels: backport

#14337 Add reply-to to email notification config
  changelog/unreleased/issue-14254.toml
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EmailEventNotificationConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
  graylog2-web-interface/src/components/event-notifications/event-notification-details/EmailNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.jsx
Labels: ready-for-review

#14343 Add global user session timeout configuration
  changelog/unreleased/issue-11379.toml
  graylog2-server/src/main/java/org/graylog/security/authservice/ProvisionerService.java
  graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java
  graylog2-server/src/main/java/org/graylog2/users/UserConfiguration.java
  graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
  graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
  graylog2-server/src/test/java/org/graylog/security/UserContextTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardV1FacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/ViewFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/MigrationHelpersTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserImplTest.java
  graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
  graylog2-web-interface/src/components/common/ISODurationInput.jsx
  graylog2-web-interface/src/components/common/ReadOnlyFormGroup.tsx
  graylog2-web-interface/src/components/configurations/UserConfig.tsx
  graylog2-web-interface/src/components/users/TimeoutInput.tsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.tsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx
  graylog2-web-interface/src/components/users/UserDetails/SettingsSection.tsx
  graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx
  graylog2-web-interface/src/hooks/useIsGlobalTimeoutEnabled.ts
  graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx
  graylog2-web-interface/src/pages/ConfigurationsPage.tsx
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.ts
Labels: ready-for-review
