Repository Graylog2/graylog2-server, pull requests merged in 2023-05, with the labels that each got.

#15155 Index Set Page Performance Improvements
  changelog/unreleased/issue-12498.toml
  graylog2-server/src/main/java/org/graylog2/indexer/IndexSetRegistry.java
  graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSetRegistry.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetService.java
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/MongoIndexSetService.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsResource.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/IndexSetsResourceTest.java
  graylog2-web-interface/src/components/indices/IndexSetsComponent.jsx
  graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
  graylog2-web-interface/src/routing/ApiRoutes.ts
  graylog2-web-interface/src/stores/indices/IndexSetsStore.ts
Labels: performance, ready-for-review

#15384 Fix: BulkActions dialog not closing after clicking on Confirm
  changelog/unreleased/issue-15259.toml
  graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx
Labels: ready-for-review

#15456 Fix issue when loading modal out of router context
  graylog2-web-interface/src/components/common/withModalTelemetry.tsx
  graylog2-web-interface/src/components/common/withPopoverTelemetry.tsx
Labels: ready-for-review

#15447 Backport: Telemetry data adjustment (#15438)
  graylog2-server/src/main/java/org/graylog2/telemetry/cluster/TelemetryClusterInfoPeriodical.java
  graylog2-server/src/main/java/org/graylog2/telemetry/cluster/TelemetryClusterService.java
  graylog2-server/src/main/java/org/graylog2/telemetry/cluster/db/DBTelemetryClusterInfo.java
  graylog2-server/src/main/java/org/graylog2/telemetry/enterprise/TelemetryLicenseStatus.java
  graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryResponseFactory.java
  graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryService.java
  graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceTest.java
  graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceWithDbTest.java
  graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryTestHelper.java
  graylog2-web-interface/src/components/authentication/AuthenticatorsEdit/HTTPHeaderAuthConfigSection.tsx
  graylog2-web-interface/src/components/authentication/BackendCreate/ServiceSelect.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/GroupSyncStep.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.tsx
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserSyncStep.tsx
  graylog2-web-interface/src/components/cluster/GraylogClusterOverview.tsx
  graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx
  graylog2-web-interface/src/components/common/withModalTelemetry.tsx
  graylog2-web-interface/src/components/common/withPopoverTelemetry.tsx
  graylog2-web-interface/src/components/configurations/IndexSetsDefaultsConfig.tsx
  graylog2-web-interface/src/components/configurations/PermissionsConfig.tsx
  graylog2-web-interface/src/components/configurations/SearchesConfig.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.tsx
  graylog2-web-interface/src/components/configurations/UserConfig.tsx
  graylog2-web-interface/src/components/configurations/decorators/DecoratorsConfigUpdate.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/BulkActions.tsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationActions.tsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.tsx
  graylog2-web-interface/src/components/inputs/CreateInputControl.jsx
  graylog2-web-interface/src/components/inputs/InputListItem.jsx
  graylog2-web-interface/src/components/inputs/InputStateControl.jsx
  graylog2-web-interface/src/components/loggers/LogLevelDropdown.jsx
  graylog2-web-interface/src/components/loggers/NodeLoggers.jsx
  graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.tsx
  graylog2-web-interface/src/components/outputs/OutputsComponent.jsx
  graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.tsx
  graylog2-web-interface/src/components/streams/CreateStreamButton.tsx
  graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
  graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx
  graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.tsx
  graylog2-web-interface/src/logic/telemetry/NavigationTelemetry.tsx
  graylog2-web-interface/src/logic/telemetry/TelemetryContext.tsx
  graylog2-web-interface/src/logic/telemetry/TelemetryProvider.tsx
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
  graylog2-web-interface/src/pages/IndexSetCreationPage.tsx
  graylog2-web-interface/src/threatintel/components/ThreatIntelPluginConfig.jsx
  graylog2-web-interface/src/views/components/CreateNewWidgetModal.tsx
  graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx
  graylog2-web-interface/src/views/components/searchbar/RangePresetDropdown.tsx
  graylog2-web-interface/src/views/components/searchbar/RefreshControls.tsx
  graylog2-web-interface/src/views/components/searchbar/SearchButton.tsx
  graylog2-web-interface/src/views/components/searchbar/StreamsFilter.tsx
  graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.tsx
  graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
  graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.tsx
Labels: ready-for-review

#15469 Backport (5.1): Fix BulkActions dialog not closing after clicking on Confirm (#15384)
  changelog/unreleased/issue-15259.toml
  graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx
Labels: ready-for-review

#15357 Fix pagination problems on Events page
  changelog/unreleased/issue-15273.toml
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/events/events/EventsContainer.jsx
  graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx
  graylog2-web-interface/src/stores/events/EventsStore.js
Labels: ready-for-review

#15480 accept json to simulate rules
  changelog/unreleased/pr-15480.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineRuleService.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/RuleResource.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/simulator/RuleSimulator.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/RuleResourceTest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/simulator/RuleSimulatorTest.java
  graylog2-web-interface/src/components/rules/RuleForm.tsx
Labels: feature

#15516 Add use-query-params to vendor-module
  graylog2-web-interface/package.json
  graylog2-web-interface/packages/graylog-web-plugin/package.json
  graylog2-web-interface/vendor.modules.js
  graylog2-web-interface/webpack/vendor-module-ids.json
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#15374 Backport (5.0): Fix extractors reordering issues (#14757)
  changelog/unreleased/issue-14693.toml
  graylog2-web-interface/src/components/extractors/ExtractorSortModal.jsx
  graylog2-web-interface/src/components/extractors/ExtractorsList.jsx
  graylog2-web-interface/src/pages/ExtractorsPage.jsx
Labels: ready-for-review, backport

#15606 Define vendor_subtype GIM field (5.1)
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Labels: backport

#15607 Define vendor_subtype GIM field (5.0)
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Labels: backport

#15554 Use dynamic path for Dashboard telemetry
  graylog2-web-interface/src/util/URLUtils.ts
  graylog2-web-interface/src/views/components/widgets/Widget.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.tsx
Labels: ready-for-review

#15644 backport - rename traffic stats (#15636)
  graylog2-web-interface/src/logic/telemetry/TelemetryProvider.tsx
Labels: ready-for-review
