Repository Graylog2/graylog2-server, pull requests merged in 2023-07, with the labels that each got.

#15842 feat: Modifies route active check to account for nested routes
  graylog2-web-interface/src/components/navigation/Navigation.tsx
Labels: security

#15806 Backport handle opt in/out capturing (#15743)
  graylog2-web-interface/src/logic/telemetry/TelemetryProvider.tsx
  graylog2-web-interface/src/logic/telemetry/TelemetrySettingsConfig.tsx
Labels: ready-for-review

#15915 Fix join / substring pipeline function parameter name (#15891)
  changelog/unreleased/issue-11868.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Join.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Substring.java
Labels: backport

#15883 Rule Builder UI Help Icon
  graylog2-web-interface/src/components/rules/Rule.jsx
  graylog2-web-interface/src/components/rules/RuleHelper.jsx
  graylog2-web-interface/src/components/rules/rule-builder/RuleBlockForm.tsx
  graylog2-web-interface/src/components/rules/rule-builder/RuleBuilder.tsx
  graylog2-web-interface/src/components/rules/rule-helper/RuleHelper.css
  graylog2-web-interface/src/components/rules/rule-helper/RuleHelper.tsx
  graylog2-web-interface/src/components/rules/rule-helper/RulerHelperTable.tsx
  graylog2-web-interface/src/components/rules/rule-helper/helpers.ts
Labels: feature, frontend

#16060 add prometheus example configuration for archiver
  misc/archiver.conf
Labels: ready-for-review
