Repository Graylog2/graylog2-server, pull requests merged in 2023-04, with the labels that each got.

#14892 Execute a single rule in isolation
  changelog/unreleased/issue-14891.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/RuleResource.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/SimulateRuleRequest.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/RuleResourceTest.java
  graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
  graylog2-web-interface/src/components/rules/RuleContext.tsx
  graylog2-web-interface/src/components/rules/RuleForm.test.tsx
  graylog2-web-interface/src/components/rules/RuleForm.tsx
  graylog2-web-interface/src/components/search/MessageDetail.jsx
  graylog2-web-interface/src/components/search/MessageFields.jsx
  graylog2-web-interface/src/components/search/MessageShow.jsx
  graylog2-web-interface/src/routing/ApiRoutes.ts
  graylog2-web-interface/src/stores/rules/RulesStore.ts
Labels: ready-for-review

#15147 Add undo reset button to encrypted form fields
  changelog/unreleased/issue-14767.toml
  graylog2-web-interface/src/components/configurationforms/BooleanField.tsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationFormField.tsx
  graylog2-web-interface/src/components/configurationforms/DropdownField.tsx
  graylog2-web-interface/src/components/configurationforms/EncryptedInlineBinaryField.tsx
  graylog2-web-interface/src/components/configurationforms/ListField.tsx
  graylog2-web-interface/src/components/configurationforms/NumberField.tsx
  graylog2-web-interface/src/components/configurationforms/TextField.tsx
  graylog2-web-interface/src/components/configurationforms/TitleField.tsx
Labels: ready-for-review, ux

#15154 Input form: Only reset title when initial title changes or modal is closed
  graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx
Labels: bug, ux

#15069 Backport Use different set of database types on cloud (#13911)
  changelog/unreleased/issue-1065.toml
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.test.tsx
  graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.tsx
Labels: ready-for-review

#15025 Configuration Form Makeover
  changelog/unreleased/issue-14735.toml
  graylog2-web-interface/src/components/configurations/ConfigurationTypes.ts
  graylog2-web-interface/src/components/configurations/EventsConfig.jsx
  graylog2-web-interface/src/components/configurations/EventsConfig.tsx
  graylog2-web-interface/src/components/configurations/IndexSetsDefaultsConfig.tsx
  graylog2-web-interface/src/components/configurations/MessageProcessorsConfig.jsx
  graylog2-web-interface/src/components/configurations/MessageProcessorsConfig.tsx
  graylog2-web-interface/src/components/configurations/PermissionsConfig.tsx
  graylog2-web-interface/src/components/configurations/PluginsConfig.tsx
  graylog2-web-interface/src/components/configurations/SearchesConfig.tsx
  graylog2-web-interface/src/components/configurations/SidecarConfig.jsx
  graylog2-web-interface/src/components/configurations/SidecarConfig.test.tsx
  graylog2-web-interface/src/components/configurations/SidecarConfig.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.test.tsx
  graylog2-web-interface/src/components/configurations/UrlWhiteListConfig.tsx
  graylog2-web-interface/src/components/configurations/UserConfig.tsx
  graylog2-web-interface/src/components/configurations/helpers.ts
  graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.tsx
  graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx
  graylog2-web-interface/src/pages/ConfigurationsPage.tsx
  graylog2-web-interface/src/pages/configurations/ConfigletContainer.tsx
  graylog2-web-interface/src/pages/configurations/ConfigurationSection.tsx
  graylog2-web-interface/src/pages/configurations/PluginConfigRows.tsx
Labels: performance, ready-for-review, ux, frontend

#15098 fix inputs ui route in cloud
  graylog2-web-interface/src/routing/AppRouter.tsx
Labels: bug, ready-for-review

#15226 Fix: Unable to add custom field when creating event definition
  changelog/unreleased/issue-15209.toml
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.tsx
Labels: ready-for-review

#15247 show edit telemetry setting for builtin admin
  changelog/unreleased/issue-15244.toml
  graylog2-web-interface/src/components/users/UserDetails/UserDetails.tsx
  graylog2-web-interface/src/logic/telemetry/TelemetrySettingsConfig.tsx
Labels: ready-for-review

#15293 Fix sidecar process button position issue on safari
  changelog/unreleased/issue-14939.toml
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx
Labels: ready-for-review

#15286 Fix: Allow creating notification in event definition wizard when no notification exists
  changelog/unreleased/issue-13825.toml
  graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
Labels: ready-for-review
