Repository Graylog2/graylog2-server, pull requests merged in 2023-11, with the labels that each got.

#17138 (Backport 5.1) - Add Alert Notification ID to System Notification for Missing Email Recipients
  changelog/unreleased/issue-16988.toml
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
Labels: backport

#17137 (Backport 5.2) - Add Alert Notification ID to System Notification for Missing Email Recipients
  changelog/unreleased/issue-16988.toml
  graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
Labels: backport

#17104 Move existing DataNode config into separate page
  changelog/unreleased/issue-17085.toml
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CertificateRenewal.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CertificateRenewalPolicyConfig.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/DataNodeConfiguration.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/index.tsx
  graylog2-web-interface/src/components/datanode/DataNodesPageNavigation.tsx
  graylog2-web-interface/src/components/navigation/SystemMenu.test.tsx
  graylog2-web-interface/src/components/navigation/SystemMenu.tsx
  graylog2-web-interface/src/pages/ConfigurationsPage.tsx
  graylog2-web-interface/src/pages/DataNodesPage.tsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.tsx
  graylog2-web-interface/src/routing/Routes.ts
Labels: ready-for-review

#17203 backport 5.2: set state to SKIPPED if "resume startup" is called with no data nodes…
  graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightStatusResource.java
  graylog2-web-interface/src/preflight/App.test.tsx
  graylog2-web-interface/src/preflight/components/ResumeStartupButton.tsx
Labels: ready-for-review

#17220 Fix/17204 rules editor tooltip
  changelog/unreleased/issue-17204.toml
  graylog2-web-interface/src/components/common/SourceCodeEditor.tsx
  graylog2-web-interface/src/components/rules/RuleForm.tsx
Labels: bug, frontend

#17223 Fix/5.2 17204 rules editor tooltip
  changelog/unreleased/issue-17204.toml
  graylog2-web-interface/src/components/rules/RuleForm.tsx
Labels: bug, frontend

#17205 (Open) - Make Illuminate Pipeline Functions Available for General Use
  changelog/unreleased/issue-6032.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/AbstractArrayFunction.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayContains.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayRemove.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/StringArrayAdd.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupAll.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayContains.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayRemove.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupAll.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringArrayAdd.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/with-arrays.json
Labels: secdev-cycle6

#17233 Fix contentPack create revision not redirecting after creation
  changelog/unreleased/pr-17233.toml
  graylog2-web-interface/src/pages/EditContentPackPage.jsx
Labels: ready-for-review

#17073 Fix Content pack install modal have two superposed modal element
  changelog/unreleased/pr-17073.toml
  graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.tsx
  graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackVersions.test.jsx
  graylog2-web-interface/src/components/content-packs/ContentPackVersions.tsx
  graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
  graylog2-web-interface/src/components/content-packs/ContentPacksList.test.tsx
  graylog2-web-interface/src/components/content-packs/ContentPacksList.tsx
  graylog2-web-interface/src/components/content-packs/Types.ts
  graylog2-web-interface/src/components/content-packs/components/ContentPackListItem.test.tsx
  graylog2-web-interface/src/components/content-packs/components/ContentPackListItem.tsx
  graylog2-web-interface/src/components/content-packs/components/ContentPackVersionItem.tsx
  graylog2-web-interface/src/pages/ContentPacksPage.tsx
  graylog2-web-interface/src/routing/ApiRoutes.ts
Labels: ready-for-review

#17246 Add CRC to sidecar default template
  changelog/unreleased/issue-17040.toml
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java
  graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/SidecarServiceTest.java
Labels: backport

#17201 Fix "Stats are disabled by default" color on IndexSet page
  graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx
Labels: ready-for-review

#17280 Fix Sidecar collector configuration form submit button not being clickable
  changelog/unreleased/pr-17280.toml
  graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx
Labels: ready-for-review

#17262 Fix 'Create event definition' button to use Anchor
  graylog2-web-interface/src/pages/EventDefinitionsPage.tsx
Labels: ready-for-review

#16758 Custom HTTP notification
  changelog/unreleased/pr-16758.toml
  graylog2-server/src/main/java/org/graylog/events/EventsModule.java
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/HttpEventNotificationConfigV2Entity.java
  graylog2-server/src/main/java/org/graylog/events/event/EventDto.java
  graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationModelData.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfigV2.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPNotification.java
  graylog2-web-interface/src/components/common/SourceCodeEditor.tsx
  graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetailsV2.tsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationFormV2.tsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationSummaryV2.tsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
  graylog2-web-interface/src/components/event-notifications/event-notification-types/templates.ts
  graylog2-web-interface/src/components/event-notifications/types.d.ts
  graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.ts
Labels: secdev-cycle6

#17235 Allow "JSON path value from HTTP API" Input to Use POST/PUT
  changelog/unreleased/pr-17235.toml
  graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpPollTransport.java
  graylog2-server/src/test/java/org/graylog2/inputs/transports/HttpPollTransportTest.java
Labels: secdev-cycle6

#17328 Fix Custom HTTP Notification content pack
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/HttpEventNotificationConfigV2Entity.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfigV2.java
Labels: secdev-cycle6

#17342 Fix page size select not working on Alerts & Events page
  changelog/unreleased/issue-17199.toml
  graylog2-web-interface/src/components/events/events/Events.jsx
  graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx
Labels: bug

#17345 Backport 5.2 (Open) - Make Illuminate Pipeline Functions Available for General Use
  changelog/unreleased/issue-6032.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/AbstractArrayFunction.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayContains.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayRemove.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/StringArrayAdd.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupAll.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayContains.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayRemove.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupAll.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringArrayAdd.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/with-arrays.json
Labels: backport, secdev-cycle6

#17289 Fix inputs extractors list not updating after deletion
  changelog/unreleased/pr-17289.toml
  graylog2-web-interface/src/components/extractors/ExtractorsList.tsx
  graylog2-web-interface/src/pages/EditExtractorsPage.jsx
  graylog2-web-interface/src/stores/extractors/ExtractorsStore.ts
Labels: ready-for-review

#17346 Hide field type refresh interval on the indices form for cloud
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
Labels: ready-for-review

#17369 Add option to send HTTP notification API key/secret as header
  changelog/unreleased/issue-14691.toml
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfigV2.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPNotification.java
  graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetailsV2.tsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationFormV2.tsx
  graylog2-web-interface/src/components/event-notifications/types.d.ts
Labels: needs-backport

#17024 backport 5.1: change loggers for indexer subsystem (#17012)
  changelog/unreleased/pr-17012.toml
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
Labels: ready-for-review

#17023 backport 5.0: change loggers for indexer subsystem (#17012)
  changelog/unreleased/pr-17012.toml
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
Labels: ready-for-review

#17387 Backport 5.1: Add option to send HTTP notification API Key/Value as header
  changelog/unreleased/issue-14691.toml
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java
  graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
Labels: backport

#17388 Backport 5.2: Add option to send HTTP notification API Key/Value as header
  changelog/unreleased/issue-14691.toml
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java
  graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx
  graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
Labels: backport

#17449 Wrap ContentTooLongException into a BatchSizeTooLargeException
  changelog/unreleased/pr-17449.toml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
  graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java
Labels: needs-backport

#17350 UPGRADING.md update for AD User Assets - Only Allow objectSid as Unique ID Attribute When Importing and base64 decode
  UPGRADING.md
Labels: secdev-cycle6
