Repository Graylog2/graylog2-server, pull requests merged in 2023-09, with the labels that each got.

#16478 Update UPGRADING.md to Reflect MS Defender for Endpoint Input Changes
  UPGRADING.md
Labels: secdev-cycle5

#16445 Fix indexset edit
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.tsx
Labels: ready-for-review

#16434 create additional Sidecar roles(#15380) - backport 5.0
  changelog/unreleased/pr-15380.toml
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/SidecarModule.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20230502164900_AddSidecarManagerAndReaderRole.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
Labels: ready-for-review

#16433 create additional Sidecar roles(#15380) - backport 5.1
  changelog/unreleased/pr-15380.toml
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/SidecarModule.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20230502164900_AddSidecarManagerAndReaderRole.java
  graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
Labels: ready-for-review

#16514 Add ability to clean field names for set_field and set_fields pipeline functions
  changelog/unreleased/pr-16514.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetField.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setField.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setFields.txt
Labels: secdev-cycle5

#16576 Add ability to clean field names for set_field and set_fields pipeline functions (5.1)
  changelog/unreleased/pr-16514.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetField.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java
  graylog2-server/src/main/java/org/graylog2/plugin/Message.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setField.txt
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setFields.txt
Labels: backport, secdev-cycle5

#16577 Add new GIM Schema fields, update UPGRADING.md (5.1)
  UPGRADING.md
  graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Labels: backport

#16515 Remove Edit Event Definition button from events scoped as immutable
  changelog/unreleased/issue-15916.toml
  graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java
  graylog2-web-interface/src/pages/ViewEventDefinitionPage.test.tsx
  graylog2-web-interface/src/pages/ViewEventDefinitionPage.tsx
Labels: secdev-cycle5
