Repository Graylog2/graylog2-server, pull requests merged in 2023-02, with the labels that each got.

#14240 use separate inputs endpoint for stream rules
  changelog/unreleased/pr-14240.toml
  graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
  graylog2-server/src/main/java/org/graylog2/commands/Server.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/RestResourcesModule.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/rules/StreamRuleInputsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/streams/rules/responses/StreamRuleInputsList.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java
  graylog2-server/src/main/java/org/graylog2/shared/inputs/InputDescription.java
  graylog2-server/src/main/java/org/graylog2/streams/StreamsModule.java
  graylog2-server/src/main/java/org/graylog2/streams/input/StreamRuleInput.java
  graylog2-server/src/main/java/org/graylog2/streams/input/StreamRuleInputsProvider.java
  graylog2-server/src/main/java/org/graylog2/streams/input/StreamRuleServerInputsProvider.java
  graylog2-web-interface/src/components/streamrules/StreamRule.jsx
  graylog2-web-interface/src/components/streamrules/StreamRuleModal.test.tsx
  graylog2-web-interface/src/components/streamrules/StreamRuleModal.tsx
  graylog2-web-interface/src/stores/inputs/StreamRulesInputsStore.ts
Labels: ready-for-review

#14636 Add normalize function
  changelog/unreleased/issue-6527.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/NormalizeFields.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/normalizeFields.txt
Labels: ready-for-review

#14521 Hybrid index rotation strategy UI
  graylog2-server/src/main/java/org/graylog2/configuration/IndexSetsDefaultConfiguration.java
  graylog2-web-interface/package.json
  graylog2-web-interface/src/components/common/RangeInput.test.tsx
  graylog2-web-interface/src/components/common/RangeInput.tsx
  graylog2-web-interface/src/components/configurations/IndexSetsDefaultsConfig.tsx
  graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.jsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
  graylog2-web-interface/src/components/indices/rotation/TimeBasedSizeOptimizingStrategyConfiguration.tsx
  graylog2-web-interface/src/components/indices/rotation/TimeBasedSizeOptimizingStrategySummary.tsx
  graylog2-web-interface/src/components/indices/rotation/index.ts
  graylog2-web-interface/src/hooks/useMaxIndexRotationLimit.ts
  graylog2-web-interface/src/stores/indices/IndicesStore.ts
  graylog2-web-interface/yarn.lock
Labels: ready-for-review

#14644 Make `WidgetPosition` singleton, implement `equals`.
  graylog2-web-interface/src/views/logic/widgets/WidgetPosition.ts
Labels: bug

#14435 Sidecar Failure Tracking View
  changelog/unreleased/pr-14435.toml
  graylog2-web-interface/src/components/sidecars/common/SidecarsPageNavigation.tsx
  graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.test.tsx
  graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingList.tsx
  graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingListContainer.tsx
  graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingRows.tsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/VerboseMessageModal.jsx
  graylog2-web-interface/src/components/sidecars/types.d.ts
  graylog2-web-interface/src/pages/SidecarFailureTrackingPage.jsx
  graylog2-web-interface/src/pages/index.jsx
  graylog2-web-interface/src/routing/AppRouter.tsx
  graylog2-web-interface/src/routing/Routes.ts
Labels: ready-for-review

#14671 Server changes to support Azure multi-node capability (5.0)
  graylog2-server/src/main/java/org/graylog2/inputs/InputService.java
  graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java
  graylog2-server/src/main/resources/log4j2.xml
Labels: backport

#14658 fix field value providers dropdown in Event definition form
  graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.tsx
Labels: ready-for-review

#14459 Support encrypted values in input configuration
  UPGRADING.md
  changelog/unreleased/issue-14433.toml
  graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ValueReference.java
  graylog2-server/src/main/java/org/graylog2/database/PersistedServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/filters/ExtractorFilter.java
  graylog2-server/src/main/java/org/graylog2/filters/StaticFieldFilter.java
  graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java
  graylog2-server/src/main/java/org/graylog2/inputs/WithInputConfiguration.java
  graylog2-server/src/main/java/org/graylog2/inputs/encryption/EncryptedInputConfigMigration.java
  graylog2-server/src/main/java/org/graylog2/inputs/encryption/EncryptedInputConfigs.java
  graylog2-server/src/main/java/org/graylog2/inputs/jackson/InputConfigurationDeserializer.java
  graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpPollTransport.java
  graylog2-server/src/main/java/org/graylog2/jackson/InputConfigurationBeanDeserializerModifier.java
  graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
  graylog2-server/src/main/java/org/graylog2/migrations/V20230213160000_EncryptedInputConfigMigration.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/Configuration.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/ConfigurationRequest.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/AbstractConfigurationField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/ConfigurationField.java
  graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/TextField.java
  graylog2-server/src/main/java/org/graylog2/rest/models/system/inputs/requests/InputCreateRequest.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
  graylog2-server/src/main/java/org/graylog2/security/AESTools.java
  graylog2-server/src/main/java/org/graylog2/security/encryption/EncryptedValueDeserializer.java
  graylog2-server/src/main/java/org/graylog2/security/encryption/EncryptedValueService.java
  graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java
  graylog2-server/src/main/java/org/graylog2/shared/inputs/MessageInputFactory.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ValueReferenceTest.java
  graylog2-server/src/test/java/org/graylog2/filters/ExtractorFilterTest.java
  graylog2-server/src/test/java/org/graylog2/filters/StaticFieldFilterTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/InputServiceImplTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/encryption/EncryptedInputConfigMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/encryption/EncryptedInputConfigsTest.java
  graylog2-server/src/test/java/org/graylog2/inputs/jackson/InputConfigurationDeserializerTest.java
  graylog2-server/src/test/java/org/graylog2/jackson/InputConfigurationBeanDeserializerModifierTest.java
  graylog2-server/src/test/java/org/graylog2/migrations/V20230213160000_EncryptedInputConfigMigrationTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/inputs/InputsResourceMaskingPasswordsTest.java
  graylog2-server/src/test/java/org/graylog2/security/encryption/EncryptedValueDeserializerTest.java
  graylog2-server/src/test/java/org/graylog2/security/encryption/EncryptedValueTest.java
  graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/ObjectMapperProviderTest.java
  graylog2-server/src/test/resources/org/graylog2/migrations/V20230213160000_EncryptedInputConfigMigrationTest.json
  graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationFormField.tsx
  graylog2-web-interface/src/components/configurationforms/ConfigurationWell.jsx
  graylog2-web-interface/src/components/configurationforms/TextField.tsx
  graylog2-web-interface/src/components/configurationforms/index.jsx
  graylog2-web-interface/src/components/configurationforms/types.ts
  graylog2-web-interface/src/stores/inputs/InputTypesStore.ts
  graylog2-web-interface/test/fixtures/configurationforms.ts
Labels: ready-for-review

#14780 Improve CSV File Adapter error handling (4.3)
  changelog/unreleased/pr-14670.toml
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Labels: backport

#14779 Improve CSV File Adapter error handling (5.0)
  changelog/unreleased/pr-14670.toml
  graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
  graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Labels: backport

#14565 Info box for auto assigned configs
  changelog/unreleased/issue-14229.toml
  graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.tsx
Labels: ready-for-review

#14757 Fix extractors reordering issues
  changelog/unreleased/issue-14693.toml
  graylog2-web-interface/src/components/extractors/ExtractorSortModal.jsx
  graylog2-web-interface/src/components/extractors/ExtractorsList.jsx
  graylog2-web-interface/src/pages/ExtractorsPage.jsx
Labels: ready-for-review

#14814 Add default InputService.allByType() method (5.0)
  graylog2-server/src/main/java/org/graylog2/inputs/InputService.java
Labels: backport
