Repository Graylog2/graylog2-server, pull requests merged in 2024-05, with the labels that each got.

#19228 remove preflight resume startup
  changelog/unreleased/pr-19228.toml
  graylog2-web-interface/src/preflight/App.test.tsx
  graylog2-web-interface/src/preflight/components/ConfigurationWizard/ConfigurationWizard.tsx
  graylog2-web-interface/src/preflight/components/Setup/Setup.tsx
Labels: ready-for-review

#19260 Fix manage extractor link for local input
  changelog/unreleased/pr-19260.toml
  graylog2-web-interface/src/components/inputs/InputListItem.jsx
Labels: ready-for-review, needs-backport

#19274 Backport - Fix manage extractor link for local input (#19260)
  changelog/unreleased/pr-19260.toml
  graylog2-web-interface/src/components/inputs/InputListItem.jsx
Labels: ready-for-review

#19262 Use filter when searching DB for event definitions
  changelog/unreleased/issue-19007.toml
  graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
Labels: needs-backport

#19100 Datanode remote reindex migration UI features
  changelog/unreleased/issue-18876.toml
  graylog2-web-interface/src/components/datanode/hooks/useRemoteReindexMigrationStatus.ts
  graylog2-web-interface/src/components/datanode/migrations/MigrationWizard.tsx
  graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.test.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
  graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
Labels: ready-for-review

#19261 Clarify rule simulation processing
  changelog/unreleased/issue-18359.toml
  graylog2-web-interface/src/components/rules/RuleContext.tsx
  graylog2-web-interface/src/components/rules/RuleForm.test.tsx
  graylog2-web-interface/src/components/rules/RuleSimulation.tsx
  graylog2-web-interface/src/components/rules/rule-builder/RuleBuilder.test.tsx
  graylog2-web-interface/src/components/rules/rule-builder/helpers.ts
Labels: ready-for-review

#19294 Backport - Close IndexSet the delete modal and reload list after deleting.
  changelog/unreleased/pr-19030.toml
  graylog2-web-interface/src/components/indices/IndexSetDeletionForm.jsx
  graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx
Labels: ready-for-review

#19293 Maximum downtime estimate during migration
  changelog/unreleased/issue-19270.toml
  graylog2-web-interface/src/components/datanode/hooks/useJournalDowntimeSize.ts
  graylog2-web-interface/src/components/datanode/migrations/in-place/JournalDowntimeWarning.tsx
Labels: ready-for-review

#19119 Backport 6.0: Markdown remediation steps
  graylog2-web-interface/src/components/common/MarkdownEditor/Editor.test.tsx
  graylog2-web-interface/src/components/common/MarkdownEditor/Editor.tsx
  graylog2-web-interface/src/components/common/MarkdownEditor/EditorModal.tsx
  graylog2-web-interface/src/components/common/MarkdownEditor/Preview.tsx
  graylog2-web-interface/src/components/common/MarkdownEditor/PreviewModal.tsx
  graylog2-web-interface/src/components/common/MarkdownEditor/index.tsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.tsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.tsx
Labels: backport

#19309 Backport 6.0: Search Cleanup Job: Fix interval checking, skip static referenced searches
  graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchesCleanUpJob.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/StaticReferencedSearch.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/StaticSearchLoader.java
  graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
  graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobTest.java
  graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
Labels: backport

#19352 Display Data Node Logs
  changelog/unreleased/issue-17730.toml
  graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DataNodeApiProxyResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DataNodeRestApiProxyResource.java
  graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
  graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeLogsDialog.tsx
  graylog2-web-interface/src/components/datanode/hooks/useDataNodeLogs.ts
  graylog2-web-interface/src/components/datanode/migrations/CompatibilityCheckStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
Labels: ready-for-review

#19385 Backport 6.0: Conditionally set authentication cookie sameSite for training instances
  graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/CookieFactory.java
Labels: backport

#19312 Data Node Migration: remove unnecessary steps/big texts/unavailable paths
  changelog/unreleased/issue-19229.toml
  graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java
  graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActions.java
  graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java
  graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationState.java
  graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineBuilder.java
  graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationActionsAdapter.java
  graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineBuilderTest.java
  graylog2-web-interface/src/components/common/ConfirmDialog.tsx
  graylog2-web-interface/src/components/datanode/Constants.ts
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAConfiguration.tsx
  graylog2-web-interface/src/components/datanode/hooks/useRemoteReindexMigrationStatus.ts
  graylog2-web-interface/src/components/datanode/migrations/InPlaceMigration.test.tsx
  graylog2-web-interface/src/components/datanode/migrations/InPlaceMigration.tsx
  graylog2-web-interface/src/components/datanode/migrations/ManualMigrationStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/MigrationWelcomeStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.test.tsx
  graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/JwtAuthenticationInfo.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
  graylog2-web-interface/src/components/datanode/migrations/in-place/Welcome.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/ExistingDataMigrationQuestion.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
Labels: ready-for-review

#19397 fix: Remove MD custom style to use app font sizes
  graylog2-web-interface/src/components/common/MarkdownEditor/Preview.tsx
Labels: bug, secdev-cycle3, UX improvement

#19404 Disable sigma event definition duplicate and delete options
  changelog/unreleased/pr-19404.toml
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx
Labels: bug, needs-backport, secdev-cycle3

#19472 Backport 6.0: string_array_add pipeline function: Add handling for null elements argument
  changelog/unreleased/pr-19439.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/StringArrayAdd.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringArrayAdd.txt
Labels: backport

#19473 Backport 5.2: string_array_add pipeline function: Add handling for null elements argument
  changelog/unreleased/pr-19439.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/StringArrayAdd.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringArrayAdd.txt
Labels: backport

#18898 Fix Grok field extraction for patterns with converters
  changelog/unreleased/issue-18883.toml
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grokIssue18883.txt
  pom.xml
Labels: needs-backport

#19487 Fix sidecar undefined error
  changelog/unreleased/pr-19487.toml
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationActions.tsx
Labels: ready-for-review
