Repository Graylog2/graylog2-server, pull requests merged in 2024-09, with the labels that each got.

#20273 Add stream_data_routing types to queryValidation
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/views/components/searchbar/PluggableSearchBarControls.tsx
  graylog2-web-interface/src/views/components/searchbar/queryvalidation/types.ts
Labels: ready-for-review

#20317 Make collapsed section header clickable
  graylog2-web-interface/src/components/common/Section.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
  graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
Labels: ready-for-review

#20300 (Backport 6.0) - Return remediation steps with events
  changelog/unreleased/issue-19354.toml
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchResult.java
  graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java
  graylog2-web-interface/src/components/events/events/EventDetails.tsx
  graylog2-web-interface/src/components/events/events/types.ts
Labels: backport

#20319 Backport 6.0: Escape JSON in Custom HTTP Notifications
  changelog/6.0.5/pr-19951.toml
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/providers/JsonSafeEngineProvider.java
  graylog2-server/src/test/java/org/graylog/events/notifications/types/HTTPEventNotificationV2Test.java
Labels: backport

#20339 Show DWH journal info on node overview page
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/nodes/NodeOverview.jsx
  graylog2-web-interface/src/components/nodes/NodeOverview.tsx
  graylog2-web-interface/src/stores/system/SystemPluginsStore.tsx
Labels: ready-for-review

#20354 Add throughput and description to stream details
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
Labels: ready-for-review

#20237 Remote Reindex UI improvements
  changelog/unreleased/pr-20237.toml
  graylog2-web-interface/src/components/datanode/hooks/useSaveRemoteReindexMigrationFormValues.ts
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
Labels: ready-for-review

#20225 Datanode migration telemetry
  changelog/unreleased/issue-20086.toml
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAConfiguration.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CACreateForm.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAUpload.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CertificateRenewalPolicyConfig.tsx
  graylog2-web-interface/src/components/datanode/migrations/ManualMigrationStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/ResetMigrationButton.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
  graylog2-web-interface/src/logic/telemetry/Constants.ts
Labels: ready-for-review

#20372 Convert orphaned `referenced` search filters to inline filters for content pack installation
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/ReferencedQueryStringSearchFilter.java
Labels: secdev-cycle5

#20389 Fix unescaped double quotes in nested event fields for TeamsNotificationV2
  changelog/unreleased/pr-20389.toml
  graylog2-server/src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2.java
  graylog2-server/src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2Test.java
Labels: needs-backport

#20406 Backport 6.0: Fix unescaped double quotes in nested event fields for TeamsNotificationV2
  changelog/unreleased/pr-20389.toml
  graylog2-server/src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2.java
  graylog2-server/src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2Test.java
Labels: backport

#20450 server.conf instead of graylog.conf
  changelog/unreleased/issue-20448.toml
  graylog2-web-interface/src/components/datanode/migrations/in-place/RestartGraylog.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/ExistingDataMigrationQuestion.tsx
Labels: ready-for-review

#20502 Check info status before displaying info icon in search bar
  changelog/unreleased/issue-20409.toml
  graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
Labels: ready-for-review, needs-backport

#20495 Fix new Datanode EntityDataTable issues
  changelog/unreleased/issue-20481.toml
  graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
  graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeBulkActions.tsx
  graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeList.tsx
  graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
  graylog2-web-interface/src/logic/sleep.ts
Labels: ready-for-review

#20522 Increase stream list actionsCellWidth
  changelog/unreleased/issue-20515.toml
  graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx
Labels: ready-for-review

#20549 feat: Include stream categories in Query.filter
  graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.tsx
  graylog2-web-interface/src/components/events/events/types.ts
  graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.ts
  graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.ts
  graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.test.ts
  graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.ts
  graylog2-web-interface/src/views/logic/queries/Query.ts
  graylog2-web-interface/src/views/logic/queries/QueryGenerator.ts
  graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts
  graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts
  graylog2-web-interface/src/views/logic/views/UseCreateViewForEventDefinition.ts
  graylog2-web-interface/src/views/logic/views/ViewGenerator.ts
  graylog2-web-interface/src/views/logic/views/ViewStateGenerator.ts
  graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx
  graylog2-web-interface/src/views/pages/NewSearchPage.tsx
  graylog2-web-interface/test/fixtures/createEventDefinitionFromValue.ts
  graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
Labels: frontend, 6.1 Candidate
