Repository Graylog2/graylog2-server, pull requests merged in 2024-10, with the labels that each got.

#20590 Add shake animation highlight to Query validation Icon when status is Info
  graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
Labels: ready-for-review

#20587 Add missing stream details telemetry events
  graylog2-web-interface/src/components/streamrules/CreateStreamRuleButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamPipelinesConnectionForm.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterDeleteButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleEditButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/AddOutputButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetUpdateForm.tsx
  graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
  graylog2-web-interface/src/logic/telemetry/Constants.ts
Labels: ready-for-review

#20608 added datanode permissions
  changelog/unreleased/pr-20608.toml
  graylog2-web-interface/src/components/navigation/bindings.ts
Labels: ready-for-review

#20620 Index Set field description copy update
  graylog2-web-interface/src/components/common/TimeUnitInput.jsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/TemplateDetails.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/TemplateForm.tsx
Labels: ready-for-review

#20628 Fix Datanode Details Page Error
  changelog/unreleased/issue-20604.toml
  graylog2-web-interface/src/components/common/PaginatedEntityTable/useTableFetchContext.ts
  graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
  graylog2-web-interface/src/pages/DataNodePage.tsx
Labels: ready-for-review

#20678 Add missing any/all option to stream rules in routing/intake page
  changelog/unreleased/pr-20678.toml
  graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.jsx
  graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingIntake.tsx
Labels: ready-for-review

#20702 Disable cross_subdomain_cookie for telemetry
  graylog2-web-interface/src/logic/telemetry/TelemetryInit.tsx
Labels: ready-for-review

#20712 (Backport 6.1) Add missing any/all option to stream rules in routing/intake page (#2…
  changelog/unreleased/pr-20678.toml
  graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.jsx
  graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingIntake.tsx
Labels: backport

#20714 Hide stream rule Matching-Type-Switcher when stream is not editable
  changelog/unreleased/pr-20714.toml
  graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.tsx
Labels: ready-for-review

#20739 Nit/update markdown expand icon
  graylog2-web-interface/src/components/common/MarkdownEditor/Preview.tsx
Labels: frontend

#20768 Increase ForkTsCheckerWebpackPlugin memoryLimit
  graylog2-web-interface/webpack/core.js
Labels: ready-for-review

#20804 Data warehouse UI improvements
  graylog2-web-interface/src/components/common/Section.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/AddOutputButton.tsx
Labels: ready-for-review

#20819 Backport 6.1: Syslog inputs: Trim newlines for Fortigate messages
  changelog/unreleased/pr-20788.toml
  graylog2-server/src/main/java/org/graylog2/inputs/codecs/SyslogCodec.java
  graylog2-server/src/test/java/org/graylog2/inputs/codecs/SyslogCodecTest.java
Labels: backport
