Repository Graylog2/graylog2-server, pull requests merged in 2024-02, with the labels that each got.

#18098 Fix index set defaults change not being reflected in form
  changelog/unreleased/issue-18049.toml
  graylog2-web-interface/src/components/common/RangeInput.tsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.test.tsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
  graylog2-web-interface/src/components/indices/hooks/useIndexDefaults.ts
  graylog2-web-interface/src/components/indices/hooks/useIndexSet.ts
  graylog2-web-interface/src/pages/IndexSetCreationPage.tsx
Labels: bug

#5621 Reduce time range on 'Show received messages' button
  changelog/unreleased/issue-5620.toml
  graylog2-web-interface/src/components/inputs/InputListItem.jsx
  graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
  graylog2-web-interface/src/util/TimeRangeHelper.ts
  graylog2-web-interface/src/views/logic/TimeRange.ts
Labels: performance, bug, search, needs-discussion

#18199 Use index set defaults for data tiering
  graylog2-web-interface/src/components/configurations/IndexSetsDefaultsConfig.tsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.test.tsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
  graylog2-web-interface/src/components/indices/hooks/useIndexDefaults.ts
  graylog2-web-interface/src/components/indices/hooks/useIndexSet.ts
  graylog2-web-interface/src/stores/indices/IndexSetsStore.ts
Labels: frontend

#18273 Don't override defaults with null values in index set
  graylog2-web-interface/src/components/indices/hooks/useIndexSet.ts
Labels: bug

#17768 Add data node migration wizard
  changelog/unreleased/pr-18079.toml
  graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java
  graylog2-web-interface/src/components/datanode/Constants.ts
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAConfiguration.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CACreateForm.test.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CACreateForm.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAUpload.test.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAUpload.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CertificateRenewal.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CertificateRenewalPolicyConfig.tsx
  graylog2-web-interface/src/components/datanode/Types.ts
  graylog2-web-interface/src/components/datanode/hooks/useCompatibilityCheck.ts
  graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
  graylog2-web-interface/src/components/datanode/hooks/useDataNodesCA.ts
  graylog2-web-interface/src/components/datanode/hooks/useMigrationState.ts
  graylog2-web-interface/src/components/datanode/hooks/useMigrationWizardStep.ts
  graylog2-web-interface/src/components/datanode/hooks/useRemoteReindexMigrationStatus.ts
  graylog2-web-interface/src/components/datanode/hooks/useTriggerMigrationState.ts
  graylog2-web-interface/src/components/datanode/migrations/CAStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/CertificateRenewalStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/CompatibilityCheckStep.test.tsx
  graylog2-web-interface/src/components/datanode/migrations/CompatibilityCheckStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/CompatibilityStatus.tsx
  graylog2-web-interface/src/components/datanode/migrations/ManualMigrationStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/MigrationDatanodeList.tsx
  graylog2-web-interface/src/components/datanode/migrations/MigrationFinishedStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/MigrationWelcomeStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/MigrationWizard.tsx
  graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.tsx
  graylog2-web-interface/src/components/datanode/migrations/RollingUpgradeMigration.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/MigrationError.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/ResetMigrationButton.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/ConnectionStringRemovalStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/ExistingDataMigrationQuestion.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/ShutdownClusterStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/Welcome.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/CertificatesProvisioning.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/JournalDowntimeWarning.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/JournalSizeWarning.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/RestartGraylog.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/StopMessageProcessing.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/Welcome.tsx
  graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
Labels: ready-for-review

#18370 Adjuste Data Node migration wording
  graylog2-web-interface/src/components/datanode/Constants.ts
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAConfiguration.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CACreateForm.tsx
  graylog2-web-interface/src/components/datanode/migrations/MigrationDatanodeList.tsx
  graylog2-web-interface/src/components/datanode/migrations/MigrationWelcomeStep.tsx
  graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.tsx
  graylog2-web-interface/src/components/datanode/migrations/RollingUpgradeMigration.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/Welcome.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/JournalDowntimeWarning.tsx
  graylog2-web-interface/src/components/datanode/migrations/rollingUpgrade/Welcome.tsx
Labels: ready-for-review

#18390 Update datanode migration welcome documentation
  graylog2-web-interface/src/components/datanode/Constants.ts
  graylog2-web-interface/src/components/datanode/migrations/MigrationWelcomeStep.tsx
Labels: ready-for-review
