Repository Graylog2/graylog2-server, pull requests merged in 2024-11, with the labels that each got.

#20847 Fix logic for showing/hiding pluggable event actions
  changelog/unreleased/pr-20847.toml
  graylog2-web-interface/src/components/events/events/EventDetails.tsx
Labels: needs-backport

#20858 Enterprise Traffic Graph: Ensure license data is visible on Cloud
  changelog/unreleased/pr-20858.toml
  graylog2-web-interface/src/components/common/Graph/TrafficGraph.tsx
Labels: ready-for-review

#20748 Optimize widgets warnings
  changelog/unreleased/pr-20748.toml
  graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetWarmTierAlert.tsx
Labels: ready-for-review

#20886 Backport 6.1: Fix logic for showing/hiding pluggable event actions
  changelog/unreleased/pr-20847.toml
  graylog2-web-interface/src/components/events/events/EventDetails.tsx
Labels: backport

#20887 Backport 6.0: Fix logic for showing/hiding pluggable event actions
  changelog/unreleased/pr-20847.toml
  graylog2-web-interface/src/components/events/events/EventDetails.tsx
Labels: backport

#20877 Backport 6.0: Add ability to skip no streams access check
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTO.java
  graylog2-web-interface/src/views/components/IfUserHasAccessToAnyStream.tsx
  graylog2-web-interface/src/views/pages/SearchPage.tsx
Labels: backport

#20875 Backport 6.1: Add ability to skip no streams access check
  full-backend-tests/src/test/java/org/graylog/exceptionmappers/JsonParsingErrorsIT.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTO.java
  graylog2-web-interface/src/views/components/IfUserHasAccessToAnyStream.tsx
  graylog2-web-interface/src/views/pages/SearchPage.tsx
Labels: backport

#20935 Fix Stream Routing indexset oldest message in index date
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetOldestMessageCell.tsx
  graylog2-web-interface/src/hooks/useIndexerOverview.ts
Labels: ready-for-review

#20959 Add callback to Section component.
  graylog2-web-interface/src/components/common/Section.test.tsx
  graylog2-web-interface/src/components/common/Section.tsx
Labels: ready-for-review

#20942 Backport 6.1: Add multi_grok pipeline function
  changelog/unreleased/issue-15301.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/MultiGrokMatch.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/multiGrok.txt
Labels: backport

#20943 Backport 6.0: Add multi_grok pipeline function
  changelog/unreleased/issue-15301.toml
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
  graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/MultiGrokMatch.java
  graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
  graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/multiGrok.txt
Labels: backport
