Repository Graylog2/graylog2-server, pull requests merged in 2024-08, with the labels that each got.

#20049 fix(8075): Added definitionId optional prop to FilterAggregationSummary
  graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.tsx
  graylog2-web-interface/src/components/event-definitions/types.d.ts
Labels: bug, frontend, securityui

#20033 Update DWH wordings
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingIntake.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingProcessing.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/Constants.ts
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleForm.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleList.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
Labels: ready-for-review

#20073 Ignore trailing 0x00 padding in IPFIX data sets
  changelog/unreleased/pr-20073.toml
  graylog2-server/src/main/java/org/graylog/integrations/ipfix/IpfixParser.java
  graylog2-server/src/test/java/org/graylog/integrations/ipfix/codecs/IpfixAggregatorTest.java
  graylog2-server/src/test/resources/trailingpadding.pcap
Labels: ready-for-review, backport

#20042 only hide DatanodeMigration if state 'FINISHED' and datanode is configured
  changelog/unreleased/pr-20042.toml
  graylog2-web-interface/src/components/datanode/hooks/useShowDatanodeMigration.ts
Labels: ready-for-review

#20085 add addonAfter for FormikInput
  graylog2-web-interface/src/components/common/FormikInput.tsx
Labels: ready-for-review

#19670 Lookup cache: bubble up error results without modifying
  changelog/unreleased/issue-19159.toml
  graylog2-server/src/main/java/org/graylog2/lookup/caches/CaffeineLookupCache.java
  graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
  graylog2-server/src/test/java/org/graylog2/lookup/CaffeineLookupCacheTest.java
Labels: needs-backport

#20140 DWH destination UI improvement
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/bootstrap/SegmentedControl.tsx
  graylog2-web-interface/src/components/common/Section.test.tsx
  graylog2-web-interface/src/components/common/Section.tsx
  graylog2-web-interface/src/components/common/Section/SectionComponent.tsx
  graylog2-web-interface/src/components/streamrules/DetailsStreamRule.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/SectionCountLabel.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingIntake.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingProcessing.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterActions.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterDeleteButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleEditButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleList.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/AddOutputButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationOutputs.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetArchivingCell.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetFilters.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetUpdateForm.tsx
  graylog2-web-interface/src/components/streams/hooks/useStreamOutputFilters.ts
  graylog2-web-interface/src/components/streams/hooks/useStreamOutputRuleBuilder.ts
  graylog2-web-interface/src/hooks/useIndexSetStats.ts
  graylog2-web-interface/src/routing/ApiRoutes.ts
Labels: ready-for-review

#20176 Show stream illuminate processing section only for Ilumminate stream
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingProcessing.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
Labels: ready-for-review

#20197 Filter job with streamId
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
Labels: ready-for-review

#20265 Resolve widget streams for content pack entities
  changelog/unreleased/pr-20265.toml
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
Labels: secdev-cycle5

#20263 Fix grok_exists pipeline rule
  changelog/unreleased/pr-20263.toml
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
  graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java
Labels: needs-backport

#20284 Backport 6.0: Fix grok_exists pipeline rule (#20263)
  changelog/unreleased/pr-20263.toml
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
  graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java
Labels: backport

#20285 Backport 5.2: Fix grok_exists pipeline rule (#20263)
  changelog/unreleased/pr-20263.toml
  graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
  graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java
Labels: backport

#20288 Handle stream references in content pack persistence service filtering
  changelog/unreleased/pr-20265.toml
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackPersistenceService.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream_reference.json
Labels: needs-backport, secdev-cycle5

#20298 Backport 6.0: Dashboard stream/title content pack fixes
  changelog/unreleased/pr-20244.toml
  changelog/unreleased/pr-20265.toml
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackPersistenceService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamReferenceFacade.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream_reference.json
Labels: backport

#20299 Backport 5.2: Dashboard stream/title content pack fixes
  changelog/unreleased/pr-20244.toml
  changelog/unreleased/pr-20265.toml
  graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackPersistenceService.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamReferenceFacade.java
  graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.java
  graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream.json
  graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream_reference.json
Labels: backport

#20318 Escape double quotes in all strings, not just top level model strings
  changelog/unreleased/pr-19951.toml
  graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java
  graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
  graylog2-server/src/main/java/org/graylog2/bindings/providers/JsonSafeEngineProvider.java
  graylog2-server/src/test/java/org/graylog/events/notifications/types/HTTPEventNotificationV2Test.java
Labels: needs-backport
