Repository Graylog2/graylog2-server, pull requests merged in 2024-06, with the labels that each got.

#19478 Fix upload CA tab not clickable and upload errors
  changelog/unreleased/pr-19478.toml
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAUpload.tsx
  graylog2-web-interface/src/pages/DataNodesMigrationPage.tsx
Labels: ready-for-review

#19548 BACKPORT 5.2 - Fix sidecar undefined error (#19487)
  changelog/unreleased/pr-19487.toml
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx
  graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationActions.tsx
Labels: ready-for-review

#19381 Add modal to select index template on index creation
  changelog/unreleased/pr-19381.toml
  graylog2-server/src/main/java/org/graylog2/indexer/indexset/template/IndexSetTemplateService.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetTemplateResource.java
  graylog2-server/src/main/resources/org/graylog2/indexer/indexset/template/on_prem_templates.json
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/common/FormikInput.tsx
  graylog2-web-interface/src/components/indices/CreateIndexSet.tsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.test.tsx
  graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/CreateIndexSetTemplateButton.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/IndexSetTemplateCard.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/SelectIndexSetTemplateModal.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/TemplateDetails.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/contexts/SelectedIndexSetTemplateContext.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/contexts/SelectedIndexSetTemplateProvider.tsx
  graylog2-web-interface/src/components/indices/IndexSetTemplates/hooks/useBuiltInTemplates.ts
  graylog2-web-interface/src/components/indices/IndexSetTemplates/hooks/useSelectedTemplate.ts
  graylog2-web-interface/src/components/indices/IndexSetTemplates/hooks/useTemplates.ts
  graylog2-web-interface/src/components/indices/IndicesConfiguration.tsx
  graylog2-web-interface/src/components/indices/data-tiering/DataTieringConfiguration.tsx
  graylog2-web-interface/src/components/indices/data-tiering/DataTieringVisualisation.tsx
  graylog2-web-interface/src/components/indices/hooks/useIndexSet.ts
  graylog2-web-interface/src/components/indices/index.tsx
  graylog2-web-interface/src/logic/telemetry/Constants.ts
  graylog2-web-interface/src/pages/IndexSetConfigurationPage.tsx
  graylog2-web-interface/src/pages/IndexSetCreationPage.tsx
  graylog2-web-interface/src/pages/IndexSetTemplatePage.tsx
Labels: feature, frontend

#19539 Datanode UI fixes
  changelog/unreleased/pr-19539.toml
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CACreateForm.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAUpload.tsx
  graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CertificateRenewalPolicyConfig.tsx
  graylog2-web-interface/src/components/datanode/client-certificate/CreateClientCertificateButton.tsx
  graylog2-web-interface/src/components/datanode/migrations/common/MigrationStepTriggerButtonToolbar.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
Labels: ready-for-review

#19599 Data Node Migration Linkable Logs View
  changelog/unreleased/pr-19599.toml
  graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.test.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
Labels: ready-for-review

#19570 fix sidecar failure tracking page error
  changelog/unreleased/issue-19562.toml
  graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingRows.tsx
Labels: ready-for-review

#19640 Add stream details Index set section
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/common/Section.tsx
  graylog2-web-interface/src/components/indices/hooks/useSingleIndexSet.ts
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetUpdateForm.tsx
Labels: ready-for-review

#19657 Show tasks progress in Remote Reindex Migration
  changelog/unreleased/pr-19657.toml
  graylog2-web-interface/src/components/datanode/migrations/common/RemoteReindexProgressBar.tsx
  graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx
Labels: ready-for-review

#19750 Add missing exception handling for IpInfo*Resolver
  changelog/unreleased/pr-19750.toml
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoIpAsnResolver.java
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoLocationResolver.java
Labels: needs-backport

#19760 Check for plugin presence in Stream-details page
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
Labels: ready-for-review

#19685 Stream details outputs
  graylog2-web-interface/src/components/streamrules/DetailsStreamRule.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/AddOutputButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationOutputs.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/EditOutputButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/OutputItem.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/OutputsList.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/RemoveOutputButton.tsx
  graylog2-web-interface/src/components/streams/useAvailableOutputTypes.ts
  graylog2-web-interface/src/hooks/useOutputs.ts
  graylog2-web-interface/src/hooks/useStreamOutputMutations.ts
  graylog2-web-interface/src/hooks/useStreamOutputs.ts
  graylog2-web-interface/src/stores/outputs/OutputsStore.ts
Labels: ready-for-review
