Repository Graylog2/graylog2-server, pull requests merged in 2025-05, with the labels that each got.

#22275 fix: Updated views to use new assoc assets widget (6.1)
  graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoLocationInformation.java
  graylog2-web-interface/src/components/common/MarkdownEditor/Preview.tsx
  graylog2-web-interface/src/views/components/messagelist/FormatAssetList.tsx
  graylog2-web-interface/src/views/types.ts
Labels: bug, backport, frontend, UX improvement

#22509 Ensure proper permissions for Inputs
  graylog2-web-interface/src/components/inputs/InputListItem.tsx
Labels: ready-for-review

#22446 Ensure proper permissions for Outputs
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationOutputs.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/OutputItem.tsx
Labels: ready-for-review

#22508 Add entity share to event notification
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.tsx
Labels: ready-for-review

#22531 Creating an id for a global search filter that get's inlined
  changelog/unreleased/pr-22531.toml
  graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/ReferencedQueryStringSearchFilter.java
Labels: needs-backport

#22571 Default to AdaptiveCard Schema v1.5 in TeamsNotificationV2
  changelog/unreleased/pr-22571.toml
  graylog2-web-interface/src/integrations/event-notifications/event-notification-types/TeamsNotificationV2Form.tsx
Labels: needs-backport

#22577 Default to AdaptiveCard Schema v1.5 in TeamsNotificationV2 (`6.1`)
  changelog/unreleased/pr-22571.toml
  graylog2-web-interface/src/integrations/event-notifications/event-notification-types/TeamsNotificationV2Form.tsx
Labels: backport

#22578 Default to AdaptiveCard Schema v1.5 in TeamsNotificationV2 (`6.0`)
  changelog/unreleased/pr-22571.toml
  graylog2-web-interface/src/integrations/event-notifications/event-notification-types/TeamsNotificationV2Form.tsx
Labels: backport

#22567 Fix save dashboard with sharing
  graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx
  graylog2-web-interface/src/views/components/dashboard/DashboardPropertiesModal.tsx
Labels: ready-for-review

#22602 Error when changing step when editing Event Definition
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.tsx
Labels: ready-for-review

#22409 Fix: Adding correct handling for streams filter in legacy searches
  changelog/unreleased/pr-22409.toml
  graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
  graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
  graylog2-server/src/test/resources/org/graylog2/indexer/searches/SearchesIT.json
Labels: needs-backport

#22640 Make System User DN a required field
  graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.tsx
Labels: ready-for-review

#22638 Fix stream:edit permission usage (singular vs plural)
  graylog2-web-interface/src/components/outputs/Output.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/EditOutputButton.tsx
  graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetUpdateForm.tsx
Labels: ready-for-review

#22670 make Threat Intelligence Lookup Modal closable
  graylog2-web-interface/src/threatintel/components/ThreatIntelPluginConfig.tsx
Labels: ready-for-review

#22644 Add default share request payload to share on create form group
  graylog2-web-interface/src/components/permissions/EntityCreateShareFormGroup.test.tsx
  graylog2-web-interface/src/components/permissions/EntityCreateShareFormGroup.tsx
Labels: ready-for-review
