Repository Graylog2/graylog2-server, pull requests merged in 2025-03, with the labels that each got.

#21749 Handle Immutable pipeline rule UI
  graylog2-web-interface/src/components/rules/Rule.test.tsx
  graylog2-web-interface/src/components/rules/Rule.tsx
  graylog2-web-interface/src/components/rules/RuleForm.tsx
  graylog2-web-interface/src/components/rules/RuleListEntry.test.tsx
  graylog2-web-interface/src/components/rules/RuleListEntry.tsx
  graylog2-web-interface/src/hooks/useScopePermissions.ts
  graylog2-web-interface/src/pages/RuleDetailsPage.tsx
  graylog2-web-interface/src/stores/rules/RulesStore.ts
Labels: ready-for-review

#21838 Fix overreporting of WhoIs redirect errors
  changelog/unreleased/issue-20571.toml
  graylog2-server/src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java
  graylog2-server/src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisLookupException.java
Labels: needs-backport

#21853 Fix missing Query Parameters in Event Definitions in Content Packs (6.0)
  changelog/unreleased/pr-21349.toml
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
Labels: backport

#21655 Fix missing Query Parameters in Event Definitions in Content Packs (6.1)
  changelog/unreleased/pr-21349.toml
  graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
  graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java
  graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
Labels: backport

#21470 BACKPORT 6.1 - Optimize widgets warnings (#20748)
  changelog/unreleased/pr-20748.toml
  graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
  graylog2-web-interface/src/views/components/widgets/Widget.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx
  graylog2-web-interface/src/views/components/widgets/WidgetWarmTierAlert.tsx
Labels: ready-for-review, backport

#21904 ISW - Add link to Processing and indexing error from diagnosis page
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/inputs/InputDiagnosis/Constants.ts
  graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisHelp.tsx
  graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisMessageErrors.tsx
  graylog2-web-interface/src/pages/InputDiagnosisPage.tsx
Labels: ready-for-review

#21871 AWS Kinesis/Cloudwatch input: Refer to official docs site for permissions (6.1)
  UPGRADING.md
  changelog/unreleased/pr-21755.toml
  graylog2-server/src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
  graylog2-server/src/main/java/org/graylog/integrations/aws/service/AWSService.java
  graylog2-server/src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
  graylog2-web-interface/src/integrations/aws/cloudwatch/SidebarPermissions.jsx
  graylog2-web-interface/src/integrations/aws/common/Routes.ts
Labels: backport

#21872 AWS Kinesis/Cloudwatch input: Refer to official docs site for permissions (6.0)
  UPGRADING.md
  changelog/unreleased/pr-21755.toml
  graylog2-server/src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
  graylog2-server/src/main/java/org/graylog/integrations/aws/service/AWSService.java
  graylog2-server/src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
  graylog2-web-interface/src/integrations/aws/cloudwatch/SidebarPermissions.jsx
  graylog2-web-interface/src/integrations/aws/common/Routes.ts
Labels: backport

#21862 Input diagnosis page redesign
  graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
  graylog2-web-interface/src/components/bootstrap/Indicator.tsx
  graylog2-web-interface/src/components/common/StatusColorIndicator.tsx
  graylog2-web-interface/src/components/inputs/InputDiagnosis/Constants.ts
  graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisHelp.tsx
  graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisMessageErrors.tsx
  graylog2-web-interface/src/components/inputs/InputDiagnosis/useInputDiagnosis.ts
  graylog2-web-interface/src/pages/InputDiagnosisPage.test.tsx
  graylog2-web-interface/src/pages/InputDiagnosisPage.tsx
Labels: ready-for-review

#21858 Add sorting and validation for provided CA certificate chains
  changelog/unreleased/pr-21858.toml
  graylog2-server/src/main/java/org/graylog/security/certutil/CaPersistenceService.java
  graylog2-server/src/main/java/org/graylog/security/certutil/ca/CA.java
  graylog2-server/src/main/java/org/graylog/security/certutil/ca/PemCaReader.java
  graylog2-server/src/test/java/org/graylog/security/certutil/ca/CATest.java
  graylog2-server/src/test/java/org/graylog/security/certutil/ca/PemCaReaderTest.java
Labels: needs-backport

#21917 Token creation ttl field UI
  changelog/unreleased/issue-21441.toml
  graylog2-web-interface/src/components/users/CreateTokenForm.tsx
  graylog2-web-interface/src/components/users/TokenList.test.tsx
  graylog2-web-interface/src/components/users/TokenList.tsx
  graylog2-web-interface/src/pages/UserTokensEditPage.tsx
  graylog2-web-interface/src/stores/users/UsersStore.ts
Labels: ready-for-review

#21891 Frontend work for config options; default token TTL and restrict access tokens to admin users
  graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/users/UserResourceGenerateTokenAccessTest.java
  graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java
  graylog2-web-interface/src/components/configurations/UserConfig.tsx
  graylog2-web-interface/src/components/users/TokenList.tsx
  graylog2-web-interface/src/pages/UserTokensEditPage.tsx
  graylog2-web-interface/src/stores/configurations/ConfigurationsStore.ts
Labels: ready-for-review

#22095 Safer extraction of search response in field type retrieval.
  changelog/unreleased/pr-22095.toml
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
  graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/fieldtypes/streams/StreamsForFieldRetrieverES7.java
  graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java
  graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/fieldtypes/streams/StreamsForFieldRetrieverOS2.java
Labels: needs-backport

#22133 Nit/change detection chain badge
  graylog2-web-interface/src/components/events/events/ColumnRenderers.tsx
  graylog2-web-interface/src/components/events/fetchEvents.ts
Labels: security, frontend

#22128 IndexerDiscoveryProvider will provide only AVAILABLE datanodes to prevent hitting starting indexers
  changelog/unreleased/issue-21896.toml
  graylog2-server/src/main/java/org/graylog2/configuration/IndexerDiscoveryProvider.java
Labels: data-node

#22099 fix(8852): Updated call to method that changed it's signature
  graylog2-web-interface/src/stores/event-definitions/FilterPreviewStore.js
Labels: bug, frontend

#22100 Add support for Search Filters in Aggregation events
  changelog/unreleased/issue-21726.toml
  graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
  graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
Labels: needs-backport
