Repository Graylog2/graylog2-server, pull requests merged in 2025-07, with the labels that each got.

#23027 Fix scroll on click behaviour for scroll hint on search page (`6.2`).
  changelog/unreleased/issue-19329.toml
  graylog2-web-interface/src/components/layout/PageContentLayout.tsx
  graylog2-web-interface/src/util/UIUtils.js
Labels: backport

#23028 Fix scroll on click behaviour for scroll hint on search page (`6.1`)
  changelog/unreleased/issue-19329.toml
  graylog2-web-interface/src/components/layout/PageContentLayout.tsx
  graylog2-web-interface/src/util/UIUtils.js
Labels: backport

#23052 Include eventDefinitionId on EventProcessorExecutionJob error message
  graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorExecutionJob.java
Labels: needs-backport

#23009 Fix issue causing quotes to be escaped in markdown content (6.3)
  changelog/unreleased/pr-22970.toml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/security/html/HTMLSanitizerConverter.java
  graylog2-server/src/test/java/org/graylog2/security/html/HTMLSanitizerConverterTest.java
  graylog2-server/src/test/resources/org/graylog2/security/html/html-and-markdown.md
  pom.xml
Labels: backport

#23074 fix(): Updated event procedures docs url
  graylog2-web-interface/src/util/DocsHelper.ts
Labels: frontend, needs-backport

#23011 Fix issue causing quotes to be escaped in markdown content (6.1)
  changelog/unreleased/pr-22970.toml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/security/html/HTMLSanitizerConverter.java
  graylog2-server/src/test/java/org/graylog2/security/html/HTMLSanitizerConverterTest.java
  graylog2-server/src/test/resources/org/graylog2/security/html/html-and-markdown.md
  pom.xml
Labels: backport

#23010 Fix issue causing quotes to be escaped in markdown content (6.2)
  changelog/unreleased/pr-22970.toml
  graylog2-server/pom.xml
  graylog2-server/src/main/java/org/graylog2/security/html/HTMLSanitizerConverter.java
  graylog2-server/src/test/java/org/graylog2/security/html/HTMLSanitizerConverterTest.java
  graylog2-server/src/test/resources/org/graylog2/security/html/html-and-markdown.md
  pom.xml
Labels: backport

#23111 Fix: avoid possible race condition on collection creation in `RecentActivityService`
  changelog/unreleased/pr-23111.toml
  graylog2-server/src/main/java/org/graylog/plugins/views/startpage/recentActivities/RecentActivityService.java
Labels: needs-backport

#23088 Replace custom implementation of `Button` component in preflight UI with component from core.
  graylog2-web-interface/src/preflight/components/ConfigurationWizard/CACreateForm.tsx
  graylog2-web-interface/src/preflight/components/ConfigurationWizard/CAUpload.tsx
  graylog2-web-interface/src/preflight/components/ConfigurationWizard/CertificateProvisioning.tsx
  graylog2-web-interface/src/preflight/components/ConfigurationWizard/ConfigurationFinished.tsx
  graylog2-web-interface/src/preflight/components/ConfigurationWizard/ConfigurationWizard.tsx
  graylog2-web-interface/src/preflight/components/ConfigurationWizard/RenewalPolicyConfiguration.tsx
  graylog2-web-interface/src/preflight/components/RestartConfigurationButton.tsx
  graylog2-web-interface/src/preflight/components/ResumeStartupButton.tsx
  graylog2-web-interface/src/preflight/components/Setup/DataNodesOverview.tsx
  graylog2-web-interface/src/preflight/components/common/Button.tsx
  graylog2-web-interface/src/preflight/components/common/index.ts
  graylog2-web-interface/src/preflight/navigation/HelpMenu.tsx
  graylog2-web-interface/src/views/components/searchbar/ViewsRefreshControls.test.tsx
Labels: frontend

#23138 Feat/11107 update lut page component
  graylog2-web-interface/src/components/lookup-tables/adapter-list/index.tsx
  graylog2-web-interface/src/components/lookup-tables/hooks/api/lookupTablesAPI.ts
  graylog2-web-interface/src/components/lookup-tables/index.ts
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/column-renderers.tsx
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/constants.ts
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/errors-consumer.tsx
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/index.tsx
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/types.ts
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/unit-test/fixtures.ts
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/unit-test/lookup-table.test.tsx
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/use-actions.tsx
  graylog2-web-interface/src/components/lookup-tables/lookup-table-list/utils.ts
  graylog2-web-interface/src/components/lookup-tables/lut-layout.tsx
  graylog2-web-interface/src/pages/LUTCachesPage.bkp.tsx
  graylog2-web-interface/src/pages/LUTCachesPage.tsx
  graylog2-web-interface/src/pages/LUTDataAdaptersPage.bkp.tsx
  graylog2-web-interface/src/pages/LUTDataAdaptersPage.tsx
  graylog2-web-interface/src/pages/LUTTablesPage.bkp.tsx
  graylog2-web-interface/src/pages/LUTTablesPage.tsx
  graylog2-web-interface/src/routing/AppRouter.tsx
Labels: frontend, UX improvement, lookup tables

#23026 Fix scroll on click behaviour for scroll hint on search page (`6.3`).
  changelog/unreleased/issue-19329.toml
  graylog2-web-interface/src/components/layout/PageContentLayout.tsx
  graylog2-web-interface/src/util/UIUtils.js
Labels: backport

#23173 Update SearchDbService.delete method to delete documents
  changelog/unreleased/issue-23172.toml
  graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java
Labels: needs-backport

#22979 Adding permission check to show only plugin configuration pages, that the user is allowed to see.
  changelog/unreleased/pr-22979.toml
  graylog2-web-interface/src/components/configurations/PluginsConfig.tsx
  graylog2-web-interface/src/views/types.ts
Labels: needs-backport

#23132 Add pluggable entity table column
  graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
  graylog2-web-interface/src/components/event-definitions/constants.ts
  graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.tsx
  graylog2-web-interface/src/components/event-notifications/event-notifications/Constants.ts
  graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.tsx
  graylog2-web-interface/src/components/permissions/type.ts
  graylog2-web-interface/src/components/permissions/types.ts
  graylog2-web-interface/src/components/streams/StreamsOverview/ColumnRenderers.tsx
  graylog2-web-interface/src/components/streams/StreamsOverview/Constants.ts
  graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx
  graylog2-web-interface/src/components/streams/StreamsOverview/hooks/useTableComponents.tsx
  graylog2-web-interface/src/hooks/usePluggableEntityTableElements.tsx
  graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/Constants.ts
  graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx
  graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/useColumnRenderers.tsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesModal/SavedSearchesOverview.tsx
  graylog2-web-interface/src/views/components/searchbar/saved-search/useColumnRenderes.tsx
Labels: ready-for-review
