Repository Graylog2/graylog2-server, pull requests merged in 2025-09, with the labels that each got.

#23493 Reduce padding and change title of additional grantees list on share modal
  graylog2-web-interface/src/components/permissions/EntityShareSettings.tsx
Labels: ready-for-review

#23403 Adding annotation for Config consistency
  graylog2-server/src/main/java/org/graylog2/web/customization/Config.java
Labels: needs-backport

#23559 Fix/11270 sigma event procedures scoped rules
  graylog2-web-interface/src/components/bootstrap/MantineAccordion.tsx
  graylog2-web-interface/src/components/common/Drawer.tsx
  graylog2-web-interface/src/components/common/MarkdownEditor/Preview.tsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.tsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.tsx
  graylog2-web-interface/src/components/events/events/ColumnRenderers.tsx
  graylog2-web-interface/src/views/types.ts
Labels: improvement, frontend, event procedures

#23677 Fix issue displaying table row after adding notification
  changelog/unreleased/pr-23677.toml
  graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.tsx
Labels: needs-backport

#23578 Enforce DB 7.0 and remove 5.0 references
  UPGRADING.md
  changelog/unreleased/issue-23448.toml
  data-node/migration/docker-compose.yml
  data-node/migration/es710-docker-compose.yml
  graylog2-server/src/main/java/org/graylog2/database/MongoDBVersionCheck.java
  graylog2-server/src/test/java/org/graylog/testing/containermatrix/MongodbServer.java
  graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTestsConfiguration.java
  graylog2-server/src/test/java/org/graylog2/cluster/lock/MongoLockServiceTest5.java
  graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestsDescriptorTest.java
Labels: e2e-tests

#23644 Fix/11611 assets event procedure not scrolling details drawer
  graylog2-web-interface/src/components/common/Drawer.tsx
  graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.tsx
  graylog2-web-interface/src/components/events/events/ColumnRenderers.tsx
  graylog2-web-interface/src/components/lookup-tables/LUTModals/LUTDrawer/index.tsx
  graylog2-web-interface/src/views/types.ts
Labels: frontend, UX improvement, event procedures

#23748 IT Tests: we also need to catch AssertionError and not only Exception in waitFor
  graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogRestApi.java
Labels: needs-backport

#23763 Stream Action Update Bug Fix
  graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
  graylog2-web-interface/src/pages/StreamsPage.tsx
Labels: needs-backport

#23769 introduce global_inputs_only config to enforce global inputs
  changelog/unreleased/pr-23769.toml
  graylog2-server/src/main/java/org/graylog2/Configuration.java
  graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
  graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
  graylog2-server/src/main/resources/web-interface/config.js.template
  graylog2-server/src/test/java/org/graylog2/rest/resources/system/inputs/InputsResourceTest.java
  graylog2-web-interface/src/components/inputs/InputForm.tsx
  graylog2-web-interface/src/util/AppConfig.ts
Labels: needs-backport
